export const questionBank: Record<string, { q: string; options: string[]; answer: string }[]> = {
  'P1-P2': [
    { q: 'Which word means the SAME as "happy"?', options: ['sad', 'glad', 'angry', 'tired'], answer: 'glad' },
    { q: 'Which word means the OPPOSITE of "big"?', options: ['large', 'huge', 'small', 'tall'], answer: 'small' },
    { q: 'Which word means the SAME as "fast"?', options: ['slow', 'quick', 'quiet', 'heavy'], answer: 'quick' },
    { q: 'Which word means the OPPOSITE of "hot"?', options: ['warm', 'cool', 'cold', 'dry'], answer: 'cold' },
    { q: 'Which word means the SAME as "begin"?', options: ['finish', 'end', 'stop', 'start'], answer: 'start' },
    { q: 'Which word means the OPPOSITE of "day"?', options: ['morning', 'evening', 'night', 'noon'], answer: 'night' },
    { q: 'Which word means the SAME as "beautiful"?', options: ['ugly', 'pretty', 'strange', 'tired'], answer: 'pretty' },
    { q: 'Which word means the OPPOSITE of "up"?', options: ['high', 'over', 'above', 'down'], answer: 'down' },
    { q: 'Which word means the SAME as "scary"?', options: ['funny', 'frightening', 'boring', 'exciting'], answer: 'frightening' },
    { q: 'Which word means the OPPOSITE of "clean"?', options: ['tidy', 'neat', 'dirty', 'fresh'], answer: 'dirty' },
    { q: 'Which word means the SAME as "sick"?', options: ['well', 'healthy', 'ill', 'strong'], answer: 'ill' },
    { q: 'Which word means the OPPOSITE of "open"?', options: ['wide', 'lock', 'shut', 'loose'], answer: 'shut' },
    { q: 'Which word means the SAME as "thin"?', options: ['fat', 'heavy', 'slim', 'wide'], answer: 'slim' },
    { q: 'Which word means the OPPOSITE of "old"?', options: ['ancient', 'senior', 'aged', 'young'], answer: 'young' },
    { q: 'Which word means the SAME as "angry"?', options: ['happy', 'sad', 'calm', 'furious'], answer: 'furious' },
    { q: 'Which word means the OPPOSITE of "easy"?', options: ['simple', 'light', 'difficult', 'fun'], answer: 'difficult' },
    { q: 'Which word means the SAME as "brave"?', options: ['scared', 'shy', 'courageous', 'weak'], answer: 'courageous' },
    { q: 'Which word means the OPPOSITE of "love"?', options: ['like', 'enjoy', 'hate', 'care'], answer: 'hate' },
    { q: 'Which word means the SAME as "tired"?', options: ['energetic', 'awake', 'sleepy', 'active'], answer: 'sleepy' },
    { q: 'Which word means the OPPOSITE of "first"?', options: ['second', 'middle', 'final', 'last'], answer: 'last' },
    { q: 'Which word means the SAME as "cold"?', options: ['warm', 'chilly', 'hot', 'mild'], answer: 'chilly' },
    { q: 'Which word means the OPPOSITE of "loud"?', options: ['noisy', 'quiet', 'strong', 'clear'], answer: 'quiet' },
    { q: 'Which word means the SAME as "smart"?', options: ['dumb', 'slow', 'clever', 'lazy'], answer: 'clever' },
    { q: 'Which word means the OPPOSITE of "win"?', options: ['play', 'try', 'score', 'lose'], answer: 'lose' },
    { q: 'Which word means the SAME as "sad"?', options: ['joyful', 'glad', 'unhappy', 'cheerful'], answer: 'unhappy' },
    { q: 'Which word means the OPPOSITE of "dry"?', options: ['warm', 'cold', 'wet', 'dark'], answer: 'wet' },
    { q: 'Which word means the SAME as "funny"?', options: ['dull', 'boring', 'serious', 'amusing'], answer: 'amusing' },
    { q: 'Which word means the OPPOSITE of "tall"?', options: ['large', 'wide', 'short', 'slim'], answer: 'short' },
    { q: 'Which word means the SAME as "dangerous"?', options: ['safe', 'calm', 'risky', 'gentle'], answer: 'risky' },
    { q: 'Which word means the OPPOSITE of "right"?', options: ['correct', 'true', 'wrong', 'good'], answer: 'wrong' },
    { q: 'Which word means the SAME as "kind"?', options: ['mean', 'cruel', 'rude', 'gentle'], answer: 'gentle' },
    { q: 'Which word means the OPPOSITE of "give"?', options: ['share', 'send', 'take', 'offer'], answer: 'take' },
    { q: 'Which word means the SAME as "shout"?', options: ['whisper', 'mumble', 'yell', 'hum'], answer: 'yell' },
    { q: 'Which word means the OPPOSITE of "early"?', options: ['quick', 'soon', 'late', 'fast'], answer: 'late' },
    { q: 'Which word means the SAME as "small"?', options: ['large', 'tiny', 'huge', 'wide'], answer: 'tiny' },
    { q: 'Which word means the OPPOSITE of "full"?', options: ['heavy', 'whole', 'empty', 'deep'], answer: 'empty' },
    { q: 'Which word means the SAME as "stop"?', options: ['go', 'run', 'begin', 'halt'], answer: 'halt' },
    { q: 'Which word means the OPPOSITE of "push"?', options: ['move', 'lift', 'slide', 'pull'], answer: 'pull' },
    { q: 'Which word means the SAME as "rich"?', options: ['poor', 'broke', 'wealthy', 'cheap'], answer: 'wealthy' },
    { q: 'Which word means the OPPOSITE of "strong"?', options: ['heavy', 'hard', 'weak', 'slow'], answer: 'weak' },
  ],
  'P3-P4': [
    { q: 'Which word is a SYNONYM of "enormous"?', options: ['tiny', 'average', 'huge', 'narrow'], answer: 'huge' },
    { q: 'Which word is an ANTONYM of "ancient"?', options: ['historic', 'old', 'aged', 'modern'], answer: 'modern' },
    { q: 'Which word is a SYNONYM of "cheerful"?', options: ['gloomy', 'merry', 'dull', 'cross'], answer: 'merry' },
    { q: 'Which word is an ANTONYM of "generous"?', options: ['kind', 'giving', 'stingy', 'helpful'], answer: 'stingy' },
    { q: 'Which word is a SYNONYM of "exhausted"?', options: ['energetic', 'refreshed', 'drained', 'lively'], answer: 'drained' },
    { q: 'Which word is an ANTONYM of "accept"?', options: ['receive', 'welcome', 'take', 'refuse'], answer: 'refuse' },
    { q: 'Which word is a SYNONYM of "furious"?', options: ['calm', 'pleased', 'enraged', 'gentle'], answer: 'enraged' },
    { q: 'Which word is an ANTONYM of "flexible"?', options: ['bendable', 'loose', 'elastic', 'rigid'], answer: 'rigid' },
    { q: 'Which word is a SYNONYM of "brave"?', options: ['timid', 'fearful', 'daring', 'shy'], answer: 'daring' },
    { q: 'Which word is an ANTONYM of "expand"?', options: ['grow', 'widen', 'extend', 'shrink'], answer: 'shrink' },
    { q: 'Which word is a SYNONYM of "mysterious"?', options: ['obvious', 'clear', 'simple', 'puzzling'], answer: 'puzzling' },
    { q: 'Which word is an ANTONYM of "victory"?', options: ['triumph', 'success', 'achievement', 'defeat'], answer: 'defeat' },
    { q: 'Which word is a SYNONYM of "wealthy"?', options: ['poor', 'broke', 'prosperous', 'needy'], answer: 'prosperous' },
    { q: 'Which word is an ANTONYM of "construct"?', options: ['build', 'create', 'make', 'demolish'], answer: 'demolish' },
    { q: 'Which word is a SYNONYM of "gloomy"?', options: ['bright', 'cheerful', 'sunny', 'miserable'], answer: 'miserable' },
    { q: 'Which word is an ANTONYM of "remember"?', options: ['recall', 'recognise', 'forget', 'remind'], answer: 'forget' },
    { q: 'Which word is a SYNONYM of "peculiar"?', options: ['normal', 'usual', 'common', 'strange'], answer: 'strange' },
    { q: 'Which word is an ANTONYM of "cruel"?', options: ['harsh', 'brutal', 'vicious', 'compassionate'], answer: 'compassionate' },
    { q: 'Which word is a SYNONYM of "assist"?', options: ['hinder', 'block', 'help', 'stop'], answer: 'help' },
    { q: 'Which word is an ANTONYM of "temporary"?', options: ['brief', 'short', 'fleeting', 'permanent'], answer: 'permanent' },
    { q: 'Which word is a SYNONYM of "terrified"?', options: ['calm', 'brave', 'petrified', 'bold'], answer: 'petrified' },
    { q: 'Which word is an ANTONYM of "guilty"?', options: ['criminal', 'ashamed', 'sorry', 'innocent'], answer: 'innocent' },
    { q: 'Which word is a SYNONYM of "vanish"?', options: ['appear', 'arrive', 'come', 'disappear'], answer: 'disappear' },
    { q: 'Which word is an ANTONYM of "minimum"?', options: ['least', 'lowest', 'smallest', 'maximum'], answer: 'maximum' },
    { q: 'Which word is a SYNONYM of "intelligent"?', options: ['dull', 'foolish', 'ignorant', 'brilliant'], answer: 'brilliant' },
    { q: 'Which word is an ANTONYM of "noisy"?', options: ['loud', 'rowdy', 'peaceful', 'booming'], answer: 'peaceful' },
    { q: 'Which word is a SYNONYM of "truthful"?', options: ['dishonest', 'lying', 'deceitful', 'honest'], answer: 'honest' },
    { q: 'Which word is an ANTONYM of "shallow"?', options: ['light', 'surface', 'slim', 'deep'], answer: 'deep' },
    { q: 'Which word is a SYNONYM of "purchase"?', options: ['sell', 'give', 'donate', 'buy'], answer: 'buy' },
    { q: 'Which word is an ANTONYM of "natural"?', options: ['real', 'pure', 'genuine', 'artificial'], answer: 'artificial' },
    { q: 'Which word is a SYNONYM of "stunning"?', options: ['ugly', 'plain', 'ordinary', 'magnificent'], answer: 'magnificent' },
    { q: 'Which word is an ANTONYM of "include"?', options: ['contain', 'add', 'involve', 'exclude'], answer: 'exclude' },
    { q: 'Which word is a SYNONYM of "timid"?', options: ['bold', 'confident', 'fearless', 'shy'], answer: 'shy' },
    { q: 'Which word is an ANTONYM of "borrow"?', options: ['take', 'use', 'lend', 'keep'], answer: 'lend' },
    { q: 'Which word is a SYNONYM of "determined"?', options: ['weak', 'lazy', 'unsure', 'persistent'], answer: 'persistent' },
    { q: 'Which word is an ANTONYM of "victory"?', options: ['win', 'success', 'achievement', 'failure'], answer: 'failure' },
    { q: 'Which word is a SYNONYM of "frequently"?', options: ['rarely', 'never', 'seldom', 'often'], answer: 'often' },
    { q: 'Which word is an ANTONYM of "positive"?', options: ['confident', 'hopeful', 'sure', 'negative'], answer: 'negative' },
    { q: 'Which word is a SYNONYM of "quarrel"?', options: ['agree', 'discuss', 'argue', 'cooperate'], answer: 'argue' },
    { q: 'Which word is an ANTONYM of "superior"?', options: ['better', 'higher', 'greater', 'inferior'], answer: 'inferior' },
  ],
  'P5-P6': [
    { q: 'Which word is a SYNONYM of "ambiguous"?', options: ['clear', 'certain', 'vague', 'obvious'], answer: 'vague' },
    { q: 'Which word is an ANTONYM of "advocate"?', options: ['support', 'promote', 'defend', 'oppose'], answer: 'oppose' },
    { q: 'Which word is a SYNONYM of "meticulous"?', options: ['careless', 'sloppy', 'thorough', 'hasty'], answer: 'thorough' },
    { q: 'Which word is an ANTONYM of "transparent"?', options: ['clear', 'open', 'honest', 'opaque'], answer: 'opaque' },
    { q: 'Which word is a SYNONYM of "eloquent"?', options: ['silent', 'inarticulate', 'fluent', 'quiet'], answer: 'fluent' },
    { q: 'Which word is an ANTONYM of "volatile"?', options: ['unstable', 'explosive', 'changeable', 'stable'], answer: 'stable' },
    { q: 'Which word is a SYNONYM of "benevolent"?', options: ['cruel', 'selfish', 'hostile', 'charitable'], answer: 'charitable' },
    { q: 'Which word is an ANTONYM of "scarce"?', options: ['rare', 'limited', 'lacking', 'abundant'], answer: 'abundant' },
    { q: 'Which word is a SYNONYM of "contemplate"?', options: ['ignore', 'rush', 'avoid', 'ponder'], answer: 'ponder' },
    { q: 'Which word is an ANTONYM of "accelerate"?', options: ['speed up', 'quicken', 'hasten', 'decelerate'], answer: 'decelerate' },
    { q: 'Which word is a SYNONYM of "dejected"?', options: ['elated', 'joyful', 'content', 'despondent'], answer: 'despondent' },
    { q: 'Which word is an ANTONYM of "obsolete"?', options: ['outdated', 'old', 'ancient', 'current'], answer: 'current' },
    { q: 'Which word is a SYNONYM of "scrutinise"?', options: ['ignore', 'overlook', 'examine', 'skip'], answer: 'examine' },
    { q: 'Which word is an ANTONYM of "lenient"?', options: ['tolerant', 'easygoing', 'permissive', 'strict'], answer: 'strict' },
    { q: 'Which word is a SYNONYM of "empathy"?', options: ['selfishness', 'indifference', 'compassion', 'cruelty'], answer: 'compassion' },
    { q: 'Which word is an ANTONYM of "conceal"?', options: ['hide', 'cover', 'bury', 'reveal'], answer: 'reveal' },
    { q: 'Which word is a SYNONYM of "sceptical"?', options: ['trusting', 'certain', 'doubting', 'convinced'], answer: 'doubting' },
    { q: 'Which word is an ANTONYM of "pessimistic"?', options: ['gloomy', 'negative', 'doubtful', 'optimistic'], answer: 'optimistic' },
    { q: 'Which word is a SYNONYM of "alleviate"?', options: ['worsen', 'increase', 'relieve', 'intensify'], answer: 'relieve' },
    { q: 'Which word is an ANTONYM of "rational"?', options: ['logical', 'sensible', 'reasonable', 'irrational'], answer: 'irrational' },
    { q: 'Which word is a SYNONYM of "assertive"?', options: ['passive', 'timid', 'weak', 'confident'], answer: 'confident' },
    { q: 'Which word is an ANTONYM of "unity"?', options: ['teamwork', 'harmony', 'cooperation', 'division'], answer: 'division' },
    { q: 'Which word is a SYNONYM of "monotonous"?', options: ['varied', 'exciting', 'repetitive', 'interesting'], answer: 'repetitive' },
    { q: 'Which word is an ANTONYM of "prominent"?', options: ['famous', 'notable', 'leading', 'obscure'], answer: 'obscure' },
    { q: 'Which word is a SYNONYM of "resilient"?', options: ['fragile', 'breakable', 'weak', 'tough'], answer: 'tough' },
    { q: 'Which word is an ANTONYM of "trivial"?', options: ['minor', 'petty', 'unimportant', 'significant'], answer: 'significant' },
    { q: 'Which word is a SYNONYM of "apathetic"?', options: ['passionate', 'enthusiastic', 'indifferent', 'motivated'], answer: 'indifferent' },
    { q: 'Which word is an ANTONYM of "generous"?', options: ['giving', 'charitable', 'kind', 'miserly'], answer: 'miserly' },
    { q: 'Which word is a SYNONYM of "hinder"?', options: ['assist', 'encourage', 'support', 'obstruct'], answer: 'obstruct' },
    { q: 'Which word is an ANTONYM of "commence"?', options: ['begin', 'start', 'launch', 'conclude'], answer: 'conclude' },
    { q: 'Which word is a SYNONYM of "perplexed"?', options: ['clear', 'certain', 'confident', 'bewildered'], answer: 'bewildered' },
    { q: 'Which word is an ANTONYM of "superficial"?', options: ['shallow', 'surface', 'brief', 'profound'], answer: 'profound' },
    { q: 'Which word is a SYNONYM of "candid"?', options: ['secretive', 'dishonest', 'frank', 'deceptive'], answer: 'frank' },
    { q: 'Which word is an ANTONYM of "diligent"?', options: ['hardworking', 'careful', 'thorough', 'lazy'], answer: 'lazy' },
    { q: 'Which word is a SYNONYM of "jubilant"?', options: ['miserable', 'gloomy', 'elated', 'depressed'], answer: 'elated' },
    { q: 'Which word is an ANTONYM of "encourage"?', options: ['motivate', 'inspire', 'support', 'discourage'], answer: 'discourage' },
    { q: 'Which word is a SYNONYM of "cautious"?', options: ['reckless', 'careless', 'wary', 'bold'], answer: 'wary' },
    { q: 'Which word is an ANTONYM of "rigid"?', options: ['stiff', 'firm', 'hard', 'flexible'], answer: 'flexible' },
    { q: 'Which word is a SYNONYM of "reluctant"?', options: ['eager', 'willing', 'hesitant', 'enthusiastic'], answer: 'hesitant' },
    { q: 'Which word is an ANTONYM of "transparent"?', options: ['see-through', 'clear', 'honest', 'deceptive'], answer: 'deceptive' },
  ],
  'M1-M3': [
    { q: 'Which word is a SYNONYM of "equivocal"?', options: ['clear', 'definite', 'certain', 'ambiguous'], answer: 'ambiguous' },
    { q: 'Which word is an ANTONYM of "exacerbate"?', options: ['worsen', 'aggravate', 'intensify', 'alleviate'], answer: 'alleviate' },
    { q: 'Which word is a SYNONYM of "ostentatious"?', options: ['humble', 'modest', 'subtle', 'flamboyant'], answer: 'flamboyant' },
    { q: 'Which word is an ANTONYM of "indigenous"?', options: ['native', 'local', 'original', 'foreign'], answer: 'foreign' },
    { q: 'Which word is a SYNONYM of "pragmatic"?', options: ['idealistic', 'unrealistic', 'impractical', 'practical'], answer: 'practical' },
    { q: 'Which word is an ANTONYM of "coherent"?', options: ['logical', 'clear', 'organised', 'incoherent'], answer: 'incoherent' },
    { q: 'Which word is a SYNONYM of "tenacious"?', options: ['weak', 'giving up', 'submissive', 'persistent'], answer: 'persistent' },
    { q: 'Which word is an ANTONYM of "perpetual"?', options: ['endless', 'constant', 'continuous', 'temporary'], answer: 'temporary' },
    { q: 'Which word is a SYNONYM of "nefarious"?', options: ['virtuous', 'noble', 'honourable', 'wicked'], answer: 'wicked' },
    { q: 'Which word is an ANTONYM of "frugal"?', options: ['thrifty', 'careful', 'economical', 'wasteful'], answer: 'wasteful' },
    { q: 'Which word is a SYNONYM of "reticent"?', options: ['talkative', 'outspoken', 'reserved', 'vocal'], answer: 'reserved' },
    { q: 'Which word is an ANTONYM of "innocuous"?', options: ['harmless', 'safe', 'gentle', 'harmful'], answer: 'harmful' },
    { q: 'Which word is a SYNONYM of "acrimonious"?', options: ['pleasant', 'friendly', 'bitter', 'warm'], answer: 'bitter' },
    { q: 'Which word is an ANTONYM of "vindicate"?', options: ['prove innocent', 'justify', 'clear', 'condemn'], answer: 'condemn' },
    { q: 'Which word is a SYNONYM of "ephemeral"?', options: ['lasting', 'permanent', 'eternal', 'fleeting'], answer: 'fleeting' },
    { q: 'Which word is an ANTONYM of "proliferate"?', options: ['multiply', 'increase', 'spread', 'diminish'], answer: 'diminish' },
    { q: 'Which word is a SYNONYM of "impetuous"?', options: ['cautious', 'careful', 'rash', 'thoughtful'], answer: 'rash' },
    { q: 'Which word is an ANTONYM of "altruistic"?', options: ['selfless', 'generous', 'giving', 'selfish'], answer: 'selfish' },
    { q: 'Which word is a SYNONYM of "disparate"?', options: ['similar', 'identical', 'equal', 'different'], answer: 'different' },
    { q: 'Which word is an ANTONYM of "candour"?', options: ['honesty', 'openness', 'frankness', 'deception'], answer: 'deception' },
    { q: 'Which word is a SYNONYM of "loquacious"?', options: ['quiet', 'silent', 'reserved', 'talkative'], answer: 'talkative' },
    { q: 'Which word is an ANTONYM of "ameliorate"?', options: ['improve', 'enhance', 'better', 'worsen'], answer: 'worsen' },
    { q: 'Which word is a SYNONYM of "obsequious"?', options: ['bold', 'defiant', 'fawning', 'assertive'], answer: 'fawning' },
    { q: 'Which word is an ANTONYM of "empirical"?', options: ['observed', 'tested', 'evidence-based', 'theoretical'], answer: 'theoretical' },
    { q: 'Which word is a SYNONYM of "magnanimous"?', options: ['petty', 'grudging', 'mean', 'generous'], answer: 'generous' },
    { q: 'Which word is an ANTONYM of "subjugate"?', options: ['control', 'dominate', 'oppress', 'liberate'], answer: 'liberate' },
    { q: 'Which word is a SYNONYM of "vacillate"?', options: ['decide', 'commit', 'resolve', 'waver'], answer: 'waver' },
    { q: 'Which word is an ANTONYM of "explicit"?', options: ['clear', 'direct', 'obvious', 'implicit'], answer: 'implicit' },
    { q: 'Which word is a SYNONYM of "pernicious"?', options: ['harmless', 'beneficial', 'helpful', 'destructive'], answer: 'destructive' },
    { q: 'Which word is an ANTONYM of "stoic"?', options: ['calm', 'unemotional', 'enduring', 'emotional'], answer: 'emotional' },
    { q: 'Which word is a SYNONYM of "contentious"?', options: ['agreeable', 'peaceful', 'harmonious', 'controversial'], answer: 'controversial' },
    { q: 'Which word is an ANTONYM of "eloquence"?', options: ['fluency', 'persuasion', 'articulacy', 'inarticulate speech'], answer: 'inarticulate speech' },
    { q: 'Which word is a SYNONYM of "spurious"?', options: ['genuine', 'real', 'authentic', 'false'], answer: 'false' },
    { q: 'Which word is an ANTONYM of "dogmatic"?', options: ['rigid', 'inflexible', 'opinionated', 'open-minded'], answer: 'open-minded' },
    { q: 'Which word is a SYNONYM of "austere"?', options: ['lavish', 'luxurious', 'extravagant', 'severe'], answer: 'severe' },
    { q: 'Which word is an ANTONYM of "credulous"?', options: ['naive', 'trusting', 'gullible', 'sceptical'], answer: 'sceptical' },
    { q: 'Which word is a SYNONYM of "banal"?', options: ['original', 'fresh', 'creative', 'clichéd'], answer: 'clichéd' },
    { q: 'Which word is an ANTONYM of "antagonise"?', options: ['provoke', 'irritate', 'aggravate', 'placate'], answer: 'placate' },
    { q: 'Which word is a SYNONYM of "mitigate"?', options: ['worsen', 'intensify', 'reduce', 'increase'], answer: 'reduce' },
    { q: 'Which word is an ANTONYM of "lucid"?', options: ['clear', 'transparent', 'intelligible', 'confused'], answer: 'confused' },
  ],
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}
