'use client'
import { useState, useRef, useEffect } from 'react'
import Link from 'next/link'

const SPEEDS = [
  { label: '🐢 Very Slow', value: 0.55 },
  { label: '🚶 Slow', value: 0.72 },
  { label: '🏃 Normal', value: 0.9 },
  { label: '⚡ Fast', value: 1.1 },
]

const LANGUAGES = [
  { value: 'none', label: '🌍 English only' },
  { value: 'Thai', label: '🇹🇭 Thai' },
  { value: 'Japanese', label: '🇯🇵 Japanese' },
  { value: 'Korean', label: '🇰🇷 Korean' },
  { value: 'Chinese', label: '🇨🇳 Chinese' },
  { value: 'Arabic', label: '🇸🇦 Arabic' },
  { value: 'Spanish', label: '🇪🇸 Spanish' },
  { value: 'French', label: '🇫🇷 French' },
  { value: 'German', label: '🇩🇪 German' },
  { value: 'Portuguese', label: '🇧🇷 Portuguese' },
  { value: 'Russian', label: '🇷🇺 Russian' },
  { value: 'Vietnamese', label: '🇻🇳 Vietnamese' },
  { value: 'Indonesian', label: '🇮🇩 Indonesian' },
]

const PARTS = [
  {
    number: 1, title: 'What Is Doping?', emoji: '💊', color: '#7c3aed',
    text: `In sport, doping means using banned substances or methods to improve your performance. This includes taking drugs that make you stronger, faster, or able to train harder and recover more quickly than your body could naturally. Doping is considered cheating because it gives athletes an unfair advantage over competitors who follow the rules.\n\nThe list of banned substances in sport is long and includes steroids (which build muscle), stimulants (which increase energy and alertness), blood boosters (which help carry more oxygen to the muscles), and even some common medicines that can affect performance. The list is maintained by an organisation called the World Anti-Doping Agency, or WADA, which was created in 1999 to fight doping in sport worldwide.\n\nDoping is not new. Ancient Greek athletes ate special diets and drank potions to try to gain an advantage. In the early modern Olympics, some athletes used strychnine — a poison — in small doses as a stimulant. In the 1960s and 1970s, the use of steroids became widespread in sports like weightlifting, athletics, and cycling. By the 1980s, doping had become one of the biggest problems in international sport.\n\nThe reason athletes dope is simple: it works. Performance-enhancing drugs can dramatically improve speed, strength, and endurance. The difference between winning a gold medal and finishing fourth is often tiny — sometimes just hundredths of a second. For athletes who have trained their entire lives, the temptation to use drugs that could make the difference between glory and anonymity can be enormous.`,
    vocab: [
      { word: 'Substances', definition: 'Materials or chemicals — in sport, this usually means drugs or medicines.' },
      { word: 'Steroids', definition: 'Drugs that help build muscle and increase strength, banned in most sports.' },
      { word: 'Stimulant', definition: 'A substance that makes you feel more awake, alert, and energetic.' },
      { word: 'Anonymity', definition: 'The state of being unknown — nobody knows who you are.' },
    ],
    questions: [
      { n: 1, q: 'Why do you think doping is considered cheating? Is it different from other forms of cheating in sport?' },
      { n: 2, q: 'Ancient athletes also tried to gain advantages with special diets and potions. Does this change how you think about modern doping?' },
      { n: 3, q: 'The difference between gold and fourth place can be hundredths of a second. Does this help you understand why athletes might be tempted to dope?' },
    ]
  },
  {
    number: 2, title: 'Famous Doping Scandals', emoji: '📰', color: '#6d28d9',
    text: `Some doping scandals have been so dramatic that they have changed entire sports.\n\nThe most famous individual case is probably Lance Armstrong, the American cyclist who won the Tour de France seven times in a row between 1999 and 2005. Armstrong was celebrated as one of the greatest athletes of all time, especially because he had survived cancer before returning to cycling. But in 2012, after years of accusations and denials, the US Anti-Doping Agency published evidence that Armstrong had been using performance-enhancing drugs throughout his career. He was stripped of all seven titles and banned from cycling for life.\n\nThe biggest state-sponsored doping scandal involved Russia. An investigation revealed that the Russian government had been running a systematic doping programme for its athletes for years, with the knowledge and support of the country\'s sports ministry and secret service. Russian agents even developed a method for secretly replacing doped urine samples with clean ones during the 2014 Winter Olympics in Sochi. As a result, Russia was banned from competing under its own flag at several Olympic Games.\n\nIn athletics, sprinter Ben Johnson won the 100 metres at the 1988 Seoul Olympics in a world-record time, only to be stripped of his medal two days later after testing positive for steroids. More recently, entire national athletics teams have been suspended for widespread doping — Kenya and Ethiopia, powerhouses of distance running, have both faced serious doping investigations.\n\nThese scandals have damaged public trust in sport. When an athlete performs extraordinarily well, many fans now wonder whether the performance is genuine — a suspicion that is unfair to clean athletes but is a direct consequence of years of doping.`,
    vocab: [
      { word: 'Stripped', definition: 'Had something taken away as a punishment — like losing a title or medal.' },
      { word: 'State-sponsored', definition: 'Organised, funded, or supported by a country\'s government.' },
      { word: 'Systematic', definition: 'Done in an organised, planned way — following a system rather than being random.' },
      { word: 'Suspended', definition: 'Temporarily stopped from taking part in something, usually as a punishment.' },
    ],
    questions: [
      { n: 4, q: 'Lance Armstrong was a cancer survivor and a hero to millions. How do you think people felt when they discovered he had been cheating?' },
      { n: 5, q: 'Russia\'s government helped its athletes cheat. Should an entire country be punished for the actions of its government? Is this fair to clean Russian athletes?' },
      { n: 6, q: 'The passage says fans now doubt extraordinary performances. How does doping affect people who watch sport? Does it change how you watch?' },
    ]
  },
  {
    number: 3, title: 'The Science of Catching Cheaters', emoji: '🔬', color: '#5b21b6',
    text: `The fight against doping is essentially an arms race between cheaters who develop new ways to dope and scientists who develop new ways to detect it. The cheaters are often one step ahead.\n\nThe most common method of testing is the urine test. Athletes are required to provide urine samples after competitions and during random out-of-competition tests. These samples are sent to accredited laboratories where they are analysed for the presence of banned substances. If a banned substance is found, the athlete faces suspension and the loss of any results achieved while doping.\n\nBut urine tests have limitations. Some drugs leave the body very quickly and can only be detected within a few hours of use. Athletes and their advisors know this and time their drug use carefully to avoid detection. To address this, anti-doping authorities introduced the Athlete Biological Passport — a system that tracks an athlete\'s blood values over time. Instead of looking for specific drugs, the passport looks for unusual changes in blood chemistry that might indicate doping, even if the specific drug cannot be identified.\n\nAnother powerful tool is sample storage. Anti-doping authorities now store urine and blood samples for up to ten years. As testing technology improves, old samples can be re-tested with newer, more sensitive methods. Several Olympic medallists have been caught years after competing when their stored samples were re-analysed with improved technology.\n\nDespite these advances, many experts believe that a significant number of doped athletes are never caught. The drugs are becoming more sophisticated, the methods of concealment are improving, and the financial rewards of winning are so enormous that the incentive to cheat remains very strong.`,
    vocab: [
      { word: 'Arms race', definition: 'A competition where both sides keep trying to get ahead of the other — originally about weapons.' },
      { word: 'Accredited', definition: 'Officially recognised and approved as meeting certain quality standards.' },
      { word: 'Concealment', definition: 'The act of hiding something so that it cannot be found or discovered.' },
      { word: 'Incentive', definition: 'Something that motivates or encourages you to do something — a reward or reason.' },
    ],
    questions: [
      { n: 7, q: 'Athletes can be caught years later when old samples are re-tested. Do you think this is fair? How would it feel to lose a medal years after winning it?' },
      { n: 8, q: 'The passage describes doping detection as an "arms race." Who do you think is currently winning — the cheaters or the scientists?' },
      { n: 9, q: 'If many doped athletes are never caught, what does this mean for athletes who compete clean? Is the current system fair enough?' },
    ]
  },
  {
    number: 4, title: 'Is Clean Sport Possible?', emoji: '⚖️', color: '#4c1d95',
    text: `The fundamental question about doping is whether it can ever be completely eliminated from sport. Some people believe it can — with better testing, harsher punishments, and stronger education programmes for young athletes. Others argue that as long as enormous rewards exist for winning, some athletes will always look for shortcuts.\n\nSome commentators have gone further and asked a controversial question: should doping simply be allowed? Their argument is that if everyone could use performance-enhancing drugs, the playing field would be level and nobody would have an unfair advantage. They also point out that athletes already use many forms of technology and training methods that enhance performance — altitude training, oxygen tents, advanced nutrition — and ask where exactly the line between acceptable and unacceptable enhancement should be drawn.\n\nMost people reject this argument for two important reasons. First, many performance-enhancing drugs are genuinely dangerous. Steroids can cause heart disease, liver damage, and psychological problems. Blood boosters can cause fatal blood clots. Allowing doping would essentially force athletes to risk their health in order to compete. Second, sport is supposed to celebrate natural human ability. If athletes can simply take pills to run faster or lift more, the achievement becomes chemical rather than human.\n\nWhat most experts agree on is that the fight against doping requires more than just testing. It requires a culture change — teaching young athletes from the beginning of their careers that doping is wrong, that health matters more than medals, and that a clean fourth place is worth more than a doped gold medal. Whether the sporting world can create that culture remains to be seen.`,
    vocab: [
      { word: 'Eliminated', definition: 'Completely removed or got rid of — made to disappear entirely.' },
      { word: 'Controversial', definition: 'Causing strong disagreement and arguments between people with different opinions.' },
      { word: 'Enhancement', definition: 'Something that makes something else better or more effective — an improvement.' },
      { word: 'Culture change', definition: 'A fundamental shift in how a group of people think, behave, and what they consider acceptable.' },
    ],
    questions: [
      { n: 10, q: 'Some people say doping should be allowed to make sport fair. Do you agree or disagree? What would happen to sport if doping were legal?' },
      { n: 11, q: 'Athletes use altitude training, special nutrition, and advanced technology. Is this really different from taking drugs? Where is the line?' },
      { n: 12, q: 'Do you believe that "a clean fourth place is worth more than a doped gold medal"? Would most athletes agree with this?' },
    ]
  },
]

async function fetchTranslation(text: string, lang: string, type: 'word' | 'question' | 'message'): Promise<string> {
  const systems: Record<string, string> = {
    word: `You are a language learning assistant. Translate this English vocabulary entry to ${lang}. Return ONLY the translated word and a brief explanation in ${lang} (max 25 words). No extra text, no English.`,
    question: `You are a translator. Translate this English discussion question to ${lang}. Return ONLY the translated question. No extra text.`,
    message: `You are a translator. Translate this English text to ${lang}. Return ONLY the translation. No extra text.`,
  }
  const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: systems[type], messages: [{ role: 'user', content: text }] }) })
  const data = await res.json()
  return data.content || ''
}

function TranslateBtn({ text, type, lang, color, onTranslated }: { text: string; type: 'word' | 'question' | 'message'; lang: string; color: string; onTranslated: (t: string) => void }) {
  const [loading, setLoading] = useState(false)
  const [done, setDone] = useState(false)
  const handleClick = async () => { if (lang === 'none' || loading || done) return; setLoading(true); const result = await fetchTranslation(text, lang, type); onTranslated(result); setDone(true); setLoading(false) }
  const isDisabled = lang === 'none'
  return <button onClick={handleClick} disabled={isDisabled || loading || done} title={isDisabled ? 'Select a language above to translate' : done ? 'Translated' : `Translate to ${lang}`} style={{ background: isDisabled ? '#f3f4f6' : done ? '#f0fdf4' : color + '15', color: isDisabled ? '#d1d5db' : done ? '#16a34a' : color, border: `1px solid ${isDisabled ? '#e5e7eb' : done ? '#86efac' : color + '40'}`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: isDisabled ? 'not-allowed' : done ? 'default' : 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s' }}>{loading ? '...' : done ? '✓ 🌍' : '🌍'}</button>
}

function ListenBtn({ text, speed, color }: { text: string; speed: number; color: string }) {
  const [loading, setLoading] = useState(false); const [playing, setPlaying] = useState(false); const sourceRef = useRef<AudioBufferSourceNode | null>(null)
  const handleClick = async () => { if (playing && sourceRef.current) { try { sourceRef.current.stop() } catch {} sourceRef.current = null; setPlaying(false); return }; setLoading(true); try { const res = await fetch('/api/tts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); if (!res.ok) { setLoading(false); return }; const ab = await res.arrayBuffer(); const ac = new AudioContext(); const buf = await ac.decodeAudioData(ab); const src = ac.createBufferSource(); src.buffer = buf; src.playbackRate.value = speed; src.connect(ac.destination); src.onended = () => { setPlaying(false); sourceRef.current = null }; sourceRef.current = src; setLoading(false); setPlaying(true); src.start(0) } catch { setLoading(false); setPlaying(false) } }
  return <button onClick={handleClick} style={{ background: playing ? color : color + '15', color: playing ? 'white' : color, border: `1px solid ${color}40`, padding: '2px 10px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s', display: 'flex', alignItems: 'center', gap: '4px' }}>{loading ? '...' : playing ? '⏹ Stop' : '🔊 Listen'}</button>
}

type Message = { role: 'user' | 'assistant'; content: string; translation?: string }

function ConversationBox({ question, color, translationLang, speed }: { question: string; color: string; translationLang: string; speed: number }) {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [listening, setListening] = useState(false); const [interimText, setInterimText] = useState(''); const [open, setOpen] = useState(false); const recognitionRef = useRef<any>(null); const transcriptRef = useRef('')
  const SYSTEM = `You are a friendly and enthusiastic English conversation partner helping a B1 level student aged 10-12 practise English discussion skills. The reading topic is "Doping in Sport — The Cheaters and the Science". The current discussion question is: "${question}". Keep every response to 2-3 sentences maximum. Use simple, clear, exciting language for a young learner. Be enthusiastic and curious about dreams! Always end with one fun follow-up question to keep the conversation going. If the student makes a significant grammar error, gently correct it using "💡 Quick tip: ..." at the very end.`
  const sendMessage = async (text: string) => { if (!text.trim() || loading) return; const userMsg: Message = { role: 'user', content: text.trim() }; const updated = [...messages, userMsg]; setMessages(updated); setInput(''); setLoading(true); try { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: SYSTEM, messages: updated.map(m => ({ role: m.role, content: m.content })) }) }); const data = await res.json(); setMessages(prev => [...prev, { role: 'assistant', content: data.content || 'Sorry, try again.' }]) } catch { setMessages(prev => [...prev, { role: 'assistant', content: 'Connection error — please try again.' }]) }; setLoading(false) }
  const setMessageTranslation = (idx: number, translation: string) => { setMessages(prev => prev.map((m, i) => i === idx ? { ...m, translation } : m)) }
  const startVoice = () => { const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!SR) { alert('Voice input requires Chrome browser.'); return }; transcriptRef.current = ''; const r = new SR(); r.lang = 'en-US'; r.continuous = true; r.interimResults = true; r.onstart = () => { setListening(true); setInterimText('') }; r.onresult = (e: any) => { let f = ''; let int = ''; for (let i = 0; i < e.results.length; i++) { if (e.results[i].isFinal) { f += e.results[i][0].transcript + ' ' } else { int += e.results[i][0].transcript } }; transcriptRef.current = f; setInterimText(f + int) }; r.onerror = () => { setListening(false); setInterimText('') }; r.onend = () => { setListening(false); const text = transcriptRef.current.trim() || interimText.trim(); if (text) { setInterimText(''); transcriptRef.current = ''; sendMessage(text) } else { setInterimText(''); transcriptRef.current = '' } }; recognitionRef.current = r; r.start() }
  const stopVoice = () => { recognitionRef.current?.stop() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  if (!open) return <button onClick={() => setOpen(true)} style={{ marginTop: '10px', width: '100%', background: color + '12', border: `2px dashed ${color}40`, borderRadius: '12px', padding: '10px', color, fontWeight: '700', fontSize: '13px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>🤖 Practice answering with AI</button>
  return (
    <div style={{ marginTop: '10px', background: '#faf5ff', borderRadius: '14px', border: `2px solid ${color}30`, overflow: 'hidden' }}>
      <div style={{ background: color, padding: '10px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span style={{ color: 'white', fontWeight: '700', fontSize: '13px' }}>🤖 AI Conversation Partner</span><div style={{ display: 'flex', gap: '6px' }}><button onClick={() => setMessages([])} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>🔄 Reset</button><button onClick={() => setOpen(false)} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>✕ Close</button></div></div>
      {messages.length === 0 && <div style={{ padding: '14px 16px', color: '#6b7280', fontSize: '13px', lineHeight: '1.6', borderBottom: '1px solid #ede9fe' }}>💡 Type your answer or tap <strong>🎤 Start Recording</strong> — speak your full answer, then tap <strong>⏹ Stop & Send</strong>.</div>}
      {messages.length > 0 && <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px', maxHeight: '320px', overflowY: 'auto' }}>{messages.map((m, i) => (<div key={i} style={{ display: 'flex', gap: '8px', alignItems: 'flex-start', flexDirection: m.role === 'user' ? 'row-reverse' : 'row' }}><div style={{ fontSize: '20px', flexShrink: 0 }}>{m.role === 'user' ? '🧑‍🎓' : '🤖'}</div><div style={{ maxWidth: '80%', display: 'flex', flexDirection: 'column', gap: '4px', alignItems: m.role === 'user' ? 'flex-end' : 'flex-start' }}><div style={{ background: m.role === 'user' ? color : 'white', color: m.role === 'user' ? 'white' : '#374151', padding: '10px 14px', borderRadius: m.role === 'user' ? '16px 4px 16px 16px' : '4px 16px 16px 16px', fontSize: '14px', lineHeight: '1.6', boxShadow: '0 1px 4px rgba(0,0,0,0.08)', border: m.role === 'assistant' ? '1px solid #e5e7eb' : 'none' }}>{m.content}</div>{m.role === 'assistant' && <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}><ListenBtn text={m.content} speed={speed} color={color} />{!m.translation && <TranslateBtn text={m.content} type="message" lang={translationLang} color={color} onTranslated={(t) => setMessageTranslation(i, t)} />}</div>}{m.translation && <div style={{ background: '#faf5ff', border: '1px solid #ede9fe', borderRadius: '10px', padding: '8px 12px', fontSize: '13px', color: '#374151', lineHeight: '1.5' }}><span style={{ color: color, fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>🌍 Translation</span>{m.translation}</div>}</div></div>))}{loading && <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}><span style={{ fontSize: '20px' }}>🤖</span><div style={{ background: 'white', padding: '10px 14px', borderRadius: '4px 16px 16px 16px', fontSize: '14px', color: '#9ca3af', border: '1px solid #e5e7eb' }}>Thinking...</div></div>}</div>}
      <div style={{ padding: '12px 16px', borderTop: '1px solid #ede9fe', display: 'flex', gap: '8px', alignItems: 'flex-end' }}><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(input) } }} placeholder="Type your answer here..." rows={2} style={{ flex: 1, padding: '10px 12px', borderRadius: '10px', border: '2px solid #e5e7eb', fontSize: '14px', outline: 'none', resize: 'none', fontFamily: 'inherit', lineHeight: '1.5' }} /><div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}><button onClick={listening ? stopVoice : startVoice} style={{ background: listening ? '#ef4444' : '#22c55e', color: 'white', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: listening ? '0 0 0 4px rgba(239,68,68,0.3)' : 'none', transition: 'all 0.2s' }}>{listening ? '⏹' : '🎤'}</button><button onClick={() => sendMessage(input)} disabled={!input.trim() || loading} style={{ background: input.trim() && !loading ? color : '#e5e7eb', color: input.trim() && !loading ? 'white' : '#9ca3af', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: input.trim() && !loading ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>➤</button></div></div>
      {!listening && <div style={{ padding: '4px 16px 10px', display: 'flex', gap: '16px' }}><span style={{ color: '#9ca3af', fontSize: '11px' }}>🎤 = Start recording</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>⏹ = Stop & send</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>➤ = Send typed</span></div>}
      {listening && <div style={{ padding: '10px 16px 14px', borderTop: '1px solid #fee2e2', background: '#fef2f2' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ display: 'inline-block', width: '10px', height: '10px', borderRadius: '50%', background: '#ef4444', animation: 'pulse 1s infinite', flexShrink: 0 }} /><span style={{ color: '#ef4444', fontSize: '12px', fontWeight: '700' }}>Recording... speak your full answer</span></div><button onClick={stopVoice} style={{ background: '#ef4444', color: 'white', border: 'none', padding: '6px 16px', borderRadius: '10px', fontWeight: '800', fontSize: '13px', cursor: 'pointer', boxShadow: '0 2px 8px rgba(239,68,68,0.4)' }}>⏹ Stop & Send</button></div><div style={{ background: 'white', borderRadius: '10px', padding: '10px 14px', fontSize: '14px', color: interimText ? '#374151' : '#9ca3af', lineHeight: '1.6', border: '1px solid #fca5a5', fontStyle: 'italic', minHeight: '40px' }}>{interimText || 'Waiting for speech...'}{interimText && <span style={{ display: 'inline-block', width: '2px', height: '16px', background: '#ef4444', marginLeft: '2px', verticalAlign: 'middle', animation: 'pulse 1s infinite' }} />}</div></div>}
    </div>
  )
}

export default function DopingPage() {
  const [speed, setSpeed] = useState(0.9); const [translationLang, setTranslationLang] = useState('none'); const [selectedText, setSelectedText] = useState<string | null>(null); const [lookupDef, setLookupDef] = useState(''); const [lookupTranslation, setLookupTranslation] = useState(''); const [lookupLoading, setLookupLoading] = useState(false); const [vocabTranslations, setVocabTranslations] = useState<Record<string, string>>({}); const [questionTranslations, setQuestionTranslations] = useState<Record<number, string>>({})
  useEffect(() => { const handleSelection = () => { const sel = window.getSelection(); if (!sel) return; const text = sel.toString().trim().replace(/\s+/g, ' '); if (!text || text.split(' ').length > 6) return; const anchor = sel.anchorNode?.parentElement; if (!anchor?.closest('[data-passage]')) return; handleLookup(text) }; document.addEventListener('mouseup', handleSelection); document.addEventListener('touchend', handleSelection); return () => { document.removeEventListener('mouseup', handleSelection); document.removeEventListener('touchend', handleSelection) } }, [translationLang])
  const handleLookup = async (text: string) => { if (!text || text.length < 2) return; setSelectedText(text); setLookupDef(''); setLookupTranslation(''); setLookupLoading(true); speakWord(text); const isPhrase = text.includes(' '); try { if (translationLang === 'none') { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: isPhrase ? `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 20 words) explaining what the phrase means. No extra text.` : `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 15 words) defining this word. No extra text.`, messages: [{ role: 'user', content: isPhrase ? `What does "${text}" mean?` : `Define: "${text}"` }] }) }); const data = await res.json(); setLookupDef(data.content || 'No definition found.') } else { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: `You are a language learning assistant for young B1 English students. Respond ONLY with valid JSON (no markdown, no backticks): {"definition": "one simple English sentence max 15 words", "translation": "the word/phrase in ${translationLang} with a brief explanation in ${translationLang}, max 25 words"}`, messages: [{ role: 'user', content: `Word or phrase: "${text}"` }] }) }); const data = await res.json(); try { const parsed = JSON.parse(data.content); setLookupDef(parsed.definition || 'No definition found.'); setLookupTranslation(parsed.translation || '') } catch { setLookupDef(data.content || 'No definition found.'); setLookupTranslation('') } } } catch { setLookupDef('Could not load definition.') }; setLookupLoading(false) }
  function speakText(text: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const sentences = text.match(/[^.!?]+[.!?]+/g) || [text]; sentences.forEach(s => { const u = new SpeechSynthesisUtterance(s.trim()); u.lang = 'en-GB'; u.rate = speed; u.pitch = 1; window.speechSynthesis.speak(u) }) }
  function speakWord(word: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(word); u.lang = 'en-GB'; u.rate = 0.85; u.pitch = 1; window.speechSynthesis.speak(u) }
  function stopAudio() { if (typeof window === 'undefined') return; window.speechSynthesis.cancel() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  return (
    <main style={{ background: '#f4f6fa', minHeight: '100vh' }}>
      <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}} @keyframes slideUp{from{transform:translateY(100%);opacity:0}to{transform:translateY(0);opacity:1}}`}</style>
      <section style={{ background: 'linear-gradient(135deg, #0d0520 0%, #2e1065 50%, #4c1d95 100%)', padding: '56px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <Link href="/esl-resources/reading-comprehension/b1" style={{ color: 'rgba(255,255,255,0.6)', textDecoration: 'none', fontSize: '14px', display: 'inline-block', marginBottom: '20px' }}>← B1 Reading Comprehension</Link>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', flexWrap: 'wrap' }}>
            <div style={{ fontSize: '72px', flexShrink: 0 }}>💉</div>
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '12px' }}>
                <span style={{ background: '#7c3aed', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>B1 Intermediate</span>
                <span style={{ background: 'rgba(99,102,241,0.5)', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>Sport & Society</span>
                <span style={{ background: 'rgba(255,255,255,0.15)', color: 'white', fontSize: '12px', fontWeight: '600', padding: '4px 12px', borderRadius: '20px' }}>4 Parts · 12 Questions</span>
              </div>
              <h1 style={{ color: 'white', fontSize: '32px', fontWeight: 'bold', margin: '0 0 8px', lineHeight: '1.3' }}>Doping in Sport</h1>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '16px', margin: 0, lineHeight: '1.6' }}>Faster, stronger, higher — but at what cost? How athletes cheat with drugs, how they get caught, and why doping remains sport's biggest problem.</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '20px', marginTop: '28px', flexWrap: 'wrap' }}>{[{ icon: '📄', label: '4 reading parts' }, { icon: '💬', label: '12 discussion questions' }, { icon: '📚', label: '16 vocabulary words' }, { icon: '✍️', label: 'Highlight any text' }, { icon: '🌍', label: 'Multi-language lookup' }, { icon: '🤖', label: 'AI conversation partner' }].map(s => <div key={s.label} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'rgba(255,255,255,0.75)', fontSize: '13px' }}><span>{s.icon}</span> {s.label}</div>)}</div>
        </div>
      </section>
      <section style={{ background: 'white', borderBottom: '1px solid #eee', padding: '14px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', alignItems: 'center', marginBottom: '10px' }}><span style={{ color: '#888', fontSize: '12px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>How to use:</span>{['🔊 Play passage aloud', '✍️ Highlight any text for lookup', '🌍 Translate vocab, questions & AI answers', '🤖 Practice with AI'].map((step, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#555', fontSize: '13px' }}><span style={{ background: '#7c3aed', color: 'white', width: '18px', height: '18px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '10px', fontWeight: 'bold', flexShrink: 0 }}>{i + 1}</span>{step}</div>)}</div>
          <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap', alignItems: 'center' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🔊 Speed:</span>{SPEEDS.map(s => <button key={s.value} onClick={() => setSpeed(s.value)} style={{ padding: '4px 12px', borderRadius: '20px', border: '2px solid', borderColor: speed === s.value ? '#7c3aed' : '#e5e7eb', background: speed === s.value ? '#7c3aed' : 'white', color: speed === s.value ? 'white' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', transition: 'all 0.2s' }}>{s.label}</button>)}</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🌍 Translate to:</span><select value={translationLang} onChange={e => { setTranslationLang(e.target.value); setVocabTranslations({}); setQuestionTranslations({}) }} style={{ padding: '5px 12px', borderRadius: '20px', border: '2px solid', borderColor: translationLang !== 'none' ? '#7c3aed' : '#e5e7eb', background: translationLang !== 'none' ? '#faf5ff' : 'white', color: translationLang !== 'none' ? '#4c1d95' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', outline: 'none' }}>{LANGUAGES.map(l => <option key={l.value} value={l.value}>{l.label}</option>)}</select></div>
          </div>
        </div>
      </section>
      <div style={{ maxWidth: '860px', margin: '0 auto', padding: '32px 24px', display: 'flex', flexDirection: 'column', gap: '28px' }}>
        {PARTS.map(part => (
          <div key={part.number} style={{ background: 'white', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 2px 12px rgba(0,0,0,0.07)' }}>
            <div style={{ background: `linear-gradient(135deg, ${part.color}22, ${part.color}08)`, borderLeft: `5px solid ${part.color}`, padding: '20px 24px', display: 'flex', gap: '14px', alignItems: 'center', flexWrap: 'wrap' }}>
              <div style={{ background: part.color, color: 'white', width: '36px', height: '36px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '16px', flexShrink: 0 }}>{part.number}</div>
              <div style={{ flex: 1 }}><div style={{ color: part.color, fontSize: '11px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '2px' }}>Part {part.number}</div><h2 data-passage="true" style={{ color: '#1a1a2e', fontSize: '18px', fontWeight: 'bold', margin: 0, userSelect: 'text', cursor: 'text' }}>{part.emoji} {part.title}</h2></div>
              <div style={{ display: 'flex', gap: '8px', flexShrink: 0 }}><button onClick={() => speakText(part.text.replace(/\n\n/g, ' '))} style={{ background: part.color, color: 'white', border: 'none', padding: '8px 16px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', boxShadow: `0 3px 10px ${part.color}40` }}>▶ Play Passage</button><button onClick={stopAudio} style={{ background: 'white', color: '#6b7280', border: '2px solid #e5e7eb', padding: '8px 12px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer' }}>⏹ Stop</button></div>
            </div>
            <div style={{ background: '#faf5ff', padding: '8px 28px', borderBottom: '1px solid #ede9fe' }}><span style={{ color: '#4c1d95', fontSize: '12px', fontWeight: '600' }}>✍️ Highlight any word or phrase to hear it and see its meaning{translationLang !== 'none' && <span style={{ color: '#7c3aed' }}> + {currentLang?.label} translation</span>}</span></div>
            <div data-passage="true" style={{ padding: '24px 28px 20px', userSelect: 'text', cursor: 'text' }}>{part.text.split('\n\n').map((para, i) => <p key={i} style={{ color: '#374151', fontSize: '16px', lineHeight: '1.85', margin: i === 0 ? '0 0 18px' : '0', fontFamily: 'Georgia, serif' }}>{para}</p>)}</div>
            <div style={{ margin: '0 28px 24px', background: part.color + '08', border: `1px solid ${part.color}25`, borderRadius: '14px', overflow: 'hidden' }}>
              <div style={{ background: part.color + '18', padding: '12px 16px', display: 'flex', alignItems: 'center', gap: '8px', borderBottom: `1px solid ${part.color}20` }}><span style={{ fontSize: '16px' }}>📚</span><span style={{ color: part.color, fontWeight: 'bold', fontSize: '13px', textTransform: 'uppercase', letterSpacing: '1px' }}>Vocabulary — Part {part.number}</span></div>
              <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>{part.vocab.map((v, i) => { const vKey = `${part.number}-${v.word}`; return (<div key={v.word} style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', paddingBottom: i < part.vocab.length - 1 ? '10px' : '0', borderBottom: i < part.vocab.length - 1 ? `1px solid ${part.color}15` : 'none' }}><div style={{ background: part.color, color: 'white', width: '22px', height: '22px', borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '11px', flexShrink: 0, marginTop: '2px' }}>{i + 1}</div><div style={{ flex: 1 }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '3px', flexWrap: 'wrap' }}><span data-passage="true" style={{ fontWeight: 'bold', color: '#1a1a2e', fontSize: '15px', userSelect: 'text', cursor: 'text' }}>{v.word}</span><button onClick={() => speakWord(v.word)} style={{ background: part.color + '15', color: part.color, border: `1px solid ${part.color}30`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0 }}>🔊</button><TranslateBtn text={`Word: "${v.word}"\nDefinition: "${v.definition}"`} type="word" lang={translationLang} color={part.color} onTranslated={(t) => setVocabTranslations(prev => ({ ...prev, [vKey]: t }))} />{translationLang === 'none' && <span style={{ color: '#d1d5db', fontSize: '11px' }}>← select a language to translate</span>}</div><span data-passage="true" style={{ color: '#6b7280', fontSize: '14px', lineHeight: '1.5', userSelect: 'text', cursor: 'text' }}>{v.definition}</span>{vocabTranslations[vKey] && <div style={{ marginTop: '6px', background: '#faf5ff', border: '1px solid #ede9fe', borderRadius: '8px', padding: '8px 12px' }}><span style={{ color: '#4c1d95', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: '#374151', fontSize: '14px', lineHeight: '1.5' }}>{vocabTranslations[vKey]}</span></div>}</div></div>) })}</div>
            </div>
            <div style={{ background: '#1a1a2e', padding: '20px 28px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}><span style={{ fontSize: '18px' }}>💬</span><span style={{ color: '#c4b5fd', fontWeight: 'bold', fontSize: '14px', textTransform: 'uppercase', letterSpacing: '1px' }}>Discussion Questions</span></div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>{part.questions.map(q => (<div key={q.n}><div style={{ display: 'flex', gap: '14px', alignItems: 'flex-start' }}><div style={{ background: part.color, color: 'white', width: '28px', height: '28px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '13px', flexShrink: 0, marginTop: '1px' }}>{q.n}</div><div style={{ flex: 1 }}><p data-passage="true" style={{ color: 'rgba(255,255,255,0.88)', fontSize: '15px', lineHeight: '1.6', margin: '0 0 6px', userSelect: 'text', cursor: 'text' }}>{q.q}</p><div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><TranslateBtn text={q.q} type="question" lang={translationLang} color={part.color} onTranslated={(t) => setQuestionTranslations(prev => ({ ...prev, [q.n]: t }))} />{translationLang === 'none' && <span style={{ color: '#4b5563', fontSize: '11px' }}>← select a language to translate</span>}</div>{questionTranslations[q.n] && <div style={{ marginTop: '8px', background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.3)', borderRadius: '10px', padding: '10px 14px' }}><span style={{ color: '#c4b5fd', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: 'rgba(255,255,255,0.9)', fontSize: '14px', lineHeight: '1.6' }}>{questionTranslations[q.n]}</span></div>}</div></div><div style={{ marginLeft: '42px' }}><ConversationBox question={q.q} color={part.color} translationLang={translationLang} speed={speed} /></div></div>))}</div>
            </div>
          </div>
        ))}
        <div style={{ textAlign: 'center', paddingBottom: selectedText ? '140px' : '16px' }}><Link href="/esl-resources/reading-comprehension/b1" style={{ color: '#7c3aed', textDecoration: 'none', fontWeight: 'bold', fontSize: '14px' }}>← Back to B1 Reading Comprehension</Link></div>
      </div>
      {selectedText && <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 200, animation: 'slideUp 0.25s ease' }}><div style={{ maxWidth: '860px', margin: '0 auto', background: 'white', borderRadius: '20px 20px 0 0', padding: '20px 24px 32px', boxShadow: '0 -8px 32px rgba(0,0,0,0.2)', border: '2px solid #ede9fe', borderBottom: 'none' }}><div style={{ width: '40px', height: '4px', background: '#e5e7eb', borderRadius: '4px', margin: '0 auto 16px' }} /><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}><span style={{ fontSize: '22px', fontWeight: '900', color: '#1a1a2e', fontFamily: 'Georgia, serif' }}>"{selectedText}"</span><button onClick={() => speakWord(selectedText)} style={{ background: '#faf5ff', color: '#4c1d95', border: '2px solid #ede9fe', padding: '6px 14px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', flexShrink: 0 }}>🔊 Hear it</button></div><button onClick={() => setSelectedText(null)} style={{ background: '#f3f4f6', border: 'none', width: '32px', height: '32px', borderRadius: '8px', cursor: 'pointer', fontSize: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#6b7280', flexShrink: 0, marginLeft: '12px' }}>✕</button></div>{lookupLoading ? <div style={{ background: '#faf5ff', borderRadius: '12px', padding: '14px 18px', border: '1px solid #ede9fe', color: '#9ca3af', fontSize: '15px' }}>{translationLang !== 'none' ? `Looking up definition and ${currentLang?.label} translation...` : 'Looking up...'}</div> : <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}><div style={{ background: '#faf5ff', borderRadius: '12px', padding: '14px 18px', border: '1px solid #ede9fe' }}><div style={{ color: '#4c1d95', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>📖 English Definition</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupDef}</span></div>{translationLang !== 'none' && lookupTranslation && <div style={{ background: '#faf5ff', borderRadius: '12px', padding: '14px 18px', border: '1px solid #c4b5fd' }}><div style={{ color: '#5b21b6', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>{currentLang?.label} Translation</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupTranslation}</span></div>}</div>}</div></div>}
    </main>
  )
}
