export const questionBank: Record<string, { q: string; options: string[]; answer: string }[]> = {
  'P1-P2': [
    { q: "What is the opposite of 'big'?", options: ['small', 'tall', 'fast', 'happy'], answer: 'small' },
    { q: 'Which word is a colour?', options: ['dog', 'run', 'blue', 'jump'], answer: 'blue' },
    { q: "How many letters are in the word 'cat'?", options: ['2', '3', '4', '5'], answer: '3' },
    { q: "Which animal says 'moo'?", options: ['pig', 'dog', 'cow', 'cat'], answer: 'cow' },
    { q: 'What comes after Monday?', options: ['Sunday', 'Friday', 'Wednesday', 'Tuesday'], answer: 'Tuesday' },
    { q: "Which word rhymes with 'hat'?", options: ['dog', 'cat', 'big', 'run'], answer: 'cat' },
    { q: 'What do you use to write?', options: ['fork', 'spoon', 'pencil', 'plate'], answer: 'pencil' },
    { q: 'Which is a fruit?', options: ['carrot', 'potato', 'apple', 'broccoli'], answer: 'apple' },
    { q: "What is 'happy' the opposite of?", options: ['sad', 'big', 'fast', 'tall'], answer: 'sad' },
    { q: 'Which word is a number?', options: ['red', 'five', 'dog', 'run'], answer: 'five' },
    { q: 'What colour is the sky?', options: ['green', 'red', 'blue', 'yellow'], answer: 'blue' },
    { q: "Which word means 'a place to sleep'?", options: ['kitchen', 'bedroom', 'garden', 'school'], answer: 'bedroom' },
    { q: 'What do fish live in?', options: ['trees', 'sky', 'water', 'sand'], answer: 'water' },
    { q: 'Which is NOT a day of the week?', options: ['Monday', 'March', 'Friday', 'Sunday'], answer: 'March' },
    { q: 'What sound does a dog make?', options: ['moo', 'oink', 'bark', 'meow'], answer: 'bark' },
    { q: 'Which word is an action word?', options: ['big', 'run', 'dog', 'red'], answer: 'run' },
    { q: 'What is the first letter of the alphabet?', options: ['B', 'C', 'A', 'D'], answer: 'A' },
    { q: 'Which is a vegetable?', options: ['apple', 'banana', 'carrot', 'grape'], answer: 'carrot' },
    { q: 'How many days are in a week?', options: ['5', '6', '8', '7'], answer: '7' },
    { q: "Which word means the opposite of 'hot'?", options: ['warm', 'cold', 'soft', 'loud'], answer: 'cold' },
  ],
  'P3-P4': [
    { q: 'Which word is a noun?', options: ['quickly', 'run', 'beautiful', 'teacher'], answer: 'teacher' },
    { q: "What is the plural of 'child'?", options: ['childs', 'childes', 'children', 'childrens'], answer: 'children' },
    { q: 'Which sentence is correct?', options: ['She go to school', 'She goes to school', 'She going to school', 'She goed to school'], answer: 'She goes to school' },
    { q: "What does 'enormous' mean?", options: ['tiny', 'very large', 'very fast', 'very cold'], answer: 'very large' },
    { q: 'Which word is an adjective?', options: ['jump', 'quickly', 'beautiful', 'teacher'], answer: 'beautiful' },
    { q: "What is the past tense of 'eat'?", options: ['eated', 'eating', 'eats', 'ate'], answer: 'ate' },
    { q: 'Which punctuation ends a question?', options: ['.', '!', ',', '?'], answer: '?' },
    { q: "What does 'nocturnal' mean?", options: ['active at night', 'active in morning', 'very fast', 'very slow'], answer: 'active at night' },
    { q: "Which word means 'very happy'?", options: ['sad', 'angry', 'delighted', 'worried'], answer: 'delighted' },
    { q: "What is a synonym for 'big'?", options: ['tiny', 'small', 'large', 'little'], answer: 'large' },
    { q: 'Which is a compound word?', options: ['beautiful', 'quickly', 'football', 'jumping'], answer: 'football' },
    { q: "What is the opposite of 'ancient'?", options: ['old', 'modern', 'big', 'slow'], answer: 'modern' },
    { q: 'Which word has a silent letter?', options: ['cat', 'run', 'knife', 'dog'], answer: 'knife' },
    { q: "What does 'predict' mean?", options: ['to look back', 'to say what will happen', 'to forget', 'to remember'], answer: 'to say what will happen' },
    { q: "Which uses 'their' correctly?", options: ['Their going home', 'Their is a dog', 'It is their dog', 'There their'], answer: 'It is their dog' },
    { q: 'What is an antonym?', options: ['same meaning', 'opposite meaning', 'a describing word', 'an action word'], answer: 'opposite meaning' },
    { q: 'Which word is spelled correctly?', options: ['beutiful', 'beautiful', 'beautifull', 'beautyful'], answer: 'beautiful' },
    { q: "What does the prefix 'aqua' mean?", options: ['fire', 'earth', 'water', 'air'], answer: 'water' },
    { q: 'Which is a proper noun?', options: ['city', 'Bangkok', 'country', 'school'], answer: 'Bangkok' },
    { q: "What is the subject in: 'The dog runs fast'?", options: ['runs', 'fast', 'The', 'dog'], answer: 'dog' },
  ],
  'P5-P6': [
    { q: 'Which word is a conjunction?', options: ['quickly', 'because', 'beautiful', 'jump'], answer: 'because' },
    { q: "What is the superlative form of 'good'?", options: ['gooder', 'more good', 'best', 'better'], answer: 'best' },
    { q: 'Which sentence is in passive voice?', options: ['The dog bit the man', 'The man was bitten by the dog', 'The man bit the dog', 'The dog runs fast'], answer: 'The man was bitten by the dog' },
    { q: "What does 'ambiguous' mean?", options: ['very clear', 'having two meanings', 'very large', 'very small'], answer: 'having two meanings' },
    { q: 'Which is a metaphor?', options: ['She runs like a cheetah', 'She is a cheetah', 'She runs very fast', 'The fast runner'], answer: 'She is a cheetah' },
    { q: "What does the prefix 'un-' mean?", options: ['again', 'before', 'not', 'after'], answer: 'not' },
    { q: 'Which word means to make something better?', options: ['worsen', 'improve', 'destroy', 'ignore'], answer: 'improve' },
    { q: 'What is an idiom?', options: ['a single word', 'a phrase with a different meaning', 'a type of verb', 'a punctuation mark'], answer: 'a phrase with a different meaning' },
    { q: 'Which sentence contains a simile?', options: ['He is a lion', 'He roared loudly', 'He is as brave as a lion', 'The brave boy'], answer: 'He is as brave as a lion' },
    { q: "What does the suffix '-tion' indicate?", options: ['adjective', 'verb', 'noun', 'adverb'], answer: 'noun' },
    { q: "Which literary device is 'The wind whispered'?", options: ['simile', 'metaphor', 'personification', 'alliteration'], answer: 'personification' },
    { q: "What is the meaning of 'benevolent'?", options: ['cruel', 'kind and generous', 'very angry', 'very scared'], answer: 'kind and generous' },
    { q: "Which word contains a prefix meaning 'wrong'?", options: ['preview', 'misuse', 'rewrite', 'unhappy'], answer: 'misuse' },
    { q: "What is the plural of 'phenomenon'?", options: ['phenomenons', 'phenomena', 'phenomenas', 'phenomenes'], answer: 'phenomena' },
    { q: 'Which is an example of alliteration?', options: ['She sells sea shells', 'The sun is hot', 'He ran quickly', 'I like cats'], answer: 'She sells sea shells' },
    { q: "What does 'persevere' mean?", options: ['to give up', 'to continue despite difficulty', 'to start something', 'to finish quickly'], answer: 'to continue despite difficulty' },
    { q: 'Which has correct subject-verb agreement?', options: ['The team are winning', 'The teams is winning', 'The team is winning', 'The teams are wins'], answer: 'The team is winning' },
    { q: "What is a 'theme' in a story?", options: ['the main character', 'the setting', 'the central message', 'the plot twist'], answer: 'the central message' },
    { q: 'Which word is spelled correctly?', options: ['accomodate', 'accommodate', 'acommodate', 'accommoddate'], answer: 'accommodate' },
    { q: "What does 'rhetoric' mean?", options: ['a type of dance', 'persuasive language', 'a science term', 'a math term'], answer: 'persuasive language' },
  ],
  'M1-M3': [
    { q: 'What is dramatic irony?', options: ["A character says something funny", "The audience knows something the character doesn't", "Two characters disagree", "A character lies"], answer: "The audience knows something the character doesn't" },
    { q: 'What is the subjunctive mood used for?', options: ['expressing facts', 'expressing wishes or hypotheticals', 'expressing commands', 'expressing questions'], answer: 'expressing wishes or hypotheticals' },
    { q: "Which word contains a Latin root meaning 'to carry'?", options: ['telephone', 'transport', 'television', 'telescope'], answer: 'transport' },
    { q: "What is the meaning of 'ephemeral'?", options: ['lasting forever', 'lasting a very short time', 'very large', 'very important'], answer: 'lasting a very short time' },
    { q: 'Which literary device joins contradictory terms?', options: ['simile', 'metaphor', 'oxymoron', 'alliteration'], answer: 'oxymoron' },
    { q: "What is a 'foil' character?", options: ['a villain', 'a character who contrasts the protagonist', 'the narrator', 'the main character'], answer: 'a character who contrasts the protagonist' },
    { q: 'Which uses a semicolon correctly?', options: ['I went; to the store', 'I went to the store; it was closed', 'I went to; the store', 'I; went to the store'], answer: 'I went to the store; it was closed' },
    { q: "What does 'perspicacious' mean?", options: ['having a strong smell', 'having keen insight', 'very large', 'very colorful'], answer: 'having keen insight' },
    { q: 'Which is an example of a paradox?', options: ['The sky is blue', 'Less is more', 'Cats are animals', 'Water is wet'], answer: 'Less is more' },
    { q: "What is 'diction' in writing?", options: ['the plot', 'the setting', 'the choice of words', 'the theme'], answer: 'the choice of words' },
    { q: 'Which word means excessively complimentary?', options: ['critical', 'neutral', 'sycophantic', 'objective'], answer: 'sycophantic' },
    { q: 'What is an anachronism?', options: ['something in the wrong time period', 'a type of metaphor', 'a grammar rule', 'a poetic form'], answer: 'something in the wrong time period' },
    { q: 'Which is an example of synecdoche?', options: ['She is a star', 'All hands on deck', 'Time flies', 'It was raining cats and dogs'], answer: 'All hands on deck' },
    { q: "What does 'equivocate' mean?", options: ['to be very clear', 'to use vague language to deceive', 'to speak loudly', 'to write carefully'], answer: 'to use vague language to deceive' },
    { q: 'Which uses the conditional correctly?', options: ['If I will go, I will see her', 'If I go, I will see her', 'If I go, I would saw her', 'If I went, I will see her'], answer: 'If I go, I will see her' },
    { q: "What is 'stream of consciousness' in writing?", options: ['writing about rivers', 'a technique showing character thoughts', 'a type of poem', 'a dialogue technique'], answer: 'a technique showing character thoughts' },
    { q: "Which contains the Greek root 'graph' meaning to write?", options: ['telephone', 'television', 'autograph', 'microscope'], answer: 'autograph' },
    { q: "What is the meaning of 'zeitgeist'?", options: ['a type of music', 'the spirit or mood of an era', 'a historical event', 'a political system'], answer: 'the spirit or mood of an era' },
    { q: 'Which is an example of metonymy?', options: ['She is a star', 'The crown decided', 'Time flies', 'He is as fast as lightning'], answer: 'The crown decided' },
    { q: "What does 'soliloquy' mean in drama?", options: ['a conversation between two characters', 'a speech given alone on stage', 'a song in a play', 'the final scene'], answer: 'a speech given alone on stage' },
  ],
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}
