export const questionBank: Record<string, { q: string; options: string[]; answer: string }[]> = {
  'P1-P2': [
    // Original 20
    { q: "What is the opposite of 'big'?", options: ['small', 'tall', 'fast', 'happy'], answer: 'small' },
    { q: 'Which word is a colour?', options: ['dog', 'run', 'blue', 'jump'], answer: 'blue' },
    { q: "How many letters are in the word 'cat'?", options: ['2', '3', '4', '5'], answer: '3' },
    { q: "Which animal says 'moo'?", options: ['pig', 'dog', 'cow', 'cat'], answer: 'cow' },
    { q: 'What comes after Monday?', options: ['Sunday', 'Friday', 'Wednesday', 'Tuesday'], answer: 'Tuesday' },
    { q: "Which word rhymes with 'hat'?", options: ['dog', 'cat', 'big', 'run'], answer: 'cat' },
    { q: 'What do you use to write?', options: ['fork', 'spoon', 'pencil', 'plate'], answer: 'pencil' },
    { q: 'Which is a fruit?', options: ['carrot', 'potato', 'apple', 'broccoli'], answer: 'apple' },
    { q: "What is 'happy' the opposite of?", options: ['sad', 'big', 'fast', 'tall'], answer: 'sad' },
    { q: 'Which word is a number?', options: ['red', 'five', 'dog', 'run'], answer: 'five' },
    { q: 'What colour is the sky?', options: ['green', 'red', 'blue', 'yellow'], answer: 'blue' },
    { q: "Which word means 'a place to sleep'?", options: ['kitchen', 'bedroom', 'garden', 'school'], answer: 'bedroom' },
    { q: 'What do fish live in?', options: ['trees', 'sky', 'water', 'sand'], answer: 'water' },
    { q: 'Which is NOT a day of the week?', options: ['Monday', 'March', 'Friday', 'Sunday'], answer: 'March' },
    { q: 'What sound does a dog make?', options: ['moo', 'oink', 'bark', 'meow'], answer: 'bark' },
    { q: 'Which word is an action word?', options: ['big', 'run', 'dog', 'red'], answer: 'run' },
    { q: 'What is the first letter of the alphabet?', options: ['B', 'C', 'A', 'D'], answer: 'A' },
    { q: 'Which is a vegetable?', options: ['apple', 'banana', 'carrot', 'grape'], answer: 'carrot' },
    { q: 'How many days are in a week?', options: ['5', '6', '8', '7'], answer: '7' },
    { q: "Which word means the opposite of 'hot'?", options: ['warm', 'cold', 'soft', 'loud'], answer: 'cold' },
    // New 20
    { q: "Which word rhymes with 'dog'?", options: ['cat', 'log', 'hat', 'cup'], answer: 'log' },
    { q: 'How many letters are in the word "sun"?', options: ['2', '3', '4', '5'], answer: '3' },
    { q: 'Which animal has wings and can fly?', options: ['dog', 'fish', 'bird', 'cat'], answer: 'bird' },
    { q: 'What colour is grass?', options: ['red', 'blue', 'green', 'yellow'], answer: 'green' },
    { q: 'Which comes first in the alphabet — B or D?', options: ['D', 'B', 'They are the same', 'Neither'], answer: 'B' },
    { q: 'What do you wear on your feet?', options: ['hat', 'gloves', 'shoes', 'scarf'], answer: 'shoes' },
    { q: "What is the opposite of 'tall'?", options: ['long', 'wide', 'short', 'heavy'], answer: 'short' },
    { q: 'Which number comes after 9?', options: ['8', '11', '10', '12'], answer: '10' },
    { q: 'What do we use to cut paper?', options: ['pen', 'ruler', 'scissors', 'eraser'], answer: 'scissors' },
    { q: 'Which is a drink?', options: ['apple', 'bread', 'water', 'rice'], answer: 'water' },
    { q: "Which word rhymes with 'book'?", options: ['cake', 'look', 'bell', 'run'], answer: 'look' },
    { q: "What is the opposite of 'day'?", options: ['morning', 'noon', 'night', 'evening'], answer: 'night' },
    { q: 'What do you sit on?', options: ['table', 'lamp', 'chair', 'door'], answer: 'chair' },
    { q: 'Which animal hops?', options: ['fish', 'snake', 'frog', 'cat'], answer: 'frog' },
    { q: 'How many wheels does a bike have?', options: ['1', '2', '3', '4'], answer: '2' },
    { q: 'What colour is a banana?', options: ['red', 'green', 'blue', 'yellow'], answer: 'yellow' },
    { q: "Which word means the opposite of 'open'?", options: ['wide', 'close', 'shut', 'big'], answer: 'shut' },
    { q: 'What do you use to eat soup?', options: ['fork', 'spoon', 'knife', 'chopsticks'], answer: 'spoon' },
    { q: 'Which is NOT a colour?', options: ['red', 'blue', 'run', 'green'], answer: 'run' },
    { q: 'What season comes after summer?', options: ['spring', 'winter', 'autumn', 'summer'], answer: 'autumn' },
  ],
  'P3-P4': [
    // Original 20
    { q: 'Which word is a noun?', options: ['quickly', 'run', 'beautiful', 'teacher'], answer: 'teacher' },
    { q: "What is the plural of 'child'?", options: ['childs', 'childes', 'children', 'childrens'], answer: 'children' },
    { q: 'Which sentence is correct?', options: ['She go to school', 'She goes to school', 'She going to school', 'She goed to school'], answer: 'She goes to school' },
    { q: "What does 'enormous' mean?", options: ['tiny', 'very large', 'very fast', 'very cold'], answer: 'very large' },
    { q: 'Which word is an adjective?', options: ['jump', 'quickly', 'beautiful', 'teacher'], answer: 'beautiful' },
    { q: "What is the past tense of 'eat'?", options: ['eated', 'eating', 'eats', 'ate'], answer: 'ate' },
    { q: 'Which punctuation ends a question?', options: ['.', '!', ',', '?'], answer: '?' },
    { q: "What does 'nocturnal' mean?", options: ['active at night', 'active in morning', 'very fast', 'very slow'], answer: 'active at night' },
    { q: "Which word means 'very happy'?", options: ['sad', 'angry', 'delighted', 'worried'], answer: 'delighted' },
    { q: "What is a synonym for 'big'?", options: ['tiny', 'small', 'large', 'little'], answer: 'large' },
    { q: 'Which is a compound word?', options: ['beautiful', 'quickly', 'football', 'jumping'], answer: 'football' },
    { q: "What is the opposite of 'ancient'?", options: ['old', 'modern', 'big', 'slow'], answer: 'modern' },
    { q: 'Which word has a silent letter?', options: ['cat', 'run', 'knife', 'dog'], answer: 'knife' },
    { q: "What does 'predict' mean?", options: ['to look back', 'to say what will happen', 'to forget', 'to remember'], answer: 'to say what will happen' },
    { q: "Which uses 'their' correctly?", options: ['Their going home', 'Their is a dog', 'It is their dog', 'There their'], answer: 'It is their dog' },
    { q: 'What is an antonym?', options: ['same meaning', 'opposite meaning', 'a describing word', 'an action word'], answer: 'opposite meaning' },
    { q: 'Which word is spelled correctly?', options: ['beutiful', 'beautiful', 'beautifull', 'beautyful'], answer: 'beautiful' },
    { q: "What does the prefix 'aqua' mean?", options: ['fire', 'earth', 'water', 'air'], answer: 'water' },
    { q: 'Which is a proper noun?', options: ['city', 'Bangkok', 'country', 'school'], answer: 'Bangkok' },
    { q: "What is the subject in: 'The dog runs fast'?", options: ['runs', 'fast', 'The', 'dog'], answer: 'dog' },
    // New 20
    { q: "What is the plural of 'mouse'?", options: ['mouses', 'mouse', 'mice', 'mices'], answer: 'mice' },
    { q: "What is the past tense of 'go'?", options: ['goed', 'gone', 'going', 'went'], answer: 'went' },
    { q: "Which word is a verb?", options: ['happy', 'quickly', 'jump', 'large'], answer: 'jump' },
    { q: "What does 'ancient' mean?", options: ['new', 'very old', 'very fast', 'small'], answer: 'very old' },
    { q: "Which word contains a prefix meaning 'not'?", options: ['replay', 'unhappy', 'preview', 'before'], answer: 'unhappy' },
    { q: "What is the plural of 'leaf'?", options: ['leafs', 'leave', 'leaves', 'leafe'], answer: 'leaves' },
    { q: "Which punctuation is used in a list?", options: ['full stop', 'question mark', 'comma', 'apostrophe'], answer: 'comma' },
    { q: "What does 'curious' mean?", options: ['bored', 'angry', 'eager to know', 'very tired'], answer: 'eager to know' },
    { q: "Which is an adverb?", options: ['quickly', 'dog', 'happy', 'jump'], answer: 'quickly' },
    { q: "What does the prefix 're-' mean?", options: ['not', 'before', 'again', 'after'], answer: 'again' },
    { q: "Which sentence uses 'there' correctly?", options: ["There going home", "There is a dog", "I like there dog", "Its over there"], answer: 'There is a dog' },
    { q: "What is the opposite of 'brave'?", options: ['strong', 'cowardly', 'fast', 'kind'], answer: 'cowardly' },
    { q: "Which word rhymes with 'light'?", options: ['late', 'load', 'night', 'land'], answer: 'night' },
    { q: "What does 'furious' mean?", options: ['very happy', 'very cold', 'very angry', 'very tired'], answer: 'very angry' },
    { q: "What is the plural of 'foot'?", options: ['foots', 'feets', 'feet', 'foot'], answer: 'feet' },
    { q: "Which word is a preposition?", options: ['run', 'under', 'happy', 'quickly'], answer: 'under' },
    { q: "What does 'exhausted' mean?", options: ['very happy', 'very hungry', 'very tired', 'very cold'], answer: 'very tired' },
    { q: "Which sentence is in the future tense?", options: ['She ran home', 'She runs home', 'She will run home', 'She is running'], answer: 'She will run home' },
    { q: "What is a homophone?", options: ['words that look the same', 'words that sound the same', 'words that mean the same', 'words that are opposite'], answer: 'words that sound the same' },
    { q: "Which word has a double consonant?", options: ['happy', 'quick', 'brave', 'green'], answer: 'happy' },
  ],
  'P5-P6': [
    // Original 20
    { q: 'Which word is a conjunction?', options: ['quickly', 'because', 'beautiful', 'jump'], answer: 'because' },
    { q: "What is the superlative form of 'good'?", options: ['gooder', 'more good', 'best', 'better'], answer: 'best' },
    { q: 'Which sentence is in passive voice?', options: ['The dog bit the man', 'The man was bitten by the dog', 'The man bit the dog', 'The dog runs fast'], answer: 'The man was bitten by the dog' },
    { q: "What does 'ambiguous' mean?", options: ['very clear', 'having two meanings', 'very large', 'very small'], answer: 'having two meanings' },
    { q: 'Which is a metaphor?', options: ['She runs like a cheetah', 'She is a cheetah', 'She runs very fast', 'The fast runner'], answer: 'She is a cheetah' },
    { q: "What does the prefix 'un-' mean?", options: ['again', 'before', 'not', 'after'], answer: 'not' },
    { q: 'Which word means to make something better?', options: ['worsen', 'improve', 'destroy', 'ignore'], answer: 'improve' },
    { q: 'What is an idiom?', options: ['a single word', 'a phrase with a different meaning', 'a type of verb', 'a punctuation mark'], answer: 'a phrase with a different meaning' },
    { q: 'Which sentence contains a simile?', options: ['He is a lion', 'He roared loudly', 'He is as brave as a lion', 'The brave boy'], answer: 'He is as brave as a lion' },
    { q: "What does the suffix '-tion' indicate?", options: ['adjective', 'verb', 'noun', 'adverb'], answer: 'noun' },
    { q: "Which literary device is 'The wind whispered'?", options: ['simile', 'metaphor', 'personification', 'alliteration'], answer: 'personification' },
    { q: "What is the meaning of 'benevolent'?", options: ['cruel', 'kind and generous', 'very angry', 'very scared'], answer: 'kind and generous' },
    { q: "Which word contains a prefix meaning 'wrong'?", options: ['preview', 'misuse', 'rewrite', 'unhappy'], answer: 'misuse' },
    { q: "What is the plural of 'phenomenon'?", options: ['phenomenons', 'phenomena', 'phenomenas', 'phenomenes'], answer: 'phenomena' },
    { q: 'Which is an example of alliteration?', options: ['She sells sea shells', 'The sun is hot', 'He ran quickly', 'I like cats'], answer: 'She sells sea shells' },
    { q: "What does 'persevere' mean?", options: ['to give up', 'to continue despite difficulty', 'to start something', 'to finish quickly'], answer: 'to continue despite difficulty' },
    { q: 'Which has correct subject-verb agreement?', options: ['The team are winning', 'The teams is winning', 'The team is winning', 'The teams are wins'], answer: 'The team is winning' },
    { q: "What is a 'theme' in a story?", options: ['the main character', 'the setting', 'the central message', 'the plot twist'], answer: 'the central message' },
    { q: 'Which word is spelled correctly?', options: ['accomodate', 'accommodate', 'acommodate', 'accommoddate'], answer: 'accommodate' },
    { q: "What does 'rhetoric' mean?", options: ['a type of dance', 'persuasive language', 'a science term', 'a math term'], answer: 'persuasive language' },
    // New 20
    { q: "What does 'diligent' mean?", options: ['lazy', 'hardworking and careful', 'very clever', 'very fast'], answer: 'hardworking and careful' },
    { q: "Which is an example of hyperbole?", options: ['He ran fast', 'She is tall', 'I have told you a million times', 'The dog barked'], answer: 'I have told you a million times' },
    { q: "What does the prefix 'pre-' mean?", options: ['after', 'again', 'before', 'not'], answer: 'before' },
    { q: "Which word means 'to make something worse'?", options: ['improve', 'exacerbate', 'resolve', 'assist'], answer: 'exacerbate' },
    { q: "What is a protagonist?", options: ['the villain', 'the narrator', 'the main character', 'the setting'], answer: 'the main character' },
    { q: "Which sentence uses the apostrophe correctly?", options: ["Its raining", "The dogs bone", "The dog's bone", "Its' raining"], answer: "The dog's bone" },
    { q: "What does 'vivid' mean?", options: ['dull and grey', 'bright and clear', 'very quiet', 'very old'], answer: 'bright and clear' },
    { q: "What is onomatopoeia?", options: ['a word that looks like its meaning', 'a word that sounds like what it describes', 'a comparing word', 'a describing phrase'], answer: 'a word that sounds like what it describes' },
    { q: "Which is the correct comparative form of 'bad'?", options: ['badder', 'most bad', 'worse', 'worser'], answer: 'worse' },
    { q: "What does 'inevitable' mean?", options: ['surprising', 'impossible', 'certain to happen', 'very unlikely'], answer: 'certain to happen' },
    { q: "Which word contains a suffix meaning 'able to be'?", options: ['quickly', 'comfortable', 'teacher', 'runner'], answer: 'comfortable' },
    { q: "What is the purpose of a colon?", options: ['to end a sentence', 'to introduce a list or explanation', 'to join two words', 'to show possession'], answer: 'to introduce a list or explanation' },
    { q: "What does 'concise' mean?", options: ['very long', 'clear and brief', 'confusing', 'very detailed'], answer: 'clear and brief' },
    { q: "Which is an example of foreshadowing?", options: ['describing the weather', 'a hint about future events', 'describing a character', 'a flashback scene'], answer: 'a hint about future events' },
    { q: "What does 'empathy' mean?", options: ['feeling sorry for yourself', 'understanding how others feel', 'being very angry', 'feeling very happy'], answer: 'understanding how others feel' },
    { q: "Which word is spelled correctly?", options: ['recieve', 'receive', 'recive', 'recieve'], answer: 'receive' },
    { q: "What is the meaning of 'transparent'?", options: ['very dark', 'easy to see through', 'very colourful', 'very heavy'], answer: 'easy to see through' },
    { q: "What is a subordinate clause?", options: ['the main idea of a sentence', 'a clause that cannot stand alone', 'a type of noun', 'a describing word'], answer: 'a clause that cannot stand alone' },
    { q: "What does 'audacious' mean?", options: ['very shy', 'very bold and daring', 'very quiet', 'very slow'], answer: 'very bold and daring' },
    { q: "Which literary device repeats a consonant sound at the start of words?", options: ['assonance', 'rhyme', 'alliteration', 'onomatopoeia'], answer: 'alliteration' },
  ],
  'M1-M3': [
    // Original 20
    { q: 'What is dramatic irony?', options: ["A character says something funny", "The audience knows something the character doesn't", "Two characters disagree", "A character lies"], answer: "The audience knows something the character doesn't" },
    { q: 'What is the subjunctive mood used for?', options: ['expressing facts', 'expressing wishes or hypotheticals', 'expressing commands', 'expressing questions'], answer: 'expressing wishes or hypotheticals' },
    { q: "Which word contains a Latin root meaning 'to carry'?", options: ['telephone', 'transport', 'television', 'telescope'], answer: 'transport' },
    { q: "What is the meaning of 'ephemeral'?", options: ['lasting forever', 'lasting a very short time', 'very large', 'very important'], answer: 'lasting a very short time' },
    { q: 'Which literary device joins contradictory terms?', options: ['simile', 'metaphor', 'oxymoron', 'alliteration'], answer: 'oxymoron' },
    { q: "What is a 'foil' character?", options: ['a villain', 'a character who contrasts the protagonist', 'the narrator', 'the main character'], answer: 'a character who contrasts the protagonist' },
    { q: 'Which uses a semicolon correctly?', options: ['I went; to the store', 'I went to the store; it was closed', 'I went to; the store', 'I; went to the store'], answer: 'I went to the store; it was closed' },
    { q: "What does 'perspicacious' mean?", options: ['having a strong smell', 'having keen insight', 'very large', 'very colorful'], answer: 'having keen insight' },
    { q: 'Which is an example of a paradox?', options: ['The sky is blue', 'Less is more', 'Cats are animals', 'Water is wet'], answer: 'Less is more' },
    { q: "What is 'diction' in writing?", options: ['the plot', 'the setting', 'the choice of words', 'the theme'], answer: 'the choice of words' },
    { q: 'Which word means excessively complimentary?', options: ['critical', 'neutral', 'sycophantic', 'objective'], answer: 'sycophantic' },
    { q: 'What is an anachronism?', options: ['something in the wrong time period', 'a type of metaphor', 'a grammar rule', 'a poetic form'], answer: 'something in the wrong time period' },
    { q: 'Which is an example of synecdoche?', options: ['She is a star', 'All hands on deck', 'Time flies', 'It was raining cats and dogs'], answer: 'All hands on deck' },
    { q: "What does 'equivocate' mean?", options: ['to be very clear', 'to use vague language to deceive', 'to speak loudly', 'to write carefully'], answer: 'to use vague language to deceive' },
    { q: 'Which uses the conditional correctly?', options: ['If I will go, I will see her', 'If I go, I will see her', 'If I go, I would saw her', 'If I went, I will see her'], answer: 'If I go, I will see her' },
    { q: "What is 'stream of consciousness' in writing?", options: ['writing about rivers', 'a technique showing character thoughts', 'a type of poem', 'a dialogue technique'], answer: 'a technique showing character thoughts' },
    { q: "Which contains the Greek root 'graph' meaning to write?", options: ['telephone', 'television', 'autograph', 'microscope'], answer: 'autograph' },
    { q: "What is the meaning of 'zeitgeist'?", options: ['a type of music', 'the spirit or mood of an era', 'a historical event', 'a political system'], answer: 'the spirit or mood of an era' },
    { q: 'Which is an example of metonymy?', options: ['She is a star', 'The crown decided', 'Time flies', 'He is as fast as lightning'], answer: 'The crown decided' },
    { q: "What does 'soliloquy' mean in drama?", options: ['a conversation between two characters', 'a speech given alone on stage', 'a song in a play', 'the final scene'], answer: 'a speech given alone on stage' },
    // New 20
    { q: "What is 'verisimilitude' in fiction?", options: ['an unreliable narrator', 'the appearance of being true or real', 'an unexpected plot twist', 'a circular narrative'], answer: 'the appearance of being true or real' },
    { q: "Which word contains the Latin root 'bene' meaning good?", options: ['malevolent', 'benevolent', 'belligerent', 'ambiguous'], answer: 'benevolent' },
    { q: "What is a 'motif' in literature?", options: ['the main character', 'a recurring element with symbolic meaning', 'the narrative voice', 'the climax of a story'], answer: 'a recurring element with symbolic meaning' },
    { q: "What does 'loquacious' mean?", options: ['very quiet', 'very talkative', 'very clever', 'very angry'], answer: 'very talkative' },
    { q: "What is 'bathos'?", options: ['a type of hero', 'an abrupt shift from serious to trivial', 'a form of rhyme', 'a narrative structure'], answer: 'an abrupt shift from serious to trivial' },
    { q: "Which word contains a Greek root meaning 'love'?", options: ['telescope', 'philosophy', 'geography', 'astronomy'], answer: 'philosophy' },
    { q: "What is an 'unreliable narrator'?", options: ['a narrator who speaks too quickly', 'a narrator whose account may not be accurate', 'a narrator who is anonymous', 'a narrator who speaks in third person'], answer: "a narrator whose account may not be accurate" },
    { q: "What does 'melancholy' mean?", options: ['very angry', 'very confused', 'deep sadness', 'great happiness'], answer: 'deep sadness' },
    { q: "What is 'catharsis' in drama?", options: ['the climax of a play', 'emotional release experienced by the audience', 'a type of tragic character', 'the resolution of a conflict'], answer: 'emotional release experienced by the audience' },
    { q: "Which is an example of litotes?", options: ["He's not bad at football", 'She is a superstar', 'The sun is a golden coin', 'Time is a thief'], answer: "He's not bad at football" },
    { q: "What does 'verbose' mean?", options: ['very brief', 'using too many words', 'very precise', 'very poetic'], answer: 'using too many words' },
    { q: "What is 'hubris' in classical literature?", options: ['extreme wisdom', 'extreme cowardice', 'extreme pride leading to downfall', 'extreme sadness'], answer: 'extreme pride leading to downfall' },
    { q: "What does 'juxtaposition' mean?", options: ['placing two things side by side to highlight contrast', 'repeating the same word', 'using figurative language', 'describing a setting in detail'], answer: 'placing two things side by side to highlight contrast' },
    { q: "What is an 'allegory'?", options: ['a very short poem', 'a story with a deeper symbolic meaning', 'a type of metaphor', 'a narrative told backwards'], answer: 'a story with a deeper symbolic meaning' },
    { q: "What does 'laconic' mean?", options: ['very detailed and long', 'using very few words', 'very emotional', 'very technical'], answer: 'using very few words' },
    { q: "What is 'pathetic fallacy'?", options: ['a flawed argument', 'giving human emotions to nature or weather', 'a type of irony', 'an incorrect comparison'], answer: 'giving human emotions to nature or weather' },
    { q: "What does 'ubiquitous' mean?", options: ['very rare', 'found everywhere', 'very old', 'very new'], answer: 'found everywhere' },
    { q: "What is a 'denouement'?", options: ['the opening of a story', 'the climax', 'the resolution after the climax', 'the main conflict'], answer: 'the resolution after the climax' },
    { q: "What does 'circumlocution' mean?", options: ['using direct language', 'speaking in a roundabout way', 'using technical terms', 'speaking very quickly'], answer: 'speaking in a roundabout way' },
    { q: "What is 'anaphora' as a literary device?", options: ['ending lines with the same word', 'repeating words at the start of successive clauses', 'using contradictory ideas', 'a type of rhyme scheme'], answer: 'repeating words at the start of successive clauses' },
  ],
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}
