export const questionBank: Record<string, Record<string, { q: string; options: string[]; answer: string }[]>> = {
  Animals: {
    Easy: [
      { q: 'Which animal says "meow"?', options: ['Dog', 'Cat', 'Bird', 'Fish'], answer: 'Cat' },
      { q: 'Which animal has a long neck?', options: ['Elephant', 'Tiger', 'Giraffe', 'Monkey'], answer: 'Giraffe' },
      { q: 'Which animal lives in water?', options: ['Lion', 'Fish', 'Horse', 'Rabbit'], answer: 'Fish' },
      { q: 'Which animal has black and white stripes?', options: ['Tiger', 'Cheetah', 'Zebra', 'Panda'], answer: 'Zebra' },
      { q: 'Which animal can fly?', options: ['Snake', 'Dog', 'Eagle', 'Cat'], answer: 'Eagle' },
      { q: 'Which animal is the biggest?', options: ['Dog', 'Mouse', 'Elephant', 'Cat'], answer: 'Elephant' },
      { q: 'Which animal hops?', options: ['Fish', 'Rabbit', 'Snake', 'Turtle'], answer: 'Rabbit' },
      { q: 'Which animal has a shell?', options: ['Dog', 'Bird', 'Turtle', 'Cat'], answer: 'Turtle' },
      { q: "Which animal is called man's best friend?", options: ['Cat', 'Dog', 'Rabbit', 'Fish'], answer: 'Dog' },
      { q: 'Which animal roars?', options: ['Cat', 'Mouse', 'Lion', 'Duck'], answer: 'Lion' },
      { q: 'Which animal has a very long trunk?', options: ['Horse', 'Elephant', 'Rhino', 'Bear'], answer: 'Elephant' },
      { q: 'Which animal makes honey?', options: ['Fly', 'Wasp', 'Bee', 'Ant'], answer: 'Bee' },
      { q: 'Which farm animal says "moo"?', options: ['Pig', 'Sheep', 'Cow', 'Horse'], answer: 'Cow' },
      { q: 'Which animal barks?', options: ['Cat', 'Cow', 'Dog', 'Duck'], answer: 'Dog' },
      { q: 'Which animal gives us wool?', options: ['Cow', 'Goat', 'Sheep', 'Horse'], answer: 'Sheep' },
      { q: 'Which animal is called the king of the jungle?', options: ['Tiger', 'Bear', 'Lion', 'Wolf'], answer: 'Lion' },
      { q: 'Which bird cannot fly?', options: ['Eagle', 'Parrot', 'Penguin', 'Sparrow'], answer: 'Penguin' },
      { q: 'Which animal is black and white and eats bamboo?', options: ['Zebra', 'Panda', 'Skunk', 'Badger'], answer: 'Panda' },
      { q: 'Which animal carries its babies in a pouch?', options: ['Bear', 'Wolf', 'Kangaroo', 'Fox'], answer: 'Kangaroo' },
      { q: 'Which animal is known for its long memory?', options: ['Dog', 'Elephant', 'Cat', 'Horse'], answer: 'Elephant' },
    ],
    Medium: [
      { q: 'Which animal is the fastest on land?', options: ['Lion', 'Horse', 'Cheetah', 'Tiger'], answer: 'Cheetah' },
      { q: 'Which animal has eight legs?', options: ['Ant', 'Bee', 'Spider', 'Fly'], answer: 'Spider' },
      { q: 'Which animal lives in a burrow underground?', options: ['Bird', 'Rabbit', 'Fish', 'Deer'], answer: 'Rabbit' },
      { q: 'Which sea animal has tentacles?', options: ['Shark', 'Dolphin', 'Octopus', 'Whale'], answer: 'Octopus' },
      { q: 'Which animal has a mane around its neck?', options: ['Tiger', 'Leopard', 'Lion', 'Cheetah'], answer: 'Lion' },
      { q: 'Which animal changes colour to hide?', options: ['Frog', 'Lizard', 'Chameleon', 'Snake'], answer: 'Chameleon' },
      { q: 'Which animal has a very bushy tail and lives in trees?', options: ['Rat', 'Squirrel', 'Rabbit', 'Hamster'], answer: 'Squirrel' },
      { q: 'Which animal is the largest in the ocean?', options: ['Shark', 'Dolphin', 'Blue Whale', 'Octopus'], answer: 'Blue Whale' },
      { q: 'Which animal sleeps hanging upside down in caves?', options: ['Owl', 'Bat', 'Eagle', 'Parrot'], answer: 'Bat' },
      { q: 'Which animal is known for spraying a bad smell?', options: ['Fox', 'Skunk', 'Badger', 'Weasel'], answer: 'Skunk' },
      { q: 'Which animal has a pouch and lives in Australia?', options: ['Koala', 'Wombat', 'Kangaroo', 'Dingo'], answer: 'Kangaroo' },
      { q: 'Which insect produces silk?', options: ['Bee', 'Ant', 'Silkworm', 'Butterfly'], answer: 'Silkworm' },
      { q: 'Which animal is famous for its hump?', options: ['Elephant', 'Rhino', 'Camel', 'Buffalo'], answer: 'Camel' },
      { q: 'Which animal is the symbol of Australia?', options: ['Koala', 'Kangaroo', 'Wombat', 'Dingo'], answer: 'Kangaroo' },
      { q: 'Which animal sleeps the most?', options: ['Lion', 'Koala', 'Sloth', 'Bear'], answer: 'Koala' },
      { q: 'Which animal has the strongest bite?', options: ['Lion', 'Shark', 'Crocodile', 'Tiger'], answer: 'Crocodile' },
      { q: 'Which animal can survive without water the longest?', options: ['Camel', 'Elephant', 'Giraffe', 'Horse'], answer: 'Camel' },
      { q: 'Which animal is known to use tools in the wild?', options: ['Lion', 'Horse', 'Chimpanzee', 'Elephant'], answer: 'Chimpanzee' },
      { q: 'Which animal can regrow its tail?', options: ['Snake', 'Frog', 'Lizard', 'Gecko'], answer: 'Gecko' },
      { q: 'Which animal has the thickest skin?', options: ['Elephant', 'Rhino', 'Hippo', 'Crocodile'], answer: 'Rhino' },
    ],
    Hard: [
      { q: 'Which animal has the longest lifespan?', options: ['Elephant', 'Tortoise', 'Whale', 'Parrot'], answer: 'Tortoise' },
      { q: 'Which bird has the widest wingspan?', options: ['Eagle', 'Condor', 'Albatross', 'Pelican'], answer: 'Albatross' },
      { q: 'Which animal is known to laugh?', options: ['Monkey', 'Hyena', 'Dolphin', 'Parrot'], answer: 'Hyena' },
      { q: 'Which fish is known for its electric shock?', options: ['Shark', 'Stingray', 'Electric eel', 'Pufferfish'], answer: 'Electric eel' },
      { q: 'Which animal migrates the furthest each year?', options: ['Whale', 'Eagle', 'Arctic tern', 'Salmon'], answer: 'Arctic tern' },
      { q: 'Which animal has fingerprints similar to humans?', options: ['Gorilla', 'Chimpanzee', 'Koala', 'Orangutan'], answer: 'Koala' },
      { q: 'Which animal can walk on water?', options: ['Frog', 'Duck', 'Basilisk lizard', 'Water snake'], answer: 'Basilisk lizard' },
      { q: 'Which animal has the biggest eyes of any land animal?', options: ['Elephant', 'Horse', 'Ostrich', 'Giraffe'], answer: 'Ostrich' },
      { q: 'Which animal never sleeps?', options: ['Shark', 'Dolphin', 'Bullfrog', 'Tuna'], answer: 'Bullfrog' },
      { q: 'Which animal has blue blood?', options: ['Squid', 'Octopus', 'Horseshoe crab', 'Jellyfish'], answer: 'Horseshoe crab' },
      { q: 'Which animal is the only mammal that can truly fly?', options: ['Flying squirrel', 'Bat', 'Flying lemur', 'Sugar glider'], answer: 'Bat' },
      { q: 'Which animal has the most teeth?', options: ['Shark', 'Crocodile', 'Snail', 'Great white shark'], answer: 'Snail' },
      { q: 'Which animal has the loudest call?', options: ['Elephant', 'Whale', 'Howler monkey', 'Lion'], answer: 'Howler monkey' },
      { q: 'Which animal can survive being frozen solid?', options: ['Arctic fox', 'Polar bear', 'Wood frog', 'Snow leopard'], answer: 'Wood frog' },
      { q: 'Which animal can hold its breath the longest?', options: ['Dolphin', 'Whale', 'Seal', 'Sea turtle'], answer: 'Whale' },
      { q: 'Which animal has the tallest in the world?', options: ['Elephant', 'Giraffe', 'Camel', 'Horse'], answer: 'Giraffe' },
      { q: 'Which animal can walk on water using its feet?', options: ['Frog', 'Duck', 'Basilisk lizard', 'Water snake'], answer: 'Basilisk lizard' },
      { q: 'Which animal is known to laugh like a human?', options: ['Monkey', 'Hyena', 'Dolphin', 'Parrot'], answer: 'Hyena' },
      { q: 'Which animal has the strongest smell detection?', options: ['Dog', 'Bear', 'Shark', 'Moth'], answer: 'Bear' },
      { q: 'Which animal can change its sex during its lifetime?', options: ['Frog', 'Clownfish', 'Seahorse', 'Eel'], answer: 'Clownfish' },
    ],
  },
  Food: {
    Easy: [
      { q: 'Which food is yellow and curved?', options: ['Apple', 'Banana', 'Grape', 'Orange'], answer: 'Banana' },
      { q: 'Which food comes from a chicken?', options: ['Milk', 'Egg', 'Apple', 'Bread'], answer: 'Egg' },
      { q: 'Which food is red and round?', options: ['Banana', 'Grape', 'Tomato', 'Lemon'], answer: 'Tomato' },
      { q: 'Which drink comes from a cow?', options: ['Juice', 'Water', 'Milk', 'Tea'], answer: 'Milk' },
      { q: 'Which food is spicy?', options: ['Ice cream', 'Chilli', 'Banana', 'Milk'], answer: 'Chilli' },
      { q: 'Which food do you eat for breakfast?', options: ['Pizza', 'Cereal', 'Sushi', 'Cake'], answer: 'Cereal' },
      { q: 'Which fruit is orange in colour?', options: ['Apple', 'Banana', 'Orange', 'Grape'], answer: 'Orange' },
      { q: 'Which food is baked in an oven?', options: ['Salad', 'Bread', 'Juice', 'Milk'], answer: 'Bread' },
      { q: 'Which food is sweet and cold?', options: ['Pizza', 'Ice cream', 'Soup', 'Rice'], answer: 'Ice cream' },
      { q: 'Which vegetable is orange and long?', options: ['Pea', 'Tomato', 'Carrot', 'Potato'], answer: 'Carrot' },
      { q: 'Which fruit is small, round and can be red or green?', options: ['Mango', 'Grape', 'Apple', 'Peach'], answer: 'Apple' },
      { q: 'Which food is round and covered in cheese?', options: ['Sushi', 'Pizza', 'Salad', 'Soup'], answer: 'Pizza' },
      { q: 'Which food comes from under the ground?', options: ['Apple', 'Potato', 'Banana', 'Mango'], answer: 'Potato' },
      { q: 'Which food is white, fluffy and eaten with curry?', options: ['Noodles', 'Bread', 'Rice', 'Pasta'], answer: 'Rice' },
      { q: 'Which fruit is green on the outside and red inside?', options: ['Kiwi', 'Mango', 'Watermelon', 'Apple'], answer: 'Watermelon' },
      { q: 'Which food is long, thin and made from wheat?', options: ['Rice', 'Potato', 'Spaghetti', 'Bread'], answer: 'Spaghetti' },
      { q: 'Which drink is hot and made from leaves?', options: ['Juice', 'Milk', 'Tea', 'Water'], answer: 'Tea' },
      { q: 'Which food is yellow and spread on toast?', options: ['Jam', 'Honey', 'Butter', 'Sauce'], answer: 'Butter' },
      { q: 'Which food is grilled and eaten in a bun?', options: ['Salad', 'Soup', 'Burger', 'Pasta'], answer: 'Burger' },
      { q: 'Which vegetable makes your eyes water when you cut it?', options: ['Carrot', 'Potato', 'Onion', 'Tomato'], answer: 'Onion' },
    ],
    Medium: [
      { q: 'Which food is made from soybeans and is white and wobbly?', options: ['Cheese', 'Tofu', 'Butter', 'Cream'], answer: 'Tofu' },
      { q: 'Which food is popular in Japan and made with raw fish and rice?', options: ['Pizza', 'Pasta', 'Sushi', 'Burger'], answer: 'Sushi' },
      { q: 'Which vegetable is green and looks like a tiny tree?', options: ['Pea', 'Spinach', 'Broccoli', 'Cucumber'], answer: 'Broccoli' },
      { q: 'Which food is made from flour, eggs and milk and is flat?', options: ['Cake', 'Pancake', 'Cookie', 'Muffin'], answer: 'Pancake' },
      { q: 'Which fruit has seeds on the outside?', options: ['Apple', 'Mango', 'Strawberry', 'Peach'], answer: 'Strawberry' },
      { q: 'Which food is made by bees from nectar?', options: ['Jam', 'Syrup', 'Honey', 'Butter'], answer: 'Honey' },
      { q: 'Which country invented sushi?', options: ['China', 'Korea', 'Japan', 'Thailand'], answer: 'Japan' },
      { q: 'Which fruit is known as the king of fruits in Thailand?', options: ['Mango', 'Durian', 'Papaya', 'Lychee'], answer: 'Durian' },
      { q: 'Which food is made from curdled milk?', options: ['Butter', 'Yoghurt', 'Cheese', 'Cream'], answer: 'Cheese' },
      { q: 'Which nut grows underground?', options: ['Walnut', 'Almond', 'Peanut', 'Cashew'], answer: 'Peanut' },
      { q: 'Which fruit is 92% water?', options: ['Apple', 'Mango', 'Watermelon', 'Grape'], answer: 'Watermelon' },
      { q: 'Which food is traditionally eaten on Christmas Day in the UK?', options: ['Lamb', 'Chicken', 'Turkey', 'Duck'], answer: 'Turkey' },
      { q: 'Which country is famous for inventing pizza?', options: ['France', 'Spain', 'Italy', 'Greece'], answer: 'Italy' },
      { q: 'Which spice is yellow and used in Thai curry?', options: ['Paprika', 'Turmeric', 'Cumin', 'Cinnamon'], answer: 'Turmeric' },
      { q: 'Which vegetable is also a fruit botanically?', options: ['Carrot', 'Potato', 'Tomato', 'Onion'], answer: 'Tomato' },
      { q: 'Which food is traditionally eaten on Chinese New Year?', options: ['Sushi', 'Dumplings', 'Spring rolls', 'Noodles'], answer: 'Dumplings' },
      { q: 'Which country invented fish and chips?', options: ['Australia', 'USA', 'England', 'Ireland'], answer: 'England' },
      { q: 'Which vegetable is technically a flower?', options: ['Carrot', 'Broccoli', 'Potato', 'Onion'], answer: 'Broccoli' },
      { q: 'Which food is made from fermented cabbage?', options: ['Salad', 'Coleslaw', 'Sauerkraut', 'Kimchi'], answer: 'Kimchi' },
      { q: 'Which food is made from pressed olive fruit?', options: ['Butter', 'Olive oil', 'Vinegar', 'Syrup'], answer: 'Olive oil' },
    ],
    Hard: [
      { q: 'Which spice is the most expensive in the world?', options: ['Vanilla', 'Saffron', 'Cardamom', 'Cinnamon'], answer: 'Saffron' },
      { q: 'Which country invented croissants?', options: ['France', 'Austria', 'Belgium', 'Switzerland'], answer: 'Austria' },
      { q: 'Which food contains the most vitamin C?', options: ['Orange', 'Lemon', 'Kiwi', 'Chilli pepper'], answer: 'Chilli pepper' },
      { q: 'Which country is the largest producer of rice?', options: ['Thailand', 'India', 'China', 'Vietnam'], answer: 'China' },
      { q: 'Which food gives flamingos their pink colour?', options: ['Krill', 'Algae', 'Shrimp', 'Small fish'], answer: 'Shrimp' },
      { q: 'Which food was originally sold as stomach medicine in the 1800s?', options: ['Mustard', 'Vinegar', 'Ketchup', 'Pickle'], answer: 'Ketchup' },
      { q: 'Which sweet food was found in Egyptian tombs still edible after 3000 years?', options: ['Dates', 'Salt', 'Honey', 'Grain'], answer: 'Honey' },
      { q: 'Vanilla flavouring naturally comes from which type of plant?', options: ['A lily', 'A rose', 'An orchid', 'A tulip'], answer: 'An orchid' },
      { q: 'Carrots were originally which colour before they became orange?', options: ['White', 'Yellow', 'Purple', 'Red'], answer: 'Purple' },
      { q: 'Which food is made from churned cream?', options: ['Cheese', 'Yoghurt', 'Butter', 'Cream'], answer: 'Butter' },
      { q: 'Which food is made from fermented grapes?', options: ['Beer', 'Wine', 'Juice', 'Cider'], answer: 'Wine' },
      { q: 'The word "ketchup" originally came from which language?', options: ['Dutch', 'Portuguese', 'Chinese', 'Malay'], answer: 'Chinese' },
      { q: 'Which country consumes more cheese per person than any other?', options: ['Italy', 'Greece', 'France', 'Switzerland'], answer: 'France' },
      { q: 'Which nut is technically a seed and not a true nut?', options: ['Walnut', 'Almond', 'Peanut', 'Cashew'], answer: 'Cashew' },
      { q: 'Which fruit is botanically classified as a berry?', options: ['Strawberry', 'Raspberry', 'Banana', 'Cherry'], answer: 'Banana' },
      { q: 'What percentage of the world\'s almonds come from California?', options: ['40%', '60%', '80%', '90%'], answer: '80%' },
      { q: 'Which food was the first to be microwaved accidentally?', options: ['Popcorn', 'Chocolate', 'Bread', 'Egg'], answer: 'Chocolate' },
      { q: 'Which country drinks the most tea per person in the world?', options: ['China', 'India', 'England', 'Turkey'], answer: 'Turkey' },
      { q: 'What is the most stolen food in the world?', options: ['Chocolate', 'Cheese', 'Meat', 'Seafood'], answer: 'Cheese' },
      { q: 'Which fruit takes two years to grow on its plant?', options: ['Mango', 'Pineapple', 'Papaya', 'Coconut'], answer: 'Pineapple' },
    ],
  },
  Colours: {
    Easy: [
      { q: 'What colour is the sky?', options: ['Red', 'Green', 'Blue', 'Yellow'], answer: 'Blue' },
      { q: 'What colour is grass?', options: ['Blue', 'Green', 'Red', 'Purple'], answer: 'Green' },
      { q: 'What colour is the sun?', options: ['Blue', 'Pink', 'Yellow', 'White'], answer: 'Yellow' },
      { q: 'What colour is a tomato?', options: ['Blue', 'Red', 'Green', 'Orange'], answer: 'Red' },
      { q: 'What colour is snow?', options: ['Black', 'Brown', 'White', 'Grey'], answer: 'White' },
      { q: 'What colour is a pumpkin?', options: ['Purple', 'Orange', 'Blue', 'Red'], answer: 'Orange' },
      { q: 'What colour is a banana?', options: ['Red', 'Green', 'Yellow', 'Blue'], answer: 'Yellow' },
      { q: 'What colour is coal?', options: ['White', 'Red', 'Black', 'Green'], answer: 'Black' },
      { q: 'What colour is a flamingo?', options: ['Blue', 'Pink', 'Green', 'Yellow'], answer: 'Pink' },
      { q: 'What colour is a carrot?', options: ['Orange', 'Blue', 'Purple', 'Green'], answer: 'Orange' },
      { q: 'What colour is a blueberry?', options: ['Red', 'Green', 'Purple', 'Blue'], answer: 'Blue' },
      { q: 'What colour is chocolate?', options: ['Black', 'Brown', 'Red', 'Orange'], answer: 'Brown' },
      { q: 'What colour is a cucumber?', options: ['Yellow', 'Red', 'Green', 'Blue'], answer: 'Green' },
      { q: 'What colour is a lemon?', options: ['Orange', 'Yellow', 'Green', 'White'], answer: 'Yellow' },
      { q: 'What colour is a grape?', options: ['Orange', 'Yellow', 'Purple', 'Blue'], answer: 'Purple' },
      { q: 'What colour is the night sky?', options: ['Blue', 'Grey', 'Black', 'Purple'], answer: 'Black' },
      { q: 'What colour is a fire engine?', options: ['Blue', 'Yellow', 'Red', 'Green'], answer: 'Red' },
      { q: 'What colour is a frog usually?', options: ['Red', 'Blue', 'Green', 'Yellow'], answer: 'Green' },
      { q: 'What colour is a rose?', options: ['Blue', 'Yellow', 'Red', 'Green'], answer: 'Red' },
      { q: 'What colour are teeth supposed to be?', options: ['Yellow', 'White', 'Cream', 'Grey'], answer: 'White' },
    ],
    Medium: [
      { q: 'What colour is an aubergine?', options: ['Green', 'Red', 'Purple', 'Orange'], answer: 'Purple' },
      { q: 'What colour is the ocean?', options: ['Green', 'Blue', 'Grey', 'Teal'], answer: 'Blue' },
      { q: 'What colour is a polar bear?', options: ['Grey', 'Yellow', 'White', 'Cream'], answer: 'White' },
      { q: 'What two colours make green?', options: ['Red and blue', 'Blue and yellow', 'Red and yellow', 'Black and white'], answer: 'Blue and yellow' },
      { q: 'What colour is lavender?', options: ['Pink', 'Purple', 'Blue', 'White'], answer: 'Purple' },
      { q: 'What colour do you get when you mix red and white?', options: ['Orange', 'Purple', 'Pink', 'Peach'], answer: 'Pink' },
      { q: 'What colour is the Eiffel Tower?', options: ['White', 'Silver', 'Brown', 'Grey'], answer: 'Brown' },
      { q: 'What colour is a ripe mango?', options: ['Red', 'Green', 'Yellow', 'Orange'], answer: 'Orange' },
      { q: 'What colour is jade?', options: ['Blue', 'Green', 'Red', 'Yellow'], answer: 'Green' },
      { q: 'What colour is associated with danger or stop?', options: ['Blue', 'Green', 'Red', 'Yellow'], answer: 'Red' },
      { q: 'What colour is a sapphire gemstone?', options: ['Red', 'Green', 'Blue', 'Yellow'], answer: 'Blue' },
      { q: 'What colour is an unripe banana?', options: ['Yellow', 'Brown', 'Green', 'Orange'], answer: 'Green' },
      { q: 'What colour is the planet Mars?', options: ['Blue', 'Yellow', 'Red', 'Orange'], answer: 'Red' },
      { q: 'What colour is associated with royalty?', options: ['Red', 'Gold', 'Purple', 'Blue'], answer: 'Purple' },
      { q: 'What colour do you get mixing blue and red?', options: ['Green', 'Orange', 'Purple', 'Brown'], answer: 'Purple' },
      { q: 'What colour is a post box in the UK?', options: ['Blue', 'Yellow', 'Red', 'Green'], answer: 'Red' },
      { q: 'What colour is a ripe avocado inside?', options: ['White', 'Yellow', 'Green', 'Orange'], answer: 'Green' },
      { q: 'What colour is associated with luck in China?', options: ['Blue', 'White', 'Red', 'Yellow'], answer: 'Red' },
      { q: 'What colour is the Statue of Liberty?', options: ['Brown', 'Grey', 'Green', 'Blue'], answer: 'Green' },
      { q: 'What colour do you get mixing yellow and blue?', options: ['Orange', 'Purple', 'Green', 'Brown'], answer: 'Green' },
    ],
    Hard: [
      { q: 'What colour is the flag of Thailand?', options: ['Red white blue', 'Red white green', 'Blue white yellow', 'Red yellow blue'], answer: 'Red white blue' },
      { q: 'What colour is a school chalkboard?', options: ['Black', 'Green', 'Grey', 'Blue'], answer: 'Green' },
      { q: 'What colour is associated with peace?', options: ['Red', 'Blue', 'White', 'Green'], answer: 'White' },
      { q: 'What colour is the background of the Japanese flag?', options: ['Blue', 'Red', 'White', 'Yellow'], answer: 'White' },
      { q: 'What colour is amber?', options: ['Red', 'Yellow-orange', 'Brown', 'Gold'], answer: 'Yellow-orange' },
      { q: 'What colour is indigo?', options: ['Light blue', 'Dark blue-purple', 'Green', 'Violet'], answer: 'Dark blue-purple' },
      { q: 'What colour is a ruby gemstone?', options: ['Blue', 'Green', 'Red', 'Purple'], answer: 'Red' },
      { q: 'What colour represents new life and nature?', options: ['Blue', 'Red', 'Yellow', 'Green'], answer: 'Green' },
      { q: 'What colour is turquoise closest to?', options: ['Purple', 'Blue-green', 'Pink', 'Yellow'], answer: 'Blue-green' },
      { q: 'What colour is the cross on the Swiss flag?', options: ['Red', 'Blue', 'White', 'Gold'], answer: 'White' },
      { q: 'What colour is a moonstone gemstone?', options: ['Yellow', 'White', 'Blue', 'Green'], answer: 'White' },
      { q: 'What colour do you get mixing red and yellow?', options: ['Purple', 'Green', 'Orange', 'Brown'], answer: 'Orange' },
      { q: 'What colour is the background of the South Korean flag?', options: ['Blue', 'Red', 'White', 'Yellow'], answer: 'White' },
      { q: 'What colour is chartreuse?', options: ['Blue-purple', 'Yellow-green', 'Pink-red', 'Orange-brown'], answer: 'Yellow-green' },
      { q: 'What colour is the background of the Brazilian flag?', options: ['Blue', 'Yellow', 'Green', 'White'], answer: 'Green' },
      { q: 'What colour are veins under your skin?', options: ['Red', 'Blue', 'Purple', 'Green'], answer: 'Blue' },
      { q: 'What colour is the gem tanzanite?', options: ['Red', 'Green', 'Blue-violet', 'Yellow'], answer: 'Blue-violet' },
      { q: 'What colour is the Great Spot on Jupiter?', options: ['Blue', 'White', 'Red', 'Yellow'], answer: 'Red' },
      { q: 'What colour is the sand on Pfeiffer Beach in California?', options: ['White', 'Black', 'Purple', 'Pink'], answer: 'Purple' },
      { q: 'What colour is a healthy liver?', options: ['Pink', 'Red', 'Dark brown', 'Purple'], answer: 'Dark brown' },
    ],
  },
  Numbers: {
    Easy: [
      { q: 'How many days in a week?', options: ['5', '6', '7', '8'], answer: '7' },
      { q: 'How many months in a year?', options: ['10', '11', '12', '13'], answer: '12' },
      { q: 'What is 5 + 3?', options: ['7', '8', '9', '6'], answer: '8' },
      { q: 'What is 10 - 4?', options: ['5', '6', '7', '8'], answer: '6' },
      { q: 'How many fingers on one hand?', options: ['4', '5', '6', '3'], answer: '5' },
      { q: 'What is 2 x 3?', options: ['4', '5', '6', '7'], answer: '6' },
      { q: 'How many sides does a triangle have?', options: ['2', '3', '4', '5'], answer: '3' },
      { q: 'What comes after 19?', options: ['18', '21', '20', '22'], answer: '20' },
      { q: 'How many legs does a spider have?', options: ['6', '7', '8', '10'], answer: '8' },
      { q: 'What is half of 10?', options: ['3', '4', '5', '6'], answer: '5' },
      { q: 'How many sides does a square have?', options: ['3', '4', '5', '6'], answer: '4' },
      { q: 'What is 6 + 7?', options: ['11', '12', '13', '14'], answer: '13' },
      { q: 'How many hours in a day?', options: ['12', '20', '24', '48'], answer: '24' },
      { q: 'What is 15 - 8?', options: ['5', '6', '7', '8'], answer: '7' },
      { q: 'How many legs does a cat have?', options: ['2', '3', '4', '6'], answer: '4' },
      { q: 'How many seconds in one minute?', options: ['30', '60', '100', '120'], answer: '60' },
      { q: 'What is 20 + 20?', options: ['30', '35', '40', '45'], answer: '40' },
      { q: 'How many wheels does a car have?', options: ['2', '3', '4', '6'], answer: '4' },
      { q: 'What is 100 - 50?', options: ['40', '45', '50', '55'], answer: '50' },
      { q: 'How many days in a weekend?', options: ['1', '2', '3', '4'], answer: '2' },
    ],
    Medium: [
      { q: 'What is 4 x 4?', options: ['12', '14', '16', '18'], answer: '16' },
      { q: 'What is 3 x 5?', options: ['12', '13', '14', '15'], answer: '15' },
      { q: 'How many sides does a hexagon have?', options: ['4', '5', '6', '7'], answer: '6' },
      { q: 'What is 9 + 9?', options: ['16', '17', '18', '19'], answer: '18' },
      { q: 'How many minutes in half an hour?', options: ['15', '20', '30', '45'], answer: '30' },
      { q: 'What is 50 + 25?', options: ['65', '70', '75', '80'], answer: '75' },
      { q: 'How many legs does an insect have?', options: ['4', '6', '8', '10'], answer: '6' },
      { q: 'What is 8 x 2?', options: ['14', '15', '16', '17'], answer: '16' },
      { q: 'How many zeros in one hundred?', options: ['1', '2', '3', '4'], answer: '2' },
      { q: 'What is 7 x 3?', options: ['18', '19', '20', '21'], answer: '21' },
      { q: 'How many sides does an octagon have?', options: ['6', '7', '8', '9'], answer: '8' },
      { q: 'What is 25% of 100?', options: ['10', '20', '25', '50'], answer: '25' },
      { q: 'How many weeks in a year?', options: ['48', '50', '52', '54'], answer: '52' },
      { q: 'What is 9 x 9?', options: ['72', '81', '90', '99'], answer: '81' },
      { q: 'How many sides does a pentagon have?', options: ['4', '5', '6', '7'], answer: '5' },
      { q: 'What is 50% of 200?', options: ['50', '75', '100', '150'], answer: '100' },
      { q: 'How many days in a leap year?', options: ['364', '365', '366', '367'], answer: '366' },
      { q: 'What is 7 x 8?', options: ['54', '56', '58', '60'], answer: '56' },
      { q: 'How many centimetres in a metre?', options: ['10', '100', '1000', '10000'], answer: '100' },
      { q: 'What is the square root of 64?', options: ['6', '7', '8', '9'], answer: '8' },
    ],
    Hard: [
      { q: 'What is 12 x 12?', options: ['122', '132', '142', '144'], answer: '144' },
      { q: 'What is 11 x 11?', options: ['111', '121', '131', '141'], answer: '121' },
      { q: 'What is 144 divided by 12?', options: ['10', '11', '12', '13'], answer: '12' },
      { q: 'What is 1000 - 375?', options: ['525', '600', '625', '650'], answer: '625' },
      { q: 'What is 15% of 100?', options: ['10', '12', '15', '20'], answer: '15' },
      { q: 'What is 13 x 13?', options: ['159', '169', '179', '189'], answer: '169' },
      { q: 'How many millimetres in a centimetre?', options: ['5', '10', '100', '1000'], answer: '10' },
      { q: 'What is 75% of 200?', options: ['100', '125', '150', '175'], answer: '150' },
      { q: 'How many sides does a nonagon have?', options: ['7', '8', '9', '10'], answer: '9' },
      { q: 'What is 1000 + 999?', options: ['1888', '1899', '1999', '2000'], answer: '1999' },
      { q: 'What is 6 x 7?', options: ['36', '40', '42', '48'], answer: '42' },
      { q: 'How many metres in a kilometre?', options: ['10', '100', '1000', '10000'], answer: '1000' },
      { q: 'What is the next prime number after 7?', options: ['8', '9', '10', '11'], answer: '11' },
      { q: 'What is 200 divided by 4?', options: ['40', '50', '60', '70'], answer: '50' },
      { q: 'How many degrees in a right angle?', options: ['45', '60', '90', '180'], answer: '90' },
      { q: 'What is 1000 divided by 10?', options: ['10', '100', '1000', '10000'], answer: '100' },
      { q: 'What is the square root of 169?', options: ['11', '12', '13', '14'], answer: '13' },
      { q: 'What is 15% of 300?', options: ['30', '40', '45', '50'], answer: '45' },
      { q: 'How many degrees in a full circle?', options: ['90', '180', '270', '360'], answer: '360' },
      { q: 'What is 2 to the power of 10?', options: ['512', '1024', '2048', '4096'], answer: '1024' },
    ],
  },
  Jobs: {
    Easy: [
      { q: 'Who teaches children at school?', options: ['Doctor', 'Teacher', 'Chef', 'Driver'], answer: 'Teacher' },
      { q: 'Who puts out fires?', options: ['Policeman', 'Firefighter', 'Nurse', 'Pilot'], answer: 'Firefighter' },
      { q: 'Who flies an aeroplane?', options: ['Driver', 'Captain', 'Pilot', 'Sailor'], answer: 'Pilot' },
      { q: 'Who cooks food in a restaurant?', options: ['Waiter', 'Chef', 'Baker', 'Farmer'], answer: 'Chef' },
      { q: 'Who helps sick people?', options: ['Teacher', 'Driver', 'Doctor', 'Farmer'], answer: 'Doctor' },
      { q: 'Who grows food on a farm?', options: ['Pilot', 'Farmer', 'Chef', 'Builder'], answer: 'Farmer' },
      { q: 'Who builds houses?', options: ['Teacher', 'Nurse', 'Builder', 'Chef'], answer: 'Builder' },
      { q: 'Who delivers letters?', options: ['Postman', 'Driver', 'Chef', 'Nurse'], answer: 'Postman' },
      { q: 'Who keeps people safe in a town?', options: ['Teacher', 'Policeman', 'Farmer', 'Chef'], answer: 'Policeman' },
      { q: 'Who looks after teeth?', options: ['Doctor', 'Nurse', 'Dentist', 'Vet'], answer: 'Dentist' },
      { q: 'Who looks after sick animals?', options: ['Doctor', 'Nurse', 'Dentist', 'Vet'], answer: 'Vet' },
      { q: 'Who cuts and styles hair?', options: ['Tailor', 'Barber', 'Nurse', 'Chef'], answer: 'Barber' },
      { q: 'Who makes bread and cakes?', options: ['Chef', 'Farmer', 'Baker', 'Butcher'], answer: 'Baker' },
      { q: 'Who repairs cars?', options: ['Builder', 'Plumber', 'Mechanic', 'Electrician'], answer: 'Mechanic' },
      { q: 'Who fixes water pipes?', options: ['Builder', 'Plumber', 'Mechanic', 'Electrician'], answer: 'Plumber' },
      { q: 'Who fixes electrical problems?', options: ['Builder', 'Plumber', 'Mechanic', 'Electrician'], answer: 'Electrician' },
      { q: 'Who writes books?', options: ['Editor', 'Publisher', 'Author', 'Journalist'], answer: 'Author' },
      { q: 'Who helps customers in a shop?', options: ['Manager', 'Shop assistant', 'Accountant', 'Driver'], answer: 'Shop assistant' },
      { q: 'Who catches fish for a living?', options: ['Farmer', 'Sailor', 'Fisherman', 'Diver'], answer: 'Fisherman' },
      { q: 'Who performs in plays and films?', options: ['Director', 'Writer', 'Actor', 'Producer'], answer: 'Actor' },
    ],
    Medium: [
      { q: 'Who takes photos professionally?', options: ['Artist', 'Journalist', 'Photographer', 'Designer'], answer: 'Photographer' },
      { q: 'Who defends people in court?', options: ['Judge', 'Lawyer', 'Policeman', 'Doctor'], answer: 'Lawyer' },
      { q: 'Who takes care of passengers on a plane?', options: ['Pilot', 'Flight attendant', 'Engineer', 'Guard'], answer: 'Flight attendant' },
      { q: 'Who manages money for a company?', options: ['Lawyer', 'Engineer', 'Accountant', 'Teacher'], answer: 'Accountant' },
      { q: 'Who designs buildings?', options: ['Builder', 'Architect', 'Engineer', 'Plumber'], answer: 'Architect' },
      { q: 'Who performs operations in a hospital?', options: ['Nurse', 'Doctor', 'Surgeon', 'Dentist'], answer: 'Surgeon' },
      { q: 'Who reports the news on TV?', options: ['Actor', 'Journalist', 'Director', 'Presenter'], answer: 'Presenter' },
      { q: 'Who creates software and apps?', options: ['Engineer', 'Designer', 'Programmer', 'Scientist'], answer: 'Programmer' },
      { q: 'Who makes and repairs shoes?', options: ['Tailor', 'Cobbler', 'Weaver', 'Carpenter'], answer: 'Cobbler' },
      { q: 'Who makes clothes by sewing fabric?', options: ['Weaver', 'Cobbler', 'Tailor', 'Knitter'], answer: 'Tailor' },
      { q: 'Who works in space?', options: ['Pilot', 'Astronaut', 'Engineer', 'Scientist'], answer: 'Astronaut' },
      { q: 'Who looks after guests in a hotel?', options: ['Manager', 'Receptionist', 'Concierge', 'Porter'], answer: 'Receptionist' },
      { q: 'Who paints pictures for a living?', options: ['Designer', 'Sculptor', 'Artist', 'Architect'], answer: 'Artist' },
      { q: 'Who digs underground tunnels and mines?', options: ['Builder', 'Miner', 'Engineer', 'Plumber'], answer: 'Miner' },
      { q: 'Who trains athletes to improve performance?', options: ['Teacher', 'Referee', 'Coach', 'Manager'], answer: 'Coach' },
      { q: 'Who manages a football team?', options: ['Coach', 'Referee', 'Manager', 'Captain'], answer: 'Manager' },
      { q: 'Who makes wooden furniture by hand?', options: ['Plumber', 'Joiner', 'Carpenter', 'Builder'], answer: 'Carpenter' },
      { q: 'Who rescues people from the sea?', options: ['Sailor', 'Coastguard', 'Fisherman', 'Diver'], answer: 'Coastguard' },
      { q: 'Who looks after people on a cruise ship?', options: ['Captain', 'Steward', 'Pilot', 'Engineer'], answer: 'Steward' },
      { q: 'Who composes music?', options: ['Conductor', 'Musician', 'Composer', 'Singer'], answer: 'Composer' },
    ],
    Hard: [
      { q: 'Who translates spoken words between languages?', options: ['Author', 'Journalist', 'Interpreter', 'Editor'], answer: 'Interpreter' },
      { q: 'Who creates maps?', options: ['Geologist', 'Cartographer', 'Surveyor', 'Architect'], answer: 'Cartographer' },
      { q: 'Who studies rocks and the Earth?', options: ['Biologist', 'Geologist', 'Astronomer', 'Chemist'], answer: 'Geologist' },
      { q: 'Who studies stars and planets?', options: ['Meteorologist', 'Geologist', 'Astronomer', 'Physicist'], answer: 'Astronomer' },
      { q: 'Who studies ancient civilisations and digs up artefacts?', options: ['Historian', 'Archaeologist', 'Geologist', 'Anthropologist'], answer: 'Archaeologist' },
      { q: 'Who examines dead bodies to find the cause of death?', options: ['Surgeon', 'Pathologist', 'Doctor', 'Coroner'], answer: 'Pathologist' },
      { q: 'Who makes and sells glasses and contact lenses?', options: ['Doctor', 'Optician', 'Pharmacist', 'Surgeon'], answer: 'Optician' },
      { q: 'Who leads an orchestra?', options: ['Composer', 'Musician', 'Conductor', 'Producer'], answer: 'Conductor' },
      { q: 'Who makes medicines available to patients?', options: ['Doctor', 'Nurse', 'Pharmacist', 'Surgeon'], answer: 'Pharmacist' },
      { q: 'Who designs the look of websites and apps?', options: ['Programmer', 'UI designer', 'Engineer', 'Analyst'], answer: 'UI designer' },
      { q: 'Who performs magic tricks on stage?', options: ['Clown', 'Juggler', 'Magician', 'Actor'], answer: 'Magician' },
      { q: 'Who operates heavy machinery on a building site?', options: ['Builder', 'Crane operator', 'Engineer', 'Surveyor'], answer: 'Crane operator' },
      { q: 'Who teaches people to swim?', options: ['Coach', 'Swimming instructor', 'Lifeguard', 'Trainer'], answer: 'Swimming instructor' },
      { q: 'Who drives a taxi?', options: ['Pilot', 'Driver', 'Sailor', 'Engineer'], answer: 'Driver' },
      { q: 'Who looks after passengers on a ship?', options: ['Pilot', 'Sailor', 'Steward', 'Captain'], answer: 'Captain' },
      { q: 'Who studies human societies and cultures?', options: ['Historian', 'Archaeologist', 'Anthropologist', 'Sociologist'], answer: 'Anthropologist' },
      { q: 'Who writes the music score for films?', options: ['Producer', 'Director', 'Composer', 'Sound engineer'], answer: 'Composer' },
      { q: 'Who repairs broken pipes and boilers in your home?', options: ['Electrician', 'Builder', 'Plumber', 'Carpenter'], answer: 'Plumber' },
      { q: 'Who is responsible for a ship\'s navigation?', options: ['Captain', 'First mate', 'Navigator', 'Helmsman'], answer: 'Navigator' },
      { q: 'Who analyses data to help businesses make decisions?', options: ['Programmer', 'Data analyst', 'Engineer', 'Accountant'], answer: 'Data analyst' },
    ],
  },
  'Body Parts': {
    Easy: [
      { q: 'What do you use to see?', options: ['Ears', 'Eyes', 'Nose', 'Mouth'], answer: 'Eyes' },
      { q: 'What do you use to hear?', options: ['Eyes', 'Nose', 'Ears', 'Hands'], answer: 'Ears' },
      { q: 'What do you use to smell?', options: ['Mouth', 'Eyes', 'Nose', 'Ears'], answer: 'Nose' },
      { q: 'What do you kick a ball with?', options: ['Hands', 'Head', 'Feet', 'Ears'], answer: 'Feet' },
      { q: 'What do you use to eat?', options: ['Ears', 'Mouth', 'Eyes', 'Nose'], answer: 'Mouth' },
      { q: 'What sits on top of your body?', options: ['Arm', 'Leg', 'Head', 'Foot'], answer: 'Head' },
      { q: 'What do you write with?', options: ['Feet', 'Ears', 'Hands', 'Nose'], answer: 'Hands' },
      { q: 'What connects your foot to your body?', options: ['Arm', 'Leg', 'Neck', 'Shoulder'], answer: 'Leg' },
      { q: 'What connects your head to your body?', options: ['Arm', 'Neck', 'Leg', 'Shoulder'], answer: 'Neck' },
      { q: 'What pumps blood around your body?', options: ['Brain', 'Lungs', 'Heart', 'Stomach'], answer: 'Heart' },
      { q: 'What do you breathe with?', options: ['Heart', 'Liver', 'Lungs', 'Kidneys'], answer: 'Lungs' },
      { q: 'What do you use to chew food?', options: ['Lips', 'Tongue', 'Teeth', 'Gums'], answer: 'Teeth' },
      { q: 'What is at the end of your arm?', options: ['Elbow', 'Shoulder', 'Wrist', 'Hand'], answer: 'Hand' },
      { q: 'What is at the end of your leg?', options: ['Knee', 'Hip', 'Ankle', 'Foot'], answer: 'Foot' },
      { q: 'What covers and protects your body?', options: ['Hair', 'Nails', 'Skin', 'Bones'], answer: 'Skin' },
      { q: 'What is inside your mouth and helps you taste?', options: ['Teeth', 'Lips', 'Tongue', 'Gums'], answer: 'Tongue' },
      { q: 'What do you use to clap?', options: ['Feet', 'Knees', 'Hands', 'Elbows'], answer: 'Hands' },
      { q: 'What grows on top of your head?', options: ['Skin', 'Nails', 'Hair', 'Fur'], answer: 'Hair' },
      { q: 'What do you use to wave hello?', options: ['Foot', 'Elbow', 'Hand', 'Knee'], answer: 'Hand' },
      { q: 'What part of your face do you wink with?', options: ['Nose', 'Mouth', 'Ear', 'Eye'], answer: 'Eye' },
    ],
    Medium: [
      { q: 'What do you use to think?', options: ['Heart', 'Stomach', 'Brain', 'Lungs'], answer: 'Brain' },
      { q: 'What do you bend in the middle of your arm?', options: ['Wrist', 'Elbow', 'Shoulder', 'Knuckle'], answer: 'Elbow' },
      { q: 'What do you bend in the middle of your leg?', options: ['Hip', 'Ankle', 'Knee', 'Shin'], answer: 'Knee' },
      { q: 'What holds your body upright like a frame?', options: ['Muscles', 'Skin', 'Skeleton', 'Nerves'], answer: 'Skeleton' },
      { q: 'What is at the top of your spine?', options: ['Chest', 'Skull', 'Hip', 'Rib'], answer: 'Skull' },
      { q: 'What helps you balance when you walk?', options: ['Arms', 'Ears', 'Eyes', 'Nose'], answer: 'Ears' },
      { q: 'What connects your arm to your body at the top?', options: ['Elbow', 'Wrist', 'Shoulder', 'Neck'], answer: 'Shoulder' },
      { q: 'What is the coloured part of your eye called?', options: ['Pupil', 'Iris', 'Retina', 'Lens'], answer: 'Iris' },
      { q: 'What is the largest organ in the human body?', options: ['Heart', 'Brain', 'Liver', 'Skin'], answer: 'Skin' },
      { q: 'What connects muscles to bones?', options: ['Ligament', 'Tendon', 'Vein', 'Nerve'], answer: 'Tendon' },
      { q: 'What is the bone that protects your brain?', options: ['Ribcage', 'Spine', 'Skull', 'Pelvis'], answer: 'Skull' },
      { q: 'What filters waste from your blood?', options: ['Liver', 'Lungs', 'Kidneys', 'Stomach'], answer: 'Kidneys' },
      { q: 'What is the muscular bag that digests food?', options: ['Liver', 'Intestine', 'Stomach', 'Pancreas'], answer: 'Stomach' },
      { q: 'What is the white part of your eye called?', options: ['Iris', 'Cornea', 'Sclera', 'Retina'], answer: 'Sclera' },
      { q: 'What is the tube that carries food to your stomach?', options: ['Trachea', 'Larynx', 'Oesophagus', 'Intestine'], answer: 'Oesophagus' },
      { q: 'What connects one bone to another?', options: ['Tendon', 'Muscle', 'Ligament', 'Nerve'], answer: 'Ligament' },
      { q: 'What is the name of your smallest finger?', options: ['Ring finger', 'Index finger', 'Pinky', 'Thumb'], answer: 'Pinky' },
      { q: 'What is the muscle in your upper arm called?', options: ['Tricep', 'Bicep', 'Hamstring', 'Quad'], answer: 'Bicep' },
      { q: 'How many chambers does the human heart have?', options: ['2', '3', '4', '5'], answer: '4' },
      { q: 'What is the largest muscle in the human body?', options: ['Bicep', 'Hamstring', 'Gluteus maximus', 'Quad'], answer: 'Gluteus maximus' },
    ],
    Hard: [
      { q: 'What is the medical term for your kneecap?', options: ['Tibia', 'Fibula', 'Patella', 'Femur'], answer: 'Patella' },
      { q: 'What is the longest bone in the body?', options: ['Spine', 'Arm bone', 'Thigh bone', 'Shin bone'], answer: 'Thigh bone' },
      { q: 'What is the medical name for your voice box?', options: ['Trachea', 'Larynx', 'Pharynx', 'Oesophagus'], answer: 'Larynx' },
      { q: 'How many bones does an adult human body have?', options: ['106', '156', '206', '256'], answer: '206' },
      { q: 'What is the hardest substance in the human body?', options: ['Bone', 'Nail', 'Tooth enamel', 'Cartilage'], answer: 'Tooth enamel' },
      { q: 'What part of the brain controls balance?', options: ['Cerebrum', 'Cerebellum', 'Brain stem', 'Cortex'], answer: 'Cerebellum' },
      { q: 'What is the small dangly thing at the back of your throat?', options: ['Tonsil', 'Uvula', 'Adenoid', 'Epiglottis'], answer: 'Uvula' },
      { q: 'What is the joint between your hand and your arm?', options: ['Elbow', 'Knuckle', 'Wrist', 'Knuckle'], answer: 'Wrist' },
      { q: 'What is the back of your knee called?', options: ['Hamstring', 'Calf', 'Popliteal', 'Shin'], answer: 'Popliteal' },
      { q: 'What is the protective covering of the brain called?', options: ['Cortex', 'Meninges', 'Cerebellum', 'Skull'], answer: 'Meninges' },
      { q: 'What is the soft tissue inside your nose called?', options: ['Cartilage', 'Mucus', 'Bone', 'Membrane'], answer: 'Cartilage' },
      { q: 'What is the small bone at the back of your elbow called?', options: ['Kneecap', 'Funny bone', 'Shinbone', 'Collarbone'], answer: 'Funny bone' },
      { q: 'What is the name for the coloured circle around the nipple?', options: ['Areola', 'Dermis', 'Epidermis', 'Follicle'], answer: 'Areola' },
      { q: 'What is the medical name for the shin bone?', options: ['Fibula', 'Femur', 'Tibia', 'Radius'], answer: 'Tibia' },
      { q: 'What is the name of the bone running along the inside of your lower leg?', options: ['Tibia', 'Fibula', 'Femur', 'Patella'], answer: 'Fibula' },
      { q: 'What is the medical name for the collarbone?', options: ['Sternum', 'Scapula', 'Clavicle', 'Humerus'], answer: 'Clavicle' },
      { q: 'What is the name of the main artery leaving the heart?', options: ['Vena cava', 'Pulmonary artery', 'Aorta', 'Femoral artery'], answer: 'Aorta' },
      { q: 'What is the name of the fluid that lubricates your joints?', options: ['Plasma', 'Lymph', 'Synovial fluid', 'Serum'], answer: 'Synovial fluid' },
      { q: 'What is the medical term for the shoulder blade?', options: ['Clavicle', 'Humerus', 'Scapula', 'Sternum'], answer: 'Scapula' },
      { q: 'What is the name of the smallest bone in the human body?', options: ['Stirrup', 'Anvil', 'Hammer', 'Stapes'], answer: 'Stapes' },
    ],
  },
  Transport: {
    Easy: [
      { q: 'What flies in the sky?', options: ['Car', 'Boat', 'Aeroplane', 'Bus'], answer: 'Aeroplane' },
      { q: 'What travels on rails?', options: ['Car', 'Train', 'Boat', 'Bike'], answer: 'Train' },
      { q: 'What travels on water?', options: ['Car', 'Bus', 'Boat', 'Train'], answer: 'Boat' },
      { q: 'How many wheels does a bicycle have?', options: ['1', '2', '3', '4'], answer: '2' },
      { q: 'What do you call a big red vehicle in the UK?', options: ['Train', 'Tram', 'Bus', 'Taxi'], answer: 'Bus' },
      { q: 'What do astronauts travel in?', options: ['Plane', 'Rocket', 'Boat', 'Helicopter'], answer: 'Rocket' },
      { q: 'What vehicle has a driver and a meter?', options: ['Bus', 'Train', 'Taxi', 'Tram'], answer: 'Taxi' },
      { q: 'What do you pedal?', options: ['Car', 'Bike', 'Bus', 'Boat'], answer: 'Bike' },
      { q: 'What has blades on top and flies?', options: ['Plane', 'Rocket', 'Helicopter', 'Jet'], answer: 'Helicopter' },
      { q: 'What vehicle do firefighters use?', options: ['Ambulance', 'Police car', 'Fire engine', 'Bus'], answer: 'Fire engine' },
      { q: 'What carries sick people to hospital quickly?', options: ['Taxi', 'Bus', 'Ambulance', 'Van'], answer: 'Ambulance' },
      { q: 'What vehicle do police officers drive?', options: ['Ambulance', 'Police car', 'Fire engine', 'Van'], answer: 'Police car' },
      { q: 'What do farmers use to work in fields?', options: ['Van', 'Lorry', 'Tractor', 'Bus'], answer: 'Tractor' },
      { q: 'What carries heavy loads on a road?', options: ['Car', 'Van', 'Lorry', 'Bus'], answer: 'Lorry' },
      { q: 'What is a two-wheeled vehicle with an engine called?', options: ['Bicycle', 'Scooter', 'Motorcycle', 'Moped'], answer: 'Motorcycle' },
      { q: 'What carries passengers across a river or short sea crossing?', options: ['Yacht', 'Ferry', 'Canoe', 'Submarine'], answer: 'Ferry' },
      { q: 'What vehicle delivers packages to your door?', options: ['Taxi', 'Delivery van', 'Bus', 'Lorry'], answer: 'Delivery van' },
      { q: 'What pulls a carriage with no engine?', options: ['Tractor', 'Horse', 'Lorry', 'Van'], answer: 'Horse' },
      { q: 'What is a very large aeroplane called?', options: ['Jet', 'Jumbo jet', 'Glider', 'Helicopter'], answer: 'Jumbo jet' },
      { q: 'What vehicle carries goods on its back called?', options: ['Van', 'Lorry', 'Pickup truck', 'Flatbed'], answer: 'Pickup truck' },
    ],
    Medium: [
      { q: 'What vehicle runs on electricity and shares the road with cars?', options: ['Bus', 'Train', 'Tram', 'Taxi'], answer: 'Tram' },
      { q: 'What do you ride on one wheel?', options: ['Bike', 'Scooter', 'Unicycle', 'Skateboard'], answer: 'Unicycle' },
      { q: 'What carries oil across the ocean?', options: ['Ferry', 'Yacht', 'Tanker', 'Canoe'], answer: 'Tanker' },
      { q: 'What is a fast train called?', options: ['Express train', 'Bullet train', 'Steam train', 'Tram'], answer: 'Bullet train' },
      { q: 'What vehicle travels under the sea?', options: ['Ship', 'Submarine', 'Ferry', 'Yacht'], answer: 'Submarine' },
      { q: 'What do you use to travel underground in a city?', options: ['Tram', 'Bus', 'Metro', 'Taxi'], answer: 'Metro' },
      { q: 'What is a small fast boat called?', options: ['Ferry', 'Tanker', 'Speedboat', 'Canoe'], answer: 'Speedboat' },
      { q: 'What kind of plane has no engine?', options: ['Jet', 'Helicopter', 'Glider', 'Rocket'], answer: 'Glider' },
      { q: 'What vehicle goes up and down mountains on a cable?', options: ['Tram', 'Funicular', 'Cable car', 'Train'], answer: 'Cable car' },
      { q: 'What do you use to carry goods on a river?', options: ['Yacht', 'Speedboat', 'Barge', 'Ferry'], answer: 'Barge' },
      { q: 'What vehicle carries many passengers on a motorway?', options: ['Taxi', 'Car', 'Coach', 'Tram'], answer: 'Coach' },
      { q: 'What do you stand on and kick to move along?', options: ['Bike', 'Skateboard', 'Unicycle', 'Scooter'], answer: 'Skateboard' },
      { q: 'What powered the first steam trains?', options: ['Coal', 'Oil', 'Gas', 'Electricity'], answer: 'Coal' },
      { q: 'What do you call a boat with two hulls?', options: ['Monohull', 'Trimaran', 'Catamaran', 'Pontoon'], answer: 'Catamaran' },
      { q: 'What vehicle is used to fight fires from the air?', options: ['Helicopter', 'Jet', 'Water bomber', 'Drone'], answer: 'Water bomber' },
      { q: 'What carries skiers up a mountain?', options: ['Cable car', 'Funicular', 'Ski lift', 'Gondola'], answer: 'Ski lift' },
      { q: 'What vehicle is powered by the wind using sails?', options: ['Motorboat', 'Ferry', 'Sailing boat', 'Canoe'], answer: 'Sailing boat' },
      { q: 'What is a vehicle that travels on a cushion of air?', options: ['Submarine', 'Hovercraft', 'Hydrofoil', 'Catamaran'], answer: 'Hovercraft' },
      { q: 'What is an electric personal transport board called?', options: ['Skateboard', 'Hoverboard', 'Segway', 'Scooter'], answer: 'Hoverboard' },
      { q: 'What delivers fresh milk in the UK?', options: ['Van', 'Lorry', 'Milk float', 'Truck'], answer: 'Milk float' },
    ],
    Hard: [
      { q: 'What is the fastest passenger aircraft ever?', options: ['Boeing 747', 'Concorde', 'Airbus A380', 'Boeing 787'], answer: 'Concorde' },
      { q: 'What country invented the first car?', options: ['USA', 'UK', 'France', 'Germany'], answer: 'Germany' },
      { q: 'What is the fear of flying called?', options: ['Claustrophobia', 'Aviophobia', 'Acrophobia', 'Agoraphobia'], answer: 'Aviophobia' },
      { q: 'What fuel do most aeroplanes use?', options: ['Petrol', 'Diesel', 'Jet fuel', 'Hydrogen'], answer: 'Jet fuel' },
      { q: 'What is the world\'s longest railway?', options: ['Silk Road', 'Trans-Siberian', 'Orient Express', 'Blue Train'], answer: 'Trans-Siberian' },
      { q: 'What do you call the front of a ship?', options: ['Stern', 'Port', 'Bow', 'Hull'], answer: 'Bow' },
      { q: 'What is the back of a ship called?', options: ['Bow', 'Port', 'Starboard', 'Stern'], answer: 'Stern' },
      { q: 'What is Thailand\'s national airline called?', options: ['Air Asia', 'Bangkok Airways', 'Thai Airways', 'Nok Air'], answer: 'Thai Airways' },
      { q: 'What is the fastest train in the world associated with?', options: ['Germany', 'China', 'Japan', 'France'], answer: 'Japan' },
      { q: 'What is the tunnel connecting England and France called?', options: ['Euro Tunnel', 'Channel Tunnel', 'Cross-Sea Tunnel', 'Anglo Tunnel'], answer: 'Channel Tunnel' },
      { q: 'What vehicle does the Pope travel in?', options: ['Limousine', 'Bullet car', 'Popemobile', 'Carriage'], answer: 'Popemobile' },
      { q: 'What is an airport vehicle that tows planes called?', options: ['Tractor', 'Tug', 'Forklift', 'Shuttle'], answer: 'Tug' },
      { q: 'What is a vehicle that travels on both land and water?', options: ['Hovercraft', 'Submarine', 'Speedboat', 'Amphibious vehicle'], answer: 'Amphibious vehicle' },
      { q: 'What vehicle is used to spray crops from the air?', options: ['Helicopter', 'Crop duster', 'Drone', 'Glider'], answer: 'Crop duster' },
      { q: 'What is the left side of a ship called when facing forward?', options: ['Starboard', 'Stern', 'Port', 'Bow'], answer: 'Port' },
      { q: 'What vehicle travels on a monorail?', options: ['Tram', 'Train', 'Monorail train', 'Cable car'], answer: 'Monorail train' },
      { q: 'What is the name of the space vehicle that astronauts use to move in space?', options: ['Rocket', 'Space shuttle', 'Space rover', 'Satellite'], answer: 'Space shuttle' },
      { q: 'What is a hydrofoil?', options: ['A type of submarine', 'A boat that lifts above water on foils', 'A type of hovercraft', 'A solar powered boat'], answer: 'A boat that lifts above water on foils' },
      { q: 'What does ABS stand for in cars?', options: ['Automatic Braking System', 'Anti-lock Braking System', 'Advanced Brake Safety', 'Assisted Braking Sensor'], answer: 'Anti-lock Braking System' },
      { q: 'What is the name of the first commercial supersonic passenger aircraft?', options: ['Concorde', 'Tu-144', 'Boeing 2707', 'Airbus A380'], answer: 'Concorde' },
    ],
  },
  Weather: {
    Easy: [
      { q: 'What do you call water falling from the sky?', options: ['Snow', 'Rain', 'Hail', 'Fog'], answer: 'Rain' },
      { q: 'What is frozen rain called?', options: ['Fog', 'Rain', 'Snow', 'Hail'], answer: 'Snow' },
      { q: 'What do we call a very strong wind?', options: ['Breeze', 'Storm', 'Drizzle', 'Fog'], answer: 'Storm' },
      { q: 'What do you see in the sky after rain?', options: ['Cloud', 'Rainbow', 'Star', 'Moon'], answer: 'Rainbow' },
      { q: 'What is it called when you cannot see because of thick mist?', options: ['Rain', 'Snow', 'Fog', 'Wind'], answer: 'Fog' },
      { q: 'What do we call a very hot sunny day?', options: ['Cloudy', 'Rainy', 'Heatwave', 'Foggy'], answer: 'Heatwave' },
      { q: 'What protects you from rain?', options: ['Hat', 'Scarf', 'Umbrella', 'Gloves'], answer: 'Umbrella' },
      { q: 'What is thunder?', options: ['Bright light', 'Loud sound', 'Strong wind', 'Heavy rain'], answer: 'Loud sound' },
      { q: 'What season has the most snow?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], answer: 'Winter' },
      { q: 'What is the bright flash in a storm called?', options: ['Thunder', 'Lightning', 'Rainbow', 'Aurora'], answer: 'Lightning' },
      { q: 'What is it called when the sky is full of clouds?', options: ['Sunny', 'Cloudy', 'Windy', 'Foggy'], answer: 'Cloudy' },
      { q: 'What do you wear to keep warm in cold weather?', options: ['T-shirt', 'Shorts', 'Coat', 'Sandals'], answer: 'Coat' },
      { q: 'What season comes after winter?', options: ['Summer', 'Autumn', 'Spring', 'Winter'], answer: 'Spring' },
      { q: 'What season has the longest days?', options: ['Spring', 'Winter', 'Autumn', 'Summer'], answer: 'Summer' },
      { q: 'What do you build in the garden when it snows?', options: ['Sandcastle', 'Snowman', 'Treehouse', 'Kennel'], answer: 'Snowman' },
      { q: 'What season do leaves fall from trees?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], answer: 'Autumn' },
      { q: 'What do farmers need for their crops to grow?', options: ['Snow', 'Hail', 'Rain', 'Fog'], answer: 'Rain' },
      { q: 'What is very light rain called?', options: ['Drizzle', 'Downpour', 'Shower', 'Storm'], answer: 'Drizzle' },
      { q: 'What is it called when temperature drops below zero?', options: ['Heatwave', 'Frost', 'Drizzle', 'Fog'], answer: 'Frost' },
      { q: 'What is a mix of rain and snow called?', options: ['Hail', 'Frost', 'Sleet', 'Drizzle'], answer: 'Sleet' },
    ],
    Medium: [
      { q: 'What do we call a tropical storm?', options: ['Blizzard', 'Typhoon', 'Drizzle', 'Breeze'], answer: 'Typhoon' },
      { q: 'What is a light gentle wind called?', options: ['Gale', 'Hurricane', 'Breeze', 'Tornado'], answer: 'Breeze' },
      { q: 'What is a spinning column of air called?', options: ['Hurricane', 'Blizzard', 'Tornado', 'Typhoon'], answer: 'Tornado' },
      { q: 'What is it called when ice pellets fall from the sky?', options: ['Snow', 'Rain', 'Hail', 'Sleet'], answer: 'Hail' },
      { q: 'What instrument measures temperature?', options: ['Barometer', 'Thermometer', 'Compass', 'Scale'], answer: 'Thermometer' },
      { q: 'What is a very heavy rainstorm called?', options: ['Drizzle', 'Shower', 'Downpour', 'Mist'], answer: 'Downpour' },
      { q: 'What is a snowstorm called?', options: ['Typhoon', 'Blizzard', 'Tornado', 'Hurricane'], answer: 'Blizzard' },
      { q: 'What is the instrument that measures air pressure?', options: ['Thermometer', 'Compass', 'Barometer', 'Scale'], answer: 'Barometer' },
      { q: 'What is a large rotating tropical storm over the ocean?', options: ['Tornado', 'Blizzard', 'Hurricane', 'Typhoon'], answer: 'Hurricane' },
      { q: 'What do you call a sudden heavy rain shower?', options: ['Drizzle', 'Squall', 'Mist', 'Fog'], answer: 'Squall' },
      { q: 'What causes the sound of thunder?', options: ['Lightning', 'Clouds colliding', 'Rapid air expansion', 'Rain'], answer: 'Rapid air expansion' },
      { q: 'What is the eye of a hurricane?', options: ['The outer edge', 'The calm centre', 'The rainiest part', 'The fastest winds'], answer: 'The calm centre' },
      { q: 'What season is it in Australia when it is winter in Thailand?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], answer: 'Summer' },
      { q: 'What causes auroras in the sky?', options: ['Lightning', 'Solar winds', 'Moonlight', 'Clouds'], answer: 'Solar winds' },
      { q: 'What is a weather vane used to measure?', options: ['Temperature', 'Rainfall', 'Wind direction', 'Air pressure'], answer: 'Wind direction' },
      { q: 'What country experiences the most tornadoes?', options: ['Australia', 'Russia', 'USA', 'Brazil'], answer: 'USA' },
      { q: 'What instrument measures wind speed?', options: ['Barometer', 'Thermometer', 'Anemometer', 'Hygrometer'], answer: 'Anemometer' },
      { q: 'What do clouds form from?', options: ['Dust', 'Water vapour', 'Smoke', 'Ice'], answer: 'Water vapour' },
      { q: 'What season does Thailand have a monsoon?', options: ['Winter', 'Spring', 'Summer', 'Autumn'], answer: 'Summer' },
      { q: 'What is a cold snap?', options: ['A sudden heatwave', 'A sudden drop in temperature', 'A heavy snowfall', 'A strong wind'], answer: 'A sudden drop in temperature' },
    ],
    Hard: [
      { q: 'What is a scientist who studies weather called?', options: ['Geologist', 'Meteorologist', 'Biologist', 'Astronomer'], answer: 'Meteorologist' },
      { q: 'What is a haboob?', options: ['A type of rain', 'A dust storm', 'A snowstorm', 'A tornado'], answer: 'A dust storm' },
      { q: 'What is the driest type of climate called?', options: ['Tropical', 'Polar', 'Arid', 'Temperate'], answer: 'Arid' },
      { q: 'What is the hottest temperature ever recorded on Earth?', options: ['54°C', '58°C', '62°C', '66°C'], answer: '58°C' },
      { q: 'What is the rainiest country in the world?', options: ['India', 'Brazil', 'Colombia', 'Bangladesh'], answer: 'Colombia' },
      { q: 'What is the name of the scale used to measure hurricane strength?', options: ['Beaufort scale', 'Richter scale', 'Saffir-Simpson scale', 'Fujita scale'], answer: 'Saffir-Simpson scale' },
      { q: 'What is it called when warm and cold air meet and create storms?', options: ['Front', 'Cyclone', 'Pressure zone', 'Vortex'], answer: 'Front' },
      { q: 'What is the name of the layer of atmosphere closest to Earth?', options: ['Stratosphere', 'Mesosphere', 'Troposphere', 'Thermosphere'], answer: 'Troposphere' },
      { q: 'What is the Beaufort scale used to measure?', options: ['Temperature', 'Rainfall', 'Wind strength', 'Air pressure'], answer: 'Wind strength' },
      { q: 'What is a weather balloon used for?', options: ['Predicting storms', 'Measuring upper atmosphere conditions', 'Tracking hurricanes', 'Seeding clouds'], answer: 'Measuring upper atmosphere conditions' },
      { q: 'What causes the wind to blow?', options: ['Temperature differences', 'Rain clouds', 'Ocean currents', 'The moon'], answer: 'Temperature differences' },
      { q: 'What is the term for rain that is acidic?', options: ['Hard rain', 'Acid rain', 'Chemical rain', 'Toxic rain'], answer: 'Acid rain' },
      { q: 'What is the name of the warm ocean current that affects weather?', options: ['La Nina', 'El Nino', 'Gulf Stream', 'Monsoon'], answer: 'El Nino' },
      { q: 'What is the wettest city in the world?', options: ['Bangkok', 'Mumbai', 'Mawsynram', 'Singapore'], answer: 'Mawsynram' },
      { q: 'What is it called when hot air rises and cool air rushes in?', options: ['Breeze', 'Gale', 'Wind', 'Tornado'], answer: 'Wind' },
      { q: 'What is the average temperature on the surface of the sun?', options: ['1000°C', '5500°C', '10000°C', '50000°C'], answer: '5500°C' },
      { q: 'What is the name of the scale used to measure tornado strength?', options: ['Beaufort scale', 'Richter scale', 'Saffir-Simpson scale', 'Fujita scale'], answer: 'Fujita scale' },
      { q: 'What is the term for a cloud at ground level?', options: ['Mist', 'Fog', 'Smog', 'Haze'], answer: 'Fog' },
      { q: 'What percentage of the Earth\'s surface is covered by clouds at any given time?', options: ['30%', '50%', '67%', '85%'], answer: '67%' },
      { q: 'What is the name for a weather system with low air pressure at its centre?', options: ['Anticyclone', 'Cyclone', 'Front', 'Isobar'], answer: 'Cyclone' },
    ],
  },
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}