export const questionBank: Record<string, { q: string; options: string[]; answer: string }[]> = {
  Animals: [
    { q: 'Which animal says "meow"?', options: ['Dog', 'Cat', 'Bird', 'Fish'], answer: 'Cat' },
    { q: 'Which animal has a long neck?', options: ['Elephant', 'Tiger', 'Giraffe', 'Monkey'], answer: 'Giraffe' },
    { q: 'Which animal lives in water?', options: ['Lion', 'Fish', 'Horse', 'Rabbit'], answer: 'Fish' },
    { q: 'Which animal has black and white stripes?', options: ['Tiger', 'Cheetah', 'Zebra', 'Panda'], answer: 'Zebra' },
    { q: 'Which animal can fly?', options: ['Snake', 'Dog', 'Eagle', 'Cat'], answer: 'Eagle' },
    { q: 'Which animal is the biggest?', options: ['Dog', 'Mouse', 'Elephant', 'Cat'], answer: 'Elephant' },
    { q: 'Which animal hops?', options: ['Fish', 'Rabbit', 'Snake', 'Turtle'], answer: 'Rabbit' },
    { q: 'Which animal has a shell?', options: ['Dog', 'Bird', 'Turtle', 'Cat'], answer: 'Turtle' },
    { q: "Which animal is called man's best friend?", options: ['Cat', 'Dog', 'Rabbit', 'Fish'], answer: 'Dog' },
    { q: 'Which animal roars?', options: ['Cat', 'Mouse', 'Lion', 'Duck'], answer: 'Lion' },
    { q: 'Which animal has a very long trunk?', options: ['Horse', 'Elephant', 'Rhino', 'Bear'], answer: 'Elephant' },
    { q: 'Which animal is the fastest on land?', options: ['Lion', 'Horse', 'Cheetah', 'Tiger'], answer: 'Cheetah' },
    { q: 'Which animal has eight legs?', options: ['Ant', 'Bee', 'Spider', 'Fly'], answer: 'Spider' },
    { q: 'Which animal lives in a burrow underground?', options: ['Bird', 'Rabbit', 'Fish', 'Deer'], answer: 'Rabbit' },
    { q: 'Which animal has a mane around its neck?', options: ['Tiger', 'Leopard', 'Lion', 'Cheetah'], answer: 'Lion' },
    { q: 'Which bird cannot fly?', options: ['Eagle', 'Parrot', 'Penguin', 'Sparrow'], answer: 'Penguin' },
    { q: 'Which animal is black and white and eats bamboo?', options: ['Zebra', 'Panda', 'Skunk', 'Badger'], answer: 'Panda' },
    { q: 'Which sea animal has tentacles?', options: ['Shark', 'Dolphin', 'Octopus', 'Whale'], answer: 'Octopus' },
    { q: 'Which animal carries its babies in a pouch?', options: ['Bear', 'Wolf', 'Kangaroo', 'Fox'], answer: 'Kangaroo' },
    { q: 'Which animal is known for its long memory?', options: ['Dog', 'Elephant', 'Cat', 'Horse'], answer: 'Elephant' },
    { q: 'Which animal barks?', options: ['Cat', 'Cow', 'Dog', 'Duck'], answer: 'Dog' },
    { q: 'Which animal gives us wool?', options: ['Cow', 'Goat', 'Sheep', 'Horse'], answer: 'Sheep' },
    { q: 'Which animal is called the king of the jungle?', options: ['Tiger', 'Bear', 'Lion', 'Wolf'], answer: 'Lion' },
    { q: 'Which animal changes colour to hide?', options: ['Frog', 'Lizard', 'Chameleon', 'Snake'], answer: 'Chameleon' },
    { q: 'Which animal has a very bushy tail and lives in trees?', options: ['Rat', 'Squirrel', 'Rabbit', 'Hamster'], answer: 'Squirrel' },
    { q: 'Which animal makes honey?', options: ['Fly', 'Wasp', 'Bee', 'Ant'], answer: 'Bee' },
    { q: 'Which animal is the largest in the ocean?', options: ['Shark', 'Dolphin', 'Blue Whale', 'Octopus'], answer: 'Blue Whale' },
    { q: 'Which farm animal says "moo"?', options: ['Pig', 'Sheep', 'Cow', 'Horse'], answer: 'Cow' },
    { q: 'Which animal sleeps hanging upside down in caves?', options: ['Owl', 'Bat', 'Eagle', 'Parrot'], answer: 'Bat' },
    { q: 'Which animal has a very long neck to reach tall trees?', options: ['Camel', 'Giraffe', 'Elephant', 'Horse'], answer: 'Giraffe' },
  ],
  Food: [
    { q: 'Which food is yellow and curved?', options: ['Apple', 'Banana', 'Grape', 'Orange'], answer: 'Banana' },
    { q: 'Which food comes from a chicken?', options: ['Milk', 'Egg', 'Apple', 'Bread'], answer: 'Egg' },
    { q: 'Which food is red and round?', options: ['Banana', 'Grape', 'Tomato', 'Lemon'], answer: 'Tomato' },
    { q: 'Which drink comes from a cow?', options: ['Juice', 'Water', 'Milk', 'Tea'], answer: 'Milk' },
    { q: 'Which food is spicy?', options: ['Ice cream', 'Chilli', 'Banana', 'Milk'], answer: 'Chilli' },
    { q: 'Which food do you eat for breakfast?', options: ['Pizza', 'Cereal', 'Sushi', 'Cake'], answer: 'Cereal' },
    { q: 'Which fruit is orange in colour?', options: ['Apple', 'Banana', 'Orange', 'Grape'], answer: 'Orange' },
    { q: 'Which food is baked in an oven?', options: ['Salad', 'Bread', 'Juice', 'Milk'], answer: 'Bread' },
    { q: 'Which food is sweet and cold?', options: ['Pizza', 'Ice cream', 'Soup', 'Rice'], answer: 'Ice cream' },
    { q: 'Which vegetable is orange and long?', options: ['Pea', 'Tomato', 'Carrot', 'Potato'], answer: 'Carrot' },
    { q: 'Which fruit is small, round and can be red or green?', options: ['Mango', 'Grape', 'Apple', 'Peach'], answer: 'Apple' },
    { q: 'Which food is made from potatoes and is thin and crispy?', options: ['Noodles', 'Rice', 'Crisps', 'Bread'], answer: 'Crisps' },
    { q: 'Which drink is made by squeezing oranges?', options: ['Milk', 'Tea', 'Orange juice', 'Water'], answer: 'Orange juice' },
    { q: 'Which food is round and covered in cheese?', options: ['Sushi', 'Pizza', 'Salad', 'Soup'], answer: 'Pizza' },
    { q: 'Which food comes from under the ground?', options: ['Apple', 'Potato', 'Banana', 'Mango'], answer: 'Potato' },
    { q: 'Which food is white, fluffy and eaten with curry?', options: ['Noodles', 'Bread', 'Rice', 'Pasta'], answer: 'Rice' },
    { q: 'Which fruit is green on the outside and red inside?', options: ['Kiwi', 'Mango', 'Watermelon', 'Apple'], answer: 'Watermelon' },
    { q: 'Which food is made from flour, eggs and milk and is flat?', options: ['Cake', 'Pancake', 'Cookie', 'Muffin'], answer: 'Pancake' },
    { q: 'Which vegetable is green and looks like a tiny tree?', options: ['Pea', 'Spinach', 'Broccoli', 'Cucumber'], answer: 'Broccoli' },
    { q: 'Which food is long, thin and made from wheat?', options: ['Rice', 'Potato', 'Spaghetti', 'Bread'], answer: 'Spaghetti' },
    { q: 'Which food do you dip in hummus?', options: ['Cake', 'Pitta bread', 'Cereal', 'Ice cream'], answer: 'Pitta bread' },
    { q: 'Which drink is hot and made from leaves?', options: ['Juice', 'Milk', 'Tea', 'Water'], answer: 'Tea' },
    { q: 'Which food is sweet and comes in a cone or cup?', options: ['Soup', 'Ice cream', 'Salad', 'Rice'], answer: 'Ice cream' },
    { q: 'Which food is yellow and spread on toast?', options: ['Jam', 'Honey', 'Butter', 'Sauce'], answer: 'Butter' },
    { q: 'Which fruit is very sour and yellow?', options: ['Lime', 'Lemon', 'Mango', 'Peach'], answer: 'Lemon' },
    { q: 'Which food is grilled and eaten in a bun?', options: ['Salad', 'Soup', 'Burger', 'Pasta'], answer: 'Burger' },
    { q: 'Which food is made from cocoa and is sweet?', options: ['Cheese', 'Chocolate', 'Bread', 'Butter'], answer: 'Chocolate' },
    { q: 'Which vegetable makes your eyes water when you cut it?', options: ['Carrot', 'Potato', 'Onion', 'Tomato'], answer: 'Onion' },
    { q: 'Which food is cooked in a wok with vegetables and sauce?', options: ['Salad', 'Stir fry', 'Soup', 'Cereal'], answer: 'Stir fry' },
    { q: 'Which food is popular in Japan and made with raw fish and rice?', options: ['Pizza', 'Pasta', 'Sushi', 'Burger'], answer: 'Sushi' },
  ],
  Colours: [
    { q: 'What colour is the sky?', options: ['Red', 'Green', 'Blue', 'Yellow'], answer: 'Blue' },
    { q: 'What colour is grass?', options: ['Blue', 'Green', 'Red', 'Purple'], answer: 'Green' },
    { q: 'What colour is the sun?', options: ['Blue', 'Pink', 'Yellow', 'White'], answer: 'Yellow' },
    { q: 'What colour is a tomato?', options: ['Blue', 'Red', 'Green', 'Orange'], answer: 'Red' },
    { q: 'What colour is snow?', options: ['Black', 'Brown', 'White', 'Grey'], answer: 'White' },
    { q: 'What colour is a pumpkin?', options: ['Purple', 'Orange', 'Blue', 'Red'], answer: 'Orange' },
    { q: 'What colour is a banana?', options: ['Red', 'Green', 'Yellow', 'Blue'], answer: 'Yellow' },
    { q: 'What colour is coal?', options: ['White', 'Red', 'Black', 'Green'], answer: 'Black' },
    { q: 'What colour is a flamingo?', options: ['Blue', 'Pink', 'Green', 'Yellow'], answer: 'Pink' },
    { q: 'What colour is a carrot?', options: ['Orange', 'Blue', 'Purple', 'Green'], answer: 'Orange' },
    { q: 'What colour is a blueberry?', options: ['Red', 'Green', 'Purple', 'Blue'], answer: 'Blue' },
    { q: 'What colour is chocolate?', options: ['Black', 'Brown', 'Red', 'Orange'], answer: 'Brown' },
    { q: 'What colour is a cucumber?', options: ['Yellow', 'Red', 'Green', 'Blue'], answer: 'Green' },
    { q: 'What colour is a lemon?', options: ['Orange', 'Yellow', 'Green', 'White'], answer: 'Yellow' },
    { q: 'What colour is a grape?', options: ['Orange', 'Yellow', 'Purple', 'Blue'], answer: 'Purple' },
    { q: 'What colour is the night sky?', options: ['Blue', 'Grey', 'Black', 'Purple'], answer: 'Black' },
    { q: 'What colour is a fire engine?', options: ['Blue', 'Yellow', 'Red', 'Green'], answer: 'Red' },
    { q: 'What colour is a frog usually?', options: ['Red', 'Blue', 'Green', 'Yellow'], answer: 'Green' },
    { q: 'What colour is sand on a beach?', options: ['White', 'Beige', 'Yellow', 'Brown'], answer: 'Beige' },
    { q: 'What colour is a school bus?', options: ['Red', 'Yellow', 'Green', 'Blue'], answer: 'Yellow' },
    { q: 'What colour is a rose?', options: ['Blue', 'Yellow', 'Red', 'Green'], answer: 'Red' },
    { q: 'What colour are teeth supposed to be?', options: ['Yellow', 'White', 'Cream', 'Grey'], answer: 'White' },
    { q: 'What colour is an aubergine?', options: ['Green', 'Red', 'Purple', 'Orange'], answer: 'Purple' },
    { q: 'What colour is the ocean?', options: ['Green', 'Blue', 'Grey', 'Teal'], answer: 'Blue' },
    { q: 'What colour is a ripe strawberry?', options: ['Pink', 'Orange', 'Red', 'Purple'], answer: 'Red' },
    { q: 'What colour is a polar bear?', options: ['Grey', 'Yellow', 'White', 'Cream'], answer: 'White' },
    { q: 'What two colours make green?', options: ['Red and blue', 'Blue and yellow', 'Red and yellow', 'Black and white'], answer: 'Blue and yellow' },
    { q: 'What colour is a sunflower?', options: ['Orange', 'White', 'Yellow', 'Pink'], answer: 'Yellow' },
    { q: 'What colour is a raven?', options: ['Brown', 'Grey', 'Black', 'Blue'], answer: 'Black' },
    { q: 'What colour is lavender?', options: ['Pink', 'Purple', 'Blue', 'White'], answer: 'Purple' },
  ],
  Numbers: [
    { q: 'How many days in a week?', options: ['5', '6', '7', '8'], answer: '7' },
    { q: 'How many months in a year?', options: ['10', '11', '12', '13'], answer: '12' },
    { q: 'What is 5 + 3?', options: ['7', '8', '9', '6'], answer: '8' },
    { q: 'What is 10 - 4?', options: ['5', '6', '7', '8'], answer: '6' },
    { q: 'How many fingers on one hand?', options: ['4', '5', '6', '3'], answer: '5' },
    { q: 'What is 2 x 3?', options: ['4', '5', '6', '7'], answer: '6' },
    { q: 'How many sides does a triangle have?', options: ['2', '3', '4', '5'], answer: '3' },
    { q: 'What comes after 19?', options: ['18', '21', '20', '22'], answer: '20' },
    { q: 'How many legs does a spider have?', options: ['6', '7', '8', '10'], answer: '8' },
    { q: 'What is half of 10?', options: ['3', '4', '5', '6'], answer: '5' },
    { q: 'How many sides does a square have?', options: ['3', '4', '5', '6'], answer: '4' },
    { q: 'What is 6 + 7?', options: ['11', '12', '13', '14'], answer: '13' },
    { q: 'How many hours in a day?', options: ['12', '20', '24', '48'], answer: '24' },
    { q: 'What is 15 - 8?', options: ['5', '6', '7', '8'], answer: '7' },
    { q: 'How many legs does a cat have?', options: ['2', '3', '4', '6'], answer: '4' },
    { q: 'What is 4 x 4?', options: ['12', '14', '16', '18'], answer: '16' },
    { q: 'How many seconds in one minute?', options: ['30', '60', '100', '120'], answer: '60' },
    { q: 'What is 20 + 20?', options: ['30', '35', '40', '45'], answer: '40' },
    { q: 'How many wheels does a car have?', options: ['2', '3', '4', '6'], answer: '4' },
    { q: 'What is 100 - 50?', options: ['40', '45', '50', '55'], answer: '50' },
    { q: 'How many days in a weekend?', options: ['1', '2', '3', '4'], answer: '2' },
    { q: 'What is 3 x 5?', options: ['12', '13', '14', '15'], answer: '15' },
    { q: 'How many sides does a hexagon have?', options: ['4', '5', '6', '7'], answer: '6' },
    { q: 'What is 9 + 9?', options: ['16', '17', '18', '19'], answer: '18' },
    { q: 'How many minutes in half an hour?', options: ['15', '20', '30', '45'], answer: '30' },
    { q: 'What is 50 + 25?', options: ['65', '70', '75', '80'], answer: '75' },
    { q: 'How many legs does an insect have?', options: ['4', '6', '8', '10'], answer: '6' },
    { q: 'What is 8 x 2?', options: ['14', '15', '16', '17'], answer: '16' },
    { q: 'How many zeros in one hundred?', options: ['1', '2', '3', '4'], answer: '2' },
    { q: 'What is 7 x 3?', options: ['18', '19', '20', '21'], answer: '21' },
  ],
  Jobs: [
    { q: 'Who teaches children at school?', options: ['Doctor', 'Teacher', 'Chef', 'Driver'], answer: 'Teacher' },
    { q: 'Who puts out fires?', options: ['Policeman', 'Firefighter', 'Nurse', 'Pilot'], answer: 'Firefighter' },
    { q: 'Who flies an aeroplane?', options: ['Driver', 'Captain', 'Pilot', 'Sailor'], answer: 'Pilot' },
    { q: 'Who cooks food in a restaurant?', options: ['Waiter', 'Chef', 'Baker', 'Farmer'], answer: 'Chef' },
    { q: 'Who helps sick people?', options: ['Teacher', 'Driver', 'Doctor', 'Farmer'], answer: 'Doctor' },
    { q: 'Who grows food on a farm?', options: ['Pilot', 'Farmer', 'Chef', 'Builder'], answer: 'Farmer' },
    { q: 'Who builds houses?', options: ['Teacher', 'Nurse', 'Builder', 'Chef'], answer: 'Builder' },
    { q: 'Who delivers letters?', options: ['Postman', 'Driver', 'Chef', 'Nurse'], answer: 'Postman' },
    { q: 'Who keeps people safe in a town?', options: ['Teacher', 'Policeman', 'Farmer', 'Chef'], answer: 'Policeman' },
    { q: 'Who looks after teeth?', options: ['Doctor', 'Nurse', 'Dentist', 'Vet'], answer: 'Dentist' },
    { q: 'Who looks after sick animals?', options: ['Doctor', 'Nurse', 'Dentist', 'Vet'], answer: 'Vet' },
    { q: 'Who cuts and styles hair?', options: ['Tailor', 'Barber', 'Nurse', 'Chef'], answer: 'Barber' },
    { q: 'Who drives a taxi?', options: ['Pilot', 'Driver', 'Sailor', 'Engineer'], answer: 'Driver' },
    { q: 'Who makes bread and cakes?', options: ['Chef', 'Farmer', 'Baker', 'Butcher'], answer: 'Baker' },
    { q: 'Who repairs cars?', options: ['Builder', 'Plumber', 'Mechanic', 'Electrician'], answer: 'Mechanic' },
    { q: 'Who fixes water pipes?', options: ['Builder', 'Plumber', 'Mechanic', 'Electrician'], answer: 'Plumber' },
    { q: 'Who fixes electrical problems?', options: ['Builder', 'Plumber', 'Mechanic', 'Electrician'], answer: 'Electrician' },
    { q: 'Who takes photos professionally?', options: ['Artist', 'Journalist', 'Photographer', 'Designer'], answer: 'Photographer' },
    { q: 'Who defends people in court?', options: ['Judge', 'Lawyer', 'Policeman', 'Doctor'], answer: 'Lawyer' },
    { q: 'Who writes books?', options: ['Editor', 'Publisher', 'Author', 'Journalist'], answer: 'Author' },
    { q: 'Who takes care of passengers on a plane?', options: ['Pilot', 'Flight attendant', 'Engineer', 'Guard'], answer: 'Flight attendant' },
    { q: 'Who helps customers in a shop?', options: ['Manager', 'Shop assistant', 'Accountant', 'Driver'], answer: 'Shop assistant' },
    { q: 'Who manages money for a company?', options: ['Lawyer', 'Engineer', 'Accountant', 'Teacher'], answer: 'Accountant' },
    { q: 'Who designs buildings?', options: ['Builder', 'Architect', 'Engineer', 'Plumber'], answer: 'Architect' },
    { q: 'Who catches fish for a living?', options: ['Farmer', 'Sailor', 'Fisherman', 'Diver'], answer: 'Fisherman' },
    { q: 'Who performs operations in a hospital?', options: ['Nurse', 'Doctor', 'Surgeon', 'Dentist'], answer: 'Surgeon' },
    { q: 'Who reports the news on TV?', options: ['Actor', 'Journalist', 'Director', 'Presenter'], answer: 'Presenter' },
    { q: 'Who looks after passengers on a ship?', options: ['Pilot', 'Sailor', 'Steward', 'Captain'], answer: 'Captain' },
    { q: 'Who creates software and apps?', options: ['Engineer', 'Designer', 'Programmer', 'Scientist'], answer: 'Programmer' },
    { q: 'Who performs in plays and films?', options: ['Director', 'Writer', 'Actor', 'Producer'], answer: 'Actor' },
  ],
  'Body Parts': [
    { q: 'What do you use to see?', options: ['Ears', 'Eyes', 'Nose', 'Mouth'], answer: 'Eyes' },
    { q: 'What do you use to hear?', options: ['Eyes', 'Nose', 'Ears', 'Hands'], answer: 'Ears' },
    { q: 'What do you use to smell?', options: ['Mouth', 'Eyes', 'Nose', 'Ears'], answer: 'Nose' },
    { q: 'What do you kick a ball with?', options: ['Hands', 'Head', 'Feet', 'Ears'], answer: 'Feet' },
    { q: 'What do you use to eat?', options: ['Ears', 'Mouth', 'Eyes', 'Nose'], answer: 'Mouth' },
    { q: 'What sits on top of your body?', options: ['Arm', 'Leg', 'Head', 'Foot'], answer: 'Head' },
    { q: 'What do you write with?', options: ['Feet', 'Ears', 'Hands', 'Nose'], answer: 'Hands' },
    { q: 'What connects your foot to your body?', options: ['Arm', 'Leg', 'Neck', 'Shoulder'], answer: 'Leg' },
    { q: 'What connects your head to your body?', options: ['Arm', 'Neck', 'Leg', 'Shoulder'], answer: 'Neck' },
    { q: 'What do you use to think?', options: ['Heart', 'Stomach', 'Brain', 'Lungs'], answer: 'Brain' },
    { q: 'What pumps blood around your body?', options: ['Brain', 'Lungs', 'Heart', 'Stomach'], answer: 'Heart' },
    { q: 'What do you breathe with?', options: ['Heart', 'Liver', 'Lungs', 'Kidneys'], answer: 'Lungs' },
    { q: 'What do you use to chew food?', options: ['Lips', 'Tongue', 'Teeth', 'Gums'], answer: 'Teeth' },
    { q: 'What is at the end of your arm?', options: ['Elbow', 'Shoulder', 'Wrist', 'Hand'], answer: 'Hand' },
    { q: 'What is at the end of your leg?', options: ['Knee', 'Hip', 'Ankle', 'Foot'], answer: 'Foot' },
    { q: 'What do you bend in the middle of your arm?', options: ['Wrist', 'Elbow', 'Shoulder', 'Knuckle'], answer: 'Elbow' },
    { q: 'What do you bend in the middle of your leg?', options: ['Hip', 'Ankle', 'Knee', 'Shin'], answer: 'Knee' },
    { q: 'What covers and protects your body?', options: ['Hair', 'Nails', 'Skin', 'Bones'], answer: 'Skin' },
    { q: 'What is inside your mouth and helps you taste?', options: ['Teeth', 'Lips', 'Tongue', 'Gums'], answer: 'Tongue' },
    { q: 'What holds your body upright like a frame?', options: ['Muscles', 'Skin', 'Skeleton', 'Nerves'], answer: 'Skeleton' },
    { q: 'What is at the top of your spine?', options: ['Chest', 'Skull', 'Hip', 'Rib'], answer: 'Skull' },
    { q: 'What do you use to clap?', options: ['Feet', 'Knees', 'Hands', 'Elbows'], answer: 'Hands' },
    { q: 'What helps you balance when you walk?', options: ['Arms', 'Ears', 'Eyes', 'Nose'], answer: 'Ears' },
    { q: 'What grows on top of your head?', options: ['Skin', 'Nails', 'Hair', 'Fur'], answer: 'Hair' },
    { q: 'What are the hard white things in your mouth?', options: ['Bones', 'Nails', 'Teeth', 'Lips'], answer: 'Teeth' },
    { q: 'What do you use to wave hello?', options: ['Foot', 'Elbow', 'Hand', 'Knee'], answer: 'Hand' },
    { q: 'What connects your arm to your body at the top?', options: ['Elbow', 'Wrist', 'Shoulder', 'Neck'], answer: 'Shoulder' },
    { q: 'What do you use to shrug?', options: ['Hips', 'Shoulders', 'Elbows', 'Knees'], answer: 'Shoulders' },
    { q: 'What part of your face do you wink with?', options: ['Nose', 'Mouth', 'Ear', 'Eye'], answer: 'Eye' },
    { q: 'What do you use to point at something?', options: ['Thumb', 'Finger', 'Palm', 'Wrist'], answer: 'Finger' },
  ],
  Transport: [
    { q: 'What flies in the sky?', options: ['Car', 'Boat', 'Aeroplane', 'Bus'], answer: 'Aeroplane' },
    { q: 'What travels on rails?', options: ['Car', 'Train', 'Boat', 'Bike'], answer: 'Train' },
    { q: 'What travels on water?', options: ['Car', 'Bus', 'Boat', 'Train'], answer: 'Boat' },
    { q: 'How many wheels does a bicycle have?', options: ['1', '2', '3', '4'], answer: '2' },
    { q: 'What do you call a big red vehicle in the UK?', options: ['Train', 'Tram', 'Bus', 'Taxi'], answer: 'Bus' },
    { q: 'What do astronauts travel in?', options: ['Plane', 'Rocket', 'Boat', 'Helicopter'], answer: 'Rocket' },
    { q: 'What vehicle has a driver and a meter?', options: ['Bus', 'Train', 'Taxi', 'Tram'], answer: 'Taxi' },
    { q: 'What do you pedal?', options: ['Car', 'Bike', 'Bus', 'Boat'], answer: 'Bike' },
    { q: 'What vehicle carries many passengers on a motorway?', options: ['Taxi', 'Car', 'Coach', 'Tram'], answer: 'Coach' },
    { q: 'What has blades on top and flies?', options: ['Plane', 'Rocket', 'Helicopter', 'Jet'], answer: 'Helicopter' },
    { q: 'What vehicle runs on electricity and shares the road with cars?', options: ['Bus', 'Train', 'Tram', 'Taxi'], answer: 'Tram' },
    { q: 'What do you ride on one wheel?', options: ['Bike', 'Scooter', 'Unicycle', 'Skateboard'], answer: 'Unicycle' },
    { q: 'What carries oil across the ocean?', options: ['Ferry', 'Yacht', 'Tanker', 'Canoe'], answer: 'Tanker' },
    { q: 'What vehicle do firefighters use?', options: ['Ambulance', 'Police car', 'Fire engine', 'Bus'], answer: 'Fire engine' },
    { q: 'What carries sick people to hospital quickly?', options: ['Taxi', 'Bus', 'Ambulance', 'Van'], answer: 'Ambulance' },
    { q: 'What is a fast train called?', options: ['Express train', 'Bullet train', 'Steam train', 'Tram'], answer: 'Bullet train' },
    { q: 'What vehicle travels under the sea?', options: ['Ship', 'Submarine', 'Ferry', 'Yacht'], answer: 'Submarine' },
    { q: 'What do you use to travel underground in a city?', options: ['Tram', 'Bus', 'Metro', 'Taxi'], answer: 'Metro' },
    { q: 'What is a small fast boat called?', options: ['Ferry', 'Tanker', 'Speedboat', 'Canoe'], answer: 'Speedboat' },
    { q: 'What vehicle delivers packages to your door?', options: ['Taxi', 'Delivery van', 'Bus', 'Lorry'], answer: 'Delivery van' },
    { q: 'What do farmers use to work in fields?', options: ['Van', 'Lorry', 'Tractor', 'Bus'], answer: 'Tractor' },
    { q: 'What carries heavy loads on a road?', options: ['Car', 'Van', 'Lorry', 'Bus'], answer: 'Lorry' },
    { q: 'What vehicle do police officers drive?', options: ['Ambulance', 'Police car', 'Fire engine', 'Van'], answer: 'Police car' },
    { q: 'What do you stand on and kick to move along?', options: ['Bike', 'Skateboard', 'Unicycle', 'Scooter'], answer: 'Skateboard' },
    { q: 'What carries passengers across a river or short sea crossing?', options: ['Yacht', 'Ferry', 'Canoe', 'Submarine'], answer: 'Ferry' },
    { q: 'What kind of plane has no engine?', options: ['Jet', 'Helicopter', 'Glider', 'Rocket'], answer: 'Glider' },
    { q: 'What pulls a carriage with no engine?', options: ['Tractor', 'Horse', 'Lorry', 'Van'], answer: 'Horse' },
    { q: 'What vehicle goes up and down mountains on a cable?', options: ['Tram', 'Funicular', 'Cable car', 'Train'], answer: 'Cable car' },
    { q: 'What is a very large aeroplane called?', options: ['Jet', 'Jumbo jet', 'Glider', 'Helicopter'], answer: 'Jumbo jet' },
    { q: 'What do you use to carry goods on a river?', options: ['Yacht', 'Speedboat', 'Barge', 'Ferry'], answer: 'Barge' },
  ],
  Weather: [
    { q: 'What do you call water falling from the sky?', options: ['Snow', 'Rain', 'Hail', 'Fog'], answer: 'Rain' },
    { q: 'What is frozen rain called?', options: ['Fog', 'Rain', 'Snow', 'Hail'], answer: 'Snow' },
    { q: 'What do we call a very strong wind?', options: ['Breeze', 'Storm', 'Drizzle', 'Fog'], answer: 'Storm' },
    { q: 'What do you see in the sky after rain?', options: ['Cloud', 'Rainbow', 'Star', 'Moon'], answer: 'Rainbow' },
    { q: 'What is it called when you cannot see because of thick mist?', options: ['Rain', 'Snow', 'Fog', 'Wind'], answer: 'Fog' },
    { q: 'What do we call a very hot sunny day?', options: ['Cloudy', 'Rainy', 'Heatwave', 'Foggy'], answer: 'Heatwave' },
    { q: 'What protects you from rain?', options: ['Hat', 'Scarf', 'Umbrella', 'Gloves'], answer: 'Umbrella' },
    { q: 'What is thunder?', options: ['Bright light', 'Loud sound', 'Strong wind', 'Heavy rain'], answer: 'Loud sound' },
    { q: 'What season has the most snow?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], answer: 'Winter' },
    { q: 'What do we call a tropical storm?', options: ['Blizzard', 'Typhoon', 'Drizzle', 'Breeze'], answer: 'Typhoon' },
    { q: 'What is a light gentle wind called?', options: ['Gale', 'Hurricane', 'Breeze', 'Tornado'], answer: 'Breeze' },
    { q: 'What is very light rain called?', options: ['Drizzle', 'Downpour', 'Shower', 'Storm'], answer: 'Drizzle' },
    { q: 'What is a spinning column of air called?', options: ['Hurricane', 'Blizzard', 'Tornado', 'Typhoon'], answer: 'Tornado' },
    { q: 'What is it called when ice pellets fall from the sky?', options: ['Snow', 'Rain', 'Hail', 'Sleet'], answer: 'Hail' },
    { q: 'What do you wear to keep warm in cold weather?', options: ['T-shirt', 'Shorts', 'Coat', 'Sandals'], answer: 'Coat' },
    { q: 'What is it called when the sky is full of clouds?', options: ['Sunny', 'Cloudy', 'Windy', 'Foggy'], answer: 'Cloudy' },
    { q: 'What instrument measures temperature?', options: ['Barometer', 'Thermometer', 'Compass', 'Scale'], answer: 'Thermometer' },
    { q: 'What is a very heavy rainstorm called?', options: ['Drizzle', 'Shower', 'Downpour', 'Mist'], answer: 'Downpour' },
    { q: 'What season comes after winter?', options: ['Summer', 'Autumn', 'Spring', 'Winter'], answer: 'Spring' },
    { q: 'What is a snowstorm called?', options: ['Typhoon', 'Blizzard', 'Tornado', 'Hurricane'], answer: 'Blizzard' },
    { q: 'What is the bright flash in a storm called?', options: ['Thunder', 'Lightning', 'Rainbow', 'Aurora'], answer: 'Lightning' },
    { q: 'What do farmers need for their crops to grow?', options: ['Snow', 'Hail', 'Rain', 'Fog'], answer: 'Rain' },
    { q: 'What is it called when temperature drops below zero?', options: ['Heatwave', 'Frost', 'Drizzle', 'Fog'], answer: 'Frost' },
    { q: 'What season has the longest days?', options: ['Spring', 'Winter', 'Autumn', 'Summer'], answer: 'Summer' },
    { q: 'What do you build in the garden when it snows?', options: ['Sandcastle', 'Snowman', 'Treehouse', 'Kennel'], answer: 'Snowman' },
    { q: 'What is a mix of rain and snow called?', options: ['Hail', 'Frost', 'Sleet', 'Drizzle'], answer: 'Sleet' },
    { q: 'What is the instrument that measures air pressure?', options: ['Thermometer', 'Compass', 'Barometer', 'Scale'], answer: 'Barometer' },
    { q: 'What season do leaves fall from trees?', options: ['Spring', 'Summer', 'Autumn', 'Winter'], answer: 'Autumn' },
    { q: 'What is a large rotating tropical storm over the ocean?', options: ['Tornado', 'Blizzard', 'Hurricane', 'Typhoon'], answer: 'Hurricane' },
    { q: 'What do you call a sudden heavy rain shower?', options: ['Drizzle', 'Squall', 'Mist', 'Fog'], answer: 'Squall' },
  ],
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}