'use client'
import { useState, useRef, useEffect } from 'react'
import Link from 'next/link'

const SPEEDS = [
  { label: '🐢 Very Slow', value: 0.55 },
  { label: '🚶 Slow', value: 0.72 },
  { label: '🏃 Normal', value: 0.9 },
  { label: '⚡ Fast', value: 1.1 },
]

const LANGUAGES = [
  { value: 'none', label: '🌍 English only' },
  { value: 'Thai', label: '🇹🇭 Thai' },
  { value: 'Japanese', label: '🇯🇵 Japanese' },
  { value: 'Korean', label: '🇰🇷 Korean' },
  { value: 'Chinese', label: '🇨🇳 Chinese' },
  { value: 'Arabic', label: '🇸🇦 Arabic' },
  { value: 'Spanish', label: '🇪🇸 Spanish' },
  { value: 'French', label: '🇫🇷 French' },
  { value: 'German', label: '🇩🇪 German' },
  { value: 'Portuguese', label: '🇧🇷 Portuguese' },
  { value: 'Russian', label: '🇷🇺 Russian' },
  { value: 'Vietnamese', label: '🇻🇳 Vietnamese' },
  { value: 'Indonesian', label: '🇮🇩 Indonesian' },
]

const PARTS = [
  {
    number: 1, title: 'What Happens When We Sleep', emoji: '😴', color: '#6366f1',
    text: `Every night, when you close your eyes and fall asleep, your brain does something amazing — it creates its own private movie. You might fly through the sky, talk to a dinosaur, visit a place you have never been, or find yourself in the middle of a really strange adventure. These experiences are called dreams, and every human being on the planet has them.\n\nScientists have discovered that we do not dream all night long. Instead, our sleep is divided into different stages that repeat in cycles throughout the night, each lasting about 90 minutes. The stage where most of our vivid dreams happen is called REM sleep — REM stands for Rapid Eye Movement. During REM sleep, your eyes move quickly behind your closed eyelids, your brain becomes almost as active as when you are awake, and your body becomes temporarily paralysed so that you do not act out your dreams.\n\nMost people dream for about two hours every night, even if they do not remember their dreams in the morning. In fact, studies show that we forget about 95% of our dreams within five minutes of waking up. This is one reason why dreams feel so mysterious — by the time we try to tell someone about a dream, most of it has already vanished from our memory.\n\nBabies spend about 50% of their sleep in REM sleep — far more than adults, who spend about 20-25%. Some scientists believe this is because dreaming helps the brain develop and grow new connections. Even some animals dream! If you have ever watched a sleeping dog twitch its legs as though it were running, you were probably watching it dream.`,
    vocab: [
      { word: 'Vivid', definition: 'Very clear, bright, and detailed — as if it were real.' },
      { word: 'REM sleep', definition: 'A stage of sleep where your eyes move quickly and you have the most detailed dreams.' },
      { word: 'Paralysed', definition: 'Unable to move your body, even though you are still alive and your brain is active.' },
      { word: 'Vanished', definition: 'Disappeared completely, as if it were never there.' },
    ],
    questions: [
      { n: 1, q: 'Do you usually remember your dreams in the morning? If so, what kind of dreams do you have most often?' },
      { n: 2, q: 'We forget 95% of our dreams within five minutes. Why do you think our brains let us forget dreams so quickly?' },
      { n: 3, q: 'Even dogs and other animals dream! What do you think animals might dream about?' },
    ]
  },
  {
    number: 2, title: 'Why Do We Dream?', emoji: '🧠', color: '#4f46e5',
    text: `This is the big question — and the honest answer is that scientists still do not know for certain. Even after decades of research, there is no single agreed explanation for why humans dream. But there are several interesting theories.\n\nOne popular theory is that dreams help us process our emotions. During the day, you experience many feelings — excitement, worry, happiness, fear. Some scientists believe that dreaming is your brain's way of sorting through these emotions while you sleep, like organising files on a computer. This might explain why we often dream about things that worried us during the day.\n\nAnother theory is that dreams help us learn and remember. When you study for a test or learn a new skill, your brain replays those experiences during sleep to strengthen the memory. Scientists have found that students who slept well after studying performed much better on tests than students who stayed up all night revising. Some researchers even found that people who dreamt about a maze they had been trying to solve were better at solving it the next day.\n\nA third theory is that dreams are like a flight simulator for real life. By putting you in strange, difficult, or even frightening situations while you sleep, your brain may be practising how to respond to challenges. This could explain why so many dreams involve being chased, falling, or trying to solve a problem — your brain is preparing you for difficult situations, just in case.\n\nFinally, some scientists think dreams might simply be random electrical signals in the brain, and that the "stories" we experience are just our brain trying to make sense of those random signals. In this view, dreams do not have a deep meaning — they are just brain noise.`,
    vocab: [
      { word: 'Process', definition: 'To deal with something mentally — to think about it, understand it, and organise it in your mind.' },
      { word: 'Replays', definition: 'Plays something again — like watching a video a second time.' },
      { word: 'Simulator', definition: 'A machine or system that copies real conditions so people can practise without real danger.' },
      { word: 'Random', definition: 'Happening without any pattern or plan — completely by chance.' },
    ],
    questions: [
      { n: 4, q: 'Of the four theories about why we dream, which one makes the most sense to you? Why?' },
      { n: 5, q: 'Have you ever dreamt about something you were studying or practising? Did it help you learn it better?' },
      { n: 6, q: 'Many dreams involve being chased or falling. If dreams are a "flight simulator" for real life, what is your brain preparing you for?' },
    ]
  },
  {
    number: 3, title: 'Nightmares and Lucid Dreams', emoji: '👁️', color: '#4338ca',
    text: `Not all dreams are pleasant. Nightmares are scary or upsetting dreams that can wake you up feeling frightened or anxious. Almost everyone has nightmares from time to time, but children have them more often than adults. Common nightmares include being chased by something scary, falling from a great height, losing your teeth, or being unable to run or scream when you need to.\n\nScientists believe nightmares often happen when we are stressed, anxious, or have experienced something frightening. They can also be caused by eating a heavy meal before bed, watching scary films, or being too hot while sleeping. While nightmares are unpleasant, most researchers believe they are a normal part of how our brains process fear and anxiety.\n\nOn the other end of the scale, there is something truly remarkable called a lucid dream. A lucid dream is a dream in which you suddenly realise that you are dreaming — while the dream is still happening. Some people who have lucid dreams say they can actually control what happens in the dream, like choosing where to go, what to do, or even making themselves fly.\n\nLucid dreaming is not a myth — it has been scientifically proven. In experiments, scientists asked lucid dreamers to make a specific pattern of eye movements during a dream (for example, looking left, right, left, right). Because the eyes still move during REM sleep, researchers could see the pre-agreed pattern on their monitoring equipment, proving that the dreamers were consciously aware inside their dreams.\n\nSome people try to learn lucid dreaming through special techniques, such as keeping a dream diary, performing "reality checks" throughout the day, or repeating "I will know I am dreaming" before falling asleep. It takes practice, but many people have succeeded.`,
    vocab: [
      { word: 'Nightmare', definition: 'A frightening or unpleasant dream that can make you feel scared or upset when you wake up.' },
      { word: 'Lucid dream', definition: 'A dream in which you know you are dreaming and may be able to control what happens.' },
      { word: 'Consciously', definition: 'With full awareness — knowing what you are doing and being able to think about it.' },
      { word: 'Reality check', definition: 'A test you do to check whether you are dreaming or awake, such as trying to push your finger through your hand.' },
    ],
    questions: [
      { n: 7, q: 'What is the scariest nightmare you can remember? How did you feel when you woke up?' },
      { n: 8, q: 'Would you like to be able to have lucid dreams and control what happens? What would you do in a lucid dream?' },
      { n: 9, q: 'Scientists proved lucid dreaming is real by asking dreamers to move their eyes in a pattern. Why do you think this experiment was so important?' },
    ]
  },
  {
    number: 4, title: 'Dreams Around the World', emoji: '🌙', color: '#3730a3',
    text: `Throughout human history, people all over the world have been fascinated by dreams and have tried to understand what they mean. Different cultures have developed very different ideas about where dreams come from and why they matter.\n\nIn ancient Egypt, dreams were considered messages from the gods. The Egyptians had special priests called "Masters of the Secret Things" whose job was to interpret dreams for the pharaoh. They even wrote dream dictionaries — books that listed common dream images and what they were believed to mean. Dreaming about a cat, for example, was considered good luck.\n\nAboriginal Australians have one of the world's oldest continuous cultures, and dreams play a central role in their beliefs. They call it "The Dreaming" or "Dreamtime" — a spiritual realm where the world was created by ancestral beings. In their tradition, dreams are not just things that happen during sleep — they are a way of connecting with the spiritual world and understanding the land.\n\nIn modern Western culture, the most famous person associated with dreams is Sigmund Freud, an Austrian doctor who published a book called "The Interpretation of Dreams" in 1899. Freud believed that dreams were a window into the unconscious mind — the hidden part of your brain that stores thoughts, feelings, and desires that you are not aware of during the day. While many of Freud's specific ideas have been challenged by modern science, his basic insight — that dreams can tell us something about our inner thoughts and feelings — remains influential.\n\nToday, scientists continue to study dreams using brain scanning technology and sleep laboratories. We have learned an enormous amount about when dreams happen and what the brain does during dreaming. But the fundamental question — why do we dream? — remains one of the great unsolved mysteries of the human mind.`,
    vocab: [
      { word: 'Interpret', definition: 'To explain or find the meaning of something that is not immediately obvious.' },
      { word: 'Ancestral', definition: 'Relating to your ancestors — the people in your family who lived a very long time ago.' },
      { word: 'Unconscious mind', definition: 'The part of your mind that contains thoughts and feelings you are not aware of.' },
      { word: 'Influential', definition: 'Having a strong effect on how people think, behave, or understand something.' },
    ],
    questions: [
      { n: 10, q: 'Ancient Egyptians, Aboriginal Australians, and Sigmund Freud all had very different ideas about dreams. Whose ideas do you find most interesting? Why?' },
      { n: 11, q: 'In your culture, do people believe dreams have special meanings? Have you ever had a dream that you felt was trying to tell you something?' },
      { n: 12, q: 'Why we dream is still an "unsolved mystery." If you were a scientist, how would you try to answer this question?' },
    ]
  },
]

async function fetchTranslation(text: string, lang: string, type: 'word' | 'question' | 'message'): Promise<string> {
  const systems: Record<string, string> = {
    word: `You are a language learning assistant. Translate this English vocabulary entry to ${lang}. Return ONLY the translated word and a brief explanation in ${lang} (max 25 words). No extra text, no English.`,
    question: `You are a translator. Translate this English discussion question to ${lang}. Return ONLY the translated question. No extra text.`,
    message: `You are a translator. Translate this English text to ${lang}. Return ONLY the translation. No extra text.`,
  }
  const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: systems[type], messages: [{ role: 'user', content: text }] }) })
  const data = await res.json()
  return data.content || ''
}

function TranslateBtn({ text, type, lang, color, onTranslated }: { text: string; type: 'word' | 'question' | 'message'; lang: string; color: string; onTranslated: (t: string) => void }) {
  const [loading, setLoading] = useState(false)
  const [done, setDone] = useState(false)
  const handleClick = async () => { if (lang === 'none' || loading || done) return; setLoading(true); const result = await fetchTranslation(text, lang, type); onTranslated(result); setDone(true); setLoading(false) }
  const isDisabled = lang === 'none'
  return <button onClick={handleClick} disabled={isDisabled || loading || done} title={isDisabled ? 'Select a language above to translate' : done ? 'Translated' : `Translate to ${lang}`} style={{ background: isDisabled ? '#f3f4f6' : done ? '#f0fdf4' : color + '15', color: isDisabled ? '#d1d5db' : done ? '#16a34a' : color, border: `1px solid ${isDisabled ? '#e5e7eb' : done ? '#86efac' : color + '40'}`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: isDisabled ? 'not-allowed' : done ? 'default' : 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s' }}>{loading ? '...' : done ? '✓ 🌍' : '🌍'}</button>
}

function ListenBtn({ text, speed, color }: { text: string; speed: number; color: string }) {
  const [loading, setLoading] = useState(false); const [playing, setPlaying] = useState(false); const sourceRef = useRef<AudioBufferSourceNode | null>(null)
  const handleClick = async () => { if (playing && sourceRef.current) { try { sourceRef.current.stop() } catch {} sourceRef.current = null; setPlaying(false); return }; setLoading(true); try { const res = await fetch('/api/tts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); if (!res.ok) { setLoading(false); return }; const ab = await res.arrayBuffer(); const ac = new AudioContext(); const buf = await ac.decodeAudioData(ab); const src = ac.createBufferSource(); src.buffer = buf; src.playbackRate.value = speed; src.connect(ac.destination); src.onended = () => { setPlaying(false); sourceRef.current = null }; sourceRef.current = src; setLoading(false); setPlaying(true); src.start(0) } catch { setLoading(false); setPlaying(false) } }
  return <button onClick={handleClick} style={{ background: playing ? color : color + '15', color: playing ? 'white' : color, border: `1px solid ${color}40`, padding: '2px 10px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s', display: 'flex', alignItems: 'center', gap: '4px' }}>{loading ? '...' : playing ? '⏹ Stop' : '🔊 Listen'}</button>
}

type Message = { role: 'user' | 'assistant'; content: string; translation?: string }

function ConversationBox({ question, color, translationLang, speed }: { question: string; color: string; translationLang: string; speed: number }) {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [listening, setListening] = useState(false); const [interimText, setInterimText] = useState(''); const [open, setOpen] = useState(false); const recognitionRef = useRef<any>(null); const transcriptRef = useRef('')
  const SYSTEM = `You are a friendly and enthusiastic English conversation partner helping a B1 level student aged 10-12 practise English discussion skills. The reading topic is "Why Do We Dream?". The current discussion question is: "${question}". Keep every response to 2-3 sentences maximum. Use simple, clear, exciting language for a young learner. Be enthusiastic and curious about dreams! Always end with one fun follow-up question to keep the conversation going. If the student makes a significant grammar error, gently correct it using "💡 Quick tip: ..." at the very end.`
  const sendMessage = async (text: string) => { if (!text.trim() || loading) return; const userMsg: Message = { role: 'user', content: text.trim() }; const updated = [...messages, userMsg]; setMessages(updated); setInput(''); setLoading(true); try { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: SYSTEM, messages: updated.map(m => ({ role: m.role, content: m.content })) }) }); const data = await res.json(); setMessages(prev => [...prev, { role: 'assistant', content: data.content || 'Sorry, try again.' }]) } catch { setMessages(prev => [...prev, { role: 'assistant', content: 'Connection error — please try again.' }]) }; setLoading(false) }
  const setMessageTranslation = (idx: number, translation: string) => { setMessages(prev => prev.map((m, i) => i === idx ? { ...m, translation } : m)) }
  const startVoice = () => { const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!SR) { alert('Voice input requires Chrome browser.'); return }; transcriptRef.current = ''; const r = new SR(); r.lang = 'en-US'; r.continuous = true; r.interimResults = true; r.onstart = () => { setListening(true); setInterimText('') }; r.onresult = (e: any) => { let f = ''; let int = ''; for (let i = 0; i < e.results.length; i++) { if (e.results[i].isFinal) { f += e.results[i][0].transcript + ' ' } else { int += e.results[i][0].transcript } }; transcriptRef.current = f; setInterimText(f + int) }; r.onerror = () => { setListening(false); setInterimText('') }; r.onend = () => { setListening(false); const text = transcriptRef.current.trim() || interimText.trim(); if (text) { setInterimText(''); transcriptRef.current = ''; sendMessage(text) } else { setInterimText(''); transcriptRef.current = '' } }; recognitionRef.current = r; r.start() }
  const stopVoice = () => { recognitionRef.current?.stop() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  if (!open) return <button onClick={() => setOpen(true)} style={{ marginTop: '10px', width: '100%', background: color + '12', border: `2px dashed ${color}40`, borderRadius: '12px', padding: '10px', color, fontWeight: '700', fontSize: '13px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>🤖 Practice answering with AI</button>
  return (
    <div style={{ marginTop: '10px', background: '#eef2ff', borderRadius: '14px', border: `2px solid ${color}30`, overflow: 'hidden' }}>
      <div style={{ background: color, padding: '10px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span style={{ color: 'white', fontWeight: '700', fontSize: '13px' }}>🤖 AI Conversation Partner</span><div style={{ display: 'flex', gap: '6px' }}><button onClick={() => setMessages([])} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>🔄 Reset</button><button onClick={() => setOpen(false)} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>✕ Close</button></div></div>
      {messages.length === 0 && <div style={{ padding: '14px 16px', color: '#6b7280', fontSize: '13px', lineHeight: '1.6', borderBottom: '1px solid #c7d2fe' }}>💡 Type your answer or tap <strong>🎤 Start Recording</strong> — speak your full answer, then tap <strong>⏹ Stop & Send</strong>.</div>}
      {messages.length > 0 && <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px', maxHeight: '320px', overflowY: 'auto' }}>{messages.map((m, i) => (<div key={i} style={{ display: 'flex', gap: '8px', alignItems: 'flex-start', flexDirection: m.role === 'user' ? 'row-reverse' : 'row' }}><div style={{ fontSize: '20px', flexShrink: 0 }}>{m.role === 'user' ? '🧑‍🎓' : '🤖'}</div><div style={{ maxWidth: '80%', display: 'flex', flexDirection: 'column', gap: '4px', alignItems: m.role === 'user' ? 'flex-end' : 'flex-start' }}><div style={{ background: m.role === 'user' ? color : 'white', color: m.role === 'user' ? 'white' : '#374151', padding: '10px 14px', borderRadius: m.role === 'user' ? '16px 4px 16px 16px' : '4px 16px 16px 16px', fontSize: '14px', lineHeight: '1.6', boxShadow: '0 1px 4px rgba(0,0,0,0.08)', border: m.role === 'assistant' ? '1px solid #e5e7eb' : 'none' }}>{m.content}</div>{m.role === 'assistant' && <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}><ListenBtn text={m.content} speed={speed} color={color} />{!m.translation && <TranslateBtn text={m.content} type="message" lang={translationLang} color={color} onTranslated={(t) => setMessageTranslation(i, t)} />}</div>}{m.translation && <div style={{ background: '#eef2ff', border: '1px solid #c7d2fe', borderRadius: '10px', padding: '8px 12px', fontSize: '13px', color: '#374151', lineHeight: '1.5' }}><span style={{ color: color, fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>🌍 Translation</span>{m.translation}</div>}</div></div>))}{loading && <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}><span style={{ fontSize: '20px' }}>🤖</span><div style={{ background: 'white', padding: '10px 14px', borderRadius: '4px 16px 16px 16px', fontSize: '14px', color: '#9ca3af', border: '1px solid #e5e7eb' }}>Thinking...</div></div>}</div>}
      <div style={{ padding: '12px 16px', borderTop: '1px solid #c7d2fe', display: 'flex', gap: '8px', alignItems: 'flex-end' }}><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(input) } }} placeholder="Type your answer here..." rows={2} style={{ flex: 1, padding: '10px 12px', borderRadius: '10px', border: '2px solid #e5e7eb', fontSize: '14px', outline: 'none', resize: 'none', fontFamily: 'inherit', lineHeight: '1.5' }} /><div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}><button onClick={listening ? stopVoice : startVoice} style={{ background: listening ? '#ef4444' : '#22c55e', color: 'white', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: listening ? '0 0 0 4px rgba(239,68,68,0.3)' : 'none', transition: 'all 0.2s' }}>{listening ? '⏹' : '🎤'}</button><button onClick={() => sendMessage(input)} disabled={!input.trim() || loading} style={{ background: input.trim() && !loading ? color : '#e5e7eb', color: input.trim() && !loading ? 'white' : '#9ca3af', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: input.trim() && !loading ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>➤</button></div></div>
      {!listening && <div style={{ padding: '4px 16px 10px', display: 'flex', gap: '16px' }}><span style={{ color: '#9ca3af', fontSize: '11px' }}>🎤 = Start recording</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>⏹ = Stop & send</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>➤ = Send typed</span></div>}
      {listening && <div style={{ padding: '10px 16px 14px', borderTop: '1px solid #fee2e2', background: '#fef2f2' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ display: 'inline-block', width: '10px', height: '10px', borderRadius: '50%', background: '#ef4444', animation: 'pulse 1s infinite', flexShrink: 0 }} /><span style={{ color: '#ef4444', fontSize: '12px', fontWeight: '700' }}>Recording... speak your full answer</span></div><button onClick={stopVoice} style={{ background: '#ef4444', color: 'white', border: 'none', padding: '6px 16px', borderRadius: '10px', fontWeight: '800', fontSize: '13px', cursor: 'pointer', boxShadow: '0 2px 8px rgba(239,68,68,0.4)' }}>⏹ Stop & Send</button></div><div style={{ background: 'white', borderRadius: '10px', padding: '10px 14px', fontSize: '14px', color: interimText ? '#374151' : '#9ca3af', lineHeight: '1.6', border: '1px solid #fca5a5', fontStyle: 'italic', minHeight: '40px' }}>{interimText || 'Waiting for speech...'}{interimText && <span style={{ display: 'inline-block', width: '2px', height: '16px', background: '#ef4444', marginLeft: '2px', verticalAlign: 'middle', animation: 'pulse 1s infinite' }} />}</div></div>}
    </div>
  )
}

export default function DreamsPage() {
  const [speed, setSpeed] = useState(0.9); const [translationLang, setTranslationLang] = useState('none'); const [selectedText, setSelectedText] = useState<string | null>(null); const [lookupDef, setLookupDef] = useState(''); const [lookupTranslation, setLookupTranslation] = useState(''); const [lookupLoading, setLookupLoading] = useState(false); const [vocabTranslations, setVocabTranslations] = useState<Record<string, string>>({}); const [questionTranslations, setQuestionTranslations] = useState<Record<number, string>>({})
  useEffect(() => { const handleSelection = () => { const sel = window.getSelection(); if (!sel) return; const text = sel.toString().trim().replace(/\s+/g, ' '); if (!text || text.split(' ').length > 6) return; const anchor = sel.anchorNode?.parentElement; if (!anchor?.closest('[data-passage]')) return; handleLookup(text) }; document.addEventListener('mouseup', handleSelection); document.addEventListener('touchend', handleSelection); return () => { document.removeEventListener('mouseup', handleSelection); document.removeEventListener('touchend', handleSelection) } }, [translationLang])
  const handleLookup = async (text: string) => { if (!text || text.length < 2) return; setSelectedText(text); setLookupDef(''); setLookupTranslation(''); setLookupLoading(true); speakWord(text); const isPhrase = text.includes(' '); try { if (translationLang === 'none') { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: isPhrase ? `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 20 words) explaining what the phrase means. No extra text.` : `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 15 words) defining this word. No extra text.`, messages: [{ role: 'user', content: isPhrase ? `What does "${text}" mean?` : `Define: "${text}"` }] }) }); const data = await res.json(); setLookupDef(data.content || 'No definition found.') } else { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: `You are a language learning assistant for young B1 English students. Respond ONLY with valid JSON (no markdown, no backticks): {"definition": "one simple English sentence max 15 words", "translation": "the word/phrase in ${translationLang} with a brief explanation in ${translationLang}, max 25 words"}`, messages: [{ role: 'user', content: `Word or phrase: "${text}"` }] }) }); const data = await res.json(); try { const parsed = JSON.parse(data.content); setLookupDef(parsed.definition || 'No definition found.'); setLookupTranslation(parsed.translation || '') } catch { setLookupDef(data.content || 'No definition found.'); setLookupTranslation('') } } } catch { setLookupDef('Could not load definition.') }; setLookupLoading(false) }
  function speakText(text: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const sentences = text.match(/[^.!?]+[.!?]+/g) || [text]; sentences.forEach(s => { const u = new SpeechSynthesisUtterance(s.trim()); u.lang = 'en-GB'; u.rate = speed; u.pitch = 1; window.speechSynthesis.speak(u) }) }
  function speakWord(word: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(word); u.lang = 'en-GB'; u.rate = 0.85; u.pitch = 1; window.speechSynthesis.speak(u) }
  function stopAudio() { if (typeof window === 'undefined') return; window.speechSynthesis.cancel() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  return (
    <main style={{ background: '#f4f6fa', minHeight: '100vh' }}>
      <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}} @keyframes slideUp{from{transform:translateY(100%);opacity:0}to{transform:translateY(0);opacity:1}}`}</style>
      <section style={{ background: 'linear-gradient(135deg, #0d0a2e 0%, #1e1b4b 50%, #312e81 100%)', padding: '56px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <Link href="/esl-resources/reading-comprehension/b1" style={{ color: 'rgba(255,255,255,0.6)', textDecoration: 'none', fontSize: '14px', display: 'inline-block', marginBottom: '20px' }}>← B1 Reading Comprehension</Link>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', flexWrap: 'wrap' }}>
            <div style={{ fontSize: '72px', flexShrink: 0 }}>💭</div>
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '12px' }}>
                <span style={{ background: '#6366f1', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>B1 Intermediate</span>
                <span style={{ background: 'rgba(99,102,241,0.5)', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>Science & Space</span>
                <span style={{ background: 'rgba(255,255,255,0.15)', color: 'white', fontSize: '12px', fontWeight: '600', padding: '4px 12px', borderRadius: '20px' }}>4 Parts · 12 Questions</span>
              </div>
              <h1 style={{ color: 'white', fontSize: '32px', fontWeight: 'bold', margin: '0 0 8px', lineHeight: '1.3' }}>Why Do We Dream?</h1>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '16px', margin: 0, lineHeight: '1.6' }}>Every night your brain creates its own private movie. What happens when we sleep, why we dream, and what nightmares and lucid dreams can teach us about our minds.</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '20px', marginTop: '28px', flexWrap: 'wrap' }}>{[{ icon: '📄', label: '4 reading parts' }, { icon: '💬', label: '12 discussion questions' }, { icon: '📚', label: '16 vocabulary words' }, { icon: '✍️', label: 'Highlight any text' }, { icon: '🌍', label: 'Multi-language lookup' }, { icon: '🤖', label: 'AI conversation partner' }].map(s => <div key={s.label} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'rgba(255,255,255,0.75)', fontSize: '13px' }}><span>{s.icon}</span> {s.label}</div>)}</div>
        </div>
      </section>
      <section style={{ background: 'white', borderBottom: '1px solid #eee', padding: '14px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', alignItems: 'center', marginBottom: '10px' }}><span style={{ color: '#888', fontSize: '12px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>How to use:</span>{['🔊 Play passage aloud', '✍️ Highlight any text for lookup', '🌍 Translate vocab, questions & AI answers', '🤖 Practice with AI'].map((step, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#555', fontSize: '13px' }}><span style={{ background: '#6366f1', color: 'white', width: '18px', height: '18px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '10px', fontWeight: 'bold', flexShrink: 0 }}>{i + 1}</span>{step}</div>)}</div>
          <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap', alignItems: 'center' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🔊 Speed:</span>{SPEEDS.map(s => <button key={s.value} onClick={() => setSpeed(s.value)} style={{ padding: '4px 12px', borderRadius: '20px', border: '2px solid', borderColor: speed === s.value ? '#6366f1' : '#e5e7eb', background: speed === s.value ? '#6366f1' : 'white', color: speed === s.value ? 'white' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', transition: 'all 0.2s' }}>{s.label}</button>)}</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🌍 Translate to:</span><select value={translationLang} onChange={e => { setTranslationLang(e.target.value); setVocabTranslations({}); setQuestionTranslations({}) }} style={{ padding: '5px 12px', borderRadius: '20px', border: '2px solid', borderColor: translationLang !== 'none' ? '#6366f1' : '#e5e7eb', background: translationLang !== 'none' ? '#eef2ff' : 'white', color: translationLang !== 'none' ? '#3730a3' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', outline: 'none' }}>{LANGUAGES.map(l => <option key={l.value} value={l.value}>{l.label}</option>)}</select></div>
          </div>
        </div>
      </section>
      <div style={{ maxWidth: '860px', margin: '0 auto', padding: '32px 24px', display: 'flex', flexDirection: 'column', gap: '28px' }}>
        {PARTS.map(part => (
          <div key={part.number} style={{ background: 'white', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 2px 12px rgba(0,0,0,0.07)' }}>
            <div style={{ background: `linear-gradient(135deg, ${part.color}22, ${part.color}08)`, borderLeft: `5px solid ${part.color}`, padding: '20px 24px', display: 'flex', gap: '14px', alignItems: 'center', flexWrap: 'wrap' }}>
              <div style={{ background: part.color, color: 'white', width: '36px', height: '36px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '16px', flexShrink: 0 }}>{part.number}</div>
              <div style={{ flex: 1 }}><div style={{ color: part.color, fontSize: '11px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '2px' }}>Part {part.number}</div><h2 data-passage="true" style={{ color: '#1a1a2e', fontSize: '18px', fontWeight: 'bold', margin: 0, userSelect: 'text', cursor: 'text' }}>{part.emoji} {part.title}</h2></div>
              <div style={{ display: 'flex', gap: '8px', flexShrink: 0 }}><button onClick={() => speakText(part.text.replace(/\n\n/g, ' '))} style={{ background: part.color, color: 'white', border: 'none', padding: '8px 16px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', boxShadow: `0 3px 10px ${part.color}40` }}>▶ Play Passage</button><button onClick={stopAudio} style={{ background: 'white', color: '#6b7280', border: '2px solid #e5e7eb', padding: '8px 12px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer' }}>⏹ Stop</button></div>
            </div>
            <div style={{ background: '#eef2ff', padding: '8px 28px', borderBottom: '1px solid #c7d2fe' }}><span style={{ color: '#3730a3', fontSize: '12px', fontWeight: '600' }}>✍️ Highlight any word or phrase to hear it and see its meaning{translationLang !== 'none' && <span style={{ color: '#6366f1' }}> + {currentLang?.label} translation</span>}</span></div>
            <div data-passage="true" style={{ padding: '24px 28px 20px', userSelect: 'text', cursor: 'text' }}>{part.text.split('\n\n').map((para, i) => <p key={i} style={{ color: '#374151', fontSize: '16px', lineHeight: '1.85', margin: i === 0 ? '0 0 18px' : '0', fontFamily: 'Georgia, serif' }}>{para}</p>)}</div>
            <div style={{ margin: '0 28px 24px', background: part.color + '08', border: `1px solid ${part.color}25`, borderRadius: '14px', overflow: 'hidden' }}>
              <div style={{ background: part.color + '18', padding: '12px 16px', display: 'flex', alignItems: 'center', gap: '8px', borderBottom: `1px solid ${part.color}20` }}><span style={{ fontSize: '16px' }}>📚</span><span style={{ color: part.color, fontWeight: 'bold', fontSize: '13px', textTransform: 'uppercase', letterSpacing: '1px' }}>Vocabulary — Part {part.number}</span></div>
              <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>{part.vocab.map((v, i) => { const vKey = `${part.number}-${v.word}`; return (<div key={v.word} style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', paddingBottom: i < part.vocab.length - 1 ? '10px' : '0', borderBottom: i < part.vocab.length - 1 ? `1px solid ${part.color}15` : 'none' }}><div style={{ background: part.color, color: 'white', width: '22px', height: '22px', borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '11px', flexShrink: 0, marginTop: '2px' }}>{i + 1}</div><div style={{ flex: 1 }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '3px', flexWrap: 'wrap' }}><span data-passage="true" style={{ fontWeight: 'bold', color: '#1a1a2e', fontSize: '15px', userSelect: 'text', cursor: 'text' }}>{v.word}</span><button onClick={() => speakWord(v.word)} style={{ background: part.color + '15', color: part.color, border: `1px solid ${part.color}30`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0 }}>🔊</button><TranslateBtn text={`Word: "${v.word}"\nDefinition: "${v.definition}"`} type="word" lang={translationLang} color={part.color} onTranslated={(t) => setVocabTranslations(prev => ({ ...prev, [vKey]: t }))} />{translationLang === 'none' && <span style={{ color: '#d1d5db', fontSize: '11px' }}>← select a language to translate</span>}</div><span data-passage="true" style={{ color: '#6b7280', fontSize: '14px', lineHeight: '1.5', userSelect: 'text', cursor: 'text' }}>{v.definition}</span>{vocabTranslations[vKey] && <div style={{ marginTop: '6px', background: '#eef2ff', border: '1px solid #c7d2fe', borderRadius: '8px', padding: '8px 12px' }}><span style={{ color: '#3730a3', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: '#374151', fontSize: '14px', lineHeight: '1.5' }}>{vocabTranslations[vKey]}</span></div>}</div></div>) })}</div>
            </div>
            <div style={{ background: '#1a1a2e', padding: '20px 28px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}><span style={{ fontSize: '18px' }}>💬</span><span style={{ color: '#a5b4fc', fontWeight: 'bold', fontSize: '14px', textTransform: 'uppercase', letterSpacing: '1px' }}>Discussion Questions</span></div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>{part.questions.map(q => (<div key={q.n}><div style={{ display: 'flex', gap: '14px', alignItems: 'flex-start' }}><div style={{ background: part.color, color: 'white', width: '28px', height: '28px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '13px', flexShrink: 0, marginTop: '1px' }}>{q.n}</div><div style={{ flex: 1 }}><p data-passage="true" style={{ color: 'rgba(255,255,255,0.88)', fontSize: '15px', lineHeight: '1.6', margin: '0 0 6px', userSelect: 'text', cursor: 'text' }}>{q.q}</p><div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><TranslateBtn text={q.q} type="question" lang={translationLang} color={part.color} onTranslated={(t) => setQuestionTranslations(prev => ({ ...prev, [q.n]: t }))} />{translationLang === 'none' && <span style={{ color: '#4b5563', fontSize: '11px' }}>← select a language to translate</span>}</div>{questionTranslations[q.n] && <div style={{ marginTop: '8px', background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.3)', borderRadius: '10px', padding: '10px 14px' }}><span style={{ color: '#a5b4fc', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: 'rgba(255,255,255,0.9)', fontSize: '14px', lineHeight: '1.6' }}>{questionTranslations[q.n]}</span></div>}</div></div><div style={{ marginLeft: '42px' }}><ConversationBox question={q.q} color={part.color} translationLang={translationLang} speed={speed} /></div></div>))}</div>
            </div>
          </div>
        ))}
        <div style={{ textAlign: 'center', paddingBottom: selectedText ? '140px' : '16px' }}><Link href="/esl-resources/reading-comprehension/b1" style={{ color: '#6366f1', textDecoration: 'none', fontWeight: 'bold', fontSize: '14px' }}>← Back to B1 Reading Comprehension</Link></div>
      </div>
      {selectedText && <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 200, animation: 'slideUp 0.25s ease' }}><div style={{ maxWidth: '860px', margin: '0 auto', background: 'white', borderRadius: '20px 20px 0 0', padding: '20px 24px 32px', boxShadow: '0 -8px 32px rgba(0,0,0,0.2)', border: '2px solid #c7d2fe', borderBottom: 'none' }}><div style={{ width: '40px', height: '4px', background: '#e5e7eb', borderRadius: '4px', margin: '0 auto 16px' }} /><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}><span style={{ fontSize: '22px', fontWeight: '900', color: '#1a1a2e', fontFamily: 'Georgia, serif' }}>"{selectedText}"</span><button onClick={() => speakWord(selectedText)} style={{ background: '#eef2ff', color: '#3730a3', border: '2px solid #c7d2fe', padding: '6px 14px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', flexShrink: 0 }}>🔊 Hear it</button></div><button onClick={() => setSelectedText(null)} style={{ background: '#f3f4f6', border: 'none', width: '32px', height: '32px', borderRadius: '8px', cursor: 'pointer', fontSize: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#6b7280', flexShrink: 0, marginLeft: '12px' }}>✕</button></div>{lookupLoading ? <div style={{ background: '#eef2ff', borderRadius: '12px', padding: '14px 18px', border: '1px solid #c7d2fe', color: '#9ca3af', fontSize: '15px' }}>{translationLang !== 'none' ? `Looking up definition and ${currentLang?.label} translation...` : 'Looking up...'}</div> : <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}><div style={{ background: '#eef2ff', borderRadius: '12px', padding: '14px 18px', border: '1px solid #c7d2fe' }}><div style={{ color: '#3730a3', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>📖 English Definition</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupDef}</span></div>{translationLang !== 'none' && lookupTranslation && <div style={{ background: '#eef2ff', borderRadius: '12px', padding: '14px 18px', border: '1px solid #a5b4fc' }}><div style={{ color: '#4338ca', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>{currentLang?.label} Translation</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupTranslation}</span></div>}</div>}</div></div>}
    </main>
  )
}
