export type Difficulty = 'easy' | 'medium' | 'hard'

export const scrambleBank: Record<string, { word: string; hint: string; difficulty: Difficulty }[]> = {
  Animals: [
    // Easy
    { word: 'CAT', hint: 'A fluffy pet that purrs', difficulty: 'easy' },
    { word: 'DOG', hint: 'A loyal pet that barks', difficulty: 'easy' },
    { word: 'COW', hint: 'A farm animal that gives milk', difficulty: 'easy' },
    { word: 'PIG', hint: 'A pink farm animal that oinks', difficulty: 'easy' },
    { word: 'HEN', hint: 'A female chicken that lays eggs', difficulty: 'easy' },
    { word: 'BEE', hint: 'A flying insect that makes honey', difficulty: 'easy' },
    { word: 'ANT', hint: 'A tiny insect that lives in a colony', difficulty: 'easy' },
    { word: 'OWL', hint: 'A bird that is awake at night', difficulty: 'easy' },
    { word: 'FOX', hint: 'A clever orange wild animal', difficulty: 'easy' },
    { word: 'RAT', hint: 'A small rodent with a long tail', difficulty: 'easy' },
    { word: 'FROG', hint: 'A green animal that jumps and lives near water', difficulty: 'easy' },
    { word: 'BEAR', hint: 'A large furry animal that loves honey', difficulty: 'easy' },
    { word: 'DUCK', hint: 'A bird that swims and says quack', difficulty: 'easy' },
    { word: 'WOLF', hint: 'A wild dog that howls at the moon', difficulty: 'easy' },
    { word: 'CRAB', hint: 'A sea creature that walks sideways', difficulty: 'easy' },
    { word: 'DEER', hint: 'A graceful animal with antlers', difficulty: 'easy' },
    { word: 'GOAT', hint: 'A farm animal that loves to climb', difficulty: 'easy' },
    { word: 'SWAN', hint: 'A beautiful white bird that swims', difficulty: 'easy' },
    { word: 'HORSE', hint: 'A large animal people ride', difficulty: 'easy' },
    { word: 'SHEEP', hint: 'A farm animal that gives us wool', difficulty: 'easy' },
    // Medium
    { word: 'CAMEL', hint: 'A desert animal with one or two humps', difficulty: 'medium' },
    { word: 'TIGER', hint: 'A large striped wild cat', difficulty: 'medium' },
    { word: 'PANDA', hint: 'A black and white bear from China', difficulty: 'medium' },
    { word: 'KOALA', hint: 'A fluffy Australian animal that eats eucalyptus', difficulty: 'medium' },
    { word: 'SHARK', hint: 'A large dangerous fish with sharp teeth', difficulty: 'medium' },
    { word: 'PARROT', hint: 'A colourful bird that can copy human speech', difficulty: 'medium' },
    { word: 'MONKEY', hint: 'A clever animal that swings through trees', difficulty: 'medium' },
    { word: 'DONKEY', hint: 'A grey farm animal used to carry loads', difficulty: 'medium' },
    { word: 'PIGEON', hint: 'A grey bird commonly seen in cities', difficulty: 'medium' },
    { word: 'SALMON', hint: 'A pink fish that swims upstream to lay eggs', difficulty: 'medium' },
    { word: 'RABBIT', hint: 'A small fluffy animal with long ears that hops', difficulty: 'medium' },
    { word: 'TURTLE', hint: 'A slow reptile that carries its shell on its back', difficulty: 'medium' },
    { word: 'LIZARD', hint: 'A small scaly reptile with four legs', difficulty: 'medium' },
    { word: 'HIPPO', hint: 'A very large animal that loves to swim in rivers', difficulty: 'medium' },
    { word: 'EAGLE', hint: 'A large powerful bird that hunts from the sky', difficulty: 'medium' },
    // Hard
    { word: 'ELEPHANT', hint: 'A large grey animal with a trunk', difficulty: 'hard' },
    { word: 'GIRAFFE', hint: 'The tallest animal in the world', difficulty: 'hard' },
    { word: 'PENGUIN', hint: 'A bird that cannot fly and lives in cold places', difficulty: 'hard' },
    { word: 'DOLPHIN', hint: 'A smart sea mammal that jumps out of water', difficulty: 'hard' },
    { word: 'LEOPARD', hint: 'A spotted big cat', difficulty: 'hard' },
    { word: 'GORILLA', hint: 'A large powerful ape', difficulty: 'hard' },
    { word: 'OSTRICH', hint: 'The biggest bird in the world', difficulty: 'hard' },
    { word: 'CHEETAH', hint: 'The fastest land animal', difficulty: 'hard' },
    { word: 'HAMSTER', hint: 'A small furry pet that runs on a wheel', difficulty: 'hard' },
    { word: 'BUFFALO', hint: 'A large horned animal that roams in herds', difficulty: 'hard' },
    { word: 'CROCODILE', hint: 'A large reptile with sharp teeth that lives in rivers', difficulty: 'hard' },
    { word: 'FLAMINGO', hint: 'A pink bird that stands on one leg', difficulty: 'hard' },
    { word: 'CHAMELEON', hint: 'A lizard that can change colour', difficulty: 'hard' },
    { word: 'JELLYFISH', hint: 'A transparent sea creature with tentacles', difficulty: 'hard' },
    { word: 'ALBATROSS', hint: 'A large seabird with the widest wingspan of any bird', difficulty: 'hard' },
  ],
  Food: [
    // Easy
    { word: 'EGG', hint: 'A food that comes from a chicken', difficulty: 'easy' },
    { word: 'PIE', hint: 'A baked dish with pastry on top', difficulty: 'easy' },
    { word: 'JAM', hint: 'A sweet spread made from fruit', difficulty: 'easy' },
    { word: 'HAM', hint: 'A pink meat from a pig', difficulty: 'easy' },
    { word: 'NUT', hint: 'A hard-shelled seed you can eat', difficulty: 'easy' },
    { word: 'RICE', hint: 'White grains eaten as a staple food in Asia', difficulty: 'easy' },
    { word: 'MILK', hint: 'A white drink that comes from cows', difficulty: 'easy' },
    { word: 'CORN', hint: 'A yellow vegetable that grows on a cob', difficulty: 'easy' },
    { word: 'BEAN', hint: 'A small green or red vegetable', difficulty: 'easy' },
    { word: 'PEAR', hint: 'A green or yellow fruit shaped like a teardrop', difficulty: 'easy' },
    { word: 'PLUM', hint: 'A small round purple fruit', difficulty: 'easy' },
    { word: 'CAKE', hint: 'A sweet baked food eaten at birthdays', difficulty: 'easy' },
    { word: 'SOUP', hint: 'A hot liquid food eaten with a spoon', difficulty: 'easy' },
    { word: 'TUNA', hint: 'A large fish often eaten in sandwiches', difficulty: 'easy' },
    { word: 'LIME', hint: 'A small sour green fruit', difficulty: 'easy' },
    // Medium
    { word: 'MELON', hint: 'A large round sweet fruit with green skin', difficulty: 'medium' },
    { word: 'GRAPE', hint: 'A small round fruit that grows in bunches', difficulty: 'medium' },
    { word: 'BACON', hint: 'Strips of cooked pork eaten at breakfast', difficulty: 'medium' },
    { word: 'PASTA', hint: 'An Italian food made from flour and water', difficulty: 'medium' },
    { word: 'CURRY', hint: 'A spicy dish popular in India and Thailand', difficulty: 'medium' },
    { word: 'DONUT', hint: 'A round sweet fried dough with a hole in the middle', difficulty: 'medium' },
    { word: 'TOAST', hint: 'Bread that has been heated until brown and crispy', difficulty: 'medium' },
    { word: 'SALAD', hint: 'A cold dish made from raw vegetables', difficulty: 'medium' },
    { word: 'STEAK', hint: 'A thick slice of grilled or fried meat', difficulty: 'medium' },
    { word: 'PRAWN', hint: 'A small pink seafood popular in Thai dishes', difficulty: 'medium' },
    { word: 'NOODLE', hint: 'A long thin food made from flour and water', difficulty: 'medium' },
    { word: 'MUFFIN', hint: 'A small round sweet baked cake', difficulty: 'medium' },
    { word: 'WAFFLE', hint: 'A crispy grid-patterned food eaten with syrup', difficulty: 'medium' },
    { word: 'BUTTER', hint: 'A yellow spread made from cream', difficulty: 'medium' },
    { word: 'LEMON', hint: 'A sour yellow citrus fruit', difficulty: 'medium' },
    // Hard
    { word: 'SPAGHETTI', hint: 'Long thin Italian pasta', difficulty: 'hard' },
    { word: 'BROCCOLI', hint: 'A green vegetable that looks like a tree', difficulty: 'hard' },
    { word: 'CHOCOLATE', hint: 'A sweet brown treat made from cocoa', difficulty: 'hard' },
    { word: 'PINEAPPLE', hint: 'A tropical fruit with spiky skin', difficulty: 'hard' },
    { word: 'AVOCADO', hint: 'A green creamy fruit used in guacamole', difficulty: 'hard' },
    { word: 'CROISSANT', hint: 'A flaky crescent-shaped pastry', difficulty: 'hard' },
    { word: 'BLUEBERRY', hint: 'A small round dark blue fruit', difficulty: 'hard' },
    { word: 'CUCUMBER', hint: 'A long green vegetable eaten in salads', difficulty: 'hard' },
    { word: 'OMELETTE', hint: 'A dish made from beaten fried eggs', difficulty: 'hard' },
    { word: 'DUMPLING', hint: 'A small dough parcel filled with meat or vegetables', difficulty: 'hard' },
    { word: 'TIRAMISU', hint: 'An Italian dessert made with coffee and cream', difficulty: 'hard' },
    { word: 'PAELLA', hint: 'A Spanish rice dish cooked with seafood', difficulty: 'hard' },
    { word: 'SMOOTHIE', hint: 'A blended drink made from fruit', difficulty: 'hard' },
    { word: 'POPCORN', hint: 'A snack made from heated corn kernels', difficulty: 'hard' },
    { word: 'BURRITO', hint: 'A Mexican wrap filled with rice and beans', difficulty: 'hard' },
  ],
  Sports: [
    // Easy
    { word: 'RUN', hint: 'Moving fast on your feet', difficulty: 'easy' },
    { word: 'SWIM', hint: 'Moving through water using your body', difficulty: 'easy' },
    { word: 'JUMP', hint: 'Leaping off the ground', difficulty: 'easy' },
    { word: 'KICK', hint: 'Hitting a ball with your foot', difficulty: 'easy' },
    { word: 'GOLF', hint: 'A sport where you hit a small ball into a hole', difficulty: 'easy' },
    { word: 'RACE', hint: 'A competition to see who is fastest', difficulty: 'easy' },
    { word: 'DIVE', hint: 'Jumping headfirst into water', difficulty: 'easy' },
    { word: 'JUDO', hint: 'A Japanese martial art sport', difficulty: 'easy' },
    { word: 'DARTS', hint: 'Throwing small pointed objects at a round board', difficulty: 'easy' },
    { word: 'SCORE', hint: 'A point gained in a game or sport', difficulty: 'easy' },
    { word: 'CATCH', hint: 'Grabbing a ball that has been thrown to you', difficulty: 'easy' },
    { word: 'THROW', hint: 'Sending an object through the air with your hand', difficulty: 'easy' },
    { word: 'PITCH', hint: 'The field where football is played', difficulty: 'easy' },
    { word: 'MATCH', hint: 'A game between two teams', difficulty: 'easy' },
    { word: 'MEDAL', hint: 'A metal disc given to a winner', difficulty: 'easy' },
    // Medium
    { word: 'RUGBY', hint: 'A contact sport where you carry an oval ball', difficulty: 'medium' },
    { word: 'HOCKEY', hint: 'A sport played with a stick and a puck', difficulty: 'medium' },
    { word: 'ROWING', hint: 'Moving a boat through water using oars', difficulty: 'medium' },
    { word: 'SKIING', hint: 'Sliding down snowy slopes on long flat boards', difficulty: 'medium' },
    { word: 'KARATE', hint: 'A Japanese martial art using punches and kicks', difficulty: 'medium' },
    { word: 'BOXING', hint: 'A sport where two people fight with padded gloves', difficulty: 'medium' },
    { word: 'SPRINT', hint: 'Running as fast as you can over a short distance', difficulty: 'medium' },
    { word: 'TENNIS', hint: 'Hitting a ball over a net with a racket', difficulty: 'medium' },
    { word: 'RELAY', hint: 'A team running race where you pass a baton', difficulty: 'medium' },
    { word: 'COACH', hint: 'A person who trains a sports team', difficulty: 'medium' },
    { word: 'SURFING', hint: 'Riding waves on a board', difficulty: 'medium' },
    { word: 'SKATING', hint: 'Moving on ice or wheels on your feet', difficulty: 'medium' },
    { word: 'CRICKET', hint: 'A bat and ball sport popular in England', difficulty: 'medium' },
    { word: 'CYCLING', hint: 'Riding a bicycle competitively', difficulty: 'medium' },
    { word: 'JOGGING', hint: 'Running slowly for exercise', difficulty: 'medium' },
    // Hard
    { word: 'FOOTBALL', hint: 'The most popular sport in the world', difficulty: 'hard' },
    { word: 'SWIMMING', hint: 'A competitive sport done in a pool', difficulty: 'hard' },
    { word: 'BASKETBALL', hint: 'Throwing a ball through a hoop', difficulty: 'hard' },
    { word: 'BADMINTON', hint: 'Hitting a shuttlecock over a net', difficulty: 'hard' },
    { word: 'GYMNASTICS', hint: 'Performing flips and balances', difficulty: 'hard' },
    { word: 'VOLLEYBALL', hint: 'Hitting a ball over a high net with your hands', difficulty: 'hard' },
    { word: 'BASEBALL', hint: 'Hitting a ball with a bat and running bases', difficulty: 'hard' },
    { word: 'ARCHERY', hint: 'Shooting arrows at a target', difficulty: 'hard' },
    { word: 'WRESTLING', hint: 'A combat sport where you grapple your opponent', difficulty: 'hard' },
    { word: 'MARATHON', hint: 'A very long running race of 42 kilometres', difficulty: 'hard' },
    { word: 'TRIATHLON', hint: 'A race combining swimming cycling and running', difficulty: 'hard' },
    { word: 'DECATHLON', hint: 'An athletics event with ten disciplines', difficulty: 'hard' },
    { word: 'PENTATHLON', hint: 'An Olympic event with five different sports', difficulty: 'hard' },
    { word: 'LACROSSE', hint: 'A team sport played with a net on a stick', difficulty: 'hard' },
    { word: 'SQUASH', hint: 'A racket sport played inside a walled court', difficulty: 'hard' },
  ],
  Nature: [
    // Easy
    { word: 'SUN', hint: 'The bright star that gives us light and heat', difficulty: 'easy' },
    { word: 'SEA', hint: 'A large body of salt water', difficulty: 'easy' },
    { word: 'ICE', hint: 'Frozen water', difficulty: 'easy' },
    { word: 'SKY', hint: 'The blue space above us', difficulty: 'easy' },
    { word: 'RAIN', hint: 'Water that falls from clouds', difficulty: 'easy' },
    { word: 'ROCK', hint: 'A hard solid piece of the earth', difficulty: 'easy' },
    { word: 'LAKE', hint: 'A large body of water surrounded by land', difficulty: 'easy' },
    { word: 'LEAF', hint: 'The flat green part of a plant or tree', difficulty: 'easy' },
    { word: 'SEED', hint: 'A tiny thing that grows into a plant', difficulty: 'easy' },
    { word: 'WIND', hint: 'Air that moves across the land', difficulty: 'easy' },
    { word: 'WAVE', hint: 'Water that moves up and down in the sea', difficulty: 'easy' },
    { word: 'CAVE', hint: 'A hollow space inside a rock or mountain', difficulty: 'easy' },
    { word: 'POND', hint: 'A small body of still water', difficulty: 'easy' },
    { word: 'SOIL', hint: 'The dark brown earth that plants grow in', difficulty: 'easy' },
    { word: 'TREE', hint: 'A tall plant with a trunk and branches', difficulty: 'easy' },
    // Medium
    { word: 'CLOUD', hint: 'A fluffy white shape floating in the sky', difficulty: 'medium' },
    { word: 'RIVER', hint: 'A long moving body of water', difficulty: 'medium' },
    { word: 'FROST', hint: 'A thin layer of ice that forms on cold surfaces', difficulty: 'medium' },
    { word: 'BEACH', hint: 'A sandy area beside the sea', difficulty: 'medium' },
    { word: 'CORAL', hint: 'A colourful underwater structure made by tiny sea creatures', difficulty: 'medium' },
    { word: 'THORN', hint: 'A sharp point on a plant like a rose', difficulty: 'medium' },
    { word: 'PETAL', hint: 'The coloured part of a flower', difficulty: 'medium' },
    { word: 'ACORN', hint: 'The small nut that grows on an oak tree', difficulty: 'medium' },
    { word: 'CLIFF', hint: 'A steep high wall of rock beside the sea', difficulty: 'medium' },
    { word: 'SHORE', hint: 'The land at the edge of a sea or lake', difficulty: 'medium' },
    { word: 'BROOK', hint: 'A small narrow stream of water', difficulty: 'medium' },
    { word: 'DUNES', hint: 'Hills of sand shaped by the wind', difficulty: 'medium' },
    { word: 'TRUNK', hint: 'The thick main stem of a tree', difficulty: 'medium' },
    { word: 'BLOOM', hint: 'When a flower opens up and shows its colour', difficulty: 'medium' },
    { word: 'MARSH', hint: 'Wet soft muddy ground near water', difficulty: 'medium' },
    // Hard
    { word: 'VOLCANO', hint: 'A mountain that can erupt with lava', difficulty: 'hard' },
    { word: 'RAINBOW', hint: 'Coloured arc in the sky after rain', difficulty: 'hard' },
    { word: 'WATERFALL', hint: 'Water flowing over the edge of a cliff', difficulty: 'hard' },
    { word: 'GLACIER', hint: 'A slow moving river of ice', difficulty: 'hard' },
    { word: 'TORNADO', hint: 'A spinning column of destructive wind', difficulty: 'hard' },
    { word: 'DESERT', hint: 'A very dry and hot sandy landscape', difficulty: 'hard' },
    { word: 'JUNGLE', hint: 'A dense tropical forest', difficulty: 'hard' },
    { word: 'MOUNTAIN', hint: 'A very high piece of land', difficulty: 'hard' },
    { word: 'CRYSTAL', hint: 'A natural mineral with a geometric shape', difficulty: 'hard' },
    { word: 'CANYON', hint: 'A deep narrow valley cut by a river', difficulty: 'hard' },
    { word: 'AVALANCHE', hint: 'A mass of snow sliding rapidly down a mountain', difficulty: 'hard' },
    { word: 'PENINSULA', hint: 'A piece of land almost surrounded by water', difficulty: 'hard' },
    { word: 'MANGROVE', hint: 'A tropical tree that grows in coastal swampy water', difficulty: 'hard' },
    { word: 'LAGOON', hint: 'A shallow body of water separated from the sea by a reef', difficulty: 'hard' },
    { word: 'TUNDRA', hint: 'A vast flat treeless Arctic region', difficulty: 'hard' },
  ],
  School: [
    // Easy
    { word: 'PEN', hint: 'A tool used to write with ink', difficulty: 'easy' },
    { word: 'BAG', hint: 'You carry your books in this to school', difficulty: 'easy' },
    { word: 'MAP', hint: 'A drawing that shows where places are', difficulty: 'easy' },
    { word: 'DESK', hint: 'A table where you sit and work at school', difficulty: 'easy' },
    { word: 'BOOK', hint: 'Something you read with pages inside', difficulty: 'easy' },
    { word: 'EXAM', hint: 'A test you take at school', difficulty: 'easy' },
    { word: 'BELL', hint: 'It rings to tell you class has started or ended', difficulty: 'easy' },
    { word: 'GLUE', hint: 'A sticky substance used to join things together', difficulty: 'easy' },
    { word: 'PAINT', hint: 'Coloured liquid used to make pictures', difficulty: 'easy' },
    { word: 'CLASS', hint: 'A group of students who learn together', difficulty: 'easy' },
    { word: 'STUDY', hint: 'To learn and prepare for lessons', difficulty: 'easy' },
    { word: 'WRITE', hint: 'To form letters and words with a pen', difficulty: 'easy' },
    { word: 'LEARN', hint: 'To gain new knowledge or skills', difficulty: 'easy' },
    { word: 'SPELL', hint: 'To write letters of a word in the correct order', difficulty: 'easy' },
    { word: 'LUNCH', hint: 'The meal eaten in the middle of the school day', difficulty: 'easy' },
    // Medium
    { word: 'RULER', hint: 'A flat stick used for measuring', difficulty: 'medium' },
    { word: 'PENCIL', hint: 'A thin writing tool with graphite inside', difficulty: 'medium' },
    { word: 'ERASER', hint: 'A tool used to remove pencil marks', difficulty: 'medium' },
    { word: 'FOLDER', hint: 'A cardboard cover used to store papers', difficulty: 'medium' },
    { word: 'POSTER', hint: 'A large picture displayed on a wall', difficulty: 'medium' },
    { word: 'MARKER', hint: 'A thick pen used to write on whiteboards', difficulty: 'medium' },
    { word: 'REPORT', hint: 'A written assessment of a students progress', difficulty: 'medium' },
    { word: 'GRADES', hint: 'Marks given to show how well you did', difficulty: 'medium' },
    { word: 'LESSON', hint: 'A period of time when you are taught something', difficulty: 'medium' },
    { word: 'DRAMA', hint: 'A school subject where you act and perform', difficulty: 'medium' },
    { word: 'MUSIC', hint: 'A school subject where you sing and play instruments', difficulty: 'medium' },
    { word: 'SPORTS', hint: 'Physical activities done at school', difficulty: 'medium' },
    { word: 'AWARD', hint: 'A prize given for doing something well', difficulty: 'medium' },
    { word: 'PUPIL', hint: 'Another word for a student at school', difficulty: 'medium' },
    { word: 'BOARD', hint: 'The large flat surface the teacher writes on', difficulty: 'medium' },
    // Hard
    { word: 'LIBRARY', hint: 'A place full of books to borrow', difficulty: 'hard' },
    { word: 'HOMEWORK', hint: 'Work you do at home for school', difficulty: 'hard' },
    { word: 'CLASSROOM', hint: 'The room where you learn', difficulty: 'hard' },
    { word: 'TEXTBOOK', hint: 'A book used for studying a subject', difficulty: 'hard' },
    { word: 'CALCULATOR', hint: 'A device used to do maths', difficulty: 'hard' },
    { word: 'TIMETABLE', hint: 'A schedule showing when classes happen', difficulty: 'hard' },
    { word: 'UNIFORM', hint: 'The special clothes worn at school', difficulty: 'hard' },
    { word: 'SCISSORS', hint: 'A tool used for cutting paper', difficulty: 'hard' },
    { word: 'DIPLOMA', hint: 'A certificate showing you passed a course', difficulty: 'hard' },
    { word: 'PRINCIPAL', hint: 'The head teacher of a school', difficulty: 'hard' },
    { word: 'ASSEMBLY', hint: 'A meeting of the whole school together', difficulty: 'hard' },
    { word: 'DETENTION', hint: 'A punishment where a student stays after school', difficulty: 'hard' },
    { word: 'LABORATORY', hint: 'A room used for science experiments', difficulty: 'hard' },
    { word: 'GYMNASIUM', hint: 'A large room used for physical education', difficulty: 'hard' },
    { word: 'GRADUATION', hint: 'A ceremony where you receive your qualification', difficulty: 'hard' },
  ],
  Travel: [
    // Easy
    { word: 'CAR', hint: 'A vehicle with four wheels', difficulty: 'easy' },
    { word: 'BUS', hint: 'A large vehicle that carries many passengers', difficulty: 'easy' },
    { word: 'MAP', hint: 'Shows you where places are and how to get there', difficulty: 'easy' },
    { word: 'TRIP', hint: 'A short journey to somewhere', difficulty: 'easy' },
    { word: 'ROAD', hint: 'A path that vehicles travel on', difficulty: 'easy' },
    { word: 'SHIP', hint: 'A large boat that travels on the sea', difficulty: 'easy' },
    { word: 'CAMP', hint: 'Staying overnight outdoors in a tent', difficulty: 'easy' },
    { word: 'TOUR', hint: 'A journey visiting different places', difficulty: 'easy' },
    { word: 'PLANE', hint: 'A vehicle that flies through the sky', difficulty: 'easy' },
    { word: 'TRAIN', hint: 'A vehicle that travels on rails', difficulty: 'easy' },
    { word: 'BEACH', hint: 'A sandy area next to the sea', difficulty: 'easy' },
    { word: 'HOTEL', hint: 'A building where travellers pay to sleep', difficulty: 'easy' },
    { word: 'FERRY', hint: 'A boat that carries passengers across water', difficulty: 'easy' },
    { word: 'GUIDE', hint: 'A person who shows tourists around a place', difficulty: 'easy' },
    { word: 'OCEAN', hint: 'A vast area of sea crossed when travelling', difficulty: 'easy' },
    // Medium
    { word: 'TICKET', hint: 'A piece of paper that lets you travel', difficulty: 'medium' },
    { word: 'BRIDGE', hint: 'A structure built over water so you can cross', difficulty: 'medium' },
    { word: 'ISLAND', hint: 'A piece of land completely surrounded by water', difficulty: 'medium' },
    { word: 'CRUISE', hint: 'A holiday taken on a large ship', difficulty: 'medium' },
    { word: 'MARKET', hint: 'An outdoor place where people buy and sell goods', difficulty: 'medium' },
    { word: 'TEMPLE', hint: 'A religious building visited by tourists in Asia', difficulty: 'medium' },
    { word: 'SAFARI', hint: 'A trip to see wild animals in their natural habitat', difficulty: 'medium' },
    { word: 'CASTLE', hint: 'A large old stone building with towers', difficulty: 'medium' },
    { word: 'MUSEUM', hint: 'A building where historical objects are displayed', difficulty: 'medium' },
    { word: 'JUNGLE', hint: 'A thick tropical forest visited by adventurers', difficulty: 'medium' },
    { word: 'CABIN', hint: 'A small room on a ship or a simple house', difficulty: 'medium' },
    { word: 'LODGE', hint: 'A small hotel often found in a forest', difficulty: 'medium' },
    { word: 'RUINS', hint: 'The remains of old buildings visited by tourists', difficulty: 'medium' },
    { word: 'ATLAS', hint: 'A book of maps used to plan journeys', difficulty: 'medium' },
    { word: 'TAXIS', hint: 'Cars for hire that take passengers to destinations', difficulty: 'medium' },
    // Hard
    { word: 'PASSPORT', hint: 'The document you need to travel abroad', difficulty: 'hard' },
    { word: 'AIRPORT', hint: 'Where planes take off and land', difficulty: 'hard' },
    { word: 'LUGGAGE', hint: 'Your bags and suitcases when travelling', difficulty: 'hard' },
    { word: 'TOURIST', hint: 'A person visiting a place on holiday', difficulty: 'hard' },
    { word: 'CURRENCY', hint: 'The money used in a particular country', difficulty: 'hard' },
    { word: 'CUSTOMS', hint: 'The checkpoint when entering a new country', difficulty: 'hard' },
    { word: 'SOUVENIR', hint: 'A gift bought to remember a place', difficulty: 'hard' },
    { word: 'ITINERARY', hint: 'A planned schedule for a trip', difficulty: 'hard' },
    { word: 'DEPARTURE', hint: 'Leaving a place on a journey', difficulty: 'hard' },
    { word: 'ARRIVAL', hint: 'Reaching your destination', difficulty: 'hard' },
    { word: 'EXCURSION', hint: 'A short trip made for pleasure', difficulty: 'hard' },
    { word: 'EXPEDITION', hint: 'A journey made for a specific purpose', difficulty: 'hard' },
    { word: 'QUARANTINE', hint: 'A period of isolation when entering a country', difficulty: 'hard' },
    { word: 'IMMIGRATION', hint: 'The process of entering and settling in a new country', difficulty: 'hard' },
    { word: 'DESTINATION', hint: 'The place you are travelling to', difficulty: 'hard' },
  ],
  Technology: [
    // Easy
    { word: 'APP', hint: 'A program on your phone or tablet', difficulty: 'easy' },
    { word: 'NET', hint: 'Short name for the internet', difficulty: 'easy' },
    { word: 'WIFI', hint: 'Wireless connection to the internet', difficulty: 'easy' },
    { word: 'GAME', hint: 'An activity you play on a screen for fun', difficulty: 'easy' },
    { word: 'PHONE', hint: 'A device you use to call and message people', difficulty: 'easy' },
    { word: 'PHOTO', hint: 'A picture taken with a camera', difficulty: 'easy' },
    { word: 'VIDEO', hint: 'A moving picture you can watch on a screen', difficulty: 'easy' },
    { word: 'MOUSE', hint: 'A small device you move to control a computer', difficulty: 'easy' },
    { word: 'CLICK', hint: 'Pressing a mouse button to select something', difficulty: 'easy' },
    { word: 'SHARE', hint: 'Sending or showing content to others online', difficulty: 'easy' },
    { word: 'EMOJI', hint: 'A small picture used in messages to show feelings', difficulty: 'easy' },
    { word: 'LOGIN', hint: 'Entering your username and password', difficulty: 'easy' },
    { word: 'CLOUD', hint: 'Online storage where you save files', difficulty: 'easy' },
    { word: 'SWIPE', hint: 'Moving your finger across a touchscreen', difficulty: 'easy' },
    { word: 'INBOX', hint: 'The folder where you receive emails', difficulty: 'easy' },
    // Medium
    { word: 'SCREEN', hint: 'The flat display you look at on a device', difficulty: 'medium' },
    { word: 'CABLE', hint: 'A wire used to connect devices', difficulty: 'medium' },
    { word: 'ROBOT', hint: 'A machine that can do jobs automatically', difficulty: 'medium' },
    { word: 'TABLET', hint: 'A flat touchscreen device bigger than a phone', difficulty: 'medium' },
    { word: 'REMOTE', hint: 'A device used to control a TV from a distance', difficulty: 'medium' },
    { word: 'GADGET', hint: 'A small clever electronic device', difficulty: 'medium' },
    { word: 'SEARCH', hint: 'Looking for information online', difficulty: 'medium' },
    { word: 'UPLOAD', hint: 'Sending a file from your device to the internet', difficulty: 'medium' },
    { word: 'CURSOR', hint: 'The small arrow that moves on your computer screen', difficulty: 'medium' },
    { word: 'SIGNAL', hint: 'Information sent wirelessly between devices', difficulty: 'medium' },
    { word: 'MEMORY', hint: 'The part of a computer that stores information', difficulty: 'medium' },
    { word: 'UPDATE', hint: 'New software installed to improve a device', difficulty: 'medium' },
    { word: 'LAPTOP', hint: 'A portable computer you can carry around', difficulty: 'medium' },
    { word: 'BUTTON', hint: 'A small thing you press to make something work', difficulty: 'medium' },
    { word: 'PIXEL', hint: 'The smallest dot that makes up a digital image', difficulty: 'medium' },
    // Hard
    { word: 'KEYBOARD', hint: 'You type on this to use a computer', difficulty: 'hard' },
    { word: 'INTERNET', hint: 'A global network connecting computers', difficulty: 'hard' },
    { word: 'SOFTWARE', hint: 'Programs that run on a computer', difficulty: 'hard' },
    { word: 'BLUETOOTH', hint: 'Wireless technology for connecting devices', difficulty: 'hard' },
    { word: 'DOWNLOAD', hint: 'To copy a file from the internet to your device', difficulty: 'hard' },
    { word: 'CHARGER', hint: 'A device that refills your battery', difficulty: 'hard' },
    { word: 'WEBSITE', hint: 'A page or collection of pages on the internet', difficulty: 'hard' },
    { word: 'PASSWORD', hint: 'A secret word used to log in', difficulty: 'hard' },
    { word: 'PRINTER', hint: 'A machine that puts digital content on paper', difficulty: 'hard' },
    { word: 'MONITOR', hint: 'The screen of a computer', difficulty: 'hard' },
    { word: 'WIRELESS', hint: 'Connected without cables', difficulty: 'hard' },
    { word: 'MICROPHONE', hint: 'A device that picks up sound', difficulty: 'hard' },
    { word: 'ALGORITHM', hint: 'A set of rules a computer follows to solve a problem', difficulty: 'hard' },
    { word: 'DATABASE', hint: 'An organised collection of stored data', difficulty: 'hard' },
    { word: 'PROCESSOR', hint: 'The brain of a computer that carries out instructions', difficulty: 'hard' },
  ],
  Countries: [
    // Easy
    { word: 'USA', hint: 'The country with the Statue of Liberty', difficulty: 'easy' },
    { word: 'IRAN', hint: 'A Middle Eastern country formerly called Persia', difficulty: 'easy' },
    { word: 'IRAQ', hint: 'A Middle Eastern country by the Tigris River', difficulty: 'easy' },
    { word: 'PERU', hint: 'A South American country with Machu Picchu', difficulty: 'easy' },
    { word: 'CUBA', hint: 'A Caribbean island country', difficulty: 'easy' },
    { word: 'LAOS', hint: 'A small landlocked country next to Thailand', difficulty: 'easy' },
    { word: 'OMAN', hint: 'A Middle Eastern country on the Arabian Peninsula', difficulty: 'easy' },
    { word: 'TONGA', hint: 'A small Pacific island nation', difficulty: 'easy' },
    { word: 'NIGER', hint: 'A large landlocked country in West Africa', difficulty: 'easy' },
    { word: 'CHILE', hint: 'A long thin country on the west coast of South America', difficulty: 'easy' },
    { word: 'WALES', hint: 'A country in the UK with a dragon on its flag', difficulty: 'easy' },
    { word: 'SPAIN', hint: 'A sunny European country famous for flamenco', difficulty: 'easy' },
    { word: 'INDIA', hint: 'A large Asian country famous for the Taj Mahal', difficulty: 'easy' },
    { word: 'QATAR', hint: 'A small wealthy Middle Eastern country', difficulty: 'easy' },
    { word: 'NEPAL', hint: 'A small country home to Mount Everest', difficulty: 'easy' },
    // Medium
    { word: 'FRANCE', hint: 'A country famous for the Eiffel Tower', difficulty: 'medium' },
    { word: 'BRAZIL', hint: 'The largest country in South America', difficulty: 'medium' },
    { word: 'JAPAN', hint: 'An island nation in East Asia famous for sushi', difficulty: 'medium' },
    { word: 'CANADA', hint: 'The second largest country in the world', difficulty: 'medium' },
    { word: 'MEXICO', hint: 'A country famous for tacos and pyramids', difficulty: 'medium' },
    { word: 'EGYPT', hint: 'A country in North Africa famous for pyramids', difficulty: 'medium' },
    { word: 'RUSSIA', hint: 'The largest country in the world', difficulty: 'medium' },
    { word: 'ITALY', hint: 'A European country shaped like a boot', difficulty: 'medium' },
    { word: 'CHINA', hint: 'The most populous country in the world', difficulty: 'medium' },
    { word: 'KENYA', hint: 'An African country famous for safaris', difficulty: 'medium' },
    { word: 'GREECE', hint: 'A European country famous for ancient history', difficulty: 'medium' },
    { word: 'TURKEY', hint: 'A country between Europe and Asia', difficulty: 'medium' },
    { word: 'SWEDEN', hint: 'A Scandinavian country famous for IKEA', difficulty: 'medium' },
    { word: 'PANAMA', hint: 'A Central American country with a famous canal', difficulty: 'medium' },
    { word: 'JORDAN', hint: 'A Middle Eastern country home to Petra', difficulty: 'medium' },
    // Hard
    { word: 'THAILAND', hint: 'A country in Southeast Asia famous for temples', difficulty: 'hard' },
    { word: 'AUSTRALIA', hint: 'A country and continent in the southern hemisphere', difficulty: 'hard' },
    { word: 'GERMANY', hint: 'A European country famous for cars and beer', difficulty: 'hard' },
    { word: 'NORWAY', hint: 'A Scandinavian country famous for fjords', difficulty: 'hard' },
    { word: 'COLOMBIA', hint: 'A South American country famous for coffee', difficulty: 'hard' },
    { word: 'INDONESIA', hint: 'The worlds largest archipelago nation', difficulty: 'hard' },
    { word: 'ARGENTINA', hint: 'A South American country famous for tango', difficulty: 'hard' },
    { word: 'PORTUGAL', hint: 'A country in southwestern Europe', difficulty: 'hard' },
    { word: 'MALAYSIA', hint: 'A Southeast Asian country neighbouring Thailand', difficulty: 'hard' },
    { word: 'MOROCCO', hint: 'A North African country famous for its souks', difficulty: 'hard' },
    { word: 'VIETNAM', hint: 'A Southeast Asian country famous for pho', difficulty: 'hard' },
    { word: 'ETHIOPIA', hint: 'An African country known as the cradle of humanity', difficulty: 'hard' },
    { word: 'PAKISTAN', hint: 'A South Asian country bordering India', difficulty: 'hard' },
    { word: 'UKRAINE', hint: 'A large Eastern European country', difficulty: 'hard' },
    { word: 'SINGAPORE', hint: 'A tiny but wealthy city state in Southeast Asia', difficulty: 'hard' },
  ],
}

export function scrambleWord(word: string): string {
  const arr = word.split('')
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]]
  }
  const result = arr.join('')
  return result === word ? scrambleWord(word) : result
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}

export function getWordsByDifficulty(topic: string, difficulty: Difficulty): { word: string; hint: string }[] {
  const bank = scrambleBank[topic] || scrambleBank['Animals']
  return bank.filter(w => w.difficulty === difficulty)
}