export const scrambleBank: Record<string, { word: string; hint: string }[]> = {
  Animals: [
    { word: 'ELEPHANT', hint: 'A large grey animal with a trunk' },
    { word: 'GIRAFFE', hint: 'The tallest animal in the world' },
    { word: 'PENGUIN', hint: 'A bird that cannot fly and lives in cold places' },
    { word: 'DOLPHIN', hint: 'A smart sea mammal that jumps out of water' },
    { word: 'LEOPARD', hint: 'A spotted big cat' },
    { word: 'GORILLA', hint: 'A large powerful ape' },
    { word: 'OSTRICH', hint: 'The biggest bird in the world' },
    { word: 'CHEETAH', hint: 'The fastest land animal' },
    { word: 'HAMSTER', hint: 'A small furry pet that runs on a wheel' },
    { word: 'PANTHER', hint: 'A large black wild cat' },
    { word: 'BUFFALO', hint: 'A large horned animal that roams in herds' },
    { word: 'VULTURE', hint: 'A large bird that eats dead animals' },
    { word: 'LOBSTER', hint: 'A red sea creature with claws' },
    { word: 'SPARROW', hint: 'A small common brown bird' },
    { word: 'PEACOCK', hint: 'A bird with a beautiful fan-like tail' },
    { word: 'FROG', hint: 'A green animal that jumps and lives near water' },
{ word: 'BEAR', hint: 'A large furry animal that loves honey' },
{ word: 'DUCK', hint: 'A bird that swims and says quack' },
{ word: 'WOLF', hint: 'A wild dog that howls at the moon' },
{ word: 'CRAB', hint: 'A sea creature that walks sideways' },
{ word: 'DEER', hint: 'A graceful animal with antlers' },
{ word: 'GOAT', hint: 'A farm animal that loves to climb' },
{ word: 'SWAN', hint: 'A beautiful white bird that swims' },
{ word: 'MOLE', hint: 'A small animal that digs underground tunnels' },
{ word: 'WORM', hint: 'A long thin creature that lives in soil' },
{ word: 'CAMEL', hint: 'A desert animal with one or two humps' },
{ word: 'TIGER', hint: 'A large striped wild cat' },
{ word: 'PANDA', hint: 'A black and white bear from China' },
{ word: 'KOALA', hint: 'A fluffy Australian animal that eats eucalyptus' },
{ word: 'SHARK', hint: 'A large dangerous fish with sharp teeth' },
{ word: 'PARROT', hint: 'A colourful bird that can copy human speech' },
{ word: 'MONKEY', hint: 'A clever animal that swings through trees' },
{ word: 'DONKEY', hint: 'A grey farm animal used to carry loads' },
{ word: 'PIGEON', hint: 'A grey bird commonly seen in cities' },
{ word: 'SALMON', hint: 'A pink fish that swims upstream to lay eggs' },
{ word: 'HORSE', hint: 'A large animal people ride' },
{ word: 'SHEEP', hint: 'A farm animal that gives us wool' },
{ word: 'MOUSE', hint: 'A tiny furry animal that loves cheese' },
{ word: 'EAGLE', hint: 'A large powerful bird that hunts from the sky' },
{ word: 'SNAIL', hint: 'A slow creature that carries its home on its back' },
{ word: 'CRANE', hint: 'A tall white bird with long legs and neck' },
{ word: 'HIPPO', hint: 'A very large animal that loves to swim in rivers' },
{ word: 'PUPPY', hint: 'A baby dog' },
{ word: 'KITTY', hint: 'A young or small cat' },
{ word: 'SKUNK', hint: 'A black and white animal famous for its bad smell' },
  ],
  Food: [
    { word: 'SPAGHETTI', hint: 'Long thin Italian pasta' },
    { word: 'BROCCOLI', hint: 'A green vegetable that looks like a tree' },
    { word: 'CHOCOLATE', hint: 'A sweet brown treat made from cocoa' },
    { word: 'PINEAPPLE', hint: 'A tropical fruit with spiky skin' },
    { word: 'MUSHROOM', hint: 'A fungus that grows in damp places' },
    { word: 'AVOCADO', hint: 'A green creamy fruit used in guacamole' },
    { word: 'CROISSANT', hint: 'A flaky crescent-shaped pastry' },
    { word: 'BLUEBERRY', hint: 'A small round dark blue fruit' },
    { word: 'CUCUMBER', hint: 'A long green vegetable eaten in salads' },
    { word: 'OMELETTE', hint: 'A dish made from beaten fried eggs' },
    { word: 'DUMPLING', hint: 'A small dough parcel filled with meat or vegetables' },
    { word: 'SMOOTHIE', hint: 'A blended drink made from fruit' },
    { word: 'PANCAKE', hint: 'A flat round food cooked in a pan' },
    { word: 'POPCORN', hint: 'A snack made from heated corn kernels' },
    { word: 'BURRITO', hint: 'A Mexican wrap filled with rice and beans' },
    { word: 'SOUP', hint: 'A hot liquid food eaten with a spoon' },
{ word: 'CAKE', hint: 'A sweet baked food eaten at birthdays' },
{ word: 'CORN', hint: 'A yellow vegetable that grows on a cob' },
{ word: 'BEAN', hint: 'A small green or red vegetable' },
{ word: 'PEAR', hint: 'A green or yellow fruit shaped like a teardrop' },
{ word: 'PLUM', hint: 'A small round purple fruit' },
{ word: 'LIME', hint: 'A small sour green fruit' },
{ word: 'TUNA', hint: 'A large fish often eaten in sandwiches' },
{ word: 'NOODLE', hint: 'A long thin food made from flour and water' },
{ word: 'TOAST', hint: 'Bread that has been heated until it is brown and crispy' },
{ word: 'MELON', hint: 'A large round sweet fruit with green skin' },
{ word: 'GRAPE', hint: 'A small round fruit that grows in bunches' },
{ word: 'OLIVE', hint: 'A small green or black fruit used in cooking' },
{ word: 'BACON', hint: 'Strips of cooked pork eaten at breakfast' },
{ word: 'PASTA', hint: 'An Italian food made from flour and water in different shapes' },
{ word: 'CURRY', hint: 'A spicy dish popular in India and Thailand' },
{ word: 'DONUT', hint: 'A round sweet fried dough with a hole in the middle' },
{ word: 'WAFFLE', hint: 'A crispy grid-patterned food eaten with syrup' },
{ word: 'PICKLE', hint: 'A vegetable preserved in vinegar' },
{ word: 'MUFFIN', hint: 'A small round sweet baked cake' },
{ word: 'SALAD', hint: 'A cold dish made from raw vegetables' },
{ word: 'STEAK', hint: 'A thick slice of grilled or fried meat' },
{ word: 'CREAM', hint: 'A thick white liquid that comes from milk' },
{ word: 'SYRUP', hint: 'A sweet thick liquid poured on pancakes' },
{ word: 'SPICE', hint: 'A flavouring added to food to make it taste better' },
{ word: 'PRAWN', hint: 'A small pink seafood popular in Thai dishes' },
{ word: 'SUSHI', hint: 'A Japanese dish made with rice and raw fish' },
{ word: 'TACO', hint: 'A Mexican folded tortilla filled with meat and salad' },
{ word: 'FUDGE', hint: 'A very sweet soft candy made from sugar and butter' },
{ word: 'SCONE', hint: 'A small round baked bread eaten with butter and jam' },
  ],
  Sports: [
    { word: 'FOOTBALL', hint: 'The most popular sport in the world' },
    { word: 'SWIMMING', hint: 'Moving through water using your body' },
    { word: 'BASKETBALL', hint: 'Throwing a ball through a hoop' },
    { word: 'BADMINTON', hint: 'Hitting a shuttlecock over a net' },
    { word: 'GYMNASTICS', hint: 'Performing flips and balances' },
    { word: 'VOLLEYBALL', hint: 'Hitting a ball over a high net with your hands' },
    { word: 'BASEBALL', hint: 'Hitting a ball with a bat and running bases' },
    { word: 'CRICKET', hint: 'A bat and ball sport popular in England and India' },
    { word: 'CYCLING', hint: 'Riding a bicycle competitively' },
    { word: 'ARCHERY', hint: 'Shooting arrows at a target' },
    { word: 'WRESTLING', hint: 'A combat sport where you grapple your opponent' },
    { word: 'MARATHON', hint: 'A very long running race of 42 kilometres' },
    { word: 'SURFING', hint: 'Riding waves on a board' },
    { word: 'SKATING', hint: 'Moving on ice or wheels on your feet' },
    { word: 'TENNIS', hint: 'Hitting a ball over a net with a racket' },
    { word: 'GOLF', hint: 'A sport where you hit a small ball into a hole' },
{ word: 'RACE', hint: 'A competition to see who is fastest' },
{ word: 'JUMP', hint: 'Leaping over something in athletics' },
{ word: 'SWIM', hint: 'Moving through water using your body' },
{ word: 'KICK', hint: 'Hitting a ball with your foot' },
{ word: 'DIVE', hint: 'Jumping headfirst into water' },
{ word: 'JUDO', hint: 'A Japanese martial art sport' },
{ word: 'POLO', hint: 'A sport played on horseback hitting a ball' },
{ word: 'DARTS', hint: 'Throwing small pointed objects at a round board' },
{ word: 'BOXING', hint: 'A sport where two people fight with padded gloves' },
{ word: 'RUGBY', hint: 'A contact sport where you carry and pass an oval ball' },
{ word: 'HOCKEY', hint: 'A sport played with a stick and a small ball or puck' },
{ word: 'ROWING', hint: 'Moving a boat through water using oars' },
{ word: 'SPRINT', hint: 'Running as fast as you can over a short distance' },
{ word: 'SKIING', hint: 'Sliding down snowy slopes on long flat boards' },
{ word: 'KARATE', hint: 'A Japanese martial art using punches and kicks' },
{ word: 'DISCUS', hint: 'Throwing a heavy flat circular object as far as possible' },
{ word: 'NETBALL', hint: 'A team sport where you shoot a ball through a high ring' },
{ word: 'JOGGING', hint: 'Running slowly for exercise' },
{ word: 'SAILING', hint: 'Travelling on water using a boat with sails' },
{ word: 'THROW', hint: 'Sending an object through the air with your hand' },
{ word: 'CATCH', hint: 'Grabbing a ball that has been thrown to you' },
{ word: 'CLIMB', hint: 'Moving upwards using your hands and feet' },
{ word: 'RELAY', hint: 'A team running race where you pass a baton' },
{ word: 'SCORE', hint: 'A point gained in a game or sport' },
{ word: 'MATCH', hint: 'A game or contest between two teams or players' },
{ word: 'TRAIN', hint: 'To practise and prepare for a sport' },
{ word: 'COACH', hint: 'A person who trains a sports team' },
{ word: 'MEDAL', hint: 'A metal disc given to a winner of a competition' },
{ word: 'PITCH', hint: 'The field where football or cricket is played' },
  ],
  Nature: [
    { word: 'VOLCANO', hint: 'A mountain that can erupt with lava' },
    { word: 'RAINBOW', hint: 'Coloured arc in the sky after rain' },
    { word: 'WATERFALL', hint: 'Water flowing over the edge of a cliff' },
    { word: 'GLACIER', hint: 'A slow moving river of ice' },
    { word: 'TORNADO', hint: 'A spinning column of destructive wind' },
    { word: 'DESERT', hint: 'A very dry and hot sandy landscape' },
    { word: 'JUNGLE', hint: 'A dense tropical forest' },
    { word: 'MOUNTAIN', hint: 'A very high piece of land' },
    { word: 'THUNDER', hint: 'The loud sound during a storm' },
    { word: 'CRYSTAL', hint: 'A natural mineral with a geometric shape' },
    { word: 'FOREST', hint: 'A large area covered with trees' },
    { word: 'ISLAND', hint: 'A piece of land surrounded by water' },
    { word: 'CANYON', hint: 'A deep narrow valley cut by a river' },
    { word: 'SWAMP', hint: 'A wet muddy area of land' },
    { word: 'CAVERN', hint: 'A large underground cave' },
    { word: 'RAIN', hint: 'Water that falls from clouds' },
{ word: 'ROCK', hint: 'A hard solid piece of the earth' },
{ word: 'LAKE', hint: 'A large body of water surrounded by land' },
{ word: 'LEAF', hint: 'The flat green part of a plant or tree' },
{ word: 'SEED', hint: 'A tiny thing that grows into a plant' },
{ word: 'WIND', hint: 'Air that moves across the land' },
{ word: 'WAVE', hint: 'Water that moves up and down in the sea' },
{ word: 'SOIL', hint: 'The dark brown earth that plants grow in' },
{ word: 'CAVE', hint: 'A hollow space inside a rock or mountain' },
{ word: 'POND', hint: 'A small body of still water' },
{ word: 'CLOUD', hint: 'A fluffy white shape floating in the sky' },
{ word: 'STONE', hint: 'A small piece of rock' },
{ word: 'FIELD', hint: 'A large flat area of grass or crops' },
{ word: 'RIVER', hint: 'A long moving body of water' },
{ word: 'BEACH', hint: 'A sandy area beside the sea' },
{ word: 'FROST', hint: 'A thin layer of ice that forms on cold surfaces' },
{ word: 'THORN', hint: 'A sharp point on a plant like a rose' },
{ word: 'PETAL', hint: 'The coloured part of a flower' },
{ word: 'MARSH', hint: 'Wet soft muddy ground near water' },
{ word: 'ACORN', hint: 'The small nut that grows on an oak tree' },
{ word: 'TRUNK', hint: 'The thick main stem of a tree' },
{ word: 'BLOOM', hint: 'When a flower opens up and shows its colour' },
{ word: 'CLIFF', hint: 'A steep high wall of rock beside the sea' },
{ word: 'GROVE', hint: 'A small group of trees' },
{ word: 'PLAIN', hint: 'A large flat area of land with few trees' },
{ word: 'SHORE', hint: 'The land at the edge of a sea or lake' },
{ word: 'BROOK', hint: 'A small narrow stream of water' },
{ word: 'DUNES', hint: 'Hills of sand shaped by the wind in a desert' },
{ word: 'FUNGI', hint: 'A group of living things including mushrooms' },
{ word: 'CORAL', hint: 'A colourful underwater structure made by tiny sea creatures' },
  ],
  School: [
    { word: 'PENCIL', hint: 'A writing tool with a graphite tip' },
    { word: 'TEACHER', hint: 'The person who runs the class' },
    { word: 'LIBRARY', hint: 'A place full of books to borrow' },
    { word: 'HOMEWORK', hint: 'Work you do at home for school' },
    { word: 'CLASSROOM', hint: 'The room where you learn' },
    { word: 'TEXTBOOK', hint: 'A book used for studying a subject' },
    { word: 'CALCULATOR', hint: 'A device used to do maths' },
    { word: 'TIMETABLE', hint: 'A schedule showing when classes happen' },
    { word: 'UNIFORM', hint: 'The special clothes worn at school' },
    { word: 'SCISSORS', hint: 'A tool used for cutting paper' },
    { word: 'NOTEBOOK', hint: 'A book for writing notes in' },
    { word: 'DIPLOMA', hint: 'A certificate showing you passed a course' },
    { word: 'SUBJECT', hint: 'A topic you study at school like maths or English' },
    { word: 'CANTEEN', hint: 'The place at school where you eat lunch' },
    { word: 'PRINCIPAL', hint: 'The head teacher of a school' },
    { word: 'DESK', hint: 'A table where you sit and work at school' },
{ word: 'BOOK', hint: 'Something you read with pages inside' },
{ word: 'EXAM', hint: 'A test you take at school' },
{ word: 'BELL', hint: 'It rings to tell you class has started or ended' },
{ word: 'CHART', hint: 'A large picture with information on the classroom wall' },
{ word: 'RULER', hint: 'A flat stick used for measuring or drawing straight lines' },
{ word: 'PAINT', hint: 'Coloured liquid used to make pictures' },
{ word: 'GLUE', hint: 'A sticky substance used to join things together' },
{ word: 'BOARD', hint: 'The large flat surface the teacher writes on' },
{ word: 'CLASS', hint: 'A group of students who learn together' },
{ word: 'LESSON', hint: 'A period of time when you are taught something' },
{ word: 'PENCIL', hint: 'A thin writing tool with graphite inside' },
{ word: 'ERASER', hint: 'A tool used to remove pencil marks' },
{ word: 'FOLDER', hint: 'A cardboard cover used to store papers' },
{ word: 'STAPLE', hint: 'A small metal clip used to join papers together' },
{ word: 'POSTER', hint: 'A large picture or notice displayed on a wall' },
{ word: 'MARKER', hint: 'A thick pen used to write on whiteboards' },
{ word: 'REPORT', hint: 'A written assessment of a students progress' },
{ word: 'GRADES', hint: 'Marks given to show how well you did in school' },
{ word: 'SPORTS', hint: 'Physical activities done at school for exercise' },
{ word: 'STUDY', hint: 'To learn and prepare for lessons or exams' },
{ word: 'WRITE', hint: 'To form letters and words with a pen or pencil' },
{ word: 'LEARN', hint: 'To gain new knowledge or skills' },
{ word: 'SPELL', hint: 'To write the letters of a word in the correct order' },
{ word: 'COUNT', hint: 'To say numbers in order to find a total' },
{ word: 'DRAMA', hint: 'A school subject where you act and perform' },
{ word: 'MUSIC', hint: 'A school subject where you sing and play instruments' },
{ word: 'LUNCH', hint: 'The meal eaten in the middle of the school day' },
{ word: 'AWARD', hint: 'A prize given for doing something well at school' },
{ word: 'PUPIL', hint: 'Another word for a student at school' },
  ],
  Travel: [
    { word: 'PASSPORT', hint: 'The document you need to travel abroad' },
    { word: 'AIRPORT', hint: 'Where planes take off and land' },
    { word: 'LUGGAGE', hint: 'Your bags and suitcases when travelling' },
    { word: 'HOTEL', hint: 'A place to sleep when you are away from home' },
    { word: 'TOURIST', hint: 'A person visiting a place on holiday' },
    { word: 'CURRENCY', hint: 'The money used in a particular country' },
    { word: 'CUSTOMS', hint: 'The checkpoint when entering a new country' },
    { word: 'BOARDING', hint: 'Getting onto a plane or ship' },
    { word: 'SOUVENIR', hint: 'A gift bought to remember a place' },
    { word: 'ITINERARY', hint: 'A planned schedule for a trip' },
    { word: 'HOSTEL', hint: 'A cheap place to stay with shared rooms' },
    { word: 'VISA', hint: 'Permission to enter a foreign country' },
    { word: 'DEPARTURE', hint: 'Leaving a place on a journey' },
    { word: 'ARRIVAL', hint: 'Reaching your destination' },
    { word: 'BACKPACK', hint: 'A bag you carry on your back when travelling' },
    { word: 'TRIP', hint: 'A short journey to somewhere' },
{ word: 'ROAD', hint: 'A path that vehicles travel on' },
{ word: 'SHIP', hint: 'A large boat that travels on the sea' },
{ word: 'CAMP', hint: 'Staying overnight outdoors in a tent' },
{ word: 'TOUR', hint: 'A journey visiting different places' },
{ word: 'GUIDE', hint: 'A person who shows tourists around a place' },
{ word: 'BEACH', hint: 'A sandy area next to the sea' },
{ word: 'HOTEL', hint: 'A building where travellers pay to sleep' },
{ word: 'TRAIN', hint: 'A vehicle that travels on rails' },
{ word: 'PLANE', hint: 'A vehicle that flies through the sky' },
{ word: 'TICKET', hint: 'A piece of paper that lets you travel or enter somewhere' },
{ word: 'BRIDGE', hint: 'A structure built over water so you can cross it' },
{ word: 'JUNGLE', hint: 'A thick tropical forest visited by adventurers' },
{ word: 'ISLAND', hint: 'A piece of land completely surrounded by water' },
{ word: 'CRUISE', hint: 'A holiday taken on a large ship' },
{ word: 'MARKET', hint: 'An outdoor place where people buy and sell goods' },
{ word: 'TEMPLE', hint: 'A religious building visited by tourists in Asia' },
{ word: 'MUSEUM', hint: 'A building where historical objects are displayed' },
{ word: 'SAFARI', hint: 'A trip to see wild animals in their natural habitat' },
{ word: 'CASTLE', hint: 'A large old stone building with towers' },
{ word: 'FERRY', hint: 'A boat that carries passengers across water' },
{ word: 'CABIN', hint: 'A small room on a ship or a simple house in the woods' },
{ word: 'PLAZA', hint: 'An open public square in a town or city' },
{ word: 'RUINS', hint: 'The remains of old buildings visited by tourists' },
{ word: 'PORTS', hint: 'Places where ships load and unload passengers and goods' },
{ word: 'Globe', hint: 'A round model of the Earth showing all countries' },
{ word: 'TAXIS', hint: 'Cars for hire that take passengers to destinations' },
{ word: 'OCEAN', hint: 'A vast area of sea crossed when travelling long distances' },
{ word: 'LODGE', hint: 'A small hotel often found in a forest or national park' },
{ word: 'ATLAS', hint: 'A book of maps used to plan journeys' },
  ],
  Technology: [
    { word: 'KEYBOARD', hint: 'You type on this to use a computer' },
    { word: 'INTERNET', hint: 'A global network connecting computers' },
    { word: 'SOFTWARE', hint: 'Programs that run on a computer' },
    { word: 'BLUETOOTH', hint: 'Wireless technology for connecting devices' },
    { word: 'DOWNLOAD', hint: 'To copy a file from the internet to your device' },
    { word: 'CHARGER', hint: 'A device that refills your battery' },
    { word: 'WEBSITE', hint: 'A page or collection of pages on the internet' },
    { word: 'PASSWORD', hint: 'A secret word used to log in' },
    { word: 'PRINTER', hint: 'A machine that puts digital content on paper' },
    { word: 'MONITOR', hint: 'The screen of a computer' },
    { word: 'WIRELESS', hint: 'Connected without cables' },
    { word: 'SPEAKER', hint: 'A device that produces sound' },
    { word: 'CAMERA', hint: 'A device used to take photos' },
    { word: 'BATTERY', hint: 'Stores electricity to power devices' },
    { word: 'MICROPHONE', hint: 'A device that picks up sound' },
    { word: 'PHONE', hint: 'A device you use to call and message people' },
{ word: 'SCREEN', hint: 'The flat display you look at on a device' },
{ word: 'MOUSE', hint: 'A small device you move to control a computer' },
{ word: 'CABLE', hint: 'A wire used to connect devices' },
{ word: 'ROBOT', hint: 'A machine that can do jobs automatically' },
{ word: 'GAME', hint: 'An activity you play on a screen for fun' },
{ word: 'PHOTO', hint: 'A picture taken with a camera' },
{ word: 'VIDEO', hint: 'A moving picture you can watch on a screen' },
{ word: 'WIFI', hint: 'Wireless connection to the internet' },
{ word: 'TABLET', hint: 'A flat touchscreen device bigger than a phone' },
{ word: 'LAPTOP', hint: 'A portable computer you can carry around' },
{ word: 'BUTTON', hint: 'A small thing you press to make something work' },
{ word: 'SIGNAL', hint: 'Information sent wirelessly between devices' },
{ word: 'UPDATE', hint: 'New software installed to improve a device' },
{ word: 'MEMORY', hint: 'The part of a computer that stores information' },
{ word: 'REMOTE', hint: 'A device used to control a TV from a distance' },
{ word: 'GADGET', hint: 'A small clever electronic device' },
{ word: 'SEARCH', hint: 'Looking for information online' },
{ word: 'UPLOAD', hint: 'Sending a file from your device to the internet' },
{ word: 'CURSOR', hint: 'The small arrow that moves on your computer screen' },
{ word: 'EMOJI', hint: 'A small picture used in messages to show feelings' },
{ word: 'PIXEL', hint: 'The smallest dot that makes up a digital image' },
{ word: 'CLICK', hint: 'Pressing a mouse button to select something' },
{ word: 'SHARE', hint: 'Sending or showing content to others online' },
{ word: 'PATCH', hint: 'A small software update that fixes a bug' },
{ word: 'INBOX', hint: 'The folder where you receive emails' },
{ word: 'LOGIN', hint: 'Entering your username and password to access a device' },
{ word: 'DRAFT', hint: 'A saved but unsent email or document' },
{ word: 'CLOUD', hint: 'Online storage where you save files over the internet' },
{ word: 'SWIPE', hint: 'Moving your finger across a touchscreen' },
  ],
  Countries: [
    { word: 'THAILAND', hint: 'A country in Southeast Asia famous for temples' },
    { word: 'AUSTRALIA', hint: 'A country and continent in the southern hemisphere' },
    { word: 'FRANCE', hint: 'A country famous for the Eiffel Tower' },
    { word: 'BRAZIL', hint: 'The largest country in South America' },
    { word: 'JAPAN', hint: 'An island nation in East Asia famous for sushi' },
    { word: 'CANADA', hint: 'The second largest country in the world' },
    { word: 'GERMANY', hint: 'A European country famous for cars and beer' },
    { word: 'MEXICO', hint: 'A country famous for tacos and pyramids' },
    { word: 'EGYPT', hint: 'A country in North Africa famous for pyramids' },
    { word: 'RUSSIA', hint: 'The largest country in the world' },
    { word: 'ITALY', hint: 'A European country shaped like a boot' },
    { word: 'CHINA', hint: 'The most populous country in the world' },
    { word: 'KENYA', hint: 'An African country famous for safaris' },
    { word: 'GREECE', hint: 'A European country famous for ancient history' },
    { word: 'NORWAY', hint: 'A Scandinavian country famous for fjords' },
    { word: 'SPAIN', hint: 'A sunny European country famous for flamenco dancing' },
{ word: 'INDIA', hint: 'A large Asian country famous for spicy food and the Taj Mahal' },
{ word: 'PERU', hint: 'A South American country with Machu Picchu' },
{ word: 'CUBA', hint: 'A Caribbean island country' },
{ word: 'CHILE', hint: 'A long thin country on the west coast of South America' },
{ word: 'WALES', hint: 'A country in the UK famous for dragons on its flag' },
{ word: 'NEPAL', hint: 'A small country home to Mount Everest' },
{ word: 'GHANA', hint: 'A West African country famous for cocoa and gold' },
{ word: 'LAOS', hint: 'A small landlocked country next to Thailand' },
{ word: 'OMAN', hint: 'A Middle Eastern country on the Arabian Peninsula' },
{ word: 'TURKEY', hint: 'A country between Europe and Asia famous for kebabs' },
{ word: 'SWEDEN', hint: 'A Scandinavian country famous for IKEA and ABBA' },
{ word: 'POLAND', hint: 'A Central European country famous for pierogies' },
{ word: 'ISRAEL', hint: 'A Middle Eastern country on the Mediterranean Sea' },
{ word: 'JORDAN', hint: 'A Middle Eastern country home to Petra' },
{ word: 'TAIWAN', hint: 'An island in East Asia famous for technology' },
{ word: 'KUWAIT', hint: 'A small wealthy country in the Middle East' },
{ word: 'PANAMA', hint: 'A Central American country with a famous canal' },
{ word: 'ANGOLA', hint: 'A large country on the west coast of Africa' },
{ word: 'SERBIA', hint: 'A Balkan country in southeastern Europe' },
{ word: 'NIGER', hint: 'A large landlocked country in West Africa' },
{ word: 'SUDAN', hint: 'A large country in northeast Africa' },
{ word: 'HAITI', hint: 'A Caribbean island country' },
{ word: 'BENIN', hint: 'A small West African country' },
{ word: 'TONGA', hint: 'A small Pacific island nation' },
{ word: 'WALES', hint: 'A country in the UK with a dragon on its flag' },
{ word: 'LIBYA', hint: 'A North African country on the Mediterranean' },
{ word: 'QATAR', hint: 'A small wealthy Middle Eastern country' },
{ word: 'BURMA', hint: 'A Southeast Asian country also known as Myanmar' },
{ word: 'CONGO', hint: 'A large Central African country with a famous river' },
  ],
}

export function scrambleWord(word: string): string {
  const arr = word.split('')
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]]
  }
  const result = arr.join('')
  return result === word ? scrambleWord(word) : result
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}