export type Question = {
  q: string
  options: string[]
  answer: number
}

export const questions: Record<string, Question[]> = {
  'P1-P2': [
    { q: 'Which room do you sleep in?', options: ['kitchen', 'bedroom', 'bathroom', 'garage'], answer: 1 },
    { q: 'Which room do you cook food in?', options: ['bedroom', 'living room', 'kitchen', 'garden'], answer: 2 },
    { q: 'You sit on a _____ to watch TV.', options: ['table', 'door', 'sofa', 'window'], answer: 2 },
    { q: 'You sleep in a _____.', options: ['chair', 'sofa', 'floor', 'bed'], answer: 3 },
    { q: 'You eat dinner at a _____.', options: ['bed', 'table', 'sink', 'cupboard'], answer: 1 },
    { q: 'Which room do you have a bath or shower?', options: ['bedroom', 'kitchen', 'bathroom', 'living room'], answer: 2 },
    { q: 'You keep food cold in a _____.', options: ['oven', 'cupboard', 'fridge', 'microwave'], answer: 2 },
    { q: 'You turn on a _____ when the room is dark.', options: ['tap', 'door', 'light', 'window'], answer: 2 },
    { q: 'You dry yourself with a _____ after a shower.', options: ['pillow', 'towel', 'blanket', 'curtain'], answer: 1 },
    { q: 'Which of these is a room in a house?', options: ['car', 'park', 'kitchen', 'school'], answer: 2 },
    { q: 'You look at yourself in a _____.', options: ['mirror', 'window', 'door', 'clock'], answer: 0 },
    { q: 'You sit at a _____ to do your homework.', options: ['sofa', 'bed', 'desk', 'fridge'], answer: 2 },
    { q: 'You open a _____ to go into a room.', options: ['window', 'door', 'drawer', 'curtain'], answer: 1 },
    { q: 'You put rubbish in a _____.', options: ['box', 'bag', 'bin', 'bowl'], answer: 2 },
    { q: 'Which of these is NOT a room in a house?', options: ['bedroom', 'kitchen', 'classroom', 'bathroom'], answer: 2 },
    { q: 'You hang your clothes in a _____.', options: ['drawer', 'bookcase', 'wardrobe', 'table'], answer: 2 },
    { q: 'Where do cars park at home?', options: ['kitchen', 'garage', 'bedroom', 'garden'], answer: 1 },
    { q: 'What do you use to sweep the floor?', options: ['towel', 'pillow', 'broom', 'fork'], answer: 2 },
    { q: 'Where do you wash your hands?', options: ['in the oven', 'in the sink', 'in the drawer', 'in the wardrobe'], answer: 1 },
    { q: 'What gives water in the bathroom?', options: ['light', 'mirror', 'tap', 'plug'], answer: 2 },
  ],

  'P3-P4': [
    { q: 'What is another word for "sofa"?', options: ['chair', 'couch', 'bench', 'stool'], answer: 1 },
    { q: 'What do you use to quickly heat food?', options: ['fridge', 'freezer', 'microwave', 'fan'], answer: 2 },
    { q: 'Where do you keep folded clothes?', options: ['in a bookcase', 'in a drawer', 'in the sink', 'on a shelf'], answer: 1 },
    { q: 'The area outside a house with grass is called the _____.', options: ['roof', 'attic', 'garden', 'basement'], answer: 2 },
    { q: 'Where is a washing machine usually found?', options: ['bedroom', 'kitchen or utility room', 'attic', 'garage roof'], answer: 1 },
    { q: 'What is the room above a house, under the roof called?', options: ['basement', 'cellar', 'attic', 'utility room'], answer: 2 },
    { q: 'Where do you keep books at home?', options: ['in the wardrobe', 'in the fridge', 'on a bookshelf', 'under the bed'], answer: 2 },
    { q: 'What do you call material that covers the floor like a thick mat?', options: ['curtain', 'carpet', 'ceiling', 'cushion'], answer: 1 },
    { q: 'Where is a car kept at home?', options: ['utility room', 'kitchen', 'garage', 'attic'], answer: 2 },
    { q: 'What do you use to cover a window instead of curtains?', options: ['blinds', 'doors', 'tiles', 'bricks'], answer: 0 },
    { q: 'What do you call the room below ground level?', options: ['attic', 'loft', 'basement', 'patio'], answer: 2 },
    { q: 'What do you call the wall-to-wall floor covering in a bedroom?', options: ['tiles', 'wood', 'carpet', 'concrete'], answer: 2 },
    { q: 'What machine washes your plates and cups automatically?', options: ['washing machine', 'dishwasher', 'dryer', 'blender'], answer: 1 },
    { q: 'What do you call the hard floor covering often used in kitchens?', options: ['carpet', 'tiles', 'grass', 'wood chips'], answer: 1 },
    { q: 'What is the outdoor hard-surface area behind a house called?', options: ['attic', 'cellar', 'patio', 'loft'], answer: 2 },
    { q: 'What piece of furniture do you put a TV on?', options: ['wardrobe', 'TV stand / cabinet', 'bookcase', 'dining table'], answer: 1 },
    { q: 'What is another word for "wardrobe"?', options: ['cupboard', 'closet', 'cabinet', 'both B and C'], answer: 3 },
    { q: 'What do you call a clock that wakes you up in the morning?', options: ['wall clock', 'alarm clock', 'timer', 'bell'], answer: 1 },
    { q: 'What do you call a small shelf on the wall?', options: ['ledge', 'wall shelf', 'bracket shelf', 'all of these'], answer: 3 },
    { q: 'What connects two floors of a house?', options: ['corridor', 'hallway', 'staircase', 'doorway'], answer: 2 },
  ],

  'P5-P6': [
    { q: 'What is the room where you eat formal meals called?', options: ['living room', 'dining room', 'study', 'utility room'], answer: 1 },
    { q: 'A small room used for reading and working is called a _____.', options: ['utility room', 'pantry', 'study', 'conservatory'], answer: 2 },
    { q: 'What is a "pantry" used for?', options: ['washing clothes', 'storing food and kitchen items', 'parking cars', 'sleeping guests'], answer: 1 },
    { q: 'What do you call the passage that connects rooms?', options: ['staircase', 'corridor / hallway', 'porch', 'annex'], answer: 1 },
    { q: 'What is a "conservatory"?', options: ['a dark underground room', 'a glass-roofed room attached to a house', 'a room for cars', 'a storage area under the roof'], answer: 1 },
    { q: 'What is a "porch"?', options: ['a covered entrance area outside the front door', 'a room for washing clothes', 'a room under the stairs', 'the roof of the house'], answer: 0 },
    { q: 'What controls how warm or cool a house is?', options: ['boiler', 'thermostat', 'fuse box', 'meter'], answer: 1 },
    { q: 'What do you call the area outside where you drive a car to the house?', options: ['pathway', 'driveway', 'pavement', 'lane'], answer: 1 },
    { q: 'The _____ is used to remove dust from carpets.', options: ['mop', 'broom', 'vacuum cleaner', 'duster'], answer: 2 },
    { q: 'What is a "utility room" mainly used for?', options: ['watching TV', 'laundry and storage', 'sleeping', 'cooking meals'], answer: 1 },
    { q: '"The ceiling is leaking" — where is the ceiling?', options: ['under your feet', 'above your head', 'on the wall', 'outside the house'], answer: 1 },
    { q: 'What is a "veranda"?', options: ['a type of floor tile', 'a covered outdoor platform attached to a house', 'a room under the stairs', 'a large wardrobe'], answer: 1 },
    { q: 'What is a "skirting board"?', options: ['a board on the ceiling', 'a board between the wall and floor', 'a shelf on the wall', 'a type of carpet'], answer: 1 },
    { q: 'A room that is "en suite" means it has a _____ attached.', options: ['private bathroom', 'balcony', 'walk-in wardrobe', 'study area'], answer: 0 },
    { q: 'What is a "bay window"?', options: ['a small window near the floor', 'a window that curves or sticks out from the wall', 'a window in the ceiling', 'a window above the door'], answer: 1 },
    { q: 'What is the "mantelpiece"?', options: ['the shelf above a fireplace', 'the glass in a window', 'the door handle', 'the carpet near the front door'], answer: 0 },
    { q: 'A "semi-detached" house is _____.', options: ['a house with a garden on three sides', 'a house joined to one other house', 'a house with two floors', 'a very old house'], answer: 1 },
    { q: 'What does "double glazing" mean?', options: ['two coats of paint on walls', 'windows with two layers of glass', 'two bathrooms in a house', 'two doors at the entrance'], answer: 1 },
    { q: 'What is "insulation" in a house?', options: ['decoration on the walls', 'material that helps keep heat inside', 'the pipes that carry water', 'the electrical wiring'], answer: 1 },
    { q: 'What is an "annex"?', options: ['a large garden', 'an additional building attached to the main house', 'a type of fence', 'a basement room'], answer: 1 },
  ],

  'M1-M3': [
    { q: 'A house described as "open plan" usually means the _____.', options: ['front door is always open', 'kitchen and living area share the same space', 'all rooms have no doors', 'the windows are very large'], answer: 1 },
    { q: 'What does "furnished" mean when an apartment is advertised?', options: ['it has been recently painted', 'it includes furniture for you to use', 'it has a large garden', 'the rent is included in the price'], answer: 1 },
    { q: 'A "studio apartment" is _____.', options: ['an apartment for artists only', 'a one-room apartment combining bedroom, kitchen and living area', 'a very large luxury flat', 'an apartment near a school'], answer: 1 },
    { q: 'What does "detached house" mean?', options: ['a house that needs repair', 'a house that stands alone and is not joined to another', 'a house with a detached garage', 'an old farmhouse'], answer: 1 },
    { q: '"The property is freehold" means the owner _____.', options: ['pays rent to live there', 'owns the building and the land it sits on', 'can only stay for a fixed period', 'must maintain the garden for free'], answer: 1 },
    { q: 'What does it mean if a house is "leasehold"?', options: ['you own the building but not the land', 'you own everything including the land', 'the house is for sale immediately', 'the house has a long lease on the garage'], answer: 0 },
    { q: 'What is a "mortgage"?', options: ['a type of house insurance', 'a loan used to buy a house, paid back over many years', 'a monthly service charge for a flat', 'a fee paid to an estate agent'], answer: 1 },
    { q: 'What does "renovate" mean in relation to a house?', options: ['to sell a house quickly', 'to knock a house down', 'to repair and improve a building', 'to rent a property out'], answer: 2 },
    { q: 'What is a "downpipe"?', options: ['a pipe under the kitchen sink', 'a pipe that carries rainwater down from the roof', 'the main water pipe into a house', 'a gas pipe in the kitchen'], answer: 1 },
    { q: '"The flat is on the ground floor" — what does this mean?', options: ['it is underground', 'it is the lowest floor at street level', 'it is the top floor', 'it is on the first floor above street level'], answer: 1 },
    { q: 'What does "to let" mean on a property sign?', options: ['the property is for sale', 'the property is available to rent', 'the property has just been sold', 'the property is under construction'], answer: 1 },
    { q: 'What is a "cornice" in a house?', options: ['a type of roof tile', 'a decorative border where the wall meets the ceiling', 'a style of window frame', 'a wooden floor panel'], answer: 1 },
    { q: 'What does "damp" mean when describing a house problem?', options: ['the house is too hot', 'there is unwanted moisture or wetness in the walls', 'the windows are foggy', 'the heating does not work'], answer: 1 },
    { q: '"The property has a south-facing garden" means the garden _____.', options: ['is very large', 'faces the south and gets more sunlight', 'has a fence on the south side', 'backs onto a road'], answer: 1 },
    { q: 'What is a "surveyor" in the context of buying a house?', options: ['a person who cleans the property', 'a person who officially checks the condition of a building', 'a lawyer who handles the sale', 'a person who decorates the property'], answer: 1 },
    { q: 'What does "subsidence" mean for a house?', options: ['the house is being extended', 'the ground under the house is sinking', 'the roof needs replacing', 'the property is being subdivided'], answer: 1 },
    { q: 'A "terraced house" is one that _____.', options: ['has a large terrace garden', 'is joined to houses on both sides in a row', 'is built on a hill', 'has a basement flat'], answer: 1 },
    { q: 'What does "planning permission" relate to?', options: ['permission from the bank to buy a house', 'official permission to build or change a property', 'a plan showing the rooms in a house', 'a contract between a landlord and tenant'], answer: 1 },
    { q: 'What does it mean if a house has "negative equity"?', options: ['the house has no electricity', 'the house is worth less than the outstanding mortgage', 'the house cannot be sold', 'the owner owes money on renovations'], answer: 1 },
    { q: 'A "conveyancer" helps with _____.', options: ['building work on a house', 'the legal transfer of property ownership', 'organising house removals', 'valuing a property for sale'], answer: 1 },
  ],
}
