'use client'
import { useState, useRef, useEffect } from 'react'
import Link from 'next/link'

const SPEEDS = [
  { label: '🐢 Very Slow', value: 0.55 },
  { label: '🚶 Slow', value: 0.72 },
  { label: '🏃 Normal', value: 0.9 },
  { label: '⚡ Fast', value: 1.1 },
]

const LANGUAGES = [
  { value: 'none', label: '🌍 English only' },
  { value: 'Thai', label: '🇹🇭 Thai' },
  { value: 'Japanese', label: '🇯🇵 Japanese' },
  { value: 'Korean', label: '🇰🇷 Korean' },
  { value: 'Chinese', label: '🇨🇳 Chinese' },
  { value: 'Arabic', label: '🇸🇦 Arabic' },
  { value: 'Spanish', label: '🇪🇸 Spanish' },
  { value: 'French', label: '🇫🇷 French' },
  { value: 'German', label: '🇩🇪 German' },
  { value: 'Portuguese', label: '🇧🇷 Portuguese' },
  { value: 'Russian', label: '🇷🇺 Russian' },
  { value: 'Vietnamese', label: '🇻🇳 Vietnamese' },
  { value: 'Indonesian', label: '🇮🇩 Indonesian' },
]

const PARTS = [
  {
    number: 1, title: 'Why Complaints Are Valuable', emoji: '💎', color: '#ca8a04',
    text: `Most businesses fear customer complaints. They see them as problems to be dealt with, conversations to be ended as quickly as possible, and evidence that something has gone wrong. This instinct is understandable — nobody enjoys being told they have failed. But research consistently shows that businesses which handle complaints well outperform those that avoid them.\n\nThe reason is simple: a customer who complains is a customer who still cares. They have taken the time and effort to tell you what went wrong, which means they believe the relationship is worth saving. The far more dangerous customers are the ones who say nothing — they simply leave and never come back. Studies suggest that for every customer who complains, there are 26 who had the same problem but did not bother to say anything. They just quietly took their business elsewhere.\n\nHandled well, a complaint can actually strengthen a customer\'s loyalty. This phenomenon is known as the "service recovery paradox" — research has shown that customers whose complaints are resolved quickly and effectively often become more loyal than customers who never had a problem in the first place. The experience of being listened to, taken seriously, and having the problem fixed creates a positive emotional impression that lasts.\n\nFor professionals working in English, handling complaints effectively requires a specific set of language skills. The words and phrases you choose in a complaint situation can be the difference between a customer who leaves satisfied and one who leaves angry. Getting the language right is not just a matter of politeness — it is a business skill with direct impact on revenue and reputation.`,
    vocab: [
      { word: 'Instinct', definition: 'A natural feeling or reaction that happens without thinking.' },
      { word: 'Service recovery paradox', definition: 'The finding that customers who have a problem solved well often become more loyal than those who never had a problem.' },
      { word: 'Revenue', definition: 'The total income or money earned by a business.' },
      { word: 'Reputation', definition: 'The general opinion that people have about a person or business based on past behaviour.' },
    ],
    questions: [
      { n: 1, q: 'Do you agree that a customer who complains is more valuable than one who says nothing? Why?' },
      { n: 2, q: 'Have you ever had a bad experience with a company that was resolved so well that you became more loyal? What happened?' },
      { n: 3, q: 'The passage says for every complaint, 26 others had the same problem but said nothing. Why do you think most people do not complain?' },
    ]
  },
  {
    number: 2, title: 'The Language of Empathy', emoji: '💬', color: '#a16207',
    text: `The single most important skill in handling customer complaints is empathy — the ability to understand and share the feelings of another person. When a customer is upset, they want to feel heard before they want a solution. Many complaint-handling failures happen not because the company could not fix the problem, but because the customer did not feel that anyone cared.\n\nThe language of empathy in professional English follows specific patterns. The first step is acknowledgement — letting the customer know you have heard them and understand their frustration. Phrases like "I completely understand your frustration," "I can see why this would be upsetting," and "You\'re absolutely right to raise this" validate the customer\'s feelings without admitting fault.\n\nThe second step is taking ownership. Even if the problem was not your personal fault, taking responsibility on behalf of the company builds trust. "I\'m going to take personal responsibility for resolving this" is far more powerful than "I\'ll pass this on to the relevant department." The first creates confidence; the second creates doubt.\n\nThe third step is avoiding defensive language. When a customer says "Your product broke after two days," the natural human instinct is to defend — "Well, it depends how you used it." But defensive responses escalate complaints rather than resolving them. A better response is: "I\'m sorry to hear that. That\'s certainly not the experience we want you to have. Let me look into this for you right now."\n\nNotice the structure of effective complaint responses: acknowledge the feeling, take ownership, and move immediately to action. This pattern — empathy, ownership, action — works in almost every complaint situation, from a delayed delivery to a serious product failure.`,
    vocab: [
      { word: 'Empathy', definition: 'The ability to understand and share the feelings of another person.' },
      { word: 'Validate', definition: 'To acknowledge that someone\'s feelings or concerns are reasonable and understandable.' },
      { word: 'Escalate', definition: 'To make a situation worse or more intense rather than calming it down.' },
      { word: 'Defensive', definition: 'Reacting to criticism by protecting yourself or making excuses rather than listening.' },
    ],
    questions: [
      { n: 4, q: 'The passage says customers want to feel heard before they want a solution. Do you agree? Can you think of a time this was true for you?' },
      { n: 5, q: 'What is the difference between "I\'ll pass this on to the relevant department" and "I\'m going to take personal responsibility"? Which would you prefer to hear?' },
      { n: 6, q: 'Why is it so difficult not to be defensive when someone criticises your work or your company? How can you train yourself to respond differently?' },
    ]
  },
  {
    number: 3, title: 'Difficult Situations', emoji: '⚡', color: '#854d0e',
    text: `Not all complaints are straightforward. Some customers are genuinely angry. Some are unreasonable. Some want compensation that goes beyond what is fair. And some complaints are made in public — on social media, in review sites, or in front of other customers. Each of these situations requires a slightly different approach, but the underlying principles remain the same.\n\nWhen dealing with an angry customer, the most important thing is to remain calm. Anger is contagious — if you respond with tension, the situation will escalate. Speak slowly, keep your voice level, and use the customer\'s name if you know it. "I understand this is frustrating, Mr Chen. Let me see what I can do for you right now." The use of the name personalises the interaction and reminds both parties that this is a conversation between human beings, not a battle.\n\nWhen a customer\'s demands are unreasonable, you need to set boundaries without being confrontational. "I understand what you\'re asking for, and I wish I could do that. What I can offer you is..." This structure — acknowledge, express goodwill, offer an alternative — allows you to say no without saying no.\n\nPublic complaints on social media require special care. Never argue with a customer in public. Acknowledge the issue publicly — "We\'re sorry to hear about your experience. We take this seriously" — and then move the conversation to a private channel. "Could you send us a direct message with your details so we can resolve this for you?" This shows other readers that you respond professionally while avoiding a public argument that can damage your reputation far more than the original complaint.\n\nIn all these situations, the goal is the same: to turn a negative experience into a positive one. You will not succeed every time. But a professional, empathetic response — even to an unreasonable complaint — protects your reputation and shows other customers that you care.`,
    vocab: [
      { word: 'Contagious', definition: 'Spreading easily from one person to another — usually about emotions or behaviour.' },
      { word: 'Confrontational', definition: 'Aggressive or hostile — likely to cause an argument rather than resolve one.' },
      { word: 'Goodwill', definition: 'Friendly and helpful feelings towards someone — a genuine desire to help.' },
      { word: 'Private channel', definition: 'A one-to-one communication method such as email or direct message, not visible to the public.' },
    ],
    questions: [
      { n: 7, q: 'The passage says anger is contagious. Have you ever been in a situation where one person\'s anger made you angry too? How did you handle it?' },
      { n: 8, q: 'How would you respond to a customer who demands a full refund for a product they have used for six months? What would you say?' },
      { n: 9, q: 'Why is it important to move social media complaints to a private channel? What could go wrong if you try to resolve the issue publicly?' },
    ]
  },
  {
    number: 4, title: 'Building a Complaints Culture', emoji: '🏢', color: '#713f12',
    text: `The way an organisation handles complaints says more about its values than any mission statement or marketing campaign. Companies that handle complaints well tend to share certain characteristics — and these characteristics can be developed deliberately.\n\nThe first is psychological safety — an environment where employees feel safe admitting mistakes and reporting problems without fear of punishment. If frontline staff are afraid to escalate complaints because they will be blamed, problems are hidden rather than solved. The best organisations treat mistakes as opportunities to learn, not as reasons to punish.\n\nThe second is empowerment. The most frustrating complaint experiences happen when the person you are speaking to does not have the authority to solve your problem. "I\'ll need to check with my manager" is one of the most demoralising phrases a customer can hear. Companies that empower their frontline staff to make decisions — within clear guidelines — resolve complaints faster and with higher customer satisfaction.\n\nThe third is a system for learning from complaints. Every complaint contains information about something that went wrong. If that information is collected, analysed, and acted on, the same problem is less likely to happen again. The best companies do not just resolve individual complaints — they use complaint data to improve their products, services, and processes.\n\nFinally, the most effective organisations measure customer satisfaction after a complaint has been resolved. They follow up to ask: "Was your problem resolved? How was your experience?" This closes the loop, shows the customer that the company genuinely cares, and provides valuable data about how well the complaints process is working.\n\nHandling complaints well is not a cost — it is an investment. Every complaint resolved effectively is a customer retained, a lesson learned, and a reputation strengthened. The language you use in those moments matters enormously — and like any professional skill, it improves with knowledge, practice, and genuine care.`,
    vocab: [
      { word: 'Psychological safety', definition: 'An environment where people feel safe to speak up, take risks, and admit mistakes without fear.' },
      { word: 'Empowerment', definition: 'Giving people the authority and confidence to make decisions and take action.' },
      { word: 'Frontline staff', definition: 'Employees who deal directly with customers — the first people a customer speaks to.' },
      { word: 'Closes the loop', definition: 'Completes a process by following up to check that everything was resolved properly.' },
    ],
    questions: [
      { n: 10, q: 'The passage says "psychological safety" is important — employees should not fear being punished for mistakes. Do most workplaces you know actually work this way?' },
      { n: 11, q: 'Would you rather speak to someone who can solve your problem immediately, or someone who is very polite but has no authority? Why?' },
      { n: 12, q: 'If you were setting up a new company, what would be the most important thing you would do to create a good complaints culture?' },
    ]
  },
]

async function fetchTranslation(text: string, lang: string, type: 'word' | 'question' | 'message'): Promise<string> {
  const systems: Record<string, string> = {
    word: `You are a language learning assistant. Translate this English vocabulary entry to ${lang}. Return ONLY the translated word and a brief explanation in ${lang} (max 25 words). No extra text, no English.`,
    question: `You are a translator. Translate this English discussion question to ${lang}. Return ONLY the translated question. No extra text.`,
    message: `You are a translator. Translate this English text to ${lang}. Return ONLY the translation. No extra text.`,
  }
  const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: systems[type], messages: [{ role: 'user', content: text }] }) })
  const data = await res.json()
  return data.content || ''
}

function TranslateBtn({ text, type, lang, color, onTranslated }: { text: string; type: 'word' | 'question' | 'message'; lang: string; color: string; onTranslated: (t: string) => void }) {
  const [loading, setLoading] = useState(false)
  const [done, setDone] = useState(false)
  const handleClick = async () => { if (lang === 'none' || loading || done) return; setLoading(true); const result = await fetchTranslation(text, lang, type); onTranslated(result); setDone(true); setLoading(false) }
  const isDisabled = lang === 'none'
  return <button onClick={handleClick} disabled={isDisabled || loading || done} title={isDisabled ? 'Select a language above to translate' : done ? 'Translated' : `Translate to ${lang}`} style={{ background: isDisabled ? '#f3f4f6' : done ? '#f0fdf4' : color + '15', color: isDisabled ? '#d1d5db' : done ? '#16a34a' : color, border: `1px solid ${isDisabled ? '#e5e7eb' : done ? '#86efac' : color + '40'}`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: isDisabled ? 'not-allowed' : done ? 'default' : 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s' }}>{loading ? '...' : done ? '✓ 🌍' : '🌍'}</button>
}

function ListenBtn({ text, speed, color }: { text: string; speed: number; color: string }) {
  const [loading, setLoading] = useState(false); const [playing, setPlaying] = useState(false); const sourceRef = useRef<AudioBufferSourceNode | null>(null)
  const handleClick = async () => { if (playing && sourceRef.current) { try { sourceRef.current.stop() } catch {} sourceRef.current = null; setPlaying(false); return }; setLoading(true); try { const res = await fetch('/api/tts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); if (!res.ok) { setLoading(false); return }; const ab = await res.arrayBuffer(); const ac = new AudioContext(); const buf = await ac.decodeAudioData(ab); const src = ac.createBufferSource(); src.buffer = buf; src.playbackRate.value = speed; src.connect(ac.destination); src.onended = () => { setPlaying(false); sourceRef.current = null }; sourceRef.current = src; setLoading(false); setPlaying(true); src.start(0) } catch { setLoading(false); setPlaying(false) } }
  return <button onClick={handleClick} style={{ background: playing ? color : color + '15', color: playing ? 'white' : color, border: `1px solid ${color}40`, padding: '2px 10px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s', display: 'flex', alignItems: 'center', gap: '4px' }}>{loading ? '...' : playing ? '⏹ Stop' : '🔊 Listen'}</button>
}

type Message = { role: 'user' | 'assistant'; content: string; translation?: string }

function ConversationBox({ question, color, translationLang, speed }: { question: string; color: string; translationLang: string; speed: number }) {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [listening, setListening] = useState(false); const [interimText, setInterimText] = useState(''); const [open, setOpen] = useState(false); const recognitionRef = useRef<any>(null); const transcriptRef = useRef('')
  const SYSTEM = `You are a friendly and enthusiastic English conversation partner helping a B1 level student aged 10-12 practise English discussion skills. The reading topic is "Handling Customer Complaints — Turning Problems into Opportunities". The current discussion question is: "${question}". Keep every response to 2-3 sentences maximum. Use simple, clear, exciting language for a young learner. Be enthusiastic and curious about dreams! Always end with one fun follow-up question to keep the conversation going. If the student makes a significant grammar error, gently correct it using "💡 Quick tip: ..." at the very end.`
  const sendMessage = async (text: string) => { if (!text.trim() || loading) return; const userMsg: Message = { role: 'user', content: text.trim() }; const updated = [...messages, userMsg]; setMessages(updated); setInput(''); setLoading(true); try { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: SYSTEM, messages: updated.map(m => ({ role: m.role, content: m.content })) }) }); const data = await res.json(); setMessages(prev => [...prev, { role: 'assistant', content: data.content || 'Sorry, try again.' }]) } catch { setMessages(prev => [...prev, { role: 'assistant', content: 'Connection error — please try again.' }]) }; setLoading(false) }
  const setMessageTranslation = (idx: number, translation: string) => { setMessages(prev => prev.map((m, i) => i === idx ? { ...m, translation } : m)) }
  const startVoice = () => { const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!SR) { alert('Voice input requires Chrome browser.'); return }; transcriptRef.current = ''; const r = new SR(); r.lang = 'en-US'; r.continuous = true; r.interimResults = true; r.onstart = () => { setListening(true); setInterimText('') }; r.onresult = (e: any) => { let f = ''; let int = ''; for (let i = 0; i < e.results.length; i++) { if (e.results[i].isFinal) { f += e.results[i][0].transcript + ' ' } else { int += e.results[i][0].transcript } }; transcriptRef.current = f; setInterimText(f + int) }; r.onerror = () => { setListening(false); setInterimText('') }; r.onend = () => { setListening(false); const text = transcriptRef.current.trim() || interimText.trim(); if (text) { setInterimText(''); transcriptRef.current = ''; sendMessage(text) } else { setInterimText(''); transcriptRef.current = '' } }; recognitionRef.current = r; r.start() }
  const stopVoice = () => { recognitionRef.current?.stop() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  if (!open) return <button onClick={() => setOpen(true)} style={{ marginTop: '10px', width: '100%', background: color + '12', border: `2px dashed ${color}40`, borderRadius: '12px', padding: '10px', color, fontWeight: '700', fontSize: '13px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>🤖 Practice answering with AI</button>
  return (
    <div style={{ marginTop: '10px', background: '#fefce8', borderRadius: '14px', border: `2px solid ${color}30`, overflow: 'hidden' }}>
      <div style={{ background: color, padding: '10px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span style={{ color: 'white', fontWeight: '700', fontSize: '13px' }}>🤖 AI Conversation Partner</span><div style={{ display: 'flex', gap: '6px' }}><button onClick={() => setMessages([])} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>🔄 Reset</button><button onClick={() => setOpen(false)} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>✕ Close</button></div></div>
      {messages.length === 0 && <div style={{ padding: '14px 16px', color: '#6b7280', fontSize: '13px', lineHeight: '1.6', borderBottom: '1px solid #fef08a' }}>💡 Type your answer or tap <strong>🎤 Start Recording</strong> — speak your full answer, then tap <strong>⏹ Stop & Send</strong>.</div>}
      {messages.length > 0 && <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px', maxHeight: '320px', overflowY: 'auto' }}>{messages.map((m, i) => (<div key={i} style={{ display: 'flex', gap: '8px', alignItems: 'flex-start', flexDirection: m.role === 'user' ? 'row-reverse' : 'row' }}><div style={{ fontSize: '20px', flexShrink: 0 }}>{m.role === 'user' ? '🧑‍🎓' : '🤖'}</div><div style={{ maxWidth: '80%', display: 'flex', flexDirection: 'column', gap: '4px', alignItems: m.role === 'user' ? 'flex-end' : 'flex-start' }}><div style={{ background: m.role === 'user' ? color : 'white', color: m.role === 'user' ? 'white' : '#374151', padding: '10px 14px', borderRadius: m.role === 'user' ? '16px 4px 16px 16px' : '4px 16px 16px 16px', fontSize: '14px', lineHeight: '1.6', boxShadow: '0 1px 4px rgba(0,0,0,0.08)', border: m.role === 'assistant' ? '1px solid #e5e7eb' : 'none' }}>{m.content}</div>{m.role === 'assistant' && <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}><ListenBtn text={m.content} speed={speed} color={color} />{!m.translation && <TranslateBtn text={m.content} type="message" lang={translationLang} color={color} onTranslated={(t) => setMessageTranslation(i, t)} />}</div>}{m.translation && <div style={{ background: '#fefce8', border: '1px solid #fef08a', borderRadius: '10px', padding: '8px 12px', fontSize: '13px', color: '#374151', lineHeight: '1.5' }}><span style={{ color: color, fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>🌍 Translation</span>{m.translation}</div>}</div></div>))}{loading && <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}><span style={{ fontSize: '20px' }}>🤖</span><div style={{ background: 'white', padding: '10px 14px', borderRadius: '4px 16px 16px 16px', fontSize: '14px', color: '#9ca3af', border: '1px solid #e5e7eb' }}>Thinking...</div></div>}</div>}
      <div style={{ padding: '12px 16px', borderTop: '1px solid #fef08a', display: 'flex', gap: '8px', alignItems: 'flex-end' }}><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(input) } }} placeholder="Type your answer here..." rows={2} style={{ flex: 1, padding: '10px 12px', borderRadius: '10px', border: '2px solid #e5e7eb', fontSize: '14px', outline: 'none', resize: 'none', fontFamily: 'inherit', lineHeight: '1.5' }} /><div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}><button onClick={listening ? stopVoice : startVoice} style={{ background: listening ? '#ef4444' : '#22c55e', color: 'white', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: listening ? '0 0 0 4px rgba(239,68,68,0.3)' : 'none', transition: 'all 0.2s' }}>{listening ? '⏹' : '🎤'}</button><button onClick={() => sendMessage(input)} disabled={!input.trim() || loading} style={{ background: input.trim() && !loading ? color : '#e5e7eb', color: input.trim() && !loading ? 'white' : '#9ca3af', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: input.trim() && !loading ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>➤</button></div></div>
      {!listening && <div style={{ padding: '4px 16px 10px', display: 'flex', gap: '16px' }}><span style={{ color: '#9ca3af', fontSize: '11px' }}>🎤 = Start recording</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>⏹ = Stop & send</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>➤ = Send typed</span></div>}
      {listening && <div style={{ padding: '10px 16px 14px', borderTop: '1px solid #fee2e2', background: '#fef2f2' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ display: 'inline-block', width: '10px', height: '10px', borderRadius: '50%', background: '#ef4444', animation: 'pulse 1s infinite', flexShrink: 0 }} /><span style={{ color: '#ef4444', fontSize: '12px', fontWeight: '700' }}>Recording... speak your full answer</span></div><button onClick={stopVoice} style={{ background: '#ef4444', color: 'white', border: 'none', padding: '6px 16px', borderRadius: '10px', fontWeight: '800', fontSize: '13px', cursor: 'pointer', boxShadow: '0 2px 8px rgba(239,68,68,0.4)' }}>⏹ Stop & Send</button></div><div style={{ background: 'white', borderRadius: '10px', padding: '10px 14px', fontSize: '14px', color: interimText ? '#374151' : '#9ca3af', lineHeight: '1.6', border: '1px solid #fca5a5', fontStyle: 'italic', minHeight: '40px' }}>{interimText || 'Waiting for speech...'}{interimText && <span style={{ display: 'inline-block', width: '2px', height: '16px', background: '#ef4444', marginLeft: '2px', verticalAlign: 'middle', animation: 'pulse 1s infinite' }} />}</div></div>}
    </div>
  )
}

export default function CustomerComplaintsPage() {
  const [speed, setSpeed] = useState(0.9); const [translationLang, setTranslationLang] = useState('none'); const [selectedText, setSelectedText] = useState<string | null>(null); const [lookupDef, setLookupDef] = useState(''); const [lookupTranslation, setLookupTranslation] = useState(''); const [lookupLoading, setLookupLoading] = useState(false); const [vocabTranslations, setVocabTranslations] = useState<Record<string, string>>({}); const [questionTranslations, setQuestionTranslations] = useState<Record<number, string>>({})
  useEffect(() => { const handleSelection = () => { const sel = window.getSelection(); if (!sel) return; const text = sel.toString().trim().replace(/\s+/g, ' '); if (!text || text.split(' ').length > 6) return; const anchor = sel.anchorNode?.parentElement; if (!anchor?.closest('[data-passage]')) return; handleLookup(text) }; document.addEventListener('mouseup', handleSelection); document.addEventListener('touchend', handleSelection); return () => { document.removeEventListener('mouseup', handleSelection); document.removeEventListener('touchend', handleSelection) } }, [translationLang])
  const handleLookup = async (text: string) => { if (!text || text.length < 2) return; setSelectedText(text); setLookupDef(''); setLookupTranslation(''); setLookupLoading(true); speakWord(text); const isPhrase = text.includes(' '); try { if (translationLang === 'none') { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: isPhrase ? `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 20 words) explaining what the phrase means. No extra text.` : `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 15 words) defining this word. No extra text.`, messages: [{ role: 'user', content: isPhrase ? `What does "${text}" mean?` : `Define: "${text}"` }] }) }); const data = await res.json(); setLookupDef(data.content || 'No definition found.') } else { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: `You are a language learning assistant for young B1 English students. Respond ONLY with valid JSON (no markdown, no backticks): {"definition": "one simple English sentence max 15 words", "translation": "the word/phrase in ${translationLang} with a brief explanation in ${translationLang}, max 25 words"}`, messages: [{ role: 'user', content: `Word or phrase: "${text}"` }] }) }); const data = await res.json(); try { const parsed = JSON.parse(data.content); setLookupDef(parsed.definition || 'No definition found.'); setLookupTranslation(parsed.translation || '') } catch { setLookupDef(data.content || 'No definition found.'); setLookupTranslation('') } } } catch { setLookupDef('Could not load definition.') }; setLookupLoading(false) }
  function speakText(text: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const sentences = text.match(/[^.!?]+[.!?]+/g) || [text]; sentences.forEach(s => { const u = new SpeechSynthesisUtterance(s.trim()); u.lang = 'en-GB'; u.rate = speed; u.pitch = 1; window.speechSynthesis.speak(u) }) }
  function speakWord(word: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(word); u.lang = 'en-GB'; u.rate = 0.85; u.pitch = 1; window.speechSynthesis.speak(u) }
  function stopAudio() { if (typeof window === 'undefined') return; window.speechSynthesis.cancel() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  return (
    <main style={{ background: '#f4f6fa', minHeight: '100vh' }}>
      <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}} @keyframes slideUp{from{transform:translateY(100%);opacity:0}to{transform:translateY(0);opacity:1}}`}</style>
      <section style={{ background: 'linear-gradient(135deg, #1c1200 0%, #713f12 50%, #854d0e 100%)', padding: '56px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <Link href="/esl-resources/reading-comprehension/b1" style={{ color: 'rgba(255,255,255,0.6)', textDecoration: 'none', fontSize: '14px', display: 'inline-block', marginBottom: '20px' }}>← B1 Reading Comprehension</Link>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', flexWrap: 'wrap' }}>
            <div style={{ fontSize: '72px', flexShrink: 0 }}>🤝</div>
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '12px' }}>
                <span style={{ background: '#ca8a04', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>B1 Intermediate</span>
                <span style={{ background: 'rgba(99,102,241,0.5)', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>Business English</span>
                <span style={{ background: 'rgba(255,255,255,0.15)', color: 'white', fontSize: '12px', fontWeight: '600', padding: '4px 12px', borderRadius: '20px' }}>4 Parts · 12 Questions</span>
              </div>
              <h1 style={{ color: 'white', fontSize: '32px', fontWeight: 'bold', margin: '0 0 8px', lineHeight: '1.3' }}>Handling Customer Complaints</h1>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '16px', margin: 0, lineHeight: '1.6' }}>An angry customer is not a disaster — it is an opportunity. Learn the professional language, strategies, and psychology of turning complaints into loyalty.</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '20px', marginTop: '28px', flexWrap: 'wrap' }}>{[{ icon: '📄', label: '4 reading parts' }, { icon: '💬', label: '12 discussion questions' }, { icon: '📚', label: '16 vocabulary words' }, { icon: '✍️', label: 'Highlight any text' }, { icon: '🌍', label: 'Multi-language lookup' }, { icon: '🤖', label: 'AI conversation partner' }].map(s => <div key={s.label} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'rgba(255,255,255,0.75)', fontSize: '13px' }}><span>{s.icon}</span> {s.label}</div>)}</div>
        </div>
      </section>
      <section style={{ background: 'white', borderBottom: '1px solid #eee', padding: '14px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', alignItems: 'center', marginBottom: '10px' }}><span style={{ color: '#888', fontSize: '12px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>How to use:</span>{['🔊 Play passage aloud', '✍️ Highlight any text for lookup', '🌍 Translate vocab, questions & AI answers', '🤖 Practice with AI'].map((step, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#555', fontSize: '13px' }}><span style={{ background: '#ca8a04', color: 'white', width: '18px', height: '18px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '10px', fontWeight: 'bold', flexShrink: 0 }}>{i + 1}</span>{step}</div>)}</div>
          <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap', alignItems: 'center' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🔊 Speed:</span>{SPEEDS.map(s => <button key={s.value} onClick={() => setSpeed(s.value)} style={{ padding: '4px 12px', borderRadius: '20px', border: '2px solid', borderColor: speed === s.value ? '#ca8a04' : '#e5e7eb', background: speed === s.value ? '#ca8a04' : 'white', color: speed === s.value ? 'white' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', transition: 'all 0.2s' }}>{s.label}</button>)}</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🌍 Translate to:</span><select value={translationLang} onChange={e => { setTranslationLang(e.target.value); setVocabTranslations({}); setQuestionTranslations({}) }} style={{ padding: '5px 12px', borderRadius: '20px', border: '2px solid', borderColor: translationLang !== 'none' ? '#ca8a04' : '#e5e7eb', background: translationLang !== 'none' ? '#fefce8' : 'white', color: translationLang !== 'none' ? '#713f12' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', outline: 'none' }}>{LANGUAGES.map(l => <option key={l.value} value={l.value}>{l.label}</option>)}</select></div>
          </div>
        </div>
      </section>
      <div style={{ maxWidth: '860px', margin: '0 auto', padding: '32px 24px', display: 'flex', flexDirection: 'column', gap: '28px' }}>
        {PARTS.map(part => (
          <div key={part.number} style={{ background: 'white', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 2px 12px rgba(0,0,0,0.07)' }}>
            <div style={{ background: `linear-gradient(135deg, ${part.color}22, ${part.color}08)`, borderLeft: `5px solid ${part.color}`, padding: '20px 24px', display: 'flex', gap: '14px', alignItems: 'center', flexWrap: 'wrap' }}>
              <div style={{ background: part.color, color: 'white', width: '36px', height: '36px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '16px', flexShrink: 0 }}>{part.number}</div>
              <div style={{ flex: 1 }}><div style={{ color: part.color, fontSize: '11px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '2px' }}>Part {part.number}</div><h2 data-passage="true" style={{ color: '#1a1a2e', fontSize: '18px', fontWeight: 'bold', margin: 0, userSelect: 'text', cursor: 'text' }}>{part.emoji} {part.title}</h2></div>
              <div style={{ display: 'flex', gap: '8px', flexShrink: 0 }}><button onClick={() => speakText(part.text.replace(/\n\n/g, ' '))} style={{ background: part.color, color: 'white', border: 'none', padding: '8px 16px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', boxShadow: `0 3px 10px ${part.color}40` }}>▶ Play Passage</button><button onClick={stopAudio} style={{ background: 'white', color: '#6b7280', border: '2px solid #e5e7eb', padding: '8px 12px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer' }}>⏹ Stop</button></div>
            </div>
            <div style={{ background: '#fefce8', padding: '8px 28px', borderBottom: '1px solid #fef08a' }}><span style={{ color: '#713f12', fontSize: '12px', fontWeight: '600' }}>✍️ Highlight any word or phrase to hear it and see its meaning{translationLang !== 'none' && <span style={{ color: '#ca8a04' }}> + {currentLang?.label} translation</span>}</span></div>
            <div data-passage="true" style={{ padding: '24px 28px 20px', userSelect: 'text', cursor: 'text' }}>{part.text.split('\n\n').map((para, i) => <p key={i} style={{ color: '#374151', fontSize: '16px', lineHeight: '1.85', margin: i === 0 ? '0 0 18px' : '0', fontFamily: 'Georgia, serif' }}>{para}</p>)}</div>
            <div style={{ margin: '0 28px 24px', background: part.color + '08', border: `1px solid ${part.color}25`, borderRadius: '14px', overflow: 'hidden' }}>
              <div style={{ background: part.color + '18', padding: '12px 16px', display: 'flex', alignItems: 'center', gap: '8px', borderBottom: `1px solid ${part.color}20` }}><span style={{ fontSize: '16px' }}>📚</span><span style={{ color: part.color, fontWeight: 'bold', fontSize: '13px', textTransform: 'uppercase', letterSpacing: '1px' }}>Vocabulary — Part {part.number}</span></div>
              <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>{part.vocab.map((v, i) => { const vKey = `${part.number}-${v.word}`; return (<div key={v.word} style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', paddingBottom: i < part.vocab.length - 1 ? '10px' : '0', borderBottom: i < part.vocab.length - 1 ? `1px solid ${part.color}15` : 'none' }}><div style={{ background: part.color, color: 'white', width: '22px', height: '22px', borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '11px', flexShrink: 0, marginTop: '2px' }}>{i + 1}</div><div style={{ flex: 1 }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '3px', flexWrap: 'wrap' }}><span data-passage="true" style={{ fontWeight: 'bold', color: '#1a1a2e', fontSize: '15px', userSelect: 'text', cursor: 'text' }}>{v.word}</span><button onClick={() => speakWord(v.word)} style={{ background: part.color + '15', color: part.color, border: `1px solid ${part.color}30`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0 }}>🔊</button><TranslateBtn text={`Word: "${v.word}"\nDefinition: "${v.definition}"`} type="word" lang={translationLang} color={part.color} onTranslated={(t) => setVocabTranslations(prev => ({ ...prev, [vKey]: t }))} />{translationLang === 'none' && <span style={{ color: '#d1d5db', fontSize: '11px' }}>← select a language to translate</span>}</div><span data-passage="true" style={{ color: '#6b7280', fontSize: '14px', lineHeight: '1.5', userSelect: 'text', cursor: 'text' }}>{v.definition}</span>{vocabTranslations[vKey] && <div style={{ marginTop: '6px', background: '#fefce8', border: '1px solid #fef08a', borderRadius: '8px', padding: '8px 12px' }}><span style={{ color: '#713f12', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: '#374151', fontSize: '14px', lineHeight: '1.5' }}>{vocabTranslations[vKey]}</span></div>}</div></div>) })}</div>
            </div>
            <div style={{ background: '#1a1a2e', padding: '20px 28px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}><span style={{ fontSize: '18px' }}>💬</span><span style={{ color: '#fde047', fontWeight: 'bold', fontSize: '14px', textTransform: 'uppercase', letterSpacing: '1px' }}>Discussion Questions</span></div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>{part.questions.map(q => (<div key={q.n}><div style={{ display: 'flex', gap: '14px', alignItems: 'flex-start' }}><div style={{ background: part.color, color: 'white', width: '28px', height: '28px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '13px', flexShrink: 0, marginTop: '1px' }}>{q.n}</div><div style={{ flex: 1 }}><p data-passage="true" style={{ color: 'rgba(255,255,255,0.88)', fontSize: '15px', lineHeight: '1.6', margin: '0 0 6px', userSelect: 'text', cursor: 'text' }}>{q.q}</p><div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><TranslateBtn text={q.q} type="question" lang={translationLang} color={part.color} onTranslated={(t) => setQuestionTranslations(prev => ({ ...prev, [q.n]: t }))} />{translationLang === 'none' && <span style={{ color: '#4b5563', fontSize: '11px' }}>← select a language to translate</span>}</div>{questionTranslations[q.n] && <div style={{ marginTop: '8px', background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.3)', borderRadius: '10px', padding: '10px 14px' }}><span style={{ color: '#fde047', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: 'rgba(255,255,255,0.9)', fontSize: '14px', lineHeight: '1.6' }}>{questionTranslations[q.n]}</span></div>}</div></div><div style={{ marginLeft: '42px' }}><ConversationBox question={q.q} color={part.color} translationLang={translationLang} speed={speed} /></div></div>))}</div>
            </div>
          </div>
        ))}
        <div style={{ textAlign: 'center', paddingBottom: selectedText ? '140px' : '16px' }}><Link href="/esl-resources/reading-comprehension/b1" style={{ color: '#ca8a04', textDecoration: 'none', fontWeight: 'bold', fontSize: '14px' }}>← Back to B1 Reading Comprehension</Link></div>
      </div>
      {selectedText && <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 200, animation: 'slideUp 0.25s ease' }}><div style={{ maxWidth: '860px', margin: '0 auto', background: 'white', borderRadius: '20px 20px 0 0', padding: '20px 24px 32px', boxShadow: '0 -8px 32px rgba(0,0,0,0.2)', border: '2px solid #fef08a', borderBottom: 'none' }}><div style={{ width: '40px', height: '4px', background: '#e5e7eb', borderRadius: '4px', margin: '0 auto 16px' }} /><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}><span style={{ fontSize: '22px', fontWeight: '900', color: '#1a1a2e', fontFamily: 'Georgia, serif' }}>"{selectedText}"</span><button onClick={() => speakWord(selectedText)} style={{ background: '#fefce8', color: '#713f12', border: '2px solid #fef08a', padding: '6px 14px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', flexShrink: 0 }}>🔊 Hear it</button></div><button onClick={() => setSelectedText(null)} style={{ background: '#f3f4f6', border: 'none', width: '32px', height: '32px', borderRadius: '8px', cursor: 'pointer', fontSize: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#6b7280', flexShrink: 0, marginLeft: '12px' }}>✕</button></div>{lookupLoading ? <div style={{ background: '#fefce8', borderRadius: '12px', padding: '14px 18px', border: '1px solid #fef08a', color: '#9ca3af', fontSize: '15px' }}>{translationLang !== 'none' ? `Looking up definition and ${currentLang?.label} translation...` : 'Looking up...'}</div> : <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}><div style={{ background: '#fefce8', borderRadius: '12px', padding: '14px 18px', border: '1px solid #fef08a' }}><div style={{ color: '#713f12', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>📖 English Definition</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupDef}</span></div>{translationLang !== 'none' && lookupTranslation && <div style={{ background: '#fefce8', borderRadius: '12px', padding: '14px 18px', border: '1px solid #fde047' }}><div style={{ color: '#854d0e', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>{currentLang?.label} Translation</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupTranslation}</span></div>}</div>}</div></div>}
    </main>
  )
}
