export const questionBank: Record<string, { q: string; options: string[]; answer: string }[]> = {
  'P1-P2': [
    { q: 'A fruit that monkeys love to eat:', options: ['bananna', 'bannana', 'bananah', 'banana'], answer: 'banana' },
    { q: 'A large grey animal with a long trunk:', options: ['elefant', 'eliphant', 'elephent', 'elephant'], answer: 'elephant' },
    { q: 'The opposite of hot:', options: ['kold', 'cald', 'colld', 'cold'], answer: 'cold' },
    { q: 'Where children go to learn:', options: ['skool', 'scool', 'scoole', 'school'], answer: 'school' },
    { q: 'Someone you like and play with:', options: ['freind', 'frend', 'friand', 'friend'], answer: 'friend' },
    { q: 'A red or green fruit with seeds inside:', options: ['aple', 'appel', 'aplle', 'apple'], answer: 'apple' },
    { q: 'The liquid we drink every day:', options: ['watter', 'watar', 'woter', 'water'], answer: 'water' },
    { q: 'Feeling very glad:', options: ['hapy', 'happie', 'happi', 'happy'], answer: 'happy' },
    { q: 'The colour of the sun:', options: ['yelo', 'yelloe', 'yelow', 'yellow'], answer: 'yellow' },
    { q: 'A pretty plant that grows in a garden:', options: ['flowor', 'flouer', 'flouwer', 'flower'], answer: 'flower' },
    { q: 'A tool for writing that you can erase:', options: ['pensil', 'pencell', 'penzil', 'pencil'], answer: 'pencil' },
    { q: 'A small creature with long ears that hops:', options: ['rabbet', 'rabit', 'rabbitt', 'rabbit'], answer: 'rabbit' },
    { q: 'The first day of the working week:', options: ['Munday', 'Mondday', 'Monady', 'Monday'], answer: 'Monday' },
    { q: 'A colour between red and yellow:', options: ['orenge', 'oarnge', 'oranje', 'orange'], answer: 'orange' },
    { q: 'Your female parent:', options: ['moother', 'muthar', 'mothir', 'mother'], answer: 'mother' },
    { q: 'Where plants and vegetables grow outside:', options: ['gardin', 'gardan', 'gaarden', 'garden'], answer: 'garden' },
    { q: 'A living creature like a dog or a cat:', options: ['animul', 'animall', 'annimal', 'animal'], answer: 'animal' },
    { q: 'The first part of the day:', options: ['mornin', 'mornning', 'moarning', 'morning'], answer: 'morning' },
    { q: 'The cold season of the year:', options: ['wintir', 'winnter', 'wintur', 'winter'], answer: 'winter' },
    { q: 'Parents, children and relatives together:', options: ['famly', 'familly', 'famalie', 'family'], answer: 'family' },
    { q: 'The colour of chocolate:', options: ['brone', 'broun', 'browwn', 'brown'], answer: 'brown' },
    { q: 'Something that happens every single time:', options: ['allways', 'alwais', 'alwayz', 'always'], answer: 'always' },
    { q: 'Earlier than something else:', options: ['befor', 'befour', 'beefore', 'before'], answer: 'before' },
    { q: 'More than one person:', options: ['pepole', 'peaple', 'poeple', 'people'], answer: 'people' },
    { q: 'A road in a town or city:', options: ['streat', 'strete', 'streett', 'street'], answer: 'street' },
    { q: 'Nice-looking or attractive:', options: ['prety', 'pretie', 'pritty', 'pretty'], answer: 'pretty' },
    { q: 'A structure you walk over to cross water:', options: ['brigde', 'bridgge', 'brige', 'bridge'], answer: 'bridge' },
    { q: 'The colour between blue and red:', options: ['perple', 'purpel', 'purpull', 'purple'], answer: 'purple' },
    { q: 'A person who helps you when you are sick:', options: ['docter', 'dokter', 'doctour', 'doctor'], answer: 'doctor' },
    { q: 'The number after six:', options: ['sevven', 'sevan', 'saven', 'seven'], answer: 'seven' },
    { q: 'Your female brother or sister (girl):', options: ['siter', 'sistar', 'sisster', 'sister'], answer: 'sister' },
    { q: 'Furniture with a flat top you eat or work at:', options: ['tabel', 'taible', 'tablel', 'table'], answer: 'table' },
    { q: 'The last day of the school week:', options: ['Fryday', 'Friiday', 'Fridai', 'Friday'], answer: 'Friday' },
    { q: 'A yellow spread you put on bread:', options: ['buttar', 'buttir', 'butterr', 'butter'], answer: 'butter' },
    { q: 'The evening meal:', options: ['dinnar', 'dinnir', 'dinir', 'dinner'], answer: 'dinner' },
    { q: 'Very small in size:', options: ['littel', 'litttle', 'litle', 'little'], answer: 'little' },
    { q: 'More good than before:', options: ['bettar', 'bettir', 'betir', 'better'], answer: 'better' },
    { q: 'Something that makes you laugh:', options: ['funy', 'funnie', 'funni', 'funny'], answer: 'funny' },
    { q: 'A large striped wild cat from Asia:', options: ['tigir', 'tigar', 'tigerr', 'tiger'], answer: 'tiger' },
    { q: 'The number after nine:', options: ['tenn', 'tean', 'tein', 'ten'], answer: 'ten' },
  ],
  'P3-P4': [
    { q: 'Very pleasing to look at:', options: ['beutiful', 'beautifull', 'beautyful', 'beautiful'], answer: 'beautiful' },
    { q: 'For the reason that:', options: ['becaus', 'becuase', 'beacuse', 'because'], answer: 'because' },
    { q: 'In the same place at the same time:', options: ['togeather', 'togather', 'togethar', 'together'], answer: 'together' },
    { q: 'Not the same as something else:', options: ['diferent', 'diffrent', 'differant', 'different'], answer: 'different' },
    { q: 'As much as needed, not more:', options: ['enuff', 'enuogh', 'enogh', 'enough'], answer: 'enough' },
    { q: 'From one side to the other:', options: ['thrugh', 'throught', 'throgh', 'through'], answer: 'through' },
    { q: 'A reply to a question:', options: ['answar', 'anser', 'answir', 'answer'], answer: 'answer' },
    { q: 'To think something is true:', options: ['beleive', 'beleve', 'beleave', 'believe'], answer: 'believe' },
    { q: 'The day in the middle of the week:', options: ['Wednsday', 'Wendsday', 'Wednseday', 'Wednesday'], answer: 'Wednesday' },
    { q: 'An unexpected or shocking event:', options: ['suprise', 'surpise', 'surprize', 'surprise'], answer: 'surprise' },
    { q: 'Apart from others, kept apart:', options: ['seperate', 'seperrate', 'separete', 'separate'], answer: 'separate' },
    { q: 'The second month of the year:', options: ['Febuary', 'Feburary', 'Februery', 'February'], answer: 'February' },
    { q: 'Something that is needed or required:', options: ['neccessary', 'necesary', 'neccesary', 'necessary'], answer: 'necessary' },
    { q: 'A place with many books to borrow:', options: ['libary', 'librery', 'libarry', 'library'], answer: 'library' },
    { q: 'A plant food like a carrot or potato:', options: ['vegatable', 'vegeatble', 'vegetible', 'vegetable'], answer: 'vegetable' },
    { q: 'A sweet brown food made from cocoa:', options: ['chocolatte', 'choclate', 'chockolate', 'chocolate'], answer: 'chocolate' },
    { q: 'The day before today:', options: ['yesturday', 'yestirday', 'yesterdai', 'yesterday'], answer: 'yesterday' },
    { q: 'Holding your attention for a long time:', options: ['intresting', 'interresting', 'intersting', 'interesting'], answer: 'interesting' },
    { q: 'Having great value or meaning:', options: ['importent', 'importannt', 'imporant', 'important'], answer: 'important' },
    { q: 'Physical activity to keep fit:', options: ['excersise', 'exersise', 'exercize', 'exercise'], answer: 'exercise' },
    { q: 'The thing you like most:', options: ['favouirite', 'favorit', 'favourit', 'favourite'], answer: 'favourite' },
    { q: 'To vanish or go out of sight:', options: ['dissapear', 'disapear', 'disapeare', 'disappear'], answer: 'disappear' },
    { q: 'To picture something in your mind:', options: ['imagin', 'imaigne', 'imaggine', 'imagine'], answer: 'imagine' },
    { q: 'Not easy to do:', options: ['difficalt', 'differcult', 'difficelt', 'difficult'], answer: 'difficult' },
    { q: 'A group of words that makes complete sense:', options: ['sentance', 'sentense', 'sentince', 'sentence'], answer: 'sentence' },
    { q: 'Where something is placed:', options: ['possition', 'postion', 'posiition', 'position'], answer: 'position' },
    { q: 'A chart showing days, weeks and months:', options: ['calender', 'callender', 'calander', 'calendar'], answer: 'calendar' },
    { q: 'Very likely to happen:', options: ['probaly', 'probbably', 'probabaly', 'probably'], answer: 'probably' },
    { q: 'To get something that is given or sent:', options: ['recieve', 'receeve', 'receave', 'receive'], answer: 'receive' },
    { q: 'Information and understanding you have:', options: ['knowlege', 'knowledje', 'knowladge', 'knowledge'], answer: 'knowledge' },
    { q: 'Feeling relaxed and at ease:', options: ['comfatable', 'comfortble', 'comfortabl', 'comfortable'], answer: 'comfortable' },
    { q: 'The natural world around us:', options: ['enviroment', 'enviornment', 'envirionment', 'environment'], answer: 'environment' },
    { q: 'The people who run a country:', options: ['goverment', 'governmant', 'govarnment', 'government'], answer: 'government' },
    { q: 'The start of something:', options: ['begining', 'beggining', 'beginnnig', 'beginning'], answer: 'beginning' },
    { q: 'Finished in every way, with nothing left out:', options: ['completly', 'completeley', 'completaly', 'completely'], answer: 'completely' },
    { q: 'To keep going without stopping:', options: ['continnue', 'continew', 'continuu', 'continue'], answer: 'continue' },
    { q: 'In the middle of two things:', options: ['beetween', 'bitween', 'betwean', 'between'], answer: 'between' },
    { q: 'A choice you make after thinking:', options: ['descision', 'decission', 'desicion', 'decision'], answer: 'decision' },
    { q: 'Something you have done or been through:', options: ['experiance', 'experence', 'experiense', 'experience'], answer: 'experience' },
    { q: 'To make a mistake without meaning to:', options: ['acidentally', 'acidentaly', 'accidentaly', 'accidentally'], answer: 'accidentally' },
  ],
  'P5-P6': [
    { q: 'To provide space or room for someone:', options: ['acommodate', 'accomodate', 'accomadate', 'accommodate'], answer: 'accommodate' },
    { q: 'An event or instance of something happening:', options: ['occurence', 'occurance', 'ocurrance', 'occurrence'], answer: 'occurrence' },
    { q: 'A group of people chosen to make decisions:', options: ['commitee', 'comittee', 'committie', 'committee'], answer: 'committee' },
    { q: 'Your inner feeling of right and wrong:', options: ['consience', 'concience', 'conshience', 'conscience'], answer: 'conscience' },
    { q: 'Happening from time to time, not regularly:', options: ['ocassionally', 'ocasionally', 'occasionaly', 'occasionally'], answer: 'occasionally' },
    { q: 'The group of people who run a country\'s laws:', options: ['parliment', 'parlliament', 'parlaiment', 'parliament'], answer: 'parliament' },
    { q: 'To cause great embarrassment or shame:', options: ['embarass', 'embarras', 'embarrass', 'embarrass'], answer: 'embarrass' },
    { q: 'To make something seem larger or more important:', options: ['exagerate', 'exxagerate', 'exagerrate', 'exaggerate'], answer: 'exaggerate' },
    { q: 'To successfully reach a goal:', options: ['acheive', 'achive', 'acheeve', 'achieve'], answer: 'achieve' },
    { q: 'Certain and clear, not vague:', options: ['definate', 'definete', 'definit', 'definite'], answer: 'definite' },
    { q: 'A special right or advantage enjoyed by few:', options: ['priviledge', 'privilage', 'privlege', 'privilege'], answer: 'privilege' },
    { q: 'A promise that something will happen:', options: ['guarentee', 'guarrantee', 'garantee', 'guarantee'], answer: 'guarantee' },
    { q: 'A period of one thousand years:', options: ['millenium', 'milleniuum', 'milenium', 'millennium'], answer: 'millennium' },
    { q: 'A high-ranking military officer:', options: ['lieutanant', 'leutenant', 'liutenant', 'lieutenant'], answer: 'lieutenant' },
    { q: 'The killing of an important person for political reasons:', options: ['asassination', 'assasination', 'assassinnation', 'assassination'], answer: 'assassination' },
    { q: 'To admit or recognise something:', options: ['aknowledge', 'ackknowledge', 'acnowledge', 'acknowledge'], answer: 'acknowledge' },
    { q: 'A disease affecting the lungs:', options: ['newmonia', 'neumonia', 'pnemonia', 'pneumonia'], answer: 'pneumonia' },
    { q: 'A jumbled mixture of various items:', options: ['miscelaneous', 'miscellaneaous', 'miscellanieous', 'miscellaneous'], answer: 'miscellaneous' },
    { q: 'To take the place of something older:', options: ['supercede', 'superseed', 'superceed', 'supersede'], answer: 'supersede' },
    { q: 'The quality of continuing despite difficulty:', options: ['perserverance', 'perseverence', 'persevarance', 'perseverance'], answer: 'perseverance' },
    { q: 'Very careful and thorough in work:', options: ['concientious', 'consciencious', 'conshientious', 'conscientious'], answer: 'conscientious' },
    { q: 'Close monitoring of a person or place:', options: ['survailance', 'survillance', 'surviellance', 'surveillance'], answer: 'surveillance' },
    { q: 'Someone who starts and runs their own business:', options: ['entrepeneur', 'entreprenueur', 'entreprenur', 'entrepreneur'], answer: 'entrepreneur' },
    { q: 'A system of government with many complicated rules:', options: ['bureacracy', 'burocracy', 'beurocracy', 'bureaucracy'], answer: 'bureaucracy' },
    { q: 'A planned meeting at a secret place:', options: ['rendevouz', 'rendevous', 'rendesvouz', 'rendezvous'], answer: 'rendezvous' },
    { q: 'A link or connection between people or groups:', options: ['liason', 'laison', 'liasion', 'liaison'], answer: 'liaison' },
    { q: 'Glowing brightly, giving off light:', options: ['flourescent', 'floresent', 'flouresent', 'fluorescent'], answer: 'fluorescent' },
    { q: 'A green vegetable often served with pasta:', options: ['broccolli', 'brocolli', 'brocoli', 'broccoli'], answer: 'broccoli' },
    { q: 'A fellow worker or professional:', options: ['coleague', 'collegue', 'collegeau', 'colleague'], answer: 'colleague' },
    { q: 'A situation where you must choose between two difficult options:', options: ['dilema', 'dilemna', 'dillemma', 'dilemma'], answer: 'dilemma' },
    { q: 'Right now, without any delay:', options: ['immediatly', 'imediatley', 'immedietaly', 'immediately'], answer: 'immediately' },
    { q: 'Related to the mind and mental processes:', options: ['psycological', 'pschological', 'psychalogical', 'psychological'], answer: 'psychological' },
    { q: 'A regular beat or pattern in music or language:', options: ['rythm', 'rhytm', 'ryhthm', 'rhythm'], answer: 'rhythm' },
    { q: 'A completely empty space with no air:', options: ['vaccum', 'vacuem', 'vacuume', 'vacuum'], answer: 'vacuum' },
    { q: 'A system of spoken or written communication:', options: ['langauge', 'languige', 'languaje', 'language'], answer: 'language' },
    { q: 'A chance to do something useful or good:', options: ['oportunity', 'oppurtunity', 'opportunnity', 'opportunity'], answer: 'opportunity' },
    { q: 'The duty to deal with something or someone:', options: ['responsibilty', 'responsability', 'responsibiliti', 'responsibility'], answer: 'responsibility' },
    { q: 'The way a word is spoken or said:', options: ['pronounciation', 'prononciation', 'pronunciacion', 'pronunciation'], answer: 'pronunciation' },
    { q: 'An expert who knows a lot about a subject:', options: ['spesialist', 'specilist', 'specialst', 'specialist'], answer: 'specialist' },
    { q: 'Based on facts, not feelings or opinion:', options: ['objecttive', 'objectiv', 'objetive', 'objective'], answer: 'objective' },
  ],
  'M1-M3': [
    { q: 'A person you know but are not close friends with:', options: ['aquaintance', 'acquantance', 'acquaintence', 'acquaintance'], answer: 'acquaintance' },
    { q: 'Something placed in the wrong time period:', options: ['anacronism', 'anachronnism', 'anachronsim', 'anachronism'], answer: 'anachronism' },
    { q: 'Treating something as too small or unimportant:', options: ['supercillious', 'supercilous', 'supercillius', 'supercilious'], answer: 'supercilious' },
    { q: 'To make a problem worse or more severe:', options: ['exaserbate', 'exaccerbate', 'exacerbatte', 'exacerbate'], answer: 'exacerbate' },
    { q: 'Peculiar to a particular person or group:', options: ['idiosincratic', 'idiosyncrratic', 'idiosincratik', 'idiosyncratic'], answer: 'idiosyncratic' },
    { q: 'An expert judge in matters of taste:', options: ['connoiseur', 'conoisseur', 'connoissure', 'connoisseur'], answer: 'connoisseur' },
    { q: 'To dry something out completely:', options: ['dessicate', 'desicate', 'desiccatte', 'desiccate'], answer: 'desiccate' },
    { q: 'The state of feeling very ashamed:', options: ['embarassment', 'embarrasssment', 'embarrasment', 'embarrassment'], answer: 'embarrassment' },
    { q: 'A profuse discharge of blood:', options: ['hemorhage', 'hemmorhage', 'haemmorhage', 'haemorrhage'], answer: 'haemorrhage' },
    { q: 'A peculiar habit or characteristic:', options: ['idiosyncracy', 'idiosincrasy', 'idiosinkrasy', 'idiosyncrasy'], answer: 'idiosyncrasy' },
    { q: 'Without meaning to, by accident:', options: ['inadvirtently', 'inadvartently', 'inadvertantly', 'inadvertently'], answer: 'inadvertently' },
    { q: 'Shimmering with many colours like a rainbow:', options: ['irridescent', 'iridescant', 'irridescant', 'iridescent'], answer: 'iridescent' },
    { q: 'A tube-shaped toy with mirrors creating patterns:', options: ['kaleodoscope', 'kaliedoscope', 'kaleydoscope', 'kaleidoscope'], answer: 'kaleidoscope' },
    { q: 'Talking a lot in a very chatty way:', options: ['loquatious', 'loquasius', 'loquacous', 'loquacious'], answer: 'loquacious' },
    { q: 'Naughtily causing trouble in a playful way:', options: ['mischievious', 'mischeivous', 'mischevious', 'mischievous'], answer: 'mischievous' },
    { q: 'The word imitating the sound it describes:', options: ['onomatapoeia', 'onomatopoiea', 'onomatopeia', 'onomatopoeia'], answer: 'onomatopoeia' },
    { q: 'A miscellaneous collection of things:', options: ['paraphanalia', 'paraphernallia', 'parapharnalia', 'paraphernalia'], answer: 'paraphernalia' },
    { q: 'An extraordinary or remarkable occurrence:', options: ['phenomemon', 'phenominon', 'phenomenen', 'phenomenon'], answer: 'phenomenon' },
    { q: 'To come before something else in order:', options: ['preceed', 'presede', 'preceede', 'precede'], answer: 'precede' },
    { q: 'A form for gathering written information:', options: ['questionaire', 'questionairre', 'questionnarire', 'questionnaire'], answer: 'questionnaire' },
    { q: 'A dark shape cast by blocking light:', options: ['silouette', 'silhoette', 'silouete', 'silhouette'], answer: 'silhouette' },
    { q: 'In a complete and careful way:', options: ['thorougly', 'thoroughy', 'thourogly', 'thoroughly'], answer: 'thoroughly' },
    { q: 'Not able to be separated or divided:', options: ['inseperable', 'inseparible', 'insepareble', 'inseparable'], answer: 'inseparable' },
    { q: 'The act of speaking well of yourself:', options: ['bosting', 'bostting', 'boasting', 'boassting'], answer: 'boasting' },
    { q: 'Able to be seen through clearly:', options: ['transparrent', 'transparant', 'trnasparent', 'transparent'], answer: 'transparent' },
    { q: 'Related to numbers and counting:', options: ['numericall', 'nemerical', 'numerecal', 'numerical'], answer: 'numerical' },
    { q: 'The quality of being fair and just:', options: ['equiity', 'equety', 'equitty', 'equity'], answer: 'equity' },
    { q: 'A written set of rules for an organisation:', options: ['constituton', 'constitustion', 'constitition', 'constitution'], answer: 'constitution' },
    { q: 'Lasting only a very short time:', options: ['ephemiral', 'ephemaral', 'ephemerall', 'ephemeral'], answer: 'ephemeral' },
    { q: 'Relating to morals and right conduct:', options: ['ethicle', 'ethecal', 'ethicall', 'ethical'], answer: 'ethical' },
    { q: 'To get better after illness or difficulty:', options: ['reccover', 'recovar', 'recouver', 'recover'], answer: 'recover' },
    { q: 'The quality of being well known:', options: ['prominense', 'prominance', 'prominense', 'prominence'], answer: 'prominence' },
    { q: 'Existing or happening everywhere at once:', options: ['ubiqiutous', 'ubiquitius', 'ubiquitouss', 'ubiquitous'], answer: 'ubiquitous' },
    { q: 'Related to the stars and space:', options: ['astronimical', 'astronomicall', 'astromomical', 'astronomical'], answer: 'astronomical' },
    { q: 'An official change to a law or document:', options: ['amendmant', 'amendement', 'ammendment', 'amendment'], answer: 'amendment' },
    { q: 'The belief that all people are equal:', options: ['egalatarian', 'egalitarien', 'egaliterean', 'egalitarian'], answer: 'egalitarian' },
    { q: 'A very determined and passionate feeling:', options: ['fervant', 'fervour', 'fervoir', 'fervour'], answer: 'fervour' },
    { q: 'Able to recover quickly from difficulties:', options: ['resilant', 'resiilent', 'resilient', 'resillent'], answer: 'resilient' },
    { q: 'The process of making something simpler:', options: ['simplifacation', 'simpliffication', 'simplificaton', 'simplification'], answer: 'simplification' },
    { q: 'An unexpected piece of good luck:', options: ['serendippity', 'serendipty', 'serendipety', 'serendipity'], answer: 'serendipity' },
  ],
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}
