'use client'
import { useState, useRef, useEffect } from 'react'
import Link from 'next/link'

const SPEEDS = [
  { label: '🐢 Very Slow', value: 0.55 },
  { label: '🚶 Slow', value: 0.72 },
  { label: '🏃 Normal', value: 0.9 },
  { label: '⚡ Fast', value: 1.1 },
]

const LANGUAGES = [
  { value: 'none', label: '🌍 English only' },
  { value: 'Thai', label: '🇹🇭 Thai' },
  { value: 'Japanese', label: '🇯🇵 Japanese' },
  { value: 'Korean', label: '🇰🇷 Korean' },
  { value: 'Chinese', label: '🇨🇳 Chinese' },
  { value: 'Arabic', label: '🇸🇦 Arabic' },
  { value: 'Spanish', label: '🇪🇸 Spanish' },
  { value: 'French', label: '🇫🇷 French' },
  { value: 'German', label: '🇩🇪 German' },
  { value: 'Portuguese', label: '🇧🇷 Portuguese' },
  { value: 'Russian', label: '🇷🇺 Russian' },
  { value: 'Vietnamese', label: '🇻🇳 Vietnamese' },
  { value: 'Indonesian', label: '🇮🇩 Indonesian' },
]

const PARTS = [
  {
    number: 1, title: 'What Makes Weather Happen?', emoji: '☁️', color: '#475569',
    text: `Weather is something we experience every single day — sunshine, rain, wind, clouds, snow. But have you ever wondered what actually causes it? Why does it rain on some days and not others? Why is it hot in summer and cold in winter? And what makes a calm, sunny day turn into a violent storm?\n\nAll weather is caused by the Sun heating the Earth\'s atmosphere unevenly. The Sun\'s rays hit the equator more directly than the poles, which means tropical regions get much more heat. This creates differences in temperature across the planet, and these temperature differences drive everything else — wind, rain, clouds, and storms.\n\nWarm air rises because it is lighter than cold air. As warm air rises, it cools down, and the water vapour inside it turns into tiny droplets that form clouds. When those droplets become heavy enough, they fall as rain. This simple process — warm air rising, cooling, forming clouds, and producing rain — is the engine behind most of the world\'s weather.\n\nWind is caused by air moving from areas of high pressure to areas of low pressure. When the Sun heats the ground, the air above it warms up and rises, creating an area of low pressure. Cooler air from surrounding areas rushes in to fill the gap — and this movement of air is what we feel as wind. The bigger the difference in pressure between two areas, the stronger the wind.\n\nMost weather is gentle and predictable. But sometimes, when the right conditions come together, the atmosphere produces something far more dramatic — extreme weather events that can be among the most powerful and destructive forces on Earth.`,
    vocab: [
      { word: 'Atmosphere', definition: 'The layer of gases surrounding the Earth that we breathe and that creates our weather.' },
      { word: 'Water vapour', definition: 'Water in the form of an invisible gas — when it cools down, it turns into tiny water droplets.' },
      { word: 'High pressure', definition: 'An area where air is sinking and pushing down — usually brings calm, clear weather.' },
      { word: 'Low pressure', definition: 'An area where warm air is rising — usually brings clouds, rain, and sometimes storms.' },
    ],
    questions: [
      { n: 1, q: 'Before reading this, did you know that all weather is caused by the Sun? Does this change how you think about weather?' },
      { n: 2, q: 'Can you explain in your own words why wind happens? Try to use the words "pressure" and "temperature" in your answer.' },
      { n: 3, q: 'What is the weather usually like where you live? Do you experience extreme weather?' },
    ]
  },
  {
    number: 2, title: 'Tornadoes and Hurricanes', emoji: '🌪️', color: '#334155',
    text: `Tornadoes and hurricanes are two of the most powerful and terrifying weather events on Earth. Although they are both violent spinning storms, they are actually very different in how they form, how big they are, and how long they last.\n\nA tornado is a rapidly spinning column of air that stretches from a thunderstorm cloud down to the ground. Tornadoes are usually between 100 and 500 metres wide, and most last less than ten minutes. But in that short time, they can be incredibly destructive. The strongest tornadoes produce winds of more than 480 kilometres per hour — fast enough to pick up cars, tear roofs off buildings, and throw heavy objects hundreds of metres through the air. The United States experiences more tornadoes than any other country — about 1,200 every year, mostly in an area called "Tornado Alley" in the central United States.\n\nHurricanes are much larger and last much longer than tornadoes. A hurricane is a massive rotating storm system that forms over warm ocean water. Hurricanes can be hundreds of kilometres wide and can last for days or even weeks. They produce powerful winds, enormous waves, and torrential rain that can cause devastating flooding. Hurricane Katrina, which hit the United States in 2005, killed more than 1,800 people and caused over 125 billion dollars in damage.\n\nIn different parts of the world, hurricanes have different names. In the western Pacific, they are called typhoons. In the Indian Ocean, they are called cyclones. Thailand occasionally experiences the effects of typhoons and tropical storms, particularly in the south of the country during the monsoon season.`,
    vocab: [
      { word: 'Column', definition: 'A tall, narrow shape — like a pillar or a tower.' },
      { word: 'Torrential', definition: 'Extremely heavy — used to describe very intense rainfall.' },
      { word: 'Devastating', definition: 'Causing enormous damage and destruction.' },
      { word: 'Monsoon', definition: 'A seasonal wind pattern that brings heavy rainfall to parts of Asia and other tropical regions.' },
    ],
    questions: [
      { n: 4, q: 'What is the main difference between a tornado and a hurricane? Which one do you think is more dangerous?' },
      { n: 5, q: 'The US has about 1,200 tornadoes every year. Would you want to live in "Tornado Alley"? Why or why not?' },
      { n: 6, q: 'Thailand experiences tropical storms during monsoon season. Have you ever experienced a serious storm? What happened?' },
    ]
  },
  {
    number: 3, title: 'Lightning, Thunder and Floods', emoji: '⚡', color: '#1e293b',
    text: `Lightning is one of nature\'s most spectacular and dangerous phenomena. A single bolt of lightning can reach temperatures of 30,000 degrees Celsius — that is five times hotter than the surface of the Sun. Lightning strikes the Earth about 100 times every second — that is more than 8 million strikes per day.\n\nLightning happens when electrical charge builds up inside storm clouds. The top of the cloud becomes positively charged and the bottom becomes negatively charged. When the difference in charge becomes large enough, a massive spark of electricity jumps between the cloud and the ground — or between two clouds. This spark is the lightning bolt. The heat from the lightning causes the air around it to expand so rapidly that it creates a shockwave — and that shockwave is what we hear as thunder.\n\nYou can estimate how far away lightning is by counting the seconds between seeing the flash and hearing the thunder. Sound travels about one kilometre every three seconds, so if you count nine seconds between the flash and the thunder, the lightning is about three kilometres away.\n\nFloods are the most common and most deadly type of natural disaster in the world. They happen when water covers land that is normally dry — usually because of heavy rain, overflowing rivers, or storm surges along the coast. Flash floods are particularly dangerous because they happen very quickly, giving people little time to escape. In Thailand, flooding is a serious annual concern, particularly during the rainy season from May to October. The devastating floods of 2011, which affected more than 13 million people across Thailand, demonstrated how vulnerable even modern cities can be to extreme rainfall.`,
    vocab: [
      { word: 'Phenomena', definition: 'Remarkable events or occurrences — the plural of phenomenon.' },
      { word: 'Electrical charge', definition: 'A build-up of electricity in an object, which can cause sparks or lightning.' },
      { word: 'Shockwave', definition: 'A wave of pressure caused by an explosion or a very sudden release of energy.' },
      { word: 'Flash flood', definition: 'A sudden, fast-moving flood caused by heavy rain in a short time, often with little warning.' },
    ],
    questions: [
      { n: 7, q: 'Lightning is five times hotter than the Sun and strikes 100 times per second. Which of these facts surprises you more? Why?' },
      { n: 8, q: 'The passage explains how to estimate how far away lightning is. Have you ever tried this? Will you try it next time there is a storm?' },
      { n: 9, q: 'Thailand experienced devastating floods in 2011. Do you think cities can ever be fully protected from flooding? What could be done?' },
    ]
  },
  {
    number: 4, title: 'Is Extreme Weather Getting Worse?', emoji: '🌡️', color: '#0f172a',
    text: `Scientists around the world agree that extreme weather events are becoming more frequent and more severe. The reason is climate change — as the planet warms due to greenhouse gas emissions, the atmosphere holds more energy, and that extra energy makes weather more extreme.\n\nWarmer air can hold more water vapour, which means heavier rainfall and more intense flooding. Warmer oceans provide more energy to hurricanes, making them stronger and more destructive. Heat waves are lasting longer and reaching higher temperatures. Droughts are becoming more severe in some regions, while other regions are experiencing record-breaking rainfall.\n\nThe numbers tell a clear story. According to the World Meteorological Organization, the number of weather-related disasters has increased by five times over the past 50 years. While better warning systems mean fewer people die in each event, the economic damage from extreme weather has increased dramatically — costing the world hundreds of billions of dollars every year.\n\nSo what can be done? Scientists say the most important thing is to reduce greenhouse gas emissions by switching from fossil fuels to clean energy sources like solar, wind, and hydroelectric power. But even if we stopped all emissions today, the warming already in the system means extreme weather will continue to worsen for decades. This means communities also need to adapt — building stronger buildings, improving flood defences, developing better warning systems, and planning cities that can cope with the weather of the future, not just the weather of the past.\n\nUnderstanding extreme weather is no longer just interesting science — it is essential knowledge for everyone living on a warming planet.`,
    vocab: [
      { word: 'Greenhouse gas', definition: 'A gas like carbon dioxide that traps heat in the atmosphere and contributes to global warming.' },
      { word: 'Drought', definition: 'A long period with very little or no rain, causing water shortages and crop failures.' },
      { word: 'Adapt', definition: 'To change the way you do things in order to deal with a new situation.' },
      { word: 'Emissions', definition: 'Gases or substances released into the air, especially from burning fossil fuels.' },
    ],
    questions: [
      { n: 10, q: 'The number of weather disasters has increased five times in 50 years. Does this worry you? What do you think will happen in the next 50 years?' },
      { n: 11, q: 'The passage says we need to both reduce emissions AND adapt to worse weather. Which do you think is more important? Can we do both?' },
      { n: 12, q: 'How do you think extreme weather affects people differently depending on where they live and how much money they have?' },
    ]
  },
]

async function fetchTranslation(text: string, lang: string, type: 'word' | 'question' | 'message'): Promise<string> {
  const systems: Record<string, string> = {
    word: `You are a language learning assistant. Translate this English vocabulary entry to ${lang}. Return ONLY the translated word and a brief explanation in ${lang} (max 25 words). No extra text, no English.`,
    question: `You are a translator. Translate this English discussion question to ${lang}. Return ONLY the translated question. No extra text.`,
    message: `You are a translator. Translate this English text to ${lang}. Return ONLY the translation. No extra text.`,
  }
  const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: systems[type], messages: [{ role: 'user', content: text }] }) })
  const data = await res.json()
  return data.content || ''
}

function TranslateBtn({ text, type, lang, color, onTranslated }: { text: string; type: 'word' | 'question' | 'message'; lang: string; color: string; onTranslated: (t: string) => void }) {
  const [loading, setLoading] = useState(false)
  const [done, setDone] = useState(false)
  const handleClick = async () => { if (lang === 'none' || loading || done) return; setLoading(true); const result = await fetchTranslation(text, lang, type); onTranslated(result); setDone(true); setLoading(false) }
  const isDisabled = lang === 'none'
  return <button onClick={handleClick} disabled={isDisabled || loading || done} title={isDisabled ? 'Select a language above to translate' : done ? 'Translated' : `Translate to ${lang}`} style={{ background: isDisabled ? '#f3f4f6' : done ? '#f0fdf4' : color + '15', color: isDisabled ? '#d1d5db' : done ? '#16a34a' : color, border: `1px solid ${isDisabled ? '#e5e7eb' : done ? '#86efac' : color + '40'}`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: isDisabled ? 'not-allowed' : done ? 'default' : 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s' }}>{loading ? '...' : done ? '✓ 🌍' : '🌍'}</button>
}

function ListenBtn({ text, speed, color }: { text: string; speed: number; color: string }) {
  const [loading, setLoading] = useState(false); const [playing, setPlaying] = useState(false); const sourceRef = useRef<AudioBufferSourceNode | null>(null)
  const handleClick = async () => { if (playing && sourceRef.current) { try { sourceRef.current.stop() } catch {} sourceRef.current = null; setPlaying(false); return }; setLoading(true); try { const res = await fetch('/api/tts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); if (!res.ok) { setLoading(false); return }; const ab = await res.arrayBuffer(); const ac = new AudioContext(); const buf = await ac.decodeAudioData(ab); const src = ac.createBufferSource(); src.buffer = buf; src.playbackRate.value = speed; src.connect(ac.destination); src.onended = () => { setPlaying(false); sourceRef.current = null }; sourceRef.current = src; setLoading(false); setPlaying(true); src.start(0) } catch { setLoading(false); setPlaying(false) } }
  return <button onClick={handleClick} style={{ background: playing ? color : color + '15', color: playing ? 'white' : color, border: `1px solid ${color}40`, padding: '2px 10px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s', display: 'flex', alignItems: 'center', gap: '4px' }}>{loading ? '...' : playing ? '⏹ Stop' : '🔊 Listen'}</button>
}

type Message = { role: 'user' | 'assistant'; content: string; translation?: string }

function ConversationBox({ question, color, translationLang, speed }: { question: string; color: string; translationLang: string; speed: number }) {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [listening, setListening] = useState(false); const [interimText, setInterimText] = useState(''); const [open, setOpen] = useState(false); const recognitionRef = useRef<any>(null); const transcriptRef = useRef('')
  const SYSTEM = `You are a friendly and enthusiastic English conversation partner helping a B1 level student aged 10-12 practise English discussion skills. The reading topic is "Weather and Extreme Storms — Tornadoes, Hurricanes, Lightning and What Causes Them". The current discussion question is: "${question}". Keep every response to 2-3 sentences maximum. Use simple, clear, exciting language for a young learner. Be enthusiastic and curious about dreams! Always end with one fun follow-up question to keep the conversation going. If the student makes a significant grammar error, gently correct it using "💡 Quick tip: ..." at the very end.`
  const sendMessage = async (text: string) => { if (!text.trim() || loading) return; const userMsg: Message = { role: 'user', content: text.trim() }; const updated = [...messages, userMsg]; setMessages(updated); setInput(''); setLoading(true); try { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: SYSTEM, messages: updated.map(m => ({ role: m.role, content: m.content })) }) }); const data = await res.json(); setMessages(prev => [...prev, { role: 'assistant', content: data.content || 'Sorry, try again.' }]) } catch { setMessages(prev => [...prev, { role: 'assistant', content: 'Connection error — please try again.' }]) }; setLoading(false) }
  const setMessageTranslation = (idx: number, translation: string) => { setMessages(prev => prev.map((m, i) => i === idx ? { ...m, translation } : m)) }
  const startVoice = () => { const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!SR) { alert('Voice input requires Chrome browser.'); return }; transcriptRef.current = ''; const r = new SR(); r.lang = 'en-US'; r.continuous = true; r.interimResults = true; r.onstart = () => { setListening(true); setInterimText('') }; r.onresult = (e: any) => { let f = ''; let int = ''; for (let i = 0; i < e.results.length; i++) { if (e.results[i].isFinal) { f += e.results[i][0].transcript + ' ' } else { int += e.results[i][0].transcript } }; transcriptRef.current = f; setInterimText(f + int) }; r.onerror = () => { setListening(false); setInterimText('') }; r.onend = () => { setListening(false); const text = transcriptRef.current.trim() || interimText.trim(); if (text) { setInterimText(''); transcriptRef.current = ''; sendMessage(text) } else { setInterimText(''); transcriptRef.current = '' } }; recognitionRef.current = r; r.start() }
  const stopVoice = () => { recognitionRef.current?.stop() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  if (!open) return <button onClick={() => setOpen(true)} style={{ marginTop: '10px', width: '100%', background: color + '12', border: `2px dashed ${color}40`, borderRadius: '12px', padding: '10px', color, fontWeight: '700', fontSize: '13px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>🤖 Practice answering with AI</button>
  return (
    <div style={{ marginTop: '10px', background: '#f8fafc', borderRadius: '14px', border: `2px solid ${color}30`, overflow: 'hidden' }}>
      <div style={{ background: color, padding: '10px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span style={{ color: 'white', fontWeight: '700', fontSize: '13px' }}>🤖 AI Conversation Partner</span><div style={{ display: 'flex', gap: '6px' }}><button onClick={() => setMessages([])} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>🔄 Reset</button><button onClick={() => setOpen(false)} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>✕ Close</button></div></div>
      {messages.length === 0 && <div style={{ padding: '14px 16px', color: '#6b7280', fontSize: '13px', lineHeight: '1.6', borderBottom: '1px solid #cbd5e1' }}>💡 Type your answer or tap <strong>🎤 Start Recording</strong> — speak your full answer, then tap <strong>⏹ Stop & Send</strong>.</div>}
      {messages.length > 0 && <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px', maxHeight: '320px', overflowY: 'auto' }}>{messages.map((m, i) => (<div key={i} style={{ display: 'flex', gap: '8px', alignItems: 'flex-start', flexDirection: m.role === 'user' ? 'row-reverse' : 'row' }}><div style={{ fontSize: '20px', flexShrink: 0 }}>{m.role === 'user' ? '🧑‍🎓' : '🤖'}</div><div style={{ maxWidth: '80%', display: 'flex', flexDirection: 'column', gap: '4px', alignItems: m.role === 'user' ? 'flex-end' : 'flex-start' }}><div style={{ background: m.role === 'user' ? color : 'white', color: m.role === 'user' ? 'white' : '#374151', padding: '10px 14px', borderRadius: m.role === 'user' ? '16px 4px 16px 16px' : '4px 16px 16px 16px', fontSize: '14px', lineHeight: '1.6', boxShadow: '0 1px 4px rgba(0,0,0,0.08)', border: m.role === 'assistant' ? '1px solid #e5e7eb' : 'none' }}>{m.content}</div>{m.role === 'assistant' && <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}><ListenBtn text={m.content} speed={speed} color={color} />{!m.translation && <TranslateBtn text={m.content} type="message" lang={translationLang} color={color} onTranslated={(t) => setMessageTranslation(i, t)} />}</div>}{m.translation && <div style={{ background: '#f8fafc', border: '1px solid #cbd5e1', borderRadius: '10px', padding: '8px 12px', fontSize: '13px', color: '#374151', lineHeight: '1.5' }}><span style={{ color: color, fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>🌍 Translation</span>{m.translation}</div>}</div></div>))}{loading && <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}><span style={{ fontSize: '20px' }}>🤖</span><div style={{ background: 'white', padding: '10px 14px', borderRadius: '4px 16px 16px 16px', fontSize: '14px', color: '#9ca3af', border: '1px solid #e5e7eb' }}>Thinking...</div></div>}</div>}
      <div style={{ padding: '12px 16px', borderTop: '1px solid #cbd5e1', display: 'flex', gap: '8px', alignItems: 'flex-end' }}><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(input) } }} placeholder="Type your answer here..." rows={2} style={{ flex: 1, padding: '10px 12px', borderRadius: '10px', border: '2px solid #e5e7eb', fontSize: '14px', outline: 'none', resize: 'none', fontFamily: 'inherit', lineHeight: '1.5' }} /><div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}><button onClick={listening ? stopVoice : startVoice} style={{ background: listening ? '#ef4444' : '#22c55e', color: 'white', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: listening ? '0 0 0 4px rgba(239,68,68,0.3)' : 'none', transition: 'all 0.2s' }}>{listening ? '⏹' : '🎤'}</button><button onClick={() => sendMessage(input)} disabled={!input.trim() || loading} style={{ background: input.trim() && !loading ? color : '#e5e7eb', color: input.trim() && !loading ? 'white' : '#9ca3af', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: input.trim() && !loading ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>➤</button></div></div>
      {!listening && <div style={{ padding: '4px 16px 10px', display: 'flex', gap: '16px' }}><span style={{ color: '#9ca3af', fontSize: '11px' }}>🎤 = Start recording</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>⏹ = Stop & send</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>➤ = Send typed</span></div>}
      {listening && <div style={{ padding: '10px 16px 14px', borderTop: '1px solid #fee2e2', background: '#fef2f2' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ display: 'inline-block', width: '10px', height: '10px', borderRadius: '50%', background: '#ef4444', animation: 'pulse 1s infinite', flexShrink: 0 }} /><span style={{ color: '#ef4444', fontSize: '12px', fontWeight: '700' }}>Recording... speak your full answer</span></div><button onClick={stopVoice} style={{ background: '#ef4444', color: 'white', border: 'none', padding: '6px 16px', borderRadius: '10px', fontWeight: '800', fontSize: '13px', cursor: 'pointer', boxShadow: '0 2px 8px rgba(239,68,68,0.4)' }}>⏹ Stop & Send</button></div><div style={{ background: 'white', borderRadius: '10px', padding: '10px 14px', fontSize: '14px', color: interimText ? '#374151' : '#9ca3af', lineHeight: '1.6', border: '1px solid #fca5a5', fontStyle: 'italic', minHeight: '40px' }}>{interimText || 'Waiting for speech...'}{interimText && <span style={{ display: 'inline-block', width: '2px', height: '16px', background: '#ef4444', marginLeft: '2px', verticalAlign: 'middle', animation: 'pulse 1s infinite' }} />}</div></div>}
    </div>
  )
}

export default function ExtremeWeatherPage() {
  const [speed, setSpeed] = useState(0.9); const [translationLang, setTranslationLang] = useState('none'); const [selectedText, setSelectedText] = useState<string | null>(null); const [lookupDef, setLookupDef] = useState(''); const [lookupTranslation, setLookupTranslation] = useState(''); const [lookupLoading, setLookupLoading] = useState(false); const [vocabTranslations, setVocabTranslations] = useState<Record<string, string>>({}); const [questionTranslations, setQuestionTranslations] = useState<Record<number, string>>({})
  useEffect(() => { const handleSelection = () => { const sel = window.getSelection(); if (!sel) return; const text = sel.toString().trim().replace(/\s+/g, ' '); if (!text || text.split(' ').length > 6) return; const anchor = sel.anchorNode?.parentElement; if (!anchor?.closest('[data-passage]')) return; handleLookup(text) }; document.addEventListener('mouseup', handleSelection); document.addEventListener('touchend', handleSelection); return () => { document.removeEventListener('mouseup', handleSelection); document.removeEventListener('touchend', handleSelection) } }, [translationLang])
  const handleLookup = async (text: string) => { if (!text || text.length < 2) return; setSelectedText(text); setLookupDef(''); setLookupTranslation(''); setLookupLoading(true); speakWord(text); const isPhrase = text.includes(' '); try { if (translationLang === 'none') { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: isPhrase ? `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 20 words) explaining what the phrase means. No extra text.` : `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 15 words) defining this word. No extra text.`, messages: [{ role: 'user', content: isPhrase ? `What does "${text}" mean?` : `Define: "${text}"` }] }) }); const data = await res.json(); setLookupDef(data.content || 'No definition found.') } else { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: `You are a language learning assistant for young B1 English students. Respond ONLY with valid JSON (no markdown, no backticks): {"definition": "one simple English sentence max 15 words", "translation": "the word/phrase in ${translationLang} with a brief explanation in ${translationLang}, max 25 words"}`, messages: [{ role: 'user', content: `Word or phrase: "${text}"` }] }) }); const data = await res.json(); try { const parsed = JSON.parse(data.content); setLookupDef(parsed.definition || 'No definition found.'); setLookupTranslation(parsed.translation || '') } catch { setLookupDef(data.content || 'No definition found.'); setLookupTranslation('') } } } catch { setLookupDef('Could not load definition.') }; setLookupLoading(false) }
  function speakText(text: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const sentences = text.match(/[^.!?]+[.!?]+/g) || [text]; sentences.forEach(s => { const u = new SpeechSynthesisUtterance(s.trim()); u.lang = 'en-GB'; u.rate = speed; u.pitch = 1; window.speechSynthesis.speak(u) }) }
  function speakWord(word: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(word); u.lang = 'en-GB'; u.rate = 0.85; u.pitch = 1; window.speechSynthesis.speak(u) }
  function stopAudio() { if (typeof window === 'undefined') return; window.speechSynthesis.cancel() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  return (
    <main style={{ background: '#f4f6fa', minHeight: '100vh' }}>
      <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}} @keyframes slideUp{from{transform:translateY(100%);opacity:0}to{transform:translateY(0);opacity:1}}`}</style>
      <section style={{ background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%)', padding: '56px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <Link href="/esl-resources/reading-comprehension/b1" style={{ color: 'rgba(255,255,255,0.6)', textDecoration: 'none', fontSize: '14px', display: 'inline-block', marginBottom: '20px' }}>← B1 Reading Comprehension</Link>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', flexWrap: 'wrap' }}>
            <div style={{ fontSize: '72px', flexShrink: 0 }}>⛈️</div>
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '12px' }}>
                <span style={{ background: '#475569', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>B1 Intermediate</span>
                <span style={{ background: 'rgba(99,102,241,0.5)', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>Nature & Animals</span>
                <span style={{ background: 'rgba(255,255,255,0.15)', color: 'white', fontSize: '12px', fontWeight: '600', padding: '4px 12px', borderRadius: '20px' }}>4 Parts · 12 Questions</span>
              </div>
              <h1 style={{ color: 'white', fontSize: '32px', fontWeight: 'bold', margin: '0 0 8px', lineHeight: '1.3' }}>Weather and Extreme Storms</h1>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '16px', margin: 0, lineHeight: '1.6' }}>Tornadoes that tear buildings apart, hurricanes bigger than entire countries, and lightning bolts five times hotter than the Sun — how does extreme weather work, and is it getting worse?</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '20px', marginTop: '28px', flexWrap: 'wrap' }}>{[{ icon: '📄', label: '4 reading parts' }, { icon: '💬', label: '12 discussion questions' }, { icon: '📚', label: '16 vocabulary words' }, { icon: '✍️', label: 'Highlight any text' }, { icon: '🌍', label: 'Multi-language lookup' }, { icon: '🤖', label: 'AI conversation partner' }].map(s => <div key={s.label} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'rgba(255,255,255,0.75)', fontSize: '13px' }}><span>{s.icon}</span> {s.label}</div>)}</div>
        </div>
      </section>
      <section style={{ background: 'white', borderBottom: '1px solid #eee', padding: '14px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', alignItems: 'center', marginBottom: '10px' }}><span style={{ color: '#888', fontSize: '12px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>How to use:</span>{['🔊 Play passage aloud', '✍️ Highlight any text for lookup', '🌍 Translate vocab, questions & AI answers', '🤖 Practice with AI'].map((step, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#555', fontSize: '13px' }}><span style={{ background: '#475569', color: 'white', width: '18px', height: '18px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '10px', fontWeight: 'bold', flexShrink: 0 }}>{i + 1}</span>{step}</div>)}</div>
          <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap', alignItems: 'center' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🔊 Speed:</span>{SPEEDS.map(s => <button key={s.value} onClick={() => setSpeed(s.value)} style={{ padding: '4px 12px', borderRadius: '20px', border: '2px solid', borderColor: speed === s.value ? '#475569' : '#e5e7eb', background: speed === s.value ? '#475569' : 'white', color: speed === s.value ? 'white' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', transition: 'all 0.2s' }}>{s.label}</button>)}</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🌍 Translate to:</span><select value={translationLang} onChange={e => { setTranslationLang(e.target.value); setVocabTranslations({}); setQuestionTranslations({}) }} style={{ padding: '5px 12px', borderRadius: '20px', border: '2px solid', borderColor: translationLang !== 'none' ? '#475569' : '#e5e7eb', background: translationLang !== 'none' ? '#f8fafc' : 'white', color: translationLang !== 'none' ? '#0f172a' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', outline: 'none' }}>{LANGUAGES.map(l => <option key={l.value} value={l.value}>{l.label}</option>)}</select></div>
          </div>
        </div>
      </section>
      <div style={{ maxWidth: '860px', margin: '0 auto', padding: '32px 24px', display: 'flex', flexDirection: 'column', gap: '28px' }}>
        {PARTS.map(part => (
          <div key={part.number} style={{ background: 'white', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 2px 12px rgba(0,0,0,0.07)' }}>
            <div style={{ background: `linear-gradient(135deg, ${part.color}22, ${part.color}08)`, borderLeft: `5px solid ${part.color}`, padding: '20px 24px', display: 'flex', gap: '14px', alignItems: 'center', flexWrap: 'wrap' }}>
              <div style={{ background: part.color, color: 'white', width: '36px', height: '36px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '16px', flexShrink: 0 }}>{part.number}</div>
              <div style={{ flex: 1 }}><div style={{ color: part.color, fontSize: '11px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '2px' }}>Part {part.number}</div><h2 data-passage="true" style={{ color: '#1a1a2e', fontSize: '18px', fontWeight: 'bold', margin: 0, userSelect: 'text', cursor: 'text' }}>{part.emoji} {part.title}</h2></div>
              <div style={{ display: 'flex', gap: '8px', flexShrink: 0 }}><button onClick={() => speakText(part.text.replace(/\n\n/g, ' '))} style={{ background: part.color, color: 'white', border: 'none', padding: '8px 16px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', boxShadow: `0 3px 10px ${part.color}40` }}>▶ Play Passage</button><button onClick={stopAudio} style={{ background: 'white', color: '#6b7280', border: '2px solid #e5e7eb', padding: '8px 12px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer' }}>⏹ Stop</button></div>
            </div>
            <div style={{ background: '#f8fafc', padding: '8px 28px', borderBottom: '1px solid #cbd5e1' }}><span style={{ color: '#0f172a', fontSize: '12px', fontWeight: '600' }}>✍️ Highlight any word or phrase to hear it and see its meaning{translationLang !== 'none' && <span style={{ color: '#475569' }}> + {currentLang?.label} translation</span>}</span></div>
            <div data-passage="true" style={{ padding: '24px 28px 20px', userSelect: 'text', cursor: 'text' }}>{part.text.split('\n\n').map((para, i) => <p key={i} style={{ color: '#374151', fontSize: '16px', lineHeight: '1.85', margin: i === 0 ? '0 0 18px' : '0', fontFamily: 'Georgia, serif' }}>{para}</p>)}</div>
            <div style={{ margin: '0 28px 24px', background: part.color + '08', border: `1px solid ${part.color}25`, borderRadius: '14px', overflow: 'hidden' }}>
              <div style={{ background: part.color + '18', padding: '12px 16px', display: 'flex', alignItems: 'center', gap: '8px', borderBottom: `1px solid ${part.color}20` }}><span style={{ fontSize: '16px' }}>📚</span><span style={{ color: part.color, fontWeight: 'bold', fontSize: '13px', textTransform: 'uppercase', letterSpacing: '1px' }}>Vocabulary — Part {part.number}</span></div>
              <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>{part.vocab.map((v, i) => { const vKey = `${part.number}-${v.word}`; return (<div key={v.word} style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', paddingBottom: i < part.vocab.length - 1 ? '10px' : '0', borderBottom: i < part.vocab.length - 1 ? `1px solid ${part.color}15` : 'none' }}><div style={{ background: part.color, color: 'white', width: '22px', height: '22px', borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '11px', flexShrink: 0, marginTop: '2px' }}>{i + 1}</div><div style={{ flex: 1 }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '3px', flexWrap: 'wrap' }}><span data-passage="true" style={{ fontWeight: 'bold', color: '#1a1a2e', fontSize: '15px', userSelect: 'text', cursor: 'text' }}>{v.word}</span><button onClick={() => speakWord(v.word)} style={{ background: part.color + '15', color: part.color, border: `1px solid ${part.color}30`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0 }}>🔊</button><TranslateBtn text={`Word: "${v.word}"\nDefinition: "${v.definition}"`} type="word" lang={translationLang} color={part.color} onTranslated={(t) => setVocabTranslations(prev => ({ ...prev, [vKey]: t }))} />{translationLang === 'none' && <span style={{ color: '#d1d5db', fontSize: '11px' }}>← select a language to translate</span>}</div><span data-passage="true" style={{ color: '#6b7280', fontSize: '14px', lineHeight: '1.5', userSelect: 'text', cursor: 'text' }}>{v.definition}</span>{vocabTranslations[vKey] && <div style={{ marginTop: '6px', background: '#f8fafc', border: '1px solid #cbd5e1', borderRadius: '8px', padding: '8px 12px' }}><span style={{ color: '#0f172a', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: '#374151', fontSize: '14px', lineHeight: '1.5' }}>{vocabTranslations[vKey]}</span></div>}</div></div>) })}</div>
            </div>
            <div style={{ background: '#1a1a2e', padding: '20px 28px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}><span style={{ fontSize: '18px' }}>💬</span><span style={{ color: '#94a3b8', fontWeight: 'bold', fontSize: '14px', textTransform: 'uppercase', letterSpacing: '1px' }}>Discussion Questions</span></div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>{part.questions.map(q => (<div key={q.n}><div style={{ display: 'flex', gap: '14px', alignItems: 'flex-start' }}><div style={{ background: part.color, color: 'white', width: '28px', height: '28px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '13px', flexShrink: 0, marginTop: '1px' }}>{q.n}</div><div style={{ flex: 1 }}><p data-passage="true" style={{ color: 'rgba(255,255,255,0.88)', fontSize: '15px', lineHeight: '1.6', margin: '0 0 6px', userSelect: 'text', cursor: 'text' }}>{q.q}</p><div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><TranslateBtn text={q.q} type="question" lang={translationLang} color={part.color} onTranslated={(t) => setQuestionTranslations(prev => ({ ...prev, [q.n]: t }))} />{translationLang === 'none' && <span style={{ color: '#4b5563', fontSize: '11px' }}>← select a language to translate</span>}</div>{questionTranslations[q.n] && <div style={{ marginTop: '8px', background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.3)', borderRadius: '10px', padding: '10px 14px' }}><span style={{ color: '#94a3b8', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: 'rgba(255,255,255,0.9)', fontSize: '14px', lineHeight: '1.6' }}>{questionTranslations[q.n]}</span></div>}</div></div><div style={{ marginLeft: '42px' }}><ConversationBox question={q.q} color={part.color} translationLang={translationLang} speed={speed} /></div></div>))}</div>
            </div>
          </div>
        ))}
        <div style={{ textAlign: 'center', paddingBottom: selectedText ? '140px' : '16px' }}><Link href="/esl-resources/reading-comprehension/b1" style={{ color: '#475569', textDecoration: 'none', fontWeight: 'bold', fontSize: '14px' }}>← Back to B1 Reading Comprehension</Link></div>
      </div>
      {selectedText && <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 200, animation: 'slideUp 0.25s ease' }}><div style={{ maxWidth: '860px', margin: '0 auto', background: 'white', borderRadius: '20px 20px 0 0', padding: '20px 24px 32px', boxShadow: '0 -8px 32px rgba(0,0,0,0.2)', border: '2px solid #cbd5e1', borderBottom: 'none' }}><div style={{ width: '40px', height: '4px', background: '#e5e7eb', borderRadius: '4px', margin: '0 auto 16px' }} /><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}><span style={{ fontSize: '22px', fontWeight: '900', color: '#1a1a2e', fontFamily: 'Georgia, serif' }}>"{selectedText}"</span><button onClick={() => speakWord(selectedText)} style={{ background: '#f8fafc', color: '#0f172a', border: '2px solid #cbd5e1', padding: '6px 14px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', flexShrink: 0 }}>🔊 Hear it</button></div><button onClick={() => setSelectedText(null)} style={{ background: '#f3f4f6', border: 'none', width: '32px', height: '32px', borderRadius: '8px', cursor: 'pointer', fontSize: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#6b7280', flexShrink: 0, marginLeft: '12px' }}>✕</button></div>{lookupLoading ? <div style={{ background: '#f8fafc', borderRadius: '12px', padding: '14px 18px', border: '1px solid #cbd5e1', color: '#9ca3af', fontSize: '15px' }}>{translationLang !== 'none' ? `Looking up definition and ${currentLang?.label} translation...` : 'Looking up...'}</div> : <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}><div style={{ background: '#f8fafc', borderRadius: '12px', padding: '14px 18px', border: '1px solid #cbd5e1' }}><div style={{ color: '#0f172a', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>📖 English Definition</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupDef}</span></div>{translationLang !== 'none' && lookupTranslation && <div style={{ background: '#f8fafc', borderRadius: '12px', padding: '14px 18px', border: '1px solid #94a3b8' }}><div style={{ color: '#1e293b', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>{currentLang?.label} Translation</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupTranslation}</span></div>}</div>}</div></div>}
    </main>
  )
}
