export const questionBank: Record<string, { q: string; options: string[]; answer: string }[]> = {
  'P1-P2': [
    { q: 'What colour is a ripe banana?', options: ['green', 'red', 'yellow', 'blue'], answer: 'yellow' },
    { q: 'How many legs does a cat have?', options: ['2', '3', '4', '6'], answer: '4' },
    { q: 'What do bees make?', options: ['milk', 'honey', 'butter', 'juice'], answer: 'honey' },
    { q: 'Which is the biggest animal on land?', options: ['horse', 'dog', 'elephant', 'mouse'], answer: 'elephant' },
    { q: 'What do fish live in?', options: ['trees', 'sand', 'air', 'water'], answer: 'water' },
    { q: 'How many days are in a week?', options: ['5', '6', '7', '8'], answer: '7' },
    { q: 'What colour is the sky on a sunny day?', options: ['green', 'red', 'blue', 'yellow'], answer: 'blue' },
    { q: 'Which animal is the fastest on land?', options: ['horse', 'lion', 'dog', 'cheetah'], answer: 'cheetah' },
    { q: 'What do we call baby dogs?', options: ['kittens', 'cubs', 'chicks', 'puppies'], answer: 'puppies' },
    { q: 'How many months are in a year?', options: ['10', '11', '12', '13'], answer: '12' },
    { q: 'What is the biggest ocean?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], answer: 'Pacific' },
    { q: 'Which animal says "moo"?', options: ['dog', 'cat', 'duck', 'cow'], answer: 'cow' },
    { q: 'What do caterpillars turn into?', options: ['fish', 'bees', 'butterflies', 'frogs'], answer: 'butterflies' },
    { q: 'How many legs does a spider have?', options: ['4', '6', '8', '10'], answer: '8' },
    { q: 'What colour is a strawberry?', options: ['yellow', 'blue', 'green', 'red'], answer: 'red' },
    { q: 'Which is the tallest animal?', options: ['horse', 'elephant', 'camel', 'giraffe'], answer: 'giraffe' },
    { q: 'What do plants need to grow?', options: ['ice', 'darkness', 'fire', 'sunlight'], answer: 'sunlight' },
    { q: 'Where do penguins live?', options: ['Africa', 'Asia', 'South America', 'Antarctica'], answer: 'Antarctica' },
    { q: 'What do cows give us to drink?', options: ['eggs', 'honey', 'milk', 'wool'], answer: 'milk' },
    { q: 'Which bird cannot fly?', options: ['eagle', 'parrot', 'sparrow', 'penguin'], answer: 'penguin' },
    { q: 'What is frozen water called?', options: ['steam', 'fog', 'rain', 'ice'], answer: 'ice' },
    { q: 'How many colours are in a rainbow?', options: ['5', '6', '7', '8'], answer: '7' },
    { q: 'What do we call a group of fish?', options: ['pack', 'flock', 'herd', 'school'], answer: 'school' },
    { q: 'Which animal is known as man\'s best friend?', options: ['cat', 'horse', 'rabbit', 'dog'], answer: 'dog' },
    { q: 'Which country is famous for the Eiffel Tower?', options: ['UK', 'Germany', 'Spain', 'France'], answer: 'France' },
    { q: 'What do birds use to fly?', options: ['legs', 'fins', 'arms', 'wings'], answer: 'wings' },
    { q: 'How many sides does a triangle have?', options: ['2', '3', '4', '5'], answer: '3' },
    { q: 'What is the opposite of hot?', options: ['warm', 'cool', 'wet', 'cold'], answer: 'cold' },
    { q: 'What is the most popular sport in the world?', options: ['basketball', 'tennis', 'cricket', 'football'], answer: 'football' },
    { q: 'How many letters are in the English alphabet?', options: ['24', '25', '26', '27'], answer: '26' },
    { q: 'What does a thermometer measure?', options: ['time', 'weight', 'speed', 'temperature'], answer: 'temperature' },
    { q: 'Which planet is closest to the Sun?', options: ['Earth', 'Venus', 'Mars', 'Mercury'], answer: 'Mercury' },
    { q: 'What is the baby of a lion called?', options: ['puppy', 'kitten', 'cub', 'foal'], answer: 'cub' },
    { q: 'Which fruit is yellow and shaped like a crescent?', options: ['apple', 'mango', 'orange', 'banana'], answer: 'banana' },
    { q: 'What sound does a snake make?', options: ['bark', 'roar', 'moo', 'hiss'], answer: 'hiss' },
    { q: 'How many wheels does a car usually have?', options: ['2', '3', '4', '6'], answer: '4' },
    { q: 'What do we call the home of a bird?', options: ['den', 'burrow', 'nest', 'hive'], answer: 'nest' },
    { q: 'Which season has snow in cold countries?', options: ['spring', 'summer', 'autumn', 'winter'], answer: 'winter' },
    { q: 'What do we use to cut paper?', options: ['pen', 'ruler', 'scissors', 'eraser'], answer: 'scissors' },
    { q: 'Which is the biggest star we can see from Earth?', options: ['Moon', 'Venus', 'Sun', 'Mars'], answer: 'Sun' },
  ],
  'P3-P4': [
    { q: 'What is the capital of Thailand?', options: ['Chiang Mai', 'Phuket', 'Pattaya', 'Bangkok'], answer: 'Bangkok' },
    { q: 'Which is the longest river in the world?', options: ['Amazon', 'Mississippi', 'Yangtze', 'Nile'], answer: 'Nile' },
    { q: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], answer: '8' },
    { q: 'What is the hardest natural substance on Earth?', options: ['gold', 'iron', 'quartz', 'diamond'], answer: 'diamond' },
    { q: 'What is the capital of Japan?', options: ['Osaka', 'Kyoto', 'Hiroshima', 'Tokyo'], answer: 'Tokyo' },
    { q: 'What gas do we breathe in?', options: ['carbon dioxide', 'nitrogen', 'hydrogen', 'oxygen'], answer: 'oxygen' },
    { q: 'Which animal is known as the King of the Jungle?', options: ['tiger', 'elephant', 'leopard', 'lion'], answer: 'lion' },
    { q: 'What is the largest country in the world by area?', options: ['Canada', 'USA', 'China', 'Russia'], answer: 'Russia' },
    { q: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Brisbane', 'Canberra'], answer: 'Canberra' },
    { q: 'What is the currency of Japan?', options: ['won', 'yuan', 'baht', 'yen'], answer: 'yen' },
    { q: 'How many continents are there?', options: ['5', '6', '7', '8'], answer: '7' },
    { q: 'What is the largest animal on Earth?', options: ['elephant', 'giraffe', 'polar bear', 'blue whale'], answer: 'blue whale' },
    { q: 'Which country invented pizza?', options: ['France', 'Spain', 'Greece', 'Italy'], answer: 'Italy' },
    { q: 'What is the fastest land animal?', options: ['horse', 'lion', 'leopard', 'cheetah'], answer: 'cheetah' },
    { q: 'Which planet is known as the Red Planet?', options: ['Jupiter', 'Venus', 'Saturn', 'Mars'], answer: 'Mars' },
    { q: 'How many strings does a standard guitar have?', options: ['4', '5', '6', '8'], answer: '6' },
    { q: 'What is the capital of the USA?', options: ['New York', 'Los Angeles', 'Chicago', 'Washington D.C.'], answer: 'Washington D.C.' },
    { q: 'Which is the tallest mountain in the world?', options: ['K2', 'Kilimanjaro', 'Mont Blanc', 'Everest'], answer: 'Everest' },
    { q: 'How many legs does an insect have?', options: ['4', '6', '8', '10'], answer: '6' },
    { q: 'Which sport uses a shuttlecock?', options: ['tennis', 'squash', 'ping pong', 'badminton'], answer: 'badminton' },
    { q: 'What is the chemical formula for water?', options: ['CO2', 'O2', 'NaCl', 'H2O'], answer: 'H2O' },
    { q: 'How many players are in a football (soccer) team?', options: ['9', '10', '11', '12'], answer: '11' },
    { q: 'Which bird is famous for its colourful tail?', options: ['flamingo', 'parrot', 'eagle', 'peacock'], answer: 'peacock' },
    { q: 'What do we call a group of lions?', options: ['pack', 'herd', 'flock', 'pride'], answer: 'pride' },
    { q: 'What is the capital of France?', options: ['Brussels', 'Madrid', 'Rome', 'Paris'], answer: 'Paris' },
    { q: 'What is the boiling point of water?', options: ['90°C', '95°C', '100°C', '105°C'], answer: '100°C' },
    { q: 'Which planet has rings around it?', options: ['Jupiter', 'Mars', 'Venus', 'Saturn'], answer: 'Saturn' },
    { q: 'How many sides does a hexagon have?', options: ['5', '6', '7', '8'], answer: '6' },
    { q: 'Which is the world\'s largest fish?', options: ['great white shark', 'blue marlin', 'tuna', 'whale shark'], answer: 'whale shark' },
    { q: 'How many seconds are in a minute?', options: ['30', '50', '60', '100'], answer: '60' },
    { q: 'What fruit is known as the "king of fruits" in Southeast Asia?', options: ['mango', 'papaya', 'pineapple', 'durian'], answer: 'durian' },
    { q: 'How many bones are in the adult human body?', options: ['106', '206', '306', '406'], answer: '206' },
    { q: 'What do we call the study of stars?', options: ['astrology', 'astrophysics', 'geology', 'astronomy'], answer: 'astronomy' },
    { q: 'What is the capital of the UK?', options: ['Manchester', 'Birmingham', 'Edinburgh', 'London'], answer: 'London' },
    { q: 'What is the national sport of Japan?', options: ['judo', 'karate', 'baseball', 'sumo'], answer: 'sumo' },
    { q: 'Which is the smallest continent?', options: ['Europe', 'Antarctica', 'South America', 'Australia'], answer: 'Australia' },
    { q: 'How many hours are in a day?', options: ['12', '20', '24', '48'], answer: '24' },
    { q: 'What is the world\'s most spoken language by native speakers?', options: ['English', 'Spanish', 'Hindi', 'Mandarin Chinese'], answer: 'Mandarin Chinese' },
    { q: 'Which country is famous for the Great Wall?', options: ['Japan', 'Korea', 'Vietnam', 'China'], answer: 'China' },
    { q: 'What is the currency of Thailand?', options: ['dollar', 'yen', 'euro', 'baht'], answer: 'baht' },
  ],
  'P5-P6': [
    { q: 'What is the capital of Brazil?', options: ['São Paulo', 'Rio de Janeiro', 'Buenos Aires', 'Brasília'], answer: 'Brasília' },
    { q: 'How many elements are in the periodic table?', options: ['108', '112', '118', '124'], answer: '118' },
    { q: 'What year did World War II end?', options: ['1943', '1944', '1945', '1946'], answer: '1945' },
    { q: 'Which is the largest organ of the human body?', options: ['heart', 'brain', 'liver', 'skin'], answer: 'skin' },
    { q: 'What is the speed of light (approx)?', options: ['3,000 km/s', '30,000 km/s', '300,000 km/s', '3,000,000 km/s'], answer: '300,000 km/s' },
    { q: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Rembrandt', 'Picasso', 'Leonardo da Vinci'], answer: 'Leonardo da Vinci' },
    { q: 'Which country has the longest coastline?', options: ['Norway', 'Russia', 'Australia', 'Canada'], answer: 'Canada' },
    { q: 'Who invented the telephone?', options: ['Thomas Edison', 'Nikola Tesla', 'James Watt', 'Alexander Graham Bell'], answer: 'Alexander Graham Bell' },
    { q: 'What is the capital of South Korea?', options: ['Busan', 'Incheon', 'Daegu', 'Seoul'], answer: 'Seoul' },
    { q: 'Who was the first person to walk on the Moon?', options: ['Buzz Aldrin', 'Yuri Gagarin', 'Alan Shepard', 'Neil Armstrong'], answer: 'Neil Armstrong' },
    { q: 'What is the world\'s largest hot desert?', options: ['Arabian', 'Gobi', 'Kalahari', 'Sahara'], answer: 'Sahara' },
    { q: 'Which mountain range contains Mount Everest?', options: ['Alps', 'Andes', 'Rockies', 'Himalayas'], answer: 'Himalayas' },
    { q: 'What year did the Titanic sink?', options: ['1910', '1911', '1912', '1913'], answer: '1912' },
    { q: 'Which is the world\'s smallest country?', options: ['Monaco', 'San Marino', 'Liechtenstein', 'Vatican City'], answer: 'Vatican City' },
    { q: 'How many chambers does the human heart have?', options: ['2', '3', '4', '5'], answer: '4' },
    { q: 'What is the capital of Canada?', options: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], answer: 'Ottawa' },
    { q: 'Which organ in the body produces insulin?', options: ['liver', 'kidney', 'spleen', 'pancreas'], answer: 'pancreas' },
    { q: 'What is the largest planet in our solar system?', options: ['Saturn', 'Neptune', 'Uranus', 'Jupiter'], answer: 'Jupiter' },
    { q: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Ag', 'Au'], answer: 'Au' },
    { q: 'Who discovered penicillin?', options: ['Louis Pasteur', 'Edward Jenner', 'Joseph Lister', 'Alexander Fleming'], answer: 'Alexander Fleming' },
    { q: 'What is the most common blood type?', options: ['A', 'B', 'AB', 'O'], answer: 'O' },
    { q: 'Which gas makes up most of Earth\'s atmosphere?', options: ['oxygen', 'carbon dioxide', 'hydrogen', 'nitrogen'], answer: 'nitrogen' },
    { q: 'What is the world\'s largest rainforest?', options: ['Congo', 'Daintree', 'Tongass', 'Amazon'], answer: 'Amazon' },
    { q: 'What year did the Berlin Wall fall?', options: ['1987', '1988', '1989', '1990'], answer: '1989' },
    { q: 'What is the chemical symbol for silver?', options: ['Si', 'Au', 'Sr', 'Ag'], answer: 'Ag' },
    { q: 'What is the capital of Egypt?', options: ['Alexandria', 'Luxor', 'Giza', 'Cairo'], answer: 'Cairo' },
    { q: 'How many zeros are in one billion?', options: ['6', '7', '8', '9'], answer: '9' },
    { q: 'Which country is both a continent and a country?', options: ['Brazil', 'Russia', 'USA', 'Australia'], answer: 'Australia' },
    { q: 'What is the tallest building in the world?', options: ['Eiffel Tower', 'Empire State Building', 'Shanghai Tower', 'Burj Khalifa'], answer: 'Burj Khalifa' },
    { q: 'What is the currency of India?', options: ['dollar', 'baht', 'yen', 'rupee'], answer: 'rupee' },
    { q: 'What is the approximate population of Earth?', options: ['5 billion', '6 billion', '7 billion', '8 billion'], answer: '8 billion' },
    { q: 'Who invented the printing press?', options: ['Isaac Newton', 'Galileo', 'Copernicus', 'Johannes Gutenberg'], answer: 'Johannes Gutenberg' },
    { q: 'Which country is home to the Taj Mahal?', options: ['Pakistan', 'Bangladesh', 'Nepal', 'India'], answer: 'India' },
    { q: 'How many players are on a basketball team?', options: ['4', '5', '6', '7'], answer: '5' },
    { q: 'What is the capital of Nigeria?', options: ['Lagos', 'Accra', 'Nairobi', 'Abuja'], answer: 'Abuja' },
    { q: 'Which country has won the most FIFA World Cups?', options: ['Germany', 'Argentina', 'Italy', 'Brazil'], answer: 'Brazil' },
    { q: 'What does DNA stand for?', options: ['Dinitrogen Acid', 'Diribose Nucleic Acid', 'Deoxynitric Acid', 'Deoxyribonucleic Acid'], answer: 'Deoxyribonucleic Acid' },
    { q: 'Who wrote Romeo and Juliet?', options: ['Dickens', 'Austen', 'Twain', 'Shakespeare'], answer: 'Shakespeare' },
    { q: 'What is the boiling point of water in Fahrenheit?', options: ['100°F', '180°F', '212°F', '250°F'], answer: '212°F' },
    { q: 'Which is the world\'s most visited country?', options: ['USA', 'China', 'Spain', 'France'], answer: 'France' },
  ],
  'M1-M3': [
    { q: 'What year did India gain independence?', options: ['1945', '1946', '1947', '1948'], answer: '1947' },
    { q: 'Who developed the theory of relativity?', options: ['Isaac Newton', 'Niels Bohr', 'Max Planck', 'Albert Einstein'], answer: 'Albert Einstein' },
    { q: 'Which country is the world\'s largest producer of coffee?', options: ['Colombia', 'Vietnam', 'Ethiopia', 'Brazil'], answer: 'Brazil' },
    { q: 'What was the first country to give women the right to vote?', options: ['USA', 'UK', 'France', 'New Zealand'], answer: 'New Zealand' },
    { q: 'What is the atomic number of carbon?', options: ['4', '5', '6', '7'], answer: '6' },
    { q: 'What year was the United Nations founded?', options: ['1943', '1944', '1945', '1946'], answer: '1945' },
    { q: 'Who was the first female Nobel Prize winner?', options: ['Rosalind Franklin', 'Ada Lovelace', 'Florence Nightingale', 'Marie Curie'], answer: 'Marie Curie' },
    { q: 'What is the approximate distance from Earth to the Moon?', options: ['284,400 km', '384,400 km', '484,400 km', '584,400 km'], answer: '384,400 km' },
    { q: 'What is GDP?', options: ['total government debt', 'total value of exports', 'total tax revenue', 'total value of goods and services produced'], answer: 'total value of goods and services produced' },
    { q: 'What is the capital of Argentina?', options: ['Lima', 'Santiago', 'Montevideo', 'Buenos Aires'], answer: 'Buenos Aires' },
    { q: 'What is the speed of sound in air at room temperature?', options: ['143 m/s', '243 m/s', '343 m/s', '443 m/s'], answer: '343 m/s' },
    { q: 'Who invented the World Wide Web?', options: ['Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'Tim Berners-Lee'], answer: 'Tim Berners-Lee' },
    { q: 'What is the Gini coefficient a measure of?', options: ['economic growth', 'military strength', 'political freedom', 'income inequality'], answer: 'income inequality' },
    { q: 'Which element has the highest melting point?', options: ['gold', 'iron', 'platinum', 'tungsten'], answer: 'tungsten' },
    { q: 'What is the powerhouse of the cell?', options: ['nucleus', 'ribosome', 'cell membrane', 'mitochondria'], answer: 'mitochondria' },
    { q: 'What country has the most natural lakes?', options: ['Russia', 'USA', 'Finland', 'Canada'], answer: 'Canada' },
    { q: 'What is the pH of pure water?', options: ['5', '6', '7', '8'], answer: '7' },
    { q: 'What year did the First World War begin?', options: ['1912', '1913', '1914', '1915'], answer: '1914' },
    { q: 'How many official languages does South Africa have?', options: ['8', '9', '10', '11'], answer: '11' },
    { q: 'What is the capital of Pakistan?', options: ['Karachi', 'Lahore', 'Peshawar', 'Islamabad'], answer: 'Islamabad' },
    { q: 'Which country was first to land humans on the Moon?', options: ['Russia', 'China', 'UK', 'USA'], answer: 'USA' },
    { q: 'What is the Fibonacci sequence?', options: ['1,2,4,8,16', '2,4,6,8,10', '1,2,3,5,7', '1,1,2,3,5,8'], answer: '1,1,2,3,5,8' },
    { q: 'Which country has won the most Olympic gold medals overall?', options: ['Russia', 'China', 'UK', 'USA'], answer: 'USA' },
    { q: 'What is the most abundant element in the universe?', options: ['helium', 'carbon', 'oxygen', 'hydrogen'], answer: 'hydrogen' },
    { q: 'What does the Richter scale measure?', options: ['wind speed', 'ocean depth', 'volcanic activity', 'earthquake intensity'], answer: 'earthquake intensity' },
    { q: 'Who painted the Sistine Chapel?', options: ['Raphael', 'Leonardo da Vinci', 'Caravaggio', 'Michelangelo'], answer: 'Michelangelo' },
    { q: 'What is the law of conservation of energy?', options: ['energy can be created from nothing', 'energy always decreases', 'energy is always conserved as heat', 'energy cannot be created or destroyed, only transferred'], answer: 'energy cannot be created or destroyed, only transferred' },
    { q: 'What is the approximate age of the Earth?', options: ['2.5 billion years', '3.5 billion years', '4.5 billion years', '5.5 billion years'], answer: '4.5 billion years' },
    { q: 'Who was the first person to circumnavigate the globe?', options: ['Columbus', 'Drake', 'Cook', 'Magellan'], answer: 'Magellan' },
    { q: 'What is the half-life of a radioactive substance?', options: ['time for all atoms to decay', 'time to release half its energy', 'time for substance to become safe', 'time for half the atoms to decay'], answer: 'time for half the atoms to decay' },
    { q: 'Who wrote the Odyssey?', options: ['Virgil', 'Plato', 'Socrates', 'Homer'], answer: 'Homer' },
    { q: 'What is the currency of Brazil?', options: ['dollar', 'peso', 'sol', 'real'], answer: 'real' },
    { q: 'Which country has the most UNESCO World Heritage Sites?', options: ['France', 'China', 'Spain', 'Italy'], answer: 'Italy' },
    { q: 'What is the chemical formula for table salt?', options: ['NaOH', 'HCl', 'Na2O', 'NaCl'], answer: 'NaCl' },
    { q: 'What is the capital of Indonesia?', options: ['Bali', 'Surabaya', 'Bandung', 'Jakarta'], answer: 'Jakarta' },
    { q: 'What year was the first iPhone released?', options: ['2005', '2006', '2007', '2008'], answer: '2007' },
    { q: 'Which is the longest bone in the human body?', options: ['spine', 'tibia', 'humerus', 'femur'], answer: 'femur' },
    { q: 'What is the name for a group of stars forming a pattern?', options: ['galaxy', 'nebula', 'cluster', 'constellation'], answer: 'constellation' },
    { q: 'Who composed the Four Seasons?', options: ['Bach', 'Mozart', 'Beethoven', 'Vivaldi'], answer: 'Vivaldi' },
    { q: 'What is the main gas responsible for the greenhouse effect?', options: ['oxygen', 'nitrogen', 'argon', 'carbon dioxide'], answer: 'carbon dioxide' },
  ],
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}
