export interface Category {
  category: string
  topic: string
  answers: string[]
  timeLimit: number
}

export const categoryBank: Category[] = [
  { category: 'Animals that live in water', topic: 'Animals', timeLimit: 30, answers: ['fish', 'shark', 'whale', 'dolphin', 'octopus', 'crab', 'lobster', 'shrimp', 'prawn', 'jellyfish', 'seahorse', 'starfish', 'sea turtle', 'turtle', 'crocodile', 'frog', 'seal', 'walrus', 'otter', 'penguin', 'squid', 'clam', 'oyster', 'mussel', 'salmon', 'tuna', 'cod', 'catfish', 'stingray', 'ray', 'eel', 'piranha', 'manatee', 'dugong', 'hippo', 'hippopotamus', 'platypus', 'beaver'] },
  { category: 'Animals that live in the jungle', topic: 'Animals', timeLimit: 30, answers: ['tiger', 'lion', 'leopard', 'jaguar', 'panther', 'monkey', 'gorilla', 'chimpanzee', 'orangutan', 'elephant', 'snake', 'python', 'cobra', 'parrot', 'toucan', 'frog', 'tree frog', 'ant', 'beetle', 'butterfly', 'spider', 'tarantula', 'sloth', 'tapir', 'puma', 'cougar', 'porcupine', 'chameleon', 'gecko', 'iguana', 'macaw', 'hornbill', 'gibbon', 'boar', 'wild pig', 'deer', 'bear'] },
  { category: 'Animals with four legs', topic: 'Animals', timeLimit: 30, answers: ['dog', 'cat', 'horse', 'cow', 'pig', 'sheep', 'goat', 'elephant', 'lion', 'tiger', 'bear', 'fox', 'wolf', 'rabbit', 'deer', 'giraffe', 'zebra', 'rhino', 'hippo', 'camel', 'donkey', 'monkey', 'gorilla', 'cheetah', 'leopard', 'jaguar', 'puma', 'panda', 'koala', 'kangaroo', 'mouse', 'rat', 'hamster', 'guinea pig', 'squirrel', 'beaver', 'otter', 'badger', 'hyena', 'warthog'] },
  { category: 'Animals that can fly', topic: 'Animals', timeLimit: 30, answers: ['eagle', 'parrot', 'sparrow', 'pigeon', 'dove', 'owl', 'bat', 'butterfly', 'bee', 'wasp', 'fly', 'dragonfly', 'mosquito', 'moth', 'hawk', 'falcon', 'pelican', 'flamingo', 'crane', 'heron', 'swan', 'duck', 'goose', 'crow', 'raven', 'magpie', 'robin', 'toucan', 'macaw', 'cockatoo', 'hummingbird', 'kingfisher', 'woodpecker', 'hornbill', 'stork', 'albatross', 'seagull'] },
  { category: 'Animals found in Thailand', topic: 'Animals', timeLimit: 30, answers: ['elephant', 'tiger', 'monkey', 'cobra', 'python', 'crocodile', 'gecko', 'lizard', 'water buffalo', 'buffalo', 'cat', 'dog', 'fish', 'crab', 'shrimp', 'prawn', 'parrot', 'hornbill', 'deer', 'wild boar', 'bear', 'leopard', 'gibbon', 'orangutan', 'frog', 'toad', 'scorpion', 'centipede', 'ant', 'butterfly', 'firefly', 'shark', 'whale', 'dolphin', 'sea turtle', 'jellyfish'] },
  { category: 'Types of fruit', topic: 'Food & Drink', timeLimit: 30, answers: ['apple', 'banana', 'orange', 'mango', 'grape', 'strawberry', 'watermelon', 'pineapple', 'lemon', 'lime', 'peach', 'plum', 'cherry', 'pear', 'kiwi', 'papaya', 'coconut', 'durian', 'lychee', 'guava', 'passion fruit', 'dragonfruit', 'jackfruit', 'pomelo', 'grapefruit', 'melon', 'cantaloupe', 'blueberry', 'raspberry', 'blackberry', 'fig', 'date', 'apricot', 'avocado', 'pomegranate', 'rambutan', 'longan', 'tamarind'] },
  { category: 'Types of vegetable', topic: 'Food & Drink', timeLimit: 30, answers: ['carrot', 'potato', 'onion', 'garlic', 'tomato', 'cucumber', 'lettuce', 'spinach', 'broccoli', 'cabbage', 'cauliflower', 'corn', 'pea', 'bean', 'pumpkin', 'mushroom', 'celery', 'leek', 'asparagus', 'aubergine', 'eggplant', 'courgette', 'zucchini', 'pepper', 'chilli', 'ginger', 'lemongrass', 'spring onion', 'radish', 'turnip', 'beetroot', 'sweet potato', 'yam', 'kale', 'pak choi', 'bok choy'] },
  { category: 'Things you drink', topic: 'Food & Drink', timeLimit: 30, answers: ['water', 'juice', 'milk', 'tea', 'coffee', 'cola', 'lemonade', 'beer', 'wine', 'smoothie', 'milkshake', 'hot chocolate', 'energy drink', 'coconut water', 'soda', 'sparkling water', 'orange juice', 'apple juice', 'mango juice', 'bubble tea', 'green tea', 'iced tea', 'espresso', 'cappuccino', 'latte', 'champagne', 'whiskey', 'rum', 'vodka', 'gin', 'cocktail', 'soup', 'broth'] },
  { category: 'Thai food', topic: 'Food & Drink', timeLimit: 30, answers: ['pad thai', 'tom yum', 'green curry', 'red curry', 'massaman curry', 'pad see ew', 'khao pad', 'fried rice', 'som tam', 'papaya salad', 'larb', 'mango sticky rice', 'satay', 'spring rolls', 'tom kha', 'basil stir fry', 'pad kaprao', 'boat noodles', 'khao man gai', 'chicken rice', 'thai omelette', 'pad woon sen', 'pineapple fried rice', 'crying tiger', 'tod mun', 'khao soi', 'penang curry'] },
  { category: 'Things you eat for breakfast', topic: 'Food & Drink', timeLimit: 30, answers: ['eggs', 'toast', 'cereal', 'porridge', 'oatmeal', 'bacon', 'sausage', 'pancakes', 'waffles', 'croissant', 'bread', 'butter', 'jam', 'honey', 'yoghurt', 'fruit', 'banana', 'orange juice', 'coffee', 'tea', 'milk', 'muffin', 'bagel', 'granola', 'hash brown', 'mushrooms', 'baked beans', 'french toast', 'rice porridge', 'congee', 'noodles'] },
  { category: 'Countries in Asia', topic: 'World & Geography', timeLimit: 30, answers: ['thailand', 'japan', 'china', 'india', 'korea', 'south korea', 'north korea', 'vietnam', 'cambodia', 'laos', 'myanmar', 'malaysia', 'singapore', 'indonesia', 'philippines', 'taiwan', 'hong kong', 'bangladesh', 'pakistan', 'afghanistan', 'iran', 'iraq', 'saudi arabia', 'uae', 'qatar', 'nepal', 'sri lanka', 'mongolia', 'uzbekistan', 'kazakhstan', 'brunei', 'maldives', 'bhutan'] },
  { category: 'Capital cities', topic: 'World & Geography', timeLimit: 30, answers: ['bangkok', 'tokyo', 'beijing', 'london', 'paris', 'berlin', 'rome', 'madrid', 'moscow', 'washington', 'ottawa', 'canberra', 'new delhi', 'seoul', 'jakarta', 'manila', 'kuala lumpur', 'singapore', 'hanoi', 'phnom penh', 'vientiane', 'naypyidaw', 'cairo', 'nairobi', 'pretoria', 'buenos aires', 'brasilia', 'lima', 'bogota', 'mexico city', 'amsterdam', 'vienna', 'stockholm', 'oslo', 'helsinki', 'copenhagen', 'warsaw', 'prague', 'budapest'] },
  { category: 'Things you find at the beach', topic: 'World & Geography', timeLimit: 30, answers: ['sand', 'sea', 'waves', 'shells', 'rocks', 'pebbles', 'seaweed', 'fish', 'crab', 'starfish', 'jellyfish', 'sunbed', 'umbrella', 'towel', 'sunscreen', 'sunglasses', 'hat', 'swimsuit', 'bikini', 'surfboard', 'boat', 'lighthouse', 'lifeguard', 'ice cream', 'coconut', 'palm tree', 'bucket', 'spade', 'sandcastle', 'flip flops', 'volleyball', 'snorkel', 'cliff'] },
  { category: 'Things you find in a city', topic: 'World & Geography', timeLimit: 30, answers: ['buildings', 'skyscrapers', 'roads', 'cars', 'buses', 'taxis', 'trains', 'subway', 'metro', 'traffic lights', 'shops', 'restaurants', 'cafes', 'banks', 'hotels', 'hospitals', 'schools', 'parks', 'museums', 'cinemas', 'theatres', 'markets', 'malls', 'bridges', 'rivers', 'statues', 'fountains', 'street lights', 'billboards', 'police', 'fire station', 'library', 'post office', 'airport'] },
  { category: 'Countries in Europe', topic: 'World & Geography', timeLimit: 30, answers: ['france', 'germany', 'italy', 'spain', 'portugal', 'uk', 'england', 'scotland', 'wales', 'ireland', 'netherlands', 'belgium', 'switzerland', 'austria', 'sweden', 'norway', 'denmark', 'finland', 'poland', 'czech republic', 'hungary', 'romania', 'bulgaria', 'greece', 'turkey', 'russia', 'ukraine', 'croatia', 'serbia', 'slovakia', 'slovenia', 'latvia', 'lithuania', 'estonia', 'luxembourg', 'iceland'] },
  { category: 'Things that are red', topic: 'Colours & Descriptions', timeLimit: 30, answers: ['apple', 'tomato', 'strawberry', 'rose', 'fire engine', 'blood', 'fire', 'sunset', 'cherry', 'raspberry', 'watermelon', 'chilli', 'pepper', 'ladybird', 'postbox', 'stop sign', 'heart', 'lips', 'ruby', 'mars', 'brick', 'lobster', 'crab', 'salmon', 'ketchup', 'wine', 'barn'] },
  { category: 'Things that are blue', topic: 'Colours & Descriptions', timeLimit: 30, answers: ['sky', 'sea', 'ocean', 'water', 'blueberry', 'jeans', 'denim', 'sapphire', 'whale', 'dolphin', 'ink', 'pen', 'bruise', 'vein', 'turquoise', 'navy', 'cobalt', 'indigo', 'hydrangea', 'iris'] },
  { category: 'Things that are round', topic: 'Colours & Descriptions', timeLimit: 30, answers: ['ball', 'sun', 'moon', 'earth', 'planet', 'wheel', 'coin', 'clock', 'plate', 'pizza', 'pie', 'orange', 'apple', 'grape', 'eye', 'bubble', 'balloon', 'button', 'ring', 'donut', 'cookie', 'biscuit', 'circle', 'globe', 'drum', 'barrel', 'tyre', 'cd', 'disc'] },
  { category: 'Things that are small', topic: 'Colours & Descriptions', timeLimit: 30, answers: ['ant', 'bee', 'fly', 'mosquito', 'flea', 'snail', 'mouse', 'hamster', 'pea', 'seed', 'grain', 'coin', 'button', 'pin', 'needle', 'ring', 'earring', 'chip', 'pill', 'tablet', 'stamp', 'pebble', 'crumb', 'dot', 'spot', 'baby', 'puppy', 'kitten', 'thumb', 'fingernail'] },
  { category: 'Things in a classroom', topic: 'School & Classroom', timeLimit: 30, answers: ['desk', 'chair', 'table', 'board', 'whiteboard', 'blackboard', 'pen', 'pencil', 'ruler', 'eraser', 'rubber', 'book', 'notebook', 'textbook', 'bag', 'backpack', 'computer', 'projector', 'screen', 'clock', 'window', 'door', 'poster', 'map', 'globe', 'calculator', 'scissors', 'glue', 'tape', 'marker', 'highlighter', 'stapler', 'paper', 'folder', 'bin', 'shelf', 'bookcase', 'fan', 'air conditioner'] },
  { category: 'School subjects', topic: 'School & Classroom', timeLimit: 30, answers: ['english', 'maths', 'mathematics', 'science', 'history', 'geography', 'art', 'music', 'pe', 'physical education', 'sport', 'thai', 'thai language', 'social studies', 'biology', 'chemistry', 'physics', 'computer science', 'ict', 'drama', 'dance', 'cooking', 'home economics', 'economics', 'business', 'philosophy', 'religion', 'french', 'spanish', 'japanese', 'chinese', 'mandarin'] },
  { category: 'Things in a school bag', topic: 'School & Classroom', timeLimit: 30, answers: ['book', 'notebook', 'pencil', 'pen', 'ruler', 'eraser', 'rubber', 'calculator', 'scissors', 'glue', 'folder', 'lunch box', 'water bottle', 'phone', 'headphones', 'charger', 'wallet', 'keys', 'pencil case', 'highlighter', 'marker', 'compass', 'protractor', 'dictionary', 'flash cards', 'stickers', 'sticky notes', 'planner', 'diary'] },
  { category: 'Jobs at a school', topic: 'School & Classroom', timeLimit: 30, answers: ['teacher', 'principal', 'headmaster', 'headmistress', 'director', 'secretary', 'receptionist', 'cleaner', 'janitor', 'caretaker', 'librarian', 'nurse', 'doctor', 'security guard', 'cook', 'chef', 'canteen staff', 'bus driver', 'counsellor', 'sports coach', 'music teacher', 'art teacher', 'science teacher', 'english teacher', 'thai teacher', 'assistant teacher', 'teaching assistant'] },
  { category: 'Things you wear', topic: 'Clothes & Body', timeLimit: 30, answers: ['shirt', 't-shirt', 'trousers', 'pants', 'jeans', 'shorts', 'skirt', 'dress', 'suit', 'jacket', 'coat', 'jumper', 'sweater', 'hoodie', 'socks', 'shoes', 'boots', 'sandals', 'hat', 'cap', 'scarf', 'gloves', 'belt', 'tie', 'bow tie', 'underwear', 'bra', 'swimsuit', 'bikini', 'uniform', 'pyjamas', 'robe', 'vest', 'cardigan', 'blazer', 'raincoat', 'watch', 'glasses', 'ring', 'necklace', 'earrings'] },
  { category: 'Parts of the body', topic: 'Clothes & Body', timeLimit: 30, answers: ['head', 'hair', 'face', 'eye', 'ear', 'nose', 'mouth', 'lip', 'tooth', 'tongue', 'chin', 'cheek', 'neck', 'shoulder', 'arm', 'elbow', 'wrist', 'hand', 'finger', 'thumb', 'nail', 'chest', 'stomach', 'back', 'hip', 'leg', 'knee', 'ankle', 'foot', 'toe', 'heel', 'brain', 'heart', 'lung', 'liver', 'kidney', 'spine', 'rib', 'muscle', 'skin'] },
  { category: 'Things you wear on your feet', topic: 'Clothes & Body', timeLimit: 30, answers: ['shoes', 'boots', 'sandals', 'flip flops', 'slippers', 'trainers', 'sneakers', 'heels', 'high heels', 'socks', 'stockings', 'tights', 'wellies', 'wellington boots', 'clogs', 'loafers', 'moccasins', 'ankle boots', 'running shoes', 'football boots', 'hiking boots', 'ballet shoes', 'crocs'] },
  { category: 'Things you wear in cold weather', topic: 'Clothes & Body', timeLimit: 30, answers: ['coat', 'jacket', 'jumper', 'sweater', 'hoodie', 'scarf', 'gloves', 'hat', 'beanie', 'boots', 'thermal', 'vest', 'cardigan', 'fleece', 'parka', 'anorak', 'raincoat', 'earmuffs', 'mittens', 'tights', 'woolly socks', 'long johns', 'fur coat', 'down jacket'] },
  { category: 'Things in a kitchen', topic: 'Home & Daily Life', timeLimit: 30, answers: ['fridge', 'oven', 'microwave', 'stove', 'cooker', 'sink', 'tap', 'kettle', 'toaster', 'blender', 'mixer', 'knife', 'fork', 'spoon', 'plate', 'bowl', 'cup', 'mug', 'glass', 'pot', 'pan', 'wok', 'chopping board', 'tin opener', 'grater', 'peeler', 'spatula', 'ladle', 'colander', 'whisk', 'scales', 'timer', 'dish cloth', 'sponge', 'bin', 'cupboard', 'drawer'] },
  { category: 'Things in a bedroom', topic: 'Home & Daily Life', timeLimit: 30, answers: ['bed', 'pillow', 'duvet', 'blanket', 'sheet', 'mattress', 'wardrobe', 'cupboard', 'drawer', 'desk', 'chair', 'lamp', 'light', 'mirror', 'window', 'curtain', 'blind', 'carpet', 'rug', 'bookshelf', 'alarm clock', 'phone', 'charger', 'laptop', 'computer', 'tv', 'fan', 'air conditioner', 'photo frame', 'poster', 'clothes', 'shoes'] },
  { category: 'Things you do in the morning', topic: 'Home & Daily Life', timeLimit: 30, answers: ['wake up', 'get up', 'stretch', 'shower', 'wash face', 'brush teeth', 'get dressed', 'eat breakfast', 'drink coffee', 'drink tea', 'check phone', 'read news', 'exercise', 'meditate', 'walk', 'drive', 'take bus', 'go to work', 'go to school', 'feed pets', 'make bed', 'pack bag', 'put on makeup', 'shave', 'comb hair', 'brush hair', 'cook', 'pray'] },
  { category: 'Types of transport', topic: 'Home & Daily Life', timeLimit: 30, answers: ['car', 'bus', 'train', 'plane', 'boat', 'bike', 'bicycle', 'motorbike', 'motorcycle', 'taxi', 'tuk tuk', 'scooter', 'truck', 'van', 'lorry', 'helicopter', 'subway', 'metro', 'tram', 'ferry', 'ship', 'speedboat', 'canoe', 'cable car', 'hot air balloon', 'rocket', 'ambulance', 'fire engine', 'police car', 'horse', 'elephant', 'skateboard', 'rollerblades'] },
  { category: 'Sports you play with a ball', topic: 'Fun & Sports', timeLimit: 30, answers: ['football', 'soccer', 'basketball', 'volleyball', 'tennis', 'golf', 'baseball', 'softball', 'cricket', 'rugby', 'american football', 'bowling', 'billiards', 'pool', 'snooker', 'table tennis', 'ping pong', 'badminton', 'squash', 'handball', 'water polo', 'polo', 'croquet', 'netball', 'dodgeball', 'kickball'] },
  { category: 'Things at a party', topic: 'Fun & Sports', timeLimit: 30, answers: ['balloons', 'cake', 'candles', 'presents', 'gifts', 'music', 'dancing', 'food', 'drinks', 'streamers', 'confetti', 'decorations', 'games', 'friends', 'family', 'photos', 'selfies', 'hats', 'party hats', 'banners', 'fairy lights', 'punch', 'cocktails', 'buffet', 'napkins', 'plates', 'cups', 'straws', 'invitations', 'dj', 'karaoke', 'pinata'] },
  { category: 'Things you do at the weekend', topic: 'Fun & Sports', timeLimit: 30, answers: ['sleep', 'relax', 'watch tv', 'cook', 'clean', 'exercise', 'go shopping', 'go to the market', 'meet friends', 'go to a restaurant', 'travel', 'go to the beach', 'go swimming', 'play sport', 'read', 'play games', 'watch a film', 'go to the cinema', 'go hiking', 'go cycling', 'visit family', 'go to a temple', 'go to a museum', 'go to a park', 'go out for dinner', 'party', 'study', 'work'] },
  { category: 'Olympic sports', topic: 'Fun & Sports', timeLimit: 30, answers: ['swimming', 'running', 'cycling', 'gymnastics', 'weightlifting', 'wrestling', 'boxing', 'judo', 'taekwondo', 'tennis', 'golf', 'football', 'basketball', 'volleyball', 'beach volleyball', 'handball', 'hockey', 'rowing', 'sailing', 'shooting', 'archery', 'fencing', 'triathlon', 'table tennis', 'badminton', 'diving', 'water polo', 'marathon', 'sprint', 'long jump', 'high jump', 'javelin', 'discus', 'hammer', 'pole vault'] },
]

export const topics = [...new Set(categoryBank.map(c => c.topic))]

export function getCategoriesByTopic(topic: string): Category[] {
  return categoryBank.filter(c => c.topic === topic)
}

export function checkAnswer(input: string, answers: string[]): boolean {
  return answers.some(a => a.toLowerCase() === input.toLowerCase().trim())
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}