'use client'
import { useState, useRef, useEffect } from 'react'
import Link from 'next/link'

const SPEEDS = [
  { label: '🐢 Very Slow', value: 0.55 },
  { label: '🚶 Slow', value: 0.72 },
  { label: '🏃 Normal', value: 0.9 },
  { label: '⚡ Fast', value: 1.1 },
]

const LANGUAGES = [
  { value: 'none', label: '🌍 English only' },
  { value: 'Thai', label: '🇹🇭 Thai' },
  { value: 'Japanese', label: '🇯🇵 Japanese' },
  { value: 'Korean', label: '🇰🇷 Korean' },
  { value: 'Chinese', label: '🇨🇳 Chinese' },
  { value: 'Arabic', label: '🇸🇦 Arabic' },
  { value: 'Spanish', label: '🇪🇸 Spanish' },
  { value: 'French', label: '🇫🇷 French' },
  { value: 'German', label: '🇩🇪 German' },
  { value: 'Portuguese', label: '🇧🇷 Portuguese' },
  { value: 'Russian', label: '🇷🇺 Russian' },
  { value: 'Vietnamese', label: '🇻🇳 Vietnamese' },
  { value: 'Indonesian', label: '🇮🇩 Indonesian' },
]

const PARTS = [
  {
    number: 1, title: 'When Dinosaurs Ruled', emoji: '🌍', color: '#65a30d',
    text: `Dinosaurs first appeared on Earth about 230 million years ago, during a period called the Triassic. They were not immediately the dominant animals on the planet — at first, they were small, fast creatures living alongside many other types of reptile. But over millions of years, they evolved into an extraordinary variety of shapes and sizes, and eventually became the most successful group of land animals the Earth has ever seen.\n\nDinosaurs ruled the Earth for about 165 million years. To understand how long that is, consider this: modern humans have existed for only about 300,000 years. If the entire time dinosaurs existed were compressed into one hour, the entire history of humanity would take up less than one second.\n\nDuring their time on Earth, dinosaurs evolved into an incredible range of species. Scientists have identified more than 1,000 different species so far, and new ones are being discovered every year — on average, a new dinosaur species is named about every two weeks. Some were enormous. The Argentinosaurus may have weighed up to 70 tonnes — as heavy as 12 elephants. The Patagotitan was so long that it would have stretched across a football pitch. Others were tiny — the Microraptor was about the size of a pigeon.\n\nDinosaurs lived on every continent, including Antarctica — which was much warmer 100 million years ago than it is today. They occupied almost every ecological role — predators, herbivores, scavengers, and even fliers. They were, by any measure, one of evolution\'s greatest success stories.`,
    vocab: [
      { word: 'Dominant', definition: 'The most powerful, successful, or important — having more influence than anything else.' },
      { word: 'Evolved', definition: 'Changed slowly over millions of years through natural processes.' },
      { word: 'Herbivores', definition: 'Animals that eat only plants, not meat.' },
      { word: 'Ecological role', definition: 'The job or function that an animal plays in its environment and food chain.' },
    ],
    questions: [
      { n: 1, q: 'Dinosaurs ruled for 165 million years. Humans have existed for 300,000 years. What does this comparison make you think about?' },
      { n: 2, q: 'A new dinosaur species is discovered about every two weeks. Does this surprise you? What does it tell us about how much we still don\'t know?' },
      { n: 3, q: 'If you could see any dinosaur alive, which one would you choose and why?' },
    ]
  },
  {
    number: 2, title: 'What Were They Really Like?', emoji: '🔍', color: '#4d7c0f',
    text: `If you picture a dinosaur in your mind, you probably imagine a grey or green scaly reptile — like the ones in the Jurassic Park films. But scientists now know that this image is mostly wrong. Modern research has completely changed our understanding of what dinosaurs actually looked like.\n\nOne of the biggest discoveries of recent decades is that many dinosaurs had feathers. Not just small dinosaurs — even some large predators like Velociraptor were covered in feathers. Scientists know this because beautifully preserved fossils found in China show the clear impressions of feathers in the rock. Some dinosaurs were brightly coloured, with red, brown, black, and even iridescent feathers — more like modern birds than the grey lizards of popular imagination.\n\nThis connection between dinosaurs and birds is now well established in science. Birds are not just related to dinosaurs — they are dinosaurs. Specifically, they are the only surviving group of theropod dinosaurs, which also included Tyrannosaurus rex and Velociraptor. When you see a sparrow or a chicken, you are looking at a living dinosaur.\n\nScientists have also learned that many dinosaurs were much more active and intelligent than previously thought. Some species hunted in packs, suggesting complex social behaviour. Others built nests and cared for their young, much like modern birds. Brain scans of dinosaur skulls suggest that some species — particularly the smaller predators — were quite intelligent for reptiles, with large brain-to-body ratios comparable to modern birds.\n\nT. rex, the most famous dinosaur of all, has been particularly transformed by new research. Scientists now believe it may have had lips covering its teeth, that it could not actually roar (it probably made deep booming sounds), and that juvenile T. rex may have been covered in fluffy feathers before developing scales as adults.`,
    vocab: [
      { word: 'Fossils', definition: 'The preserved remains or impressions of ancient plants or animals found in rock.' },
      { word: 'Iridescent', definition: 'Showing colours that seem to change when seen from different angles — shimmering.' },
      { word: 'Theropod', definition: 'A group of two-legged dinosaurs that includes T. rex, Velociraptor, and modern birds.' },
      { word: 'Juvenile', definition: 'A young animal that has not yet reached adulthood.' },
    ],
    questions: [
      { n: 4, q: 'Many dinosaurs had colourful feathers, not grey scales. Does this change how you imagine them? Which image do you prefer?' },
      { n: 5, q: 'Birds are actually living dinosaurs. How does it feel to know that dinosaurs are not really extinct?' },
      { n: 6, q: 'T. rex may have had lips and fluffy feathers as a baby. Does this make it seem less scary or more interesting to you?' },
    ]
  },
  {
    number: 3, title: 'The Day the Dinosaurs Died', emoji: '☄️', color: '#3f6212',
    text: `About 66 million years ago, a rock from space about 12 kilometres wide — roughly the size of a city — slammed into what is now the coast of Mexico at a speed of about 72,000 kilometres per hour. The impact was one of the most violent events in the history of our planet, and it changed the course of life on Earth forever.\n\nThe asteroid hit with the force of billions of nuclear bombs. It created a crater more than 180 kilometres wide and 20 kilometres deep. The impact sent enormous amounts of rock, dust, and gas into the atmosphere, blocking sunlight for months or possibly years. Without sunlight, plants could not grow. Without plants, herbivorous animals starved. Without herbivores, the predators that ate them also starved. The food chain collapsed from the bottom up.\n\nAbout 75% of all species on Earth went extinct, including all non-bird dinosaurs. It was one of the five mass extinction events in Earth\'s history, and it is the most recent one. The crater, called the Chicxulub crater, was only discovered in the 1970s — it is buried under layers of rock and partly hidden beneath the ocean.\n\nNot everything died, however. Small mammals, some birds, reptiles like crocodiles and turtles, and many fish and insects survived. With the dinosaurs gone, mammals — which had been small, nocturnal creatures living in the shadow of the dinosaurs for millions of years — suddenly had the opportunity to grow larger, spread into new habitats, and diversify. Over the following millions of years, mammals evolved into the incredible variety we see today — including, eventually, humans. In a very real sense, we owe our existence to that asteroid.`,
    vocab: [
      { word: 'Asteroid', definition: 'A large rock that travels through space — sometimes they hit planets.' },
      { word: 'Crater', definition: 'A large circular hole in the ground caused by an explosion or an impact from space.' },
      { word: 'Mass extinction', definition: 'An event where a very large percentage of all living species on Earth die out in a short period.' },
      { word: 'Nocturnal', definition: 'Active at night and sleeping during the day.' },
    ],
    questions: [
      { n: 7, q: 'A rock the size of a city hit Earth and wiped out the dinosaurs. How does this make you feel about the safety of our planet today?' },
      { n: 8, q: 'If the asteroid had missed Earth, dinosaurs might still rule the planet. Do you think humans would have evolved? Why or why not?' },
      { n: 9, q: 'The passage says "we owe our existence to that asteroid." What does this mean, and do you find it a strange idea?' },
    ]
  },
  {
    number: 4, title: 'Dinosaurs Today', emoji: '🦴', color: '#365314',
    text: `The study of dinosaurs — called palaeontology — is one of the most exciting and rapidly changing areas of science. New technologies are allowing scientists to discover things about dinosaurs that would have been impossible just twenty years ago.\n\nCT scanning — the same technology used in hospitals — allows scientists to look inside dinosaur skulls without damaging them. This has revealed the size and shape of dinosaur brains, the structure of their inner ears (which tells us about their hearing and balance), and even the pathways of blood vessels and nerves. From these scans, scientists can estimate how intelligent a dinosaur was, how well it could see and hear, and how fast it could move.\n\nChemical analysis of fossils can now reveal what dinosaurs ate, how fast they grew, and even what colour they were. Tiny structures called melanosomes, preserved in fossilised feathers, contain information about pigment — allowing scientists to reconstruct the colours of some dinosaurs with remarkable accuracy.\n\nNew dinosaur fossils are being found at a faster rate than ever before. China, Argentina, and Mongolia are currently the richest sources of new discoveries. In Thailand, dinosaur fossils have been found in several provinces, including Kalasin and Nakhon Ratchasima. The Sirindhorn Museum in Kalasin is one of Southeast Asia\'s most important dinosaur research centres.\n\nPerhaps the most exciting question in modern palaeontology is whether we could ever bring dinosaurs back to life. While the Jurassic Park scenario of extracting DNA from amber is not scientifically possible — DNA breaks down far too quickly to survive 66 million years — some scientists are exploring whether we could reverse-engineer dinosaur characteristics in modern birds, since birds carry dinosaur genes. For now, this remains science fiction. But the dinosaurs themselves were once considered impossible too — until someone found their bones in the rock and began to ask questions.`,
    vocab: [
      { word: 'Palaeontology', definition: 'The scientific study of ancient life through fossils — the bones and remains of creatures that lived long ago.' },
      { word: 'CT scanning', definition: 'A medical technology that uses X-rays to create detailed pictures of the inside of objects or bodies.' },
      { word: 'Melanosomes', definition: 'Tiny structures in cells that contain pigment — they determine colour in skin, hair, and feathers.' },
      { word: 'Reverse-engineer', definition: 'To take something apart or study how it works in order to recreate it or build something similar.' },
    ],
    questions: [
      { n: 10, q: 'Scientists can now work out what colour some dinosaurs were. If you could see any dinosaur in its true colours, which would you choose?' },
      { n: 11, q: 'Thailand has its own dinosaur fossils and museum. Did you know this? Would you like to visit the Sirindhorn Museum in Kalasin?' },
      { n: 12, q: 'Should scientists try to bring dinosaurs back to life? What could go right — and what could go wrong?' },
    ]
  },
]

async function fetchTranslation(text: string, lang: string, type: 'word' | 'question' | 'message'): Promise<string> {
  const systems: Record<string, string> = {
    word: `You are a language learning assistant. Translate this English vocabulary entry to ${lang}. Return ONLY the translated word and a brief explanation in ${lang} (max 25 words). No extra text, no English.`,
    question: `You are a translator. Translate this English discussion question to ${lang}. Return ONLY the translated question. No extra text.`,
    message: `You are a translator. Translate this English text to ${lang}. Return ONLY the translation. No extra text.`,
  }
  const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: systems[type], messages: [{ role: 'user', content: text }] }) })
  const data = await res.json()
  return data.content || ''
}

function TranslateBtn({ text, type, lang, color, onTranslated }: { text: string; type: 'word' | 'question' | 'message'; lang: string; color: string; onTranslated: (t: string) => void }) {
  const [loading, setLoading] = useState(false)
  const [done, setDone] = useState(false)
  const handleClick = async () => { if (lang === 'none' || loading || done) return; setLoading(true); const result = await fetchTranslation(text, lang, type); onTranslated(result); setDone(true); setLoading(false) }
  const isDisabled = lang === 'none'
  return <button onClick={handleClick} disabled={isDisabled || loading || done} title={isDisabled ? 'Select a language above to translate' : done ? 'Translated' : `Translate to ${lang}`} style={{ background: isDisabled ? '#f3f4f6' : done ? '#f0fdf4' : color + '15', color: isDisabled ? '#d1d5db' : done ? '#16a34a' : color, border: `1px solid ${isDisabled ? '#e5e7eb' : done ? '#86efac' : color + '40'}`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: isDisabled ? 'not-allowed' : done ? 'default' : 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s' }}>{loading ? '...' : done ? '✓ 🌍' : '🌍'}</button>
}

function ListenBtn({ text, speed, color }: { text: string; speed: number; color: string }) {
  const [loading, setLoading] = useState(false); const [playing, setPlaying] = useState(false); const sourceRef = useRef<AudioBufferSourceNode | null>(null)
  const handleClick = async () => { if (playing && sourceRef.current) { try { sourceRef.current.stop() } catch {} sourceRef.current = null; setPlaying(false); return }; setLoading(true); try { const res = await fetch('/api/tts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); if (!res.ok) { setLoading(false); return }; const ab = await res.arrayBuffer(); const ac = new AudioContext(); const buf = await ac.decodeAudioData(ab); const src = ac.createBufferSource(); src.buffer = buf; src.playbackRate.value = speed; src.connect(ac.destination); src.onended = () => { setPlaying(false); sourceRef.current = null }; sourceRef.current = src; setLoading(false); setPlaying(true); src.start(0) } catch { setLoading(false); setPlaying(false) } }
  return <button onClick={handleClick} style={{ background: playing ? color : color + '15', color: playing ? 'white' : color, border: `1px solid ${color}40`, padding: '2px 10px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0, transition: 'all 0.2s', display: 'flex', alignItems: 'center', gap: '4px' }}>{loading ? '...' : playing ? '⏹ Stop' : '🔊 Listen'}</button>
}

type Message = { role: 'user' | 'assistant'; content: string; translation?: string }

function ConversationBox({ question, color, translationLang, speed }: { question: string; color: string; translationLang: string; speed: number }) {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [listening, setListening] = useState(false); const [interimText, setInterimText] = useState(''); const [open, setOpen] = useState(false); const recognitionRef = useRef<any>(null); const transcriptRef = useRef('')
  const SYSTEM = `You are a friendly and enthusiastic English conversation partner helping a B1 level student aged 10-12 practise English discussion skills. The reading topic is "Dinosaurs — The Rulers of the Earth". The current discussion question is: "${question}". Keep every response to 2-3 sentences maximum. Use simple, clear, exciting language for a young learner. Be enthusiastic and curious about dreams! Always end with one fun follow-up question to keep the conversation going. If the student makes a significant grammar error, gently correct it using "💡 Quick tip: ..." at the very end.`
  const sendMessage = async (text: string) => { if (!text.trim() || loading) return; const userMsg: Message = { role: 'user', content: text.trim() }; const updated = [...messages, userMsg]; setMessages(updated); setInput(''); setLoading(true); try { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: SYSTEM, messages: updated.map(m => ({ role: m.role, content: m.content })) }) }); const data = await res.json(); setMessages(prev => [...prev, { role: 'assistant', content: data.content || 'Sorry, try again.' }]) } catch { setMessages(prev => [...prev, { role: 'assistant', content: 'Connection error — please try again.' }]) }; setLoading(false) }
  const setMessageTranslation = (idx: number, translation: string) => { setMessages(prev => prev.map((m, i) => i === idx ? { ...m, translation } : m)) }
  const startVoice = () => { const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!SR) { alert('Voice input requires Chrome browser.'); return }; transcriptRef.current = ''; const r = new SR(); r.lang = 'en-US'; r.continuous = true; r.interimResults = true; r.onstart = () => { setListening(true); setInterimText('') }; r.onresult = (e: any) => { let f = ''; let int = ''; for (let i = 0; i < e.results.length; i++) { if (e.results[i].isFinal) { f += e.results[i][0].transcript + ' ' } else { int += e.results[i][0].transcript } }; transcriptRef.current = f; setInterimText(f + int) }; r.onerror = () => { setListening(false); setInterimText('') }; r.onend = () => { setListening(false); const text = transcriptRef.current.trim() || interimText.trim(); if (text) { setInterimText(''); transcriptRef.current = ''; sendMessage(text) } else { setInterimText(''); transcriptRef.current = '' } }; recognitionRef.current = r; r.start() }
  const stopVoice = () => { recognitionRef.current?.stop() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  if (!open) return <button onClick={() => setOpen(true)} style={{ marginTop: '10px', width: '100%', background: color + '12', border: `2px dashed ${color}40`, borderRadius: '12px', padding: '10px', color, fontWeight: '700', fontSize: '13px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}>🤖 Practice answering with AI</button>
  return (
    <div style={{ marginTop: '10px', background: '#f7fee7', borderRadius: '14px', border: `2px solid ${color}30`, overflow: 'hidden' }}>
      <div style={{ background: color, padding: '10px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span style={{ color: 'white', fontWeight: '700', fontSize: '13px' }}>🤖 AI Conversation Partner</span><div style={{ display: 'flex', gap: '6px' }}><button onClick={() => setMessages([])} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>🔄 Reset</button><button onClick={() => setOpen(false)} style={{ background: 'rgba(255,255,255,0.2)', color: 'white', border: 'none', padding: '4px 10px', borderRadius: '8px', fontSize: '12px', cursor: 'pointer', fontWeight: '600' }}>✕ Close</button></div></div>
      {messages.length === 0 && <div style={{ padding: '14px 16px', color: '#6b7280', fontSize: '13px', lineHeight: '1.6', borderBottom: '1px solid #d9f99d' }}>💡 Type your answer or tap <strong>🎤 Start Recording</strong> — speak your full answer, then tap <strong>⏹ Stop & Send</strong>.</div>}
      {messages.length > 0 && <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px', maxHeight: '320px', overflowY: 'auto' }}>{messages.map((m, i) => (<div key={i} style={{ display: 'flex', gap: '8px', alignItems: 'flex-start', flexDirection: m.role === 'user' ? 'row-reverse' : 'row' }}><div style={{ fontSize: '20px', flexShrink: 0 }}>{m.role === 'user' ? '🧑‍🎓' : '🤖'}</div><div style={{ maxWidth: '80%', display: 'flex', flexDirection: 'column', gap: '4px', alignItems: m.role === 'user' ? 'flex-end' : 'flex-start' }}><div style={{ background: m.role === 'user' ? color : 'white', color: m.role === 'user' ? 'white' : '#374151', padding: '10px 14px', borderRadius: m.role === 'user' ? '16px 4px 16px 16px' : '4px 16px 16px 16px', fontSize: '14px', lineHeight: '1.6', boxShadow: '0 1px 4px rgba(0,0,0,0.08)', border: m.role === 'assistant' ? '1px solid #e5e7eb' : 'none' }}>{m.content}</div>{m.role === 'assistant' && <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}><ListenBtn text={m.content} speed={speed} color={color} />{!m.translation && <TranslateBtn text={m.content} type="message" lang={translationLang} color={color} onTranslated={(t) => setMessageTranslation(i, t)} />}</div>}{m.translation && <div style={{ background: '#f7fee7', border: '1px solid #d9f99d', borderRadius: '10px', padding: '8px 12px', fontSize: '13px', color: '#374151', lineHeight: '1.5' }}><span style={{ color: color, fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>🌍 Translation</span>{m.translation}</div>}</div></div>))}{loading && <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}><span style={{ fontSize: '20px' }}>🤖</span><div style={{ background: 'white', padding: '10px 14px', borderRadius: '4px 16px 16px 16px', fontSize: '14px', color: '#9ca3af', border: '1px solid #e5e7eb' }}>Thinking...</div></div>}</div>}
      <div style={{ padding: '12px 16px', borderTop: '1px solid #d9f99d', display: 'flex', gap: '8px', alignItems: 'flex-end' }}><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(input) } }} placeholder="Type your answer here..." rows={2} style={{ flex: 1, padding: '10px 12px', borderRadius: '10px', border: '2px solid #e5e7eb', fontSize: '14px', outline: 'none', resize: 'none', fontFamily: 'inherit', lineHeight: '1.5' }} /><div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}><button onClick={listening ? stopVoice : startVoice} style={{ background: listening ? '#ef4444' : '#22c55e', color: 'white', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: listening ? '0 0 0 4px rgba(239,68,68,0.3)' : 'none', transition: 'all 0.2s' }}>{listening ? '⏹' : '🎤'}</button><button onClick={() => sendMessage(input)} disabled={!input.trim() || loading} style={{ background: input.trim() && !loading ? color : '#e5e7eb', color: input.trim() && !loading ? 'white' : '#9ca3af', border: 'none', width: '42px', height: '42px', borderRadius: '10px', fontSize: '18px', cursor: input.trim() && !loading ? 'pointer' : 'not-allowed', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>➤</button></div></div>
      {!listening && <div style={{ padding: '4px 16px 10px', display: 'flex', gap: '16px' }}><span style={{ color: '#9ca3af', fontSize: '11px' }}>🎤 = Start recording</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>⏹ = Stop & send</span><span style={{ color: '#9ca3af', fontSize: '11px' }}>➤ = Send typed</span></div>}
      {listening && <div style={{ padding: '10px 16px 14px', borderTop: '1px solid #fee2e2', background: '#fef2f2' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ display: 'inline-block', width: '10px', height: '10px', borderRadius: '50%', background: '#ef4444', animation: 'pulse 1s infinite', flexShrink: 0 }} /><span style={{ color: '#ef4444', fontSize: '12px', fontWeight: '700' }}>Recording... speak your full answer</span></div><button onClick={stopVoice} style={{ background: '#ef4444', color: 'white', border: 'none', padding: '6px 16px', borderRadius: '10px', fontWeight: '800', fontSize: '13px', cursor: 'pointer', boxShadow: '0 2px 8px rgba(239,68,68,0.4)' }}>⏹ Stop & Send</button></div><div style={{ background: 'white', borderRadius: '10px', padding: '10px 14px', fontSize: '14px', color: interimText ? '#374151' : '#9ca3af', lineHeight: '1.6', border: '1px solid #fca5a5', fontStyle: 'italic', minHeight: '40px' }}>{interimText || 'Waiting for speech...'}{interimText && <span style={{ display: 'inline-block', width: '2px', height: '16px', background: '#ef4444', marginLeft: '2px', verticalAlign: 'middle', animation: 'pulse 1s infinite' }} />}</div></div>}
    </div>
  )
}

export default function DinosaursPage() {
  const [speed, setSpeed] = useState(0.9); const [translationLang, setTranslationLang] = useState('none'); const [selectedText, setSelectedText] = useState<string | null>(null); const [lookupDef, setLookupDef] = useState(''); const [lookupTranslation, setLookupTranslation] = useState(''); const [lookupLoading, setLookupLoading] = useState(false); const [vocabTranslations, setVocabTranslations] = useState<Record<string, string>>({}); const [questionTranslations, setQuestionTranslations] = useState<Record<number, string>>({})
  useEffect(() => { const handleSelection = () => { const sel = window.getSelection(); if (!sel) return; const text = sel.toString().trim().replace(/\s+/g, ' '); if (!text || text.split(' ').length > 6) return; const anchor = sel.anchorNode?.parentElement; if (!anchor?.closest('[data-passage]')) return; handleLookup(text) }; document.addEventListener('mouseup', handleSelection); document.addEventListener('touchend', handleSelection); return () => { document.removeEventListener('mouseup', handleSelection); document.removeEventListener('touchend', handleSelection) } }, [translationLang])
  const handleLookup = async (text: string) => { if (!text || text.length < 2) return; setSelectedText(text); setLookupDef(''); setLookupTranslation(''); setLookupLoading(true); speakWord(text); const isPhrase = text.includes(' '); try { if (translationLang === 'none') { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: isPhrase ? `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 20 words) explaining what the phrase means. No extra text.` : `You are an English dictionary for B1 young learners aged 10-12. Respond with ONLY one simple sentence (max 15 words) defining this word. No extra text.`, messages: [{ role: 'user', content: isPhrase ? `What does "${text}" mean?` : `Define: "${text}"` }] }) }); const data = await res.json(); setLookupDef(data.content || 'No definition found.') } else { const res = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ system: `You are a language learning assistant for young B1 English students. Respond ONLY with valid JSON (no markdown, no backticks): {"definition": "one simple English sentence max 15 words", "translation": "the word/phrase in ${translationLang} with a brief explanation in ${translationLang}, max 25 words"}`, messages: [{ role: 'user', content: `Word or phrase: "${text}"` }] }) }); const data = await res.json(); try { const parsed = JSON.parse(data.content); setLookupDef(parsed.definition || 'No definition found.'); setLookupTranslation(parsed.translation || '') } catch { setLookupDef(data.content || 'No definition found.'); setLookupTranslation('') } } } catch { setLookupDef('Could not load definition.') }; setLookupLoading(false) }
  function speakText(text: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const sentences = text.match(/[^.!?]+[.!?]+/g) || [text]; sentences.forEach(s => { const u = new SpeechSynthesisUtterance(s.trim()); u.lang = 'en-GB'; u.rate = speed; u.pitch = 1; window.speechSynthesis.speak(u) }) }
  function speakWord(word: string) { if (typeof window === 'undefined') return; window.speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(word); u.lang = 'en-GB'; u.rate = 0.85; u.pitch = 1; window.speechSynthesis.speak(u) }
  function stopAudio() { if (typeof window === 'undefined') return; window.speechSynthesis.cancel() }
  const currentLang = LANGUAGES.find(l => l.value === translationLang)
  return (
    <main style={{ background: '#f4f6fa', minHeight: '100vh' }}>
      <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}} @keyframes slideUp{from{transform:translateY(100%);opacity:0}to{transform:translateY(0);opacity:1}}`}</style>
      <section style={{ background: 'linear-gradient(135deg, #1a2e05 0%, #365314 50%, #3f6212 100%)', padding: '56px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <Link href="/esl-resources/reading-comprehension/b1" style={{ color: 'rgba(255,255,255,0.6)', textDecoration: 'none', fontSize: '14px', display: 'inline-block', marginBottom: '20px' }}>← B1 Reading Comprehension</Link>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', flexWrap: 'wrap' }}>
            <div style={{ fontSize: '72px', flexShrink: 0 }}>🦕</div>
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '12px' }}>
                <span style={{ background: '#65a30d', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>B1 Intermediate</span>
                <span style={{ background: 'rgba(99,102,241,0.5)', color: 'white', fontSize: '12px', fontWeight: 'bold', padding: '4px 12px', borderRadius: '20px' }}>Nature & Animals</span>
                <span style={{ background: 'rgba(255,255,255,0.15)', color: 'white', fontSize: '12px', fontWeight: '600', padding: '4px 12px', borderRadius: '20px' }}>4 Parts · 12 Questions</span>
              </div>
              <h1 style={{ color: 'white', fontSize: '32px', fontWeight: 'bold', margin: '0 0 8px', lineHeight: '1.3' }}>Dinosaurs — The Rulers of the Earth</h1>
              <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '16px', margin: 0, lineHeight: '1.6' }}>For 165 million years, dinosaurs ruled the Earth. How did they live, why did they disappear, and what incredible secrets are their fossils still revealing today?</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '20px', marginTop: '28px', flexWrap: 'wrap' }}>{[{ icon: '📄', label: '4 reading parts' }, { icon: '💬', label: '12 discussion questions' }, { icon: '📚', label: '16 vocabulary words' }, { icon: '✍️', label: 'Highlight any text' }, { icon: '🌍', label: 'Multi-language lookup' }, { icon: '🤖', label: 'AI conversation partner' }].map(s => <div key={s.label} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'rgba(255,255,255,0.75)', fontSize: '13px' }}><span>{s.icon}</span> {s.label}</div>)}</div>
        </div>
      </section>
      <section style={{ background: 'white', borderBottom: '1px solid #eee', padding: '14px 24px' }}>
        <div style={{ maxWidth: '860px', margin: '0 auto' }}>
          <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', alignItems: 'center', marginBottom: '10px' }}><span style={{ color: '#888', fontSize: '12px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>How to use:</span>{['🔊 Play passage aloud', '✍️ Highlight any text for lookup', '🌍 Translate vocab, questions & AI answers', '🤖 Practice with AI'].map((step, i) => <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#555', fontSize: '13px' }}><span style={{ background: '#65a30d', color: 'white', width: '18px', height: '18px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '10px', fontWeight: 'bold', flexShrink: 0 }}>{i + 1}</span>{step}</div>)}</div>
          <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap', alignItems: 'center' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🔊 Speed:</span>{SPEEDS.map(s => <button key={s.value} onClick={() => setSpeed(s.value)} style={{ padding: '4px 12px', borderRadius: '20px', border: '2px solid', borderColor: speed === s.value ? '#65a30d' : '#e5e7eb', background: speed === s.value ? '#65a30d' : 'white', color: speed === s.value ? 'white' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', transition: 'all 0.2s' }}>{s.label}</button>)}</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ color: '#888', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', flexShrink: 0 }}>🌍 Translate to:</span><select value={translationLang} onChange={e => { setTranslationLang(e.target.value); setVocabTranslations({}); setQuestionTranslations({}) }} style={{ padding: '5px 12px', borderRadius: '20px', border: '2px solid', borderColor: translationLang !== 'none' ? '#65a30d' : '#e5e7eb', background: translationLang !== 'none' ? '#f7fee7' : 'white', color: translationLang !== 'none' ? '#365314' : '#555', fontWeight: '700', fontSize: '12px', cursor: 'pointer', outline: 'none' }}>{LANGUAGES.map(l => <option key={l.value} value={l.value}>{l.label}</option>)}</select></div>
          </div>
        </div>
      </section>
      <div style={{ maxWidth: '860px', margin: '0 auto', padding: '32px 24px', display: 'flex', flexDirection: 'column', gap: '28px' }}>
        {PARTS.map(part => (
          <div key={part.number} style={{ background: 'white', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 2px 12px rgba(0,0,0,0.07)' }}>
            <div style={{ background: `linear-gradient(135deg, ${part.color}22, ${part.color}08)`, borderLeft: `5px solid ${part.color}`, padding: '20px 24px', display: 'flex', gap: '14px', alignItems: 'center', flexWrap: 'wrap' }}>
              <div style={{ background: part.color, color: 'white', width: '36px', height: '36px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '16px', flexShrink: 0 }}>{part.number}</div>
              <div style={{ flex: 1 }}><div style={{ color: part.color, fontSize: '11px', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '2px' }}>Part {part.number}</div><h2 data-passage="true" style={{ color: '#1a1a2e', fontSize: '18px', fontWeight: 'bold', margin: 0, userSelect: 'text', cursor: 'text' }}>{part.emoji} {part.title}</h2></div>
              <div style={{ display: 'flex', gap: '8px', flexShrink: 0 }}><button onClick={() => speakText(part.text.replace(/\n\n/g, ' '))} style={{ background: part.color, color: 'white', border: 'none', padding: '8px 16px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', boxShadow: `0 3px 10px ${part.color}40` }}>▶ Play Passage</button><button onClick={stopAudio} style={{ background: 'white', color: '#6b7280', border: '2px solid #e5e7eb', padding: '8px 12px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer' }}>⏹ Stop</button></div>
            </div>
            <div style={{ background: '#f7fee7', padding: '8px 28px', borderBottom: '1px solid #d9f99d' }}><span style={{ color: '#365314', fontSize: '12px', fontWeight: '600' }}>✍️ Highlight any word or phrase to hear it and see its meaning{translationLang !== 'none' && <span style={{ color: '#65a30d' }}> + {currentLang?.label} translation</span>}</span></div>
            <div data-passage="true" style={{ padding: '24px 28px 20px', userSelect: 'text', cursor: 'text' }}>{part.text.split('\n\n').map((para, i) => <p key={i} style={{ color: '#374151', fontSize: '16px', lineHeight: '1.85', margin: i === 0 ? '0 0 18px' : '0', fontFamily: 'Georgia, serif' }}>{para}</p>)}</div>
            <div style={{ margin: '0 28px 24px', background: part.color + '08', border: `1px solid ${part.color}25`, borderRadius: '14px', overflow: 'hidden' }}>
              <div style={{ background: part.color + '18', padding: '12px 16px', display: 'flex', alignItems: 'center', gap: '8px', borderBottom: `1px solid ${part.color}20` }}><span style={{ fontSize: '16px' }}>📚</span><span style={{ color: part.color, fontWeight: 'bold', fontSize: '13px', textTransform: 'uppercase', letterSpacing: '1px' }}>Vocabulary — Part {part.number}</span></div>
              <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>{part.vocab.map((v, i) => { const vKey = `${part.number}-${v.word}`; return (<div key={v.word} style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', paddingBottom: i < part.vocab.length - 1 ? '10px' : '0', borderBottom: i < part.vocab.length - 1 ? `1px solid ${part.color}15` : 'none' }}><div style={{ background: part.color, color: 'white', width: '22px', height: '22px', borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '11px', flexShrink: 0, marginTop: '2px' }}>{i + 1}</div><div style={{ flex: 1 }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '3px', flexWrap: 'wrap' }}><span data-passage="true" style={{ fontWeight: 'bold', color: '#1a1a2e', fontSize: '15px', userSelect: 'text', cursor: 'text' }}>{v.word}</span><button onClick={() => speakWord(v.word)} style={{ background: part.color + '15', color: part.color, border: `1px solid ${part.color}30`, padding: '2px 8px', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', fontWeight: '700', flexShrink: 0 }}>🔊</button><TranslateBtn text={`Word: "${v.word}"\nDefinition: "${v.definition}"`} type="word" lang={translationLang} color={part.color} onTranslated={(t) => setVocabTranslations(prev => ({ ...prev, [vKey]: t }))} />{translationLang === 'none' && <span style={{ color: '#d1d5db', fontSize: '11px' }}>← select a language to translate</span>}</div><span data-passage="true" style={{ color: '#6b7280', fontSize: '14px', lineHeight: '1.5', userSelect: 'text', cursor: 'text' }}>{v.definition}</span>{vocabTranslations[vKey] && <div style={{ marginTop: '6px', background: '#f7fee7', border: '1px solid #d9f99d', borderRadius: '8px', padding: '8px 12px' }}><span style={{ color: '#365314', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: '#374151', fontSize: '14px', lineHeight: '1.5' }}>{vocabTranslations[vKey]}</span></div>}</div></div>) })}</div>
            </div>
            <div style={{ background: '#1a1a2e', padding: '20px 28px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}><span style={{ fontSize: '18px' }}>💬</span><span style={{ color: '#bef264', fontWeight: 'bold', fontSize: '14px', textTransform: 'uppercase', letterSpacing: '1px' }}>Discussion Questions</span></div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>{part.questions.map(q => (<div key={q.n}><div style={{ display: 'flex', gap: '14px', alignItems: 'flex-start' }}><div style={{ background: part.color, color: 'white', width: '28px', height: '28px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '900', fontSize: '13px', flexShrink: 0, marginTop: '1px' }}>{q.n}</div><div style={{ flex: 1 }}><p data-passage="true" style={{ color: 'rgba(255,255,255,0.88)', fontSize: '15px', lineHeight: '1.6', margin: '0 0 6px', userSelect: 'text', cursor: 'text' }}>{q.q}</p><div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}><TranslateBtn text={q.q} type="question" lang={translationLang} color={part.color} onTranslated={(t) => setQuestionTranslations(prev => ({ ...prev, [q.n]: t }))} />{translationLang === 'none' && <span style={{ color: '#4b5563', fontSize: '11px' }}>← select a language to translate</span>}</div>{questionTranslations[q.n] && <div style={{ marginTop: '8px', background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.3)', borderRadius: '10px', padding: '10px 14px' }}><span style={{ color: '#bef264', fontSize: '10px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '3px' }}>{currentLang?.label}</span><span style={{ color: 'rgba(255,255,255,0.9)', fontSize: '14px', lineHeight: '1.6' }}>{questionTranslations[q.n]}</span></div>}</div></div><div style={{ marginLeft: '42px' }}><ConversationBox question={q.q} color={part.color} translationLang={translationLang} speed={speed} /></div></div>))}</div>
            </div>
          </div>
        ))}
        <div style={{ textAlign: 'center', paddingBottom: selectedText ? '140px' : '16px' }}><Link href="/esl-resources/reading-comprehension/b1" style={{ color: '#65a30d', textDecoration: 'none', fontWeight: 'bold', fontSize: '14px' }}>← Back to B1 Reading Comprehension</Link></div>
      </div>
      {selectedText && <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 200, animation: 'slideUp 0.25s ease' }}><div style={{ maxWidth: '860px', margin: '0 auto', background: 'white', borderRadius: '20px 20px 0 0', padding: '20px 24px 32px', boxShadow: '0 -8px 32px rgba(0,0,0,0.2)', border: '2px solid #d9f99d', borderBottom: 'none' }}><div style={{ width: '40px', height: '4px', background: '#e5e7eb', borderRadius: '4px', margin: '0 auto 16px' }} /><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}><span style={{ fontSize: '22px', fontWeight: '900', color: '#1a1a2e', fontFamily: 'Georgia, serif' }}>"{selectedText}"</span><button onClick={() => speakWord(selectedText)} style={{ background: '#f7fee7', color: '#365314', border: '2px solid #d9f99d', padding: '6px 14px', borderRadius: '10px', fontWeight: '700', fontSize: '13px', cursor: 'pointer', flexShrink: 0 }}>🔊 Hear it</button></div><button onClick={() => setSelectedText(null)} style={{ background: '#f3f4f6', border: 'none', width: '32px', height: '32px', borderRadius: '8px', cursor: 'pointer', fontSize: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#6b7280', flexShrink: 0, marginLeft: '12px' }}>✕</button></div>{lookupLoading ? <div style={{ background: '#f7fee7', borderRadius: '12px', padding: '14px 18px', border: '1px solid #d9f99d', color: '#9ca3af', fontSize: '15px' }}>{translationLang !== 'none' ? `Looking up definition and ${currentLang?.label} translation...` : 'Looking up...'}</div> : <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}><div style={{ background: '#f7fee7', borderRadius: '12px', padding: '14px 18px', border: '1px solid #d9f99d' }}><div style={{ color: '#365314', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>📖 English Definition</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupDef}</span></div>{translationLang !== 'none' && lookupTranslation && <div style={{ background: '#f7fee7', borderRadius: '12px', padding: '14px 18px', border: '1px solid #bef264' }}><div style={{ color: '#3f6212', fontSize: '11px', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '6px' }}>{currentLang?.label} Translation</div><span style={{ color: '#374151', fontSize: '16px', lineHeight: '1.6' }}>{lookupTranslation}</span></div>}</div>}</div></div>}
    </main>
  )
}
