export type Difficulty = 'easy' | 'medium' | 'hard'

export interface TFQuestion {
  statement: string
  answer: boolean
  difficulty: Difficulty
  topic: string
}

export const tfBank: Record<string, TFQuestion[]> = {
  Animals: [
    // Easy
    { statement: 'A dog says meow', answer: false, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A cat has four legs', answer: true, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A fish lives in water', answer: true, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A bird has six legs', answer: false, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A rabbit hops', answer: true, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A cow gives us milk', answer: true, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A duck says moo', answer: false, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A snake has legs', answer: false, difficulty: 'easy', topic: 'Animals' },
    { statement: 'An elephant is bigger than a mouse', answer: true, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A penguin can fly', answer: false, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A lion is a mammal', answer: true, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A spider has six legs', answer: false, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A frog lives near water', answer: true, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A bee makes honey', answer: true, difficulty: 'easy', topic: 'Animals' },
    { statement: 'A whale is a fish', answer: false, difficulty: 'easy', topic: 'Animals' },
    // Medium
    { statement: 'A giraffe is the tallest animal in the world', answer: true, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A cheetah is the fastest land animal', answer: true, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A panda eats meat', answer: false, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A bat is a mammal', answer: true, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A crocodile is a reptile', answer: true, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A kangaroo is from Africa', answer: false, difficulty: 'medium', topic: 'Animals' },
    { statement: 'An octopus has eight arms', answer: true, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A shark is a mammal', answer: false, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A camel stores water in its hump', answer: false, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A starfish has five arms', answer: true, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A platypus lays eggs', answer: true, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A dolphin breathes underwater through gills', answer: false, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A chameleon can change colour', answer: true, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A koala eats eucalyptus leaves', answer: true, difficulty: 'medium', topic: 'Animals' },
    { statement: 'A gorilla is the largest primate', answer: true, difficulty: 'medium', topic: 'Animals' },
    // Hard
    { statement: 'A snail has the most teeth of any animal', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A blue whale is the largest animal that has ever lived', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A hummingbird can fly backwards', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'An ostrich can run faster than a horse', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A jellyfish has a brain', answer: false, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A group of flamingos is called a flock', answer: false, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A polar bear has black skin under its white fur', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A crocodile cannot stick out its tongue', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'An elephant is the only animal that cannot jump', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A shrimp has its heart in its head', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A group of crows is called a murder', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A mantis shrimp can see more colours than humans', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'Goldfish have a memory of only three seconds', answer: false, difficulty: 'hard', topic: 'Animals' },
    { statement: 'A narwhal horn is actually a tooth', answer: true, difficulty: 'hard', topic: 'Animals' },
    { statement: 'Tigers have striped skin as well as striped fur', answer: true, difficulty: 'hard', topic: 'Animals' },
  ],
  Food: [
    // Easy
    { statement: 'A banana is yellow', answer: true, difficulty: 'easy', topic: 'Food' },
    { statement: 'Milk comes from a chicken', answer: false, difficulty: 'easy', topic: 'Food' },
    { statement: 'Ice cream is cold', answer: true, difficulty: 'easy', topic: 'Food' },
    { statement: 'A lemon is sweet', answer: false, difficulty: 'easy', topic: 'Food' },
    { statement: 'Bread is baked in an oven', answer: true, difficulty: 'easy', topic: 'Food' },
    { statement: 'An apple is a vegetable', answer: false, difficulty: 'easy', topic: 'Food' },
    { statement: 'A carrot is orange', answer: true, difficulty: 'easy', topic: 'Food' },
    { statement: 'Pizza is eaten cold', answer: false, difficulty: 'easy', topic: 'Food' },
    { statement: 'An egg comes from a hen', answer: true, difficulty: 'easy', topic: 'Food' },
    { statement: 'Chocolate is made from cocoa', answer: true, difficulty: 'easy', topic: 'Food' },
    { statement: 'A tomato is a fruit', answer: true, difficulty: 'easy', topic: 'Food' },
    { statement: 'Butter is made from milk', answer: true, difficulty: 'easy', topic: 'Food' },
    { statement: 'Sushi comes from China', answer: false, difficulty: 'easy', topic: 'Food' },
    { statement: 'Honey is made by bees', answer: true, difficulty: 'easy', topic: 'Food' },
    { statement: 'A watermelon is red inside', answer: true, difficulty: 'easy', topic: 'Food' },
    // Medium
    { statement: 'Spaghetti is a type of pasta', answer: true, difficulty: 'medium', topic: 'Food' },
    { statement: 'Broccoli is a fruit', answer: false, difficulty: 'medium', topic: 'Food' },
    { statement: 'A peanut is a type of tree nut', answer: false, difficulty: 'medium', topic: 'Food' },
    { statement: 'Tofu is made from soybeans', answer: true, difficulty: 'medium', topic: 'Food' },
    { statement: 'Avocado is a vegetable', answer: false, difficulty: 'medium', topic: 'Food' },
    { statement: 'The croissant was invented in France', answer: false, difficulty: 'medium', topic: 'Food' },
    { statement: 'Wasabi is traditionally made from a plant', answer: true, difficulty: 'medium', topic: 'Food' },
    { statement: 'A strawberry has its seeds on the outside', answer: true, difficulty: 'medium', topic: 'Food' },
    { statement: 'Durian is known as the king of fruits in Thailand', answer: true, difficulty: 'medium', topic: 'Food' },
    { statement: 'Olive oil comes from pressing grapes', answer: false, difficulty: 'medium', topic: 'Food' },
    { statement: 'White chocolate contains cocoa solids', answer: false, difficulty: 'medium', topic: 'Food' },
    { statement: 'A chilli pepper contains more vitamin C than an orange', answer: true, difficulty: 'medium', topic: 'Food' },
    { statement: 'Cheese is made by curdling milk', answer: true, difficulty: 'medium', topic: 'Food' },
    { statement: 'Saffron is the most expensive spice in the world', answer: true, difficulty: 'medium', topic: 'Food' },
    { statement: 'China is the worlds largest producer of rice', answer: true, difficulty: 'medium', topic: 'Food' },
    // Hard
    { statement: 'Carrots were originally purple before they were orange', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'Honey never expires and can last thousands of years', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'Apples belong to the rose family', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'Almonds are a type of fruit related to peaches', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'Cashews grow inside a shell underground like peanuts', answer: false, difficulty: 'hard', topic: 'Food' },
    { statement: 'A banana is botanically a herb not a fruit', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'Vanilla comes from a type of orchid', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'Pineapples were originally from Asia', answer: false, difficulty: 'hard', topic: 'Food' },
    { statement: 'Nutmeg can be toxic in large amounts', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'Ketchup was originally sold as a medicine', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'A fig contains tiny wasps inside it', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'Chocolate was originally a drink not a solid', answer: true, difficulty: 'hard', topic: 'Food' },
    { statement: 'Potatoes are native to Ireland', answer: false, difficulty: 'hard', topic: 'Food' },
    { statement: 'Corn is botanically classified as a vegetable', answer: false, difficulty: 'hard', topic: 'Food' },
    { statement: 'Coconut water can be used as a substitute for blood plasma', answer: true, difficulty: 'hard', topic: 'Food' },
  ],
  Science: [
    // Easy
    { statement: 'The sun is a star', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'Water is made of hydrogen and oxygen', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'The moon makes its own light', answer: false, difficulty: 'easy', topic: 'Science' },
    { statement: 'Plants need sunlight to grow', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'Ice is colder than water', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'Humans need oxygen to breathe', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'A magnet can attract plastic', answer: false, difficulty: 'easy', topic: 'Science' },
    { statement: 'The Earth is flat', answer: false, difficulty: 'easy', topic: 'Science' },
    { statement: 'Fire needs oxygen to burn', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'Sound travels faster than light', answer: false, difficulty: 'easy', topic: 'Science' },
    { statement: 'Rainbows appear when it is sunny and raining at the same time', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'A volcano can erupt with lava', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'The heart pumps blood around the body', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'Flowers make seeds', answer: true, difficulty: 'easy', topic: 'Science' },
    { statement: 'We have five senses', answer: true, difficulty: 'easy', topic: 'Science' },
    // Medium
    { statement: 'Diamonds are made of carbon', answer: true, difficulty: 'medium', topic: 'Science' },
    { statement: 'The Earth takes 365 days to orbit the sun', answer: true, difficulty: 'medium', topic: 'Science' },
    { statement: 'Sound travels faster in water than in air', answer: true, difficulty: 'medium', topic: 'Science' },
    { statement: 'Gravity pulls objects towards the centre of the Earth', answer: true, difficulty: 'medium', topic: 'Science' },
    { statement: 'DNA stands for Deoxyribonucleic Acid', answer: true, difficulty: 'medium', topic: 'Science' },
    { statement: 'The largest organ in the human body is the liver', answer: false, difficulty: 'medium', topic: 'Science' },
    { statement: 'Light travels at 300000 kilometres per second', answer: true, difficulty: 'medium', topic: 'Science' },
    { statement: 'The periodic table was created by Albert Einstein', answer: false, difficulty: 'medium', topic: 'Science' },
    { statement: 'Atoms are the smallest particles in the universe', answer: false, difficulty: 'medium', topic: 'Science' },
    { statement: 'The human body has 206 bones', answer: true, difficulty: 'medium', topic: 'Science' },
    { statement: 'Plants produce oxygen through photosynthesis', answer: true, difficulty: 'medium', topic: 'Science' },
    { statement: 'The Moon is larger than the Earth', answer: false, difficulty: 'medium', topic: 'Science' },
    { statement: 'Neptune is the farthest planet from the sun', answer: true, difficulty: 'medium', topic: 'Science' },
    { statement: 'An electron has a positive charge', answer: false, difficulty: 'medium', topic: 'Science' },
    { statement: 'The chemical symbol for gold is AU', answer: true, difficulty: 'medium', topic: 'Science' },
    // Hard
    { statement: 'There are more stars in the universe than grains of sand on Earth', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'The human brain uses about 20 percent of the bodys energy', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'Quantum entanglement allows information to travel faster than light', answer: false, difficulty: 'hard', topic: 'Science' },
    { statement: 'Hot water can freeze faster than cold water in some conditions', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'The Milky Way galaxy is approximately 100000 light years across', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'Humans share about 60 percent of their DNA with bananas', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'The speed of light is exactly 300000 km per second', answer: false, difficulty: 'hard', topic: 'Science' },
    { statement: 'Black holes emit Hawking radiation', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'The element with the highest melting point is tungsten', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'A neutron star is denser than a black hole', answer: false, difficulty: 'hard', topic: 'Science' },
    { statement: 'The pH of pure water is exactly 7', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'Mitochondria are known as the powerhouse of the cell', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'The human eye can distinguish about one million colours', answer: true, difficulty: 'hard', topic: 'Science' },
    { statement: 'A light year is a measurement of time', answer: false, difficulty: 'hard', topic: 'Science' },
    { statement: 'The sun accounts for 99 percent of the mass in our solar system', answer: true, difficulty: 'hard', topic: 'Science' },
  ],
  Geography: [
    // Easy
    { statement: 'Thailand is in Asia', answer: true, difficulty: 'easy', topic: 'Geography' },
    { statement: 'The Amazon River is in Africa', answer: false, difficulty: 'easy', topic: 'Geography' },
    { statement: 'Australia is both a country and a continent', answer: true, difficulty: 'easy', topic: 'Geography' },
    { statement: 'The Sahara is a hot desert', answer: true, difficulty: 'easy', topic: 'Geography' },
    { statement: 'Mount Everest is the tallest mountain in the world', answer: true, difficulty: 'easy', topic: 'Geography' },
    { statement: 'The Pacific Ocean is the smallest ocean', answer: false, difficulty: 'easy', topic: 'Geography' },
    { statement: 'England is a country in Europe', answer: true, difficulty: 'easy', topic: 'Geography' },
    { statement: 'Japan is an island country', answer: true, difficulty: 'easy', topic: 'Geography' },
    { statement: 'The North Pole is in Antarctica', answer: false, difficulty: 'easy', topic: 'Geography' },
    { statement: 'Brazil is in South America', answer: true, difficulty: 'easy', topic: 'Geography' },
    { statement: 'The Nile is a river', answer: true, difficulty: 'easy', topic: 'Geography' },
    { statement: 'China has the largest population in the world', answer: true, difficulty: 'easy', topic: 'Geography' },
    { statement: 'Paris is the capital of Germany', answer: false, difficulty: 'easy', topic: 'Geography' },
    { statement: 'Africa is the largest continent', answer: false, difficulty: 'easy', topic: 'Geography' },
    { statement: 'The Great Wall is in China', answer: true, difficulty: 'easy', topic: 'Geography' },
    // Medium
    { statement: 'Russia is the largest country in the world by area', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'The capital of Australia is Sydney', answer: false, difficulty: 'medium', topic: 'Geography' },
    { statement: 'The Sahara Desert is larger than the USA', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'The Amazon Rainforest produces 20 percent of the worlds oxygen', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'The Nile is the longest river in the world', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'Iceland is covered mostly in ice', answer: false, difficulty: 'medium', topic: 'Geography' },
    { statement: 'Vatican City is the smallest country in the world', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'The Dead Sea is the lowest point on Earth', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'Spain and Portugal share the Iberian Peninsula', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'The Ganges River is in China', answer: false, difficulty: 'medium', topic: 'Geography' },
    { statement: 'New Zealand is east of Australia', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'The equator passes through Thailand', answer: false, difficulty: 'medium', topic: 'Geography' },
    { statement: 'Lake Baikal in Russia is the worlds deepest lake', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'Canada has more lakes than any other country', answer: true, difficulty: 'medium', topic: 'Geography' },
    { statement: 'The Andes mountain range is in Asia', answer: false, difficulty: 'medium', topic: 'Geography' },
    // Hard
    { statement: 'There are 54 countries in Africa', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'The Mariana Trench is the deepest point in the ocean', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'Kazakhstan is the worlds largest landlocked country', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'The Prime Meridian passes through Paris', answer: false, difficulty: 'hard', topic: 'Geography' },
    { statement: 'Antarctica is larger than Europe', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'The Caspian Sea is actually a lake', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'Greenland is the worlds largest island', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'Bolivia has two capital cities', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'The Amazon River flows into the Pacific Ocean', answer: false, difficulty: 'hard', topic: 'Geography' },
    { statement: 'There are seven continents on Earth', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'The Tropic of Cancer is north of the equator', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'Indonesia has more than 17000 islands', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'The Gobi Desert is in South America', answer: false, difficulty: 'hard', topic: 'Geography' },
    { statement: 'Lake Victoria is the largest lake in Africa', answer: true, difficulty: 'hard', topic: 'Geography' },
    { statement: 'The city of Istanbul is on two continents', answer: true, difficulty: 'hard', topic: 'Geography' },
  ],
  History: [
    // Easy
    { statement: 'The pyramids are in Egypt', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'World War Two ended in 1945', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'Neil Armstrong was the first man on the moon', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'The Titanic sank in the Pacific Ocean', answer: false, difficulty: 'easy', topic: 'History' },
    { statement: 'The Great Wall of China was built to keep out invaders', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'Christopher Columbus was from Spain', answer: false, difficulty: 'easy', topic: 'History' },
    { statement: 'The Roman Empire was based in Italy', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'Vikings came from Scandinavia', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'The first aeroplane was invented by the Wright Brothers', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'Cleopatra was a queen of China', answer: false, difficulty: 'easy', topic: 'History' },
    { statement: 'World War One started in 1914', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'The Eiffel Tower was built for a World Fair', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'Julius Caesar was a Roman leader', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'The Berlin Wall divided Germany', answer: true, difficulty: 'easy', topic: 'History' },
    { statement: 'The Moon landing happened in 1969', answer: true, difficulty: 'easy', topic: 'History' },
    // Medium
    { statement: 'The Black Death was caused by a virus', answer: false, difficulty: 'medium', topic: 'History' },
    { statement: 'Napoleon Bonaparte was French', answer: true, difficulty: 'medium', topic: 'History' },
    { statement: 'The ancient Olympics were held in Greece', answer: true, difficulty: 'medium', topic: 'History' },
    { statement: 'The printing press was invented in China before Europe', answer: true, difficulty: 'medium', topic: 'History' },
    { statement: 'Mahatma Gandhi led India to independence peacefully', answer: true, difficulty: 'medium', topic: 'History' },
    { statement: 'The American Declaration of Independence was signed in 1776', answer: true, difficulty: 'medium', topic: 'History' },
    { statement: 'The French Revolution happened in the 19th century', answer: false, difficulty: 'medium', topic: 'History' },
    { statement: 'Marco Polo travelled from Italy to China', answer: true, difficulty: 'medium', topic: 'History' },
    { statement: 'Shakespeare was born in London', answer: false, difficulty: 'medium', topic: 'History' },
    { statement: 'The Cold War was a military conflict with open battles', answer: false, difficulty: 'medium', topic: 'History' },
    { statement: 'Ancient Egypt used hieroglyphics as a form of writing', answer: true, difficulty: 'medium', topic: 'History' },
    { statement: 'The Magna Carta was signed in 1215', answer: true, difficulty: 'medium', topic: 'History' },
    { statement: 'The Aztec Empire was in North America', answer: false, difficulty: 'medium', topic: 'History' },
    { statement: 'The Industrial Revolution began in Britain', answer: true, difficulty: 'medium', topic: 'History' },
    { statement: 'Nelson Mandela spent 27 years in prison', answer: true, difficulty: 'medium', topic: 'History' },
    // Hard
    { statement: 'The Battle of Hastings took place in 1066', answer: true, difficulty: 'hard', topic: 'History' },
    { statement: 'Genghis Khan founded the largest contiguous empire in history', answer: true, difficulty: 'hard', topic: 'History' },
    { statement: 'The Treaty of Versailles ended World War One', answer: true, difficulty: 'hard', topic: 'History' },
    { statement: 'Pompeii was destroyed by an earthquake', answer: false, difficulty: 'hard', topic: 'History' },
    { statement: 'The Hundred Years War lasted exactly 100 years', answer: false, difficulty: 'hard', topic: 'History' },
    { statement: 'The Byzantine Empire was the continuation of the Roman Empire', answer: true, difficulty: 'hard', topic: 'History' },
    { statement: 'Cleopatra lived closer in time to us than to the building of the pyramids', answer: true, difficulty: 'hard', topic: 'History' },
    { statement: 'The first World War started because of the assassination of Archduke Franz Ferdinand', answer: true, difficulty: 'hard', topic: 'History' },
    { statement: 'The Silk Road was only used for trading silk', answer: false, difficulty: 'hard', topic: 'History' },
    { statement: 'The Renaissance started in Italy', answer: true, difficulty: 'hard', topic: 'History' },
    { statement: 'The Spanish Armada was defeated by Japan', answer: false, difficulty: 'hard', topic: 'History' },
    { statement: 'The Opium Wars were fought between Britain and China', answer: true, difficulty: 'hard', topic: 'History' },
    { statement: 'Nikola Tesla invented the telephone', answer: false, difficulty: 'hard', topic: 'History' },
    { statement: 'The Meiji Restoration modernised Japan in the 19th century', answer: true, difficulty: 'hard', topic: 'History' },
    { statement: 'The Cuban Missile Crisis happened in 1962', answer: true, difficulty: 'hard', topic: 'History' },
  ],
  Thailand: [
    // Easy
    { statement: 'Thailand is in Asia', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'The capital of Thailand is Chiang Mai', answer: false, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Thai food is often spicy', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Thailand has a king', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Thai people greet with a wai', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Pad Thai is a popular Thai dish', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Thailand is also called the Land of Smiles', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Elephants are important in Thai culture', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Thailand uses the Euro as its currency', answer: false, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Temples in Thailand are called Wats', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Thai people eat rice every day', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Thailand is a very cold country', answer: false, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Bangkok is the capital city of Thailand', answer: true, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Muay Thai is a type of cooking', answer: false, difficulty: 'easy', topic: 'Thailand' },
    { statement: 'Thailand is famous for its beaches', answer: true, difficulty: 'easy', topic: 'Thailand' },
    // Medium
    { statement: 'Thailand was formerly known as Siam', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'The Thai flag has three colours', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'Songkran is the Thai New Year water festival', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'Thailand was colonised by Britain', answer: false, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'The Thai alphabet has 44 consonants', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'Tom Yum is a type of Thai soup', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'Phuket is an island in southern Thailand', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'The official religion of Thailand is Islam', answer: false, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'Thailand shares a border with Cambodia', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'The Thai currency is called the Ringgit', answer: false, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'Loy Krathong is a festival of lights celebrated in Thailand', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'Chiang Mai is in the north of Thailand', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'Thailand is the worlds largest exporter of rice', answer: false, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'The tuk tuk is a popular form of transport in Thailand', answer: true, difficulty: 'medium', topic: 'Thailand' },
    { statement: 'Thai people drive on the left side of the road', answer: true, difficulty: 'medium', topic: 'Thailand' },
    // Hard
    { statement: 'Thailand has never been colonised by a European power', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'The Grand Palace is located in Chiang Mai', answer: false, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'The name Thailand means Land of the Free', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'Thailand has 77 provinces', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'The Chao Phraya River flows through Bangkok', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'Muay Thai has been practiced for over 2000 years', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'Thailand is the second largest country in Southeast Asia', answer: false, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'The Emerald Buddha is made of jade not emerald', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'Thailand shares its longest border with Myanmar', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'The Thai monarchy is the oldest in the world', answer: false, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'Ayutthaya was the ancient capital of Thailand', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'Thailand has five UNESCO World Heritage Sites', answer: false, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'The Thai New Year is celebrated in April', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'Doi Inthanon is the highest mountain in Thailand', answer: true, difficulty: 'hard', topic: 'Thailand' },
    { statement: 'Thailand has a population of over 70 million people', answer: true, difficulty: 'hard', topic: 'Thailand' },
  ],
  English: [
    // Easy
    { statement: 'A noun is a person place or thing', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'A verb is a doing word', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'Cat is spelled C-A-T', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'There are 25 letters in the English alphabet', answer: false, difficulty: 'easy', topic: 'English' },
    { statement: 'A sentence starts with a capital letter', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'Happy is an adjective', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'Run is a noun', answer: false, difficulty: 'easy', topic: 'English' },
    { statement: 'A question ends with a question mark', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'The opposite of hot is cold', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'Blue is a noun', answer: false, difficulty: 'easy', topic: 'English' },
    { statement: 'I comes before E except after C always', answer: false, difficulty: 'easy', topic: 'English' },
    { statement: 'A full stop ends a sentence', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'Big and large have similar meanings', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'An exclamation mark shows strong feeling', answer: true, difficulty: 'easy', topic: 'English' },
    { statement: 'All verbs end in ing', answer: false, difficulty: 'easy', topic: 'English' },
    // Medium
    { statement: 'A synonym is a word with the same meaning', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'An antonym is a word with the opposite meaning', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'Quickly is an adverb', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'A pronoun replaces a noun', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'Commas are used to separate items in a list', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'Shakespeare wrote Romeo and Juliet', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'A simile compares using like or as', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'A metaphor uses the words like or as', answer: false, difficulty: 'medium', topic: 'English' },
    { statement: 'Alliteration uses the same vowel sound repeatedly', answer: false, difficulty: 'medium', topic: 'English' },
    { statement: 'Went is the past tense of go', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'An apostrophe can show possession', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'A paragraph should only ever have one sentence', answer: false, difficulty: 'medium', topic: 'English' },
    { statement: 'Beautiful is an adjective', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'Active voice means the subject performs the action', answer: true, difficulty: 'medium', topic: 'English' },
    { statement: 'A haiku is a poem with 5 7 5 syllables', answer: true, difficulty: 'medium', topic: 'English' },
    // Hard
    { statement: 'An oxymoron is a phrase that combines contradictory terms', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'A gerund is a verb used as a noun', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'Onomatopoeia means a word that sounds like its meaning', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'The subjunctive mood expresses certainty', answer: false, difficulty: 'hard', topic: 'English' },
    { statement: 'A clause must contain a subject and a verb', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'Euphemism is using harsh language to shock the reader', answer: false, difficulty: 'hard', topic: 'English' },
    { statement: 'A preposition shows the relationship between a noun and another word', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'Personification gives human qualities to objects', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'An independent clause can stand alone as a sentence', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'Juxtaposition places contrasting ideas side by side', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'A conjunction joins two clauses together', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'Hyperbole is deliberate understatement', answer: false, difficulty: 'hard', topic: 'English' },
    { statement: 'An auxiliary verb helps the main verb', answer: true, difficulty: 'hard', topic: 'English' },
    { statement: 'Assonance is the repetition of consonant sounds', answer: false, difficulty: 'hard', topic: 'English' },
    { statement: 'A rhetorical question expects no answer', answer: true, difficulty: 'hard', topic: 'English' },
  ],
  Sport: [
    // Easy
    { statement: 'Football is played with a round ball', answer: true, difficulty: 'easy', topic: 'Sport' },
    { statement: 'A tennis match is played on a pitch', answer: false, difficulty: 'easy', topic: 'Sport' },
    { statement: 'Swimming takes place in water', answer: true, difficulty: 'easy', topic: 'Sport' },
    { statement: 'A basketball hoop is on the ground', answer: false, difficulty: 'easy', topic: 'Sport' },
    { statement: 'A goalkeeper protects the goal in football', answer: true, difficulty: 'easy', topic: 'Sport' },
    { statement: 'Golf uses a bat to hit the ball', answer: false, difficulty: 'easy', topic: 'Sport' },
    { statement: 'The Olympics happen every four years', answer: true, difficulty: 'easy', topic: 'Sport' },
    { statement: 'A red card in football means you can stay on the pitch', answer: false, difficulty: 'easy', topic: 'Sport' },
    { statement: 'Boxing uses padded gloves', answer: true, difficulty: 'easy', topic: 'Sport' },
    { statement: 'A marathon is a short running race', answer: false, difficulty: 'easy', topic: 'Sport' },
    { statement: 'Volleyball is played over a net', answer: true, difficulty: 'easy', topic: 'Sport' },
    { statement: 'A referee makes decisions in a sport', answer: true, difficulty: 'easy', topic: 'Sport' },
    { statement: 'Badminton uses a shuttlecock', answer: true, difficulty: 'easy', topic: 'Sport' },
    { statement: 'Cricket is played with a round bat', answer: false, difficulty: 'easy', topic: 'Sport' },
    { statement: 'A penalty in football is taken from the penalty spot', answer: true, difficulty: 'easy', topic: 'Sport' },
    // Medium
    { statement: 'A standard football match lasts 90 minutes', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'The Tour de France is a swimming competition', answer: false, difficulty: 'medium', topic: 'Sport' },
    { statement: 'A grand slam in tennis means winning all four major tournaments', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'Rugby union has 13 players per side', answer: false, difficulty: 'medium', topic: 'Sport' },
    { statement: 'A century in cricket means scoring 100 runs', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'Usain Bolt is a famous sprinter from Jamaica', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'The Super Bowl is the championship of American football', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'A yellow card in football means immediate dismissal', answer: false, difficulty: 'medium', topic: 'Sport' },
    { statement: 'The Ashes is a cricket series between England and Australia', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'A hat trick in football means scoring three goals', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'Polo is played on horseback', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'Table tennis originated in Japan', answer: false, difficulty: 'medium', topic: 'Sport' },
    { statement: 'Sumo wrestling is a traditional Japanese sport', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'A birdie in golf means one under par', answer: true, difficulty: 'medium', topic: 'Sport' },
    { statement: 'The FIFA World Cup is held every four years', answer: true, difficulty: 'medium', topic: 'Sport' },
    // Hard
    { statement: 'The first modern Olympic Games were held in Athens in 1896', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'A standard swimming pool for competition is 50 metres long', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'Fencing is a combat sport using three types of weapons', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'The Ryder Cup is a golf competition between Europe and the USA', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'A decathlon has ten events', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'Michael Jordan played for the Los Angeles Lakers', answer: false, difficulty: 'hard', topic: 'Sport' },
    { statement: 'The offside rule applies in basketball', answer: false, difficulty: 'hard', topic: 'Sport' },
    { statement: 'A triathlon consists of swimming cycling and running', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'A snooker table has six pockets', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'The Davis Cup is a tennis competition', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'Synchronized swimming is an Olympic sport', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'A perfect score in gymnastics is 20', answer: false, difficulty: 'hard', topic: 'Sport' },
    { statement: 'The marathon distance is 42.195 kilometres', answer: true, difficulty: 'hard', topic: 'Sport' },
    { statement: 'Archery was removed from the Olympics after 1920', answer: false, difficulty: 'hard', topic: 'Sport' },
    { statement: 'A slam dunk scores three points in basketball', answer: false, difficulty: 'hard', topic: 'Sport' },
  ],
}

export function getQuestionsByDifficulty(topic: string, difficulty: Difficulty): TFQuestion[] {
  const bank = tfBank[topic] || tfBank['Animals']
  return bank.filter(q => q.difficulty === difficulty)
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}