export const questionBank: Record<string, { q: string; options: string[]; answer: string }[]> = {
  'P1-P2': [
    { q: 'What do plants need to grow?', options: ['sand', 'sunlight', 'rocks', 'metal'], answer: 'sunlight' },
    { q: 'Which animal is a mammal?', options: ['fish', 'snake', 'dog', 'frog'], answer: 'dog' },
    { q: 'What do we breathe?', options: ['water', 'air', 'food', 'light'], answer: 'air' },
    { q: 'Which is a living thing?', options: ['rock', 'tree', 'chair', 'water'], answer: 'tree' },
    { q: 'What covers most of the Earth?', options: ['land', 'ice', 'water', 'sand'], answer: 'water' },
    { q: 'Which sense do we use to hear?', options: ['eyes', 'nose', 'ears', 'hands'], answer: 'ears' },
    { q: 'What do caterpillars turn into?', options: ['bees', 'flies', 'butterflies', 'moths'], answer: 'butterflies' },
    { q: 'Which is NOT a living thing?', options: ['cat', 'flower', 'stone', 'tree'], answer: 'stone' },
    { q: 'What do birds use to fly?', options: ['legs', 'wings', 'fins', 'arms'], answer: 'wings' },
    { q: 'What is the closest star to Earth?', options: ['moon', 'sun', 'Mars', 'Venus'], answer: 'sun' },
    { q: 'What do fish use to breathe?', options: ['lungs', 'nose', 'gills', 'skin'], answer: 'gills' },
    { q: 'What gives plants their green colour?', options: ['water', 'sunlight', 'chlorophyll', 'soil'], answer: 'chlorophyll' },
    { q: 'Which animal lives in the sea?', options: ['lion', 'elephant', 'whale', 'giraffe'], answer: 'whale' },
    { q: 'What is ice?', options: ['hot water', 'frozen water', 'steam', 'gas'], answer: 'frozen water' },
    { q: 'Which sense do we use to smell?', options: ['eyes', 'ears', 'nose', 'tongue'], answer: 'nose' },
    { q: 'What do animals need to stay alive?', options: ['toys', 'food and water', 'clothes', 'books'], answer: 'food and water' },
    { q: 'Which animal lays eggs?', options: ['dog', 'cat', 'chicken', 'rabbit'], answer: 'chicken' },
    { q: 'What happens to water when it is heated?', options: ['freezes', 'turns to ice', 'evaporates', 'turns to stone'], answer: 'evaporates' },
    { q: 'What do roots do for a plant?', options: ['make food', 'absorb water', 'make seeds', 'catch sunlight'], answer: 'absorb water' },
    { q: 'What is a tadpole?', options: ['a baby fish', 'a baby frog', 'a baby bird', 'a baby snake'], answer: 'a baby frog' },
    { q: 'Which planet do we live on?', options: ['Mars', 'Venus', 'Earth', 'Jupiter'], answer: 'Earth' },
    { q: 'What is rain made of?', options: ['ice', 'steam', 'water', 'gas'], answer: 'water' },
    { q: 'Which is a metal?', options: ['wood', 'plastic', 'glass', 'iron'], answer: 'iron' },
    { q: 'What does a thermometer measure?', options: ['weight', 'height', 'temperature', 'speed'], answer: 'temperature' },
    { q: 'Which sense do we use to taste?', options: ['eyes', 'ears', 'nose', 'tongue'], answer: 'tongue' },
    { q: 'What do bees collect from flowers?', options: ['water', 'nectar', 'soil', 'leaves'], answer: 'nectar' },
    { q: 'Which body part pumps blood?', options: ['lungs', 'brain', 'heart', 'stomach'], answer: 'heart' },
    { q: 'Which animal is a reptile?', options: ['dog', 'cat', 'lizard', 'fish'], answer: 'lizard' },
    { q: 'What do lungs do?', options: ['digest food', 'pump blood', 'help us breathe', 'think'], answer: 'help us breathe' },
    { q: 'Which is a source of light?', options: ['rock', 'wood', 'sun', 'soil'], answer: 'sun' },
    { q: 'What is the moon?', options: ['a star', 'a planet', 'a satellite of Earth', 'the sun'], answer: 'a satellite of Earth' },
    { q: 'Which material can you see through?', options: ['wood', 'metal', 'glass', 'stone'], answer: 'glass' },
    { q: 'What do plants make from sunlight?', options: ['water', 'oxygen only', 'food', 'soil'], answer: 'food' },
    { q: 'Which is an insect?', options: ['spider', 'worm', 'ant', 'snail'], answer: 'ant' },
    { q: 'Which keeps us warm in cold weather?', options: ['water', 'clothes', 'metal', 'glass'], answer: 'clothes' },
    { q: 'Which floats on water?', options: ['rock', 'metal coin', 'wood', 'iron nail'], answer: 'wood' },
    { q: 'Which is heavier — a rock or a feather?', options: ['feather', 'rock', 'they are the same', 'it depends on size'], answer: 'rock' },
    { q: 'Which is a natural material?', options: ['plastic', 'glass', 'wood', 'nylon'], answer: 'wood' },
    { q: 'What do we use to see?', options: ['ears', 'nose', 'eyes', 'hands'], answer: 'eyes' },
    { q: 'What is the sky made of?', options: ['water', 'smoke', 'air', 'glass'], answer: 'air' },
  ],
  'P3-P4': [
    { q: 'What is photosynthesis?', options: ['how animals breathe', 'how plants make food using sunlight', 'how fish swim', 'how clouds form'], answer: 'how plants make food using sunlight' },
    { q: 'Which gas do plants produce during photosynthesis?', options: ['carbon dioxide', 'nitrogen', 'oxygen', 'hydrogen'], answer: 'oxygen' },
    { q: 'What is a food chain?', options: ['a chain used in factories', 'the order in which animals eat each other', 'a type of plant', 'how water moves'], answer: 'the order in which animals eat each other' },
    { q: 'What is the state of water at 100°C?', options: ['solid', 'liquid', 'gas', 'plasma'], answer: 'gas' },
    { q: 'Which planet is closest to the Sun?', options: ['Earth', 'Venus', 'Mercury', 'Mars'], answer: 'Mercury' },
    { q: 'What is gravity?', options: ['a type of light', 'a force that pulls things down', 'a type of gas', 'a type of energy'], answer: 'a force that pulls things down' },
    { q: 'Which organ filters blood in the body?', options: ['heart', 'lungs', 'kidney', 'stomach'], answer: 'kidney' },
    { q: 'What is a habitat?', options: ["an animal's food", 'the natural home of an animal', 'a type of plant', 'a weather condition'], answer: 'the natural home of an animal' },
    { q: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], answer: '8' },
    { q: 'What is condensation?', options: ['water turning to ice', 'water vapour turning to liquid', 'ice turning to water', 'water turning to steam'], answer: 'water vapour turning to liquid' },
    { q: 'Which force slows things down?', options: ['gravity', 'magnetism', 'friction', 'electricity'], answer: 'friction' },
    { q: 'What do herbivores eat?', options: ['only meat', 'only plants', 'meat and plants', 'only fish'], answer: 'only plants' },
    { q: 'What is the hardest natural substance?', options: ['gold', 'iron', 'diamond', 'quartz'], answer: 'diamond' },
    { q: 'Which organ controls the body?', options: ['heart', 'lungs', 'kidney', 'brain'], answer: 'brain' },
    { q: 'What gas do humans breathe in?', options: ['carbon dioxide', 'nitrogen', 'oxygen', 'hydrogen'], answer: 'oxygen' },
    { q: 'What is evaporation?', options: ['liquid turning to gas', 'gas turning to liquid', 'solid turning to liquid', 'liquid turning to solid'], answer: 'liquid turning to gas' },
    { q: 'Which is a predator?', options: ['rabbit', 'deer', 'lion', 'cow'], answer: 'lion' },
    { q: 'What is a vertebrate?', options: ['an animal without a backbone', 'an animal with a backbone', 'a type of plant', 'an insect'], answer: 'an animal with a backbone' },
    { q: 'Which metal is attracted to a magnet?', options: ['gold', 'silver', 'iron', 'copper'], answer: 'iron' },
    { q: 'What causes day and night?', options: ['the moon moving', 'the Earth orbiting the sun', 'the Earth rotating', 'the sun moving'], answer: 'the Earth rotating' },
    { q: 'Which is a non-renewable energy source?', options: ['solar', 'wind', 'coal', 'water'], answer: 'coal' },
    { q: 'What is an invertebrate?', options: ['an animal with a backbone', 'an animal without a backbone', 'a type of plant', 'a large animal'], answer: 'an animal without a backbone' },
    { q: 'What is the function of leaves?', options: ['absorb water', 'make food through photosynthesis', 'absorb minerals', 'anchor the plant'], answer: 'make food through photosynthesis' },
    { q: 'Which part of the plant absorbs water from soil?', options: ['leaves', 'stem', 'roots', 'flowers'], answer: 'roots' },
    { q: 'What is a carnivore?', options: ['eats only plants', 'eats plants and animals', 'eats only animals', 'eats only insects'], answer: 'eats only animals' },
    { q: 'What is the Sun made of?', options: ['rock', 'ice', 'water', 'hot gas'], answer: 'hot gas' },
    { q: 'Which type of rock is formed from cooled lava?', options: ['sedimentary', 'metamorphic', 'igneous', 'limestone'], answer: 'igneous' },
    { q: 'What is the unit for measuring force?', options: ['kilogram', 'metre', 'Newton', 'litre'], answer: 'Newton' },
    { q: 'Which material is a good conductor of electricity?', options: ['wood', 'rubber', 'plastic', 'copper'], answer: 'copper' },
    { q: 'What is a fossil?', options: ['a living animal', 'remains of ancient organisms preserved in rock', 'a type of rock', 'a type of mineral'], answer: 'remains of ancient organisms preserved in rock' },
    { q: 'What is the largest planet in our solar system?', options: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'], answer: 'Jupiter' },
    { q: 'Which gas makes up most of Earth\'s atmosphere?', options: ['oxygen', 'carbon dioxide', 'nitrogen', 'hydrogen'], answer: 'nitrogen' },
    { q: 'What is a species?', options: ['a group of similar animals that can breed together', 'a type of habitat', 'a type of food chain', 'a group of plants'], answer: 'a group of similar animals that can breed together' },
    { q: 'What does a compass detect?', options: ['gravity', 'electricity', 'magnetic fields', 'temperature'], answer: 'magnetic fields' },
    { q: 'What is adaptation?', options: ['how animals move', 'how animals change to suit their environment', 'how plants grow', 'how animals find food'], answer: 'how animals change to suit their environment' },
    { q: 'What is a lunar eclipse?', options: ['when Earth blocks sunlight to the moon', 'when the moon blocks sunlight to Earth', 'when the sun disappears', 'when the stars align'], answer: 'when Earth blocks sunlight to the moon' },
    { q: 'What is a producer in a food chain?', options: ['an animal that eats meat', 'a plant that makes its own food', 'an animal that eats plants', 'a decomposer'], answer: 'a plant that makes its own food' },
    { q: 'What is the water cycle?', options: ['how fish move', 'how water moves through nature', 'how plants drink', 'how rain is made in factories'], answer: 'how water moves through nature' },
    { q: 'What is the process where a solid turns directly into a gas?', options: ['evaporation', 'condensation', 'sublimation', 'melting'], answer: 'sublimation' },
    { q: 'What is the function of the skeleton?', options: ['to digest food', 'to support and protect the body', 'to pump blood', 'to help breathing'], answer: 'to support and protect the body' },
  ],
  'P5-P6': [
    { q: 'What is an atom?', options: ['the smallest unit of an element', 'a type of molecule', 'a type of compound', 'a large particle'], answer: 'the smallest unit of an element' },
    { q: 'What is the chemical formula for water?', options: ['CO2', 'H2O', 'O2', 'NaCl'], answer: 'H2O' },
    { q: "What is Newton's First Law?", options: ['objects always fall', 'objects stay at rest or in motion unless a force acts', 'every action has a reaction', 'force equals mass times acceleration'], answer: 'objects stay at rest or in motion unless a force acts' },
    { q: 'What is a cell?', options: ['the basic unit of life', 'a type of battery', 'a type of molecule', 'a group of atoms'], answer: 'the basic unit of life' },
    { q: 'What is an ecosystem?', options: ['a single animal', 'a community of living things and their environment', 'a type of habitat', 'a food chain'], answer: 'a community of living things and their environment' },
    { q: 'What is the chemical symbol for oxygen?', options: ['O', 'O2', 'Ox', 'Or'], answer: 'O' },
    { q: 'What is the formula for speed?', options: ['distance x time', 'distance ÷ time', 'time ÷ distance', 'force x mass'], answer: 'distance ÷ time' },
    { q: 'What is an acid?', options: ['a substance with pH above 7', 'a substance with pH below 7', 'a neutral substance', 'a type of salt'], answer: 'a substance with pH below 7' },
    { q: 'What is DNA?', options: ['a type of protein', 'the molecule that carries genetic information', 'a type of cell', 'a type of enzyme'], answer: 'the molecule that carries genetic information' },
    { q: 'What is the greenhouse effect?', options: ['growing plants in greenhouses', 'heat being trapped in atmosphere by gases', 'the effect of sunlight on plants', 'evaporation from forests'], answer: 'heat being trapped in atmosphere by gases' },
    { q: "What is Newton's Second Law?", options: ['F = ma', 'F = mv', 'F = m/a', 'F = m + a'], answer: 'F = ma' },
    { q: 'What is the chemical symbol for carbon?', options: ['Ca', 'Co', 'C', 'Cr'], answer: 'C' },
    { q: 'What is biodiversity?', options: ['the variety of life in an area', 'how animals adapt', 'a type of ecosystem', 'how many plants there are'], answer: 'the variety of life in an area' },
    { q: 'What is the difference between mass and weight?', options: ['they are the same thing', 'mass is the amount of matter, weight is the force of gravity on it', 'weight is measured in kg', 'mass changes with location'], answer: 'mass is the amount of matter, weight is the force of gravity on it' },
    { q: 'What is a chemical reaction?', options: ['mixing two liquids', 'when substances combine to form new substances', 'heating a material', 'dissolving a solid'], answer: 'when substances combine to form new substances' },
    { q: 'What is the role of mitochondria in a cell?', options: ['to control the cell', 'to produce energy', 'to store water', 'to make proteins'], answer: 'to produce energy' },
    { q: 'What is the periodic table?', options: ['a timetable for science class', 'a table of all known elements', 'a table of compounds', 'a list of molecules'], answer: 'a table of all known elements' },
    { q: 'What is the formula for density?', options: ['mass + volume', 'mass x volume', 'mass ÷ volume', 'volume ÷ mass'], answer: 'mass ÷ volume' },
    { q: 'What is a catalyst?', options: ['a type of chemical reaction', 'a substance that speeds up a reaction without being used up', 'a type of acid', 'a type of bond'], answer: 'a substance that speeds up a reaction without being used up' },
    { q: 'What is natural selection?', options: ['humans choosing animals to breed', 'organisms with favourable traits survive to reproduce', 'a type of adaptation', 'how plants reproduce'], answer: 'organisms with favourable traits survive to reproduce' },
    { q: 'What is the chemical symbol for sodium?', options: ['S', 'So', 'Na', 'Sd'], answer: 'Na' },
    { q: 'What is refraction?', options: ['light bouncing off a surface', 'light bending as it passes through a medium', 'light being absorbed', 'light being blocked'], answer: 'light bending as it passes through a medium' },
    { q: 'What is the nucleus in a cell?', options: ['the cell wall', 'the control centre containing DNA', 'the energy producer', 'the outer membrane'], answer: 'the control centre containing DNA' },
    { q: 'What is osmosis?', options: ['movement of water through a membrane from high to low concentration', 'movement of sugar through plants', 'how plants absorb sunlight', 'how cells divide'], answer: 'movement of water through a membrane from high to low concentration' },
    { q: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], answer: 'Au' },
    { q: 'What is the name for the process where cells divide?', options: ['photosynthesis', 'respiration', 'mitosis', 'osmosis'], answer: 'mitosis' },
    { q: 'What is the chemical formula for carbon dioxide?', options: ['CO', 'CO2', 'C2O', 'CO3'], answer: 'CO2' },
    { q: 'What is a neutron?', options: ['a positively charged particle in the nucleus', 'a negatively charged particle outside the nucleus', 'a neutral particle in the nucleus', 'a type of atom'], answer: 'a neutral particle in the nucleus' },
    { q: 'What does pH measure?', options: ['temperature', 'acidity or alkalinity', 'pressure', 'density'], answer: 'acidity or alkalinity' },
    { q: 'What is kinetic energy?', options: ['stored energy', 'energy of movement', 'heat energy', 'light energy'], answer: 'energy of movement' },
    { q: 'What is the function of the chloroplast?', options: ['to store water', 'to control the cell', 'to absorb sunlight for photosynthesis', 'to produce energy'], answer: 'to absorb sunlight for photosynthesis' },
    { q: 'What is the unit for measuring electrical resistance?', options: ['Volt', 'Ampere', 'Ohm', 'Watt'], answer: 'Ohm' },
    { q: 'What is a proton?', options: ['a positively charged particle in the nucleus', 'a negatively charged particle', 'a neutral particle', 'a type of molecule'], answer: 'a positively charged particle in the nucleus' },
    { q: 'What is evolution?', options: ['how individual animals change in their lifetime', 'how species change over generations', 'how animals adapt to weather', 'how plants grow'], answer: 'how species change over generations' },
    { q: 'What is the chemical symbol for iron?', options: ['I', 'Ir', 'Fe', 'In'], answer: 'Fe' },
    { q: 'What is potential energy?', options: ['energy of movement', 'stored energy based on position or state', 'heat energy', 'electrical energy'], answer: 'stored energy based on position or state' },
    { q: 'What is the food web?', options: ['how food is transported', 'a network of connected food chains', 'how animals find food', 'how plants absorb nutrients'], answer: 'a network of connected food chains' },
    { q: 'What is the chemical formula for salt (sodium chloride)?', options: ['NaCl', 'NaOH', 'HCl', 'Na2O'], answer: 'NaCl' },
    { q: 'What is the difference between renewable and non-renewable energy?', options: ['renewable runs out, non-renewable does not', 'non-renewable runs out, renewable does not', 'they are the same', 'renewable is made by humans'], answer: 'non-renewable runs out, renewable does not' },
    { q: 'What is the speed of light?', options: ['100,000 km/s', '200,000 km/s', '300,000 km/s', '400,000 km/s'], answer: '300,000 km/s' },
  ],
  'M1-M3': [
    { q: 'What is the atomic number of an element?', options: ['the number of neutrons', 'the number of protons', 'the mass number', 'the number of electrons and protons combined'], answer: 'the number of protons' },
    { q: "What is Ohm's Law?", options: ['V = IR', 'V = I/R', 'V = I + R', 'V = I - R'], answer: 'V = IR' },
    { q: 'What is the difference between mitosis and meiosis?', options: ['mitosis produces 4 cells, meiosis produces 2', 'mitosis produces 2 identical cells, meiosis produces 4 genetically different cells', 'they are the same process', 'meiosis only occurs in plants'], answer: 'mitosis produces 2 identical cells, meiosis produces 4 genetically different cells' },
    { q: 'What is the pH of pure water?', options: ['5', '6', '7', '8'], answer: '7' },
    { q: "What is Newton's Third Law?", options: ['F = ma', 'objects stay at rest unless a force acts', 'every action has an equal and opposite reaction', 'energy cannot be created or destroyed'], answer: 'every action has an equal and opposite reaction' },
    { q: 'What is the chemical formula for glucose?', options: ['C6H12O6', 'C2H5OH', 'CH4', 'C6H6'], answer: 'C6H12O6' },
    { q: 'What is the electron configuration of carbon (atomic number 6)?', options: ['2,2', '2,4', '2,6', '4,2'], answer: '2,4' },
    { q: 'What is the Law of Conservation of Energy?', options: ['energy can be created from nothing', 'energy cannot be created or destroyed, only transferred', 'energy always decreases', 'energy is always conserved as heat'], answer: 'energy cannot be created or destroyed, only transferred' },
    { q: 'What is the difference between an element and a compound?', options: ['elements have molecules, compounds have atoms', 'elements consist of one type of atom, compounds consist of two or more types bonded together', 'they are the same thing', 'compounds cannot be broken down'], answer: 'elements consist of one type of atom, compounds consist of two or more types bonded together' },
    { q: 'What is the role of ribosomes in a cell?', options: ['to produce energy', 'to synthesize proteins', 'to store genetic information', 'to control the cell'], answer: 'to synthesize proteins' },
    { q: 'What is the half-life of a radioactive substance?', options: ['the time for all atoms to decay', 'the time for half the atoms to decay', 'the energy released', 'the time for atoms to double'], answer: 'the time for half the atoms to decay' },
    { q: 'What is the equation for photosynthesis?', options: ['CO2 + H2O → glucose + O2', 'glucose + O2 → CO2 + H2O', 'H2O → H2 + O', 'C + H2O → CH4 + O'], answer: 'CO2 + H2O → glucose + O2' },
    { q: 'What is an ionic bond?', options: ['sharing of electrons between atoms', 'transfer of electrons between atoms creating oppositely charged ions', 'a weak attraction between molecules', 'a triple bond between atoms'], answer: 'transfer of electrons between atoms creating oppositely charged ions' },
    { q: 'What is the Doppler effect?', options: ['light bending in water', 'the change in frequency of a wave due to motion', 'sound travelling faster in water', 'the reflection of sound waves'], answer: 'the change in frequency of a wave due to motion' },
    { q: "What is Avogadro's number?", options: ['6.02 x 10²³', '3.14 x 10²³', '9.8 x 10²³', '1.6 x 10¹⁹'], answer: '6.02 x 10²³' },
    { q: 'What is the equation for aerobic respiration?', options: ['CO2 + H2O → glucose + O2', 'glucose + O2 → CO2 + H2O + energy', 'glucose → CO2 + ethanol + energy', 'H2O → H2 + O2'], answer: 'glucose + O2 → CO2 + H2O + energy' },
    { q: 'What is a covalent bond?', options: ['transfer of electrons between atoms', 'sharing of electrons between atoms', 'attraction between opposite ions', 'a metallic bond'], answer: 'sharing of electrons between atoms' },
    { q: 'What is the unit for measuring frequency?', options: ['Newton', 'Joule', 'Hertz', 'Watt'], answer: 'Hertz' },
    { q: 'What is a gene?', options: ['a type of cell', 'a section of DNA that codes for a protein', 'a type of chromosome', 'the complete DNA of an organism'], answer: 'a section of DNA that codes for a protein' },
    { q: "What is Boyle's Law?", options: ['at constant temperature, pressure and volume are directly proportional', 'at constant temperature, pressure and volume are inversely proportional', 'pressure increases with temperature', 'volume increases with temperature'], answer: 'at constant temperature, pressure and volume are inversely proportional' },
    { q: 'What is the difference between speed and velocity?', options: ['they are the same', 'speed is distance/time, velocity includes direction', 'velocity is faster than speed', 'speed includes direction, velocity does not'], answer: 'speed is distance/time, velocity includes direction' },
    { q: 'What is the atomic mass of carbon?', options: ['6', '8', '12', '14'], answer: '12' },
    { q: 'What is a mutation?', options: ['a type of reproduction', 'a change in the DNA sequence', 'how cells divide', 'a type of adaptation'], answer: 'a change in the DNA sequence' },
    { q: 'What is the formula for kinetic energy?', options: ['KE = mv', 'KE = ½mv²', 'KE = mgh', 'KE = mv²'], answer: 'KE = ½mv²' },
    { q: 'What is reduction in a chemical reaction?', options: ['loss of electrons', 'gain of electrons', 'loss of hydrogen', 'gain of oxygen'], answer: 'gain of electrons' },
    { q: 'What is the structure of DNA?', options: ['single helix', 'double helix', 'triple helix', 'circular'], answer: 'double helix' },
    { q: 'What is the law of conservation of mass?', options: ['mass is always increasing', 'mass is created in reactions', 'mass is neither created nor destroyed in a reaction', 'mass converts to energy'], answer: 'mass is neither created nor destroyed in a reaction' },
    { q: 'What is work done in physics?', options: ['force x time', 'force x distance', 'mass x acceleration', 'energy x time'], answer: 'force x distance' },
    { q: 'What is the difference between dominant and recessive alleles?', options: ['they are the same', 'dominant alleles are always expressed, recessive only when two copies present', 'recessive alleles are stronger', 'dominant alleles only appear in females'], answer: 'dominant alleles are always expressed, recessive only when two copies present' },
    { q: 'What is the electromagnetic spectrum?', options: ['the range of electrical currents', 'the range of all electromagnetic radiation from radio to gamma', 'visible light only', 'the range of magnetic fields'], answer: 'the range of all electromagnetic radiation from radio to gamma' },
    { q: 'What is the mole in chemistry?', options: ['6.02 x 10²³ particles', 'the mass of one atom', 'a unit of temperature', 'a unit of pressure'], answer: '6.02 x 10²³ particles' },
    { q: 'What is the difference between exothermic and endothermic reactions?', options: ['they are the same', 'exothermic releases heat, endothermic absorbs heat', 'exothermic absorbs heat, endothermic releases heat', 'exothermic is faster'], answer: 'exothermic releases heat, endothermic absorbs heat' },
    { q: 'What is the formula for gravitational potential energy?', options: ['GPE = mv', 'GPE = ½mv²', 'GPE = mgh', 'GPE = Fd'], answer: 'GPE = mgh' },
    { q: 'What is a chromosome?', options: ['a type of cell', 'a thread-like structure of DNA and protein carrying genes', 'a type of protein', 'a section of the nucleus'], answer: 'a thread-like structure of DNA and protein carrying genes' },
    { q: "What is Faraday's Law?", options: ['current causes magnetism', 'changing magnetic field induces an EMF', 'voltage equals current times resistance', 'power equals voltage times current'], answer: 'changing magnetic field induces an EMF' },
    { q: 'What is the oxidation state of oxygen in most compounds?', options: ['+2', '-1', '-2', '+1'], answer: '-2' },
    { q: 'What is the function of the Golgi apparatus?', options: ['to produce energy', 'to process and package proteins for secretion', 'to store genetic material', 'to carry out photosynthesis'], answer: 'to process and package proteins for secretion' },
    { q: 'What is the unit for measuring power?', options: ['Joule', 'Newton', 'Watt', 'Ampere'], answer: 'Watt' },
    { q: 'What is the function of the endoplasmic reticulum?', options: ['to produce energy', 'to transport materials within the cell', 'to control cell division', 'to store genetic material'], answer: 'to transport materials within the cell' },
    { q: 'What is the Hardy-Weinberg principle?', options: ['species evolve over time', 'allele frequencies in a population remain constant without evolution', 'mutations cause evolution', 'natural selection always occurs'], answer: 'allele frequencies in a population remain constant without evolution' },
  ],
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}
