export const questionBank: Record<string, { q: string; options: string[]; answer: string }[]> = {
  'P1-P2': [
    { q: 'Which of these is a fruit?', options: ['carrot', 'potato', 'onion', 'apple'], answer: 'apple' },
    { q: 'Which food do we get from a cow?', options: ['eggs', 'honey', 'milk', 'juice'], answer: 'milk' },
    { q: 'What colour is a banana?', options: ['red', 'green', 'blue', 'yellow'], answer: 'yellow' },
    { q: 'Which of these do we drink?', options: ['bread', 'rice', 'water', 'carrot'], answer: 'water' },
    { q: 'What do we use to eat soup?', options: ['fork', 'knife', 'spoon', 'plate'], answer: 'spoon' },
    { q: 'Which of these is a vegetable?', options: ['mango', 'orange', 'grape', 'carrot'], answer: 'carrot' },
    { q: 'What is the red sauce on pizza?', options: ['honey', 'tomato sauce', 'milk', 'butter'], answer: 'tomato sauce' },
    { q: 'Which food comes from a chicken?', options: ['milk', 'honey', 'eggs', 'butter'], answer: 'eggs' },
    { q: 'Which fruit is orange on the outside?', options: ['banana', 'grape', 'orange', 'mango'], answer: 'orange' },
    { q: 'What do bees make that we eat?', options: ['milk', 'honey', 'butter', 'sugar'], answer: 'honey' },
    { q: 'Which of these is a drink?', options: ['bread', 'rice', 'orange juice', 'cake'], answer: 'orange juice' },
    { q: 'What do we put butter on?', options: ['soup', 'juice', 'bread', 'milk'], answer: 'bread' },
    { q: 'Which of these is sweet?', options: ['lemon', 'onion', 'garlic', 'chocolate'], answer: 'chocolate' },
    { q: 'Which food is round, flat and has cheese on top?', options: ['soup', 'salad', 'pizza', 'rice'], answer: 'pizza' },
    { q: 'What do we eat with a fork and knife?', options: ['juice', 'soup', 'water', 'steak'], answer: 'steak' },
    { q: 'Which fruit is very sour and yellow?', options: ['apple', 'banana', 'mango', 'lemon'], answer: 'lemon' },
    { q: 'What is rice cooked in?', options: ['a frying pan', 'the oven', 'a pot of water', 'a blender'], answer: 'a pot of water' },
    { q: 'Which of these grows underground?', options: ['apple', 'banana', 'potato', 'mango'], answer: 'potato' },
    { q: 'What is bread made from?', options: ['rice', 'milk', 'flour', 'sugar'], answer: 'flour' },
    { q: 'Which colour are most vegetables?', options: ['red', 'yellow', 'green', 'purple'], answer: 'green' },
    { q: 'What do we call the meal we eat in the morning?', options: ['lunch', 'dinner', 'snack', 'breakfast'], answer: 'breakfast' },
    { q: 'Which of these is NOT a fruit?', options: ['strawberry', 'pineapple', 'cucumber', 'watermelon'], answer: 'cucumber' },
    { q: 'What do we add to food to make it taste better?', options: ['water', 'salt', 'milk', 'juice'], answer: 'salt' },
    { q: 'Which meal do we eat at midday?', options: ['breakfast', 'lunch', 'dinner', 'brunch'], answer: 'lunch' },
    { q: 'What is a sandwich made with?', options: ['pasta', 'rice', 'bread', 'noodles'], answer: 'bread' },
    { q: 'Which of these is a dairy product?', options: ['apple', 'carrot', 'cheese', 'bread'], answer: 'cheese' },
    { q: 'What do we call food that is not cooked?', options: ['hot', 'raw', 'cold', 'fried'], answer: 'raw' },
    { q: 'Which of these foods is spicy?', options: ['milk', 'honey', 'chilli', 'bread'], answer: 'chilli' },
    { q: 'What do we call the evening meal?', options: ['breakfast', 'brunch', 'lunch', 'dinner'], answer: 'dinner' },
    { q: 'Which of these is a grain?', options: ['apple', 'milk', 'rice', 'chicken'], answer: 'rice' },
    { q: 'What do we put on a salad to make it taste good?', options: ['jam', 'dressing', 'honey', 'milk'], answer: 'dressing' },
    { q: 'Which word means food that is cooked in hot oil?', options: ['boiled', 'baked', 'fried', 'grilled'], answer: 'fried' },
    { q: 'What is ice cream made from?', options: ['water', 'juice', 'cream', 'flour'], answer: 'cream' },
    { q: 'Which of these is a seafood?', options: ['chicken', 'beef', 'fish', 'pork'], answer: 'fish' },
    { q: 'What do we call a small meal between lunch and dinner?', options: ['breakfast', 'brunch', 'supper', 'snack'], answer: 'snack' },
    { q: 'Which fruit is red and small with seeds on the outside?', options: ['cherry', 'grape', 'strawberry', 'plum'], answer: 'strawberry' },
    { q: 'What word means the food tastes very nice?', options: ['sour', 'bitter', 'delicious', 'salty'], answer: 'delicious' },
    { q: 'Which of these do we use to cook food in the oven?', options: ['bowl', 'spoon', 'baking tray', 'glass'], answer: 'baking tray' },
    { q: 'Which word means food cooked in water?', options: ['fried', 'roasted', 'grilled', 'boiled'], answer: 'boiled' },
    { q: 'What do we call a person who cooks food in a restaurant?', options: ['waiter', 'chef', 'farmer', 'baker'], answer: 'chef' },
  ],
  'P3-P4': [
    { q: 'Which word describes food that is not sweet, not salty, but has a sharp taste like vinegar?', options: ['spicy', 'bitter', 'sour', 'bland'], answer: 'sour' },
    { q: 'What is the English word for cooking food over an open flame or hot grill?', options: ['boiling', 'steaming', 'baking', 'grilling'], answer: 'grilling' },
    { q: 'Which country is famous for sushi?', options: ['China', 'Korea', 'Japan', 'Thailand'], answer: 'Japan' },
    { q: 'What do we call food that has very little taste?', options: ['sour', 'spicy', 'bland', 'bitter'], answer: 'bland' },
    { q: 'Which ingredient makes bread rise when baking?', options: ['salt', 'sugar', 'yeast', 'butter'], answer: 'yeast' },
    { q: 'What is the correct English word for a meal eaten outside on the grass?', options: ['barbecue', 'picnic', 'buffet', 'brunch'], answer: 'picnic' },
    { q: 'Which word means cooking food slowly in liquid in a pot?', options: ['frying', 'grilling', 'stewing', 'baking'], answer: 'stewing' },
    { q: 'What do we call the list of food available in a restaurant?', options: ['recipe', 'menu', 'order', 'bill'], answer: 'menu' },
    { q: 'Which of these is a herb used in cooking?', options: ['pepper', 'salt', 'sugar', 'basil'], answer: 'basil' },
    { q: 'What do we call food that is grown without chemicals?', options: ['fresh', 'organic', 'natural', 'raw'], answer: 'organic' },
    { q: 'Which country is famous for pasta and pizza?', options: ['France', 'Spain', 'Mexico', 'Italy'], answer: 'Italy' },
    { q: 'What is the main ingredient in guacamole?', options: ['tomato', 'lemon', 'avocado', 'onion'], answer: 'avocado' },
    { q: 'Which word describes food that makes your mouth feel like it is burning?', options: ['sour', 'bitter', 'sweet', 'spicy'], answer: 'spicy' },
    { q: 'What do we call a person who does not eat meat?', options: ['vegan', 'vegetarian', 'pescatarian', 'flexitarian'], answer: 'vegetarian' },
    { q: 'Which method cooks food using hot steam from water?', options: ['frying', 'grilling', 'steaming', 'roasting'], answer: 'steaming' },
    { q: 'What do we call the money we pay after eating in a restaurant?', options: ['menu', 'order', 'receipt', 'bill'], answer: 'bill' },
    { q: 'Which country is famous for Tom Yum soup?', options: ['Japan', 'Vietnam', 'China', 'Thailand'], answer: 'Thailand' },
    { q: 'What is the main ingredient in hummus?', options: ['potato', 'peanuts', 'chickpeas', 'lentils'], answer: 'chickpeas' },
    { q: 'What do we call a meal where many dishes are laid out and you serve yourself?', options: ['picnic', 'barbecue', 'buffet', 'banquet'], answer: 'buffet' },
    { q: 'Which word describes food that has gone bad and is not safe to eat?', options: ['raw', 'fresh', 'rotten', 'bland'], answer: 'rotten' },
    { q: 'What do we call the instructions for making a dish?', options: ['menu', 'method', 'recipe', 'guide'], answer: 'recipe' },
    { q: 'Which of these is a cooking utensil?', options: ['plate', 'glass', 'wok', 'napkin'], answer: 'wok' },
    { q: 'What is the English word for the outside skin of a fruit?', options: ['seed', 'flesh', 'peel', 'core'], answer: 'peel' },
    { q: 'Which country is famous for croissants and baguettes?', options: ['Spain', 'Germany', 'UK', 'France'], answer: 'France' },
    { q: 'What do we call the process of keeping food cold to stop it going bad?', options: ['cooking', 'boiling', 'refrigerating', 'freezing'], answer: 'refrigerating' },
    { q: 'Which word means to cut food into very small pieces?', options: ['slice', 'mince', 'grate', 'peel'], answer: 'mince' },
    { q: 'What is naan bread traditionally eaten with?', options: ['sushi', 'pasta', 'curry', 'pizza'], answer: 'curry' },
    { q: 'What do we call food cooked on a tray in a hot oven?', options: ['fried', 'steamed', 'grilled', 'baked'], answer: 'baked' },
    { q: 'Which of these is a condiment?', options: ['steak', 'rice', 'ketchup', 'pasta'], answer: 'ketchup' },
    { q: 'What do we call the first course of a meal?', options: ['dessert', 'side dish', 'main course', 'starter'], answer: 'starter' },
    { q: 'Which word means to mix food quickly with a spoon or whisk?', options: ['chop', 'peel', 'stir', 'slice'], answer: 'stir' },
    { q: 'What do we call the sweet course eaten at the end of a meal?', options: ['starter', 'main course', 'side dish', 'dessert'], answer: 'dessert' },
    { q: 'Which country is famous for making kimchi?', options: ['Japan', 'China', 'Thailand', 'Korea'], answer: 'Korea' },
    { q: 'What do we call a sauce made from olive oil, vinegar and herbs for salad?', options: ['gravy', 'dressing', 'marinade', 'batter'], answer: 'dressing' },
    { q: 'Which word means to cook meat or vegetables quickly in a hot pan with a little oil?', options: ['boil', 'bake', 'stir-fry', 'steam'], answer: 'stir-fry' },
    { q: 'What is the soft inside part of a fruit called?', options: ['skin', 'seed', 'peel', 'flesh'], answer: 'flesh' },
    { q: 'What do we call a Thai dish of rice noodles fried with egg and sauce?', options: ['Tom Yum', 'Pad Thai', 'Som Tam', 'Khao Man Gai'], answer: 'Pad Thai' },
    { q: 'Which word means to cook something until it becomes brown and crispy?', options: ['boil', 'steam', 'toast', 'poach'], answer: 'toast' },
    { q: 'What is the English word for the person who serves you food in a restaurant?', options: ['chef', 'cook', 'waiter', 'host'], answer: 'waiter' },
    { q: 'Which of these words means the food has a strong, unpleasant smell because it is old?', options: ['bland', 'fresh', 'stale', 'rotten'], answer: 'stale' },
  ],
  'P5-P6': [
    { q: 'What does the cooking term "sauté" mean?', options: ['cook slowly in liquid', 'cook quickly in a pan with fat', 'cook in the oven', 'cook in boiling water'], answer: 'cook quickly in a pan with fat' },
    { q: 'Which word describes a diet that contains no animal products at all?', options: ['vegetarian', 'pescatarian', 'vegan', 'flexitarian'], answer: 'vegan' },
    { q: 'What is the English word for the Japanese dish of raw fish on rice?', options: ['ramen', 'tempura', 'sushi', 'udon'], answer: 'sushi' },
    { q: 'Which term means to cook vegetables briefly in boiling water then cool them quickly?', options: ['simmer', 'blanch', 'braise', 'roast'], answer: 'blanch' },
    { q: 'What is a "marinade"?', options: ['a type of pasta', 'a liquid used to flavour food before cooking', 'a cooking technique', 'a type of sauce served with fish'], answer: 'a liquid used to flavour food before cooking' },
    { q: 'Which country is the origin of the dish "paella"?', options: ['Italy', 'Portugal', 'Mexico', 'Spain'], answer: 'Spain' },
    { q: 'What does "al dente" mean when describing pasta?', options: ['overcooked and soft', 'cooked perfectly firm to the bite', 'undercooked and hard', 'cooked with butter'], answer: 'cooked perfectly firm to the bite' },
    { q: 'What is the process of cooking food slowly in the oven in fat or oil called?', options: ['steaming', 'blanching', 'poaching', 'roasting'], answer: 'roasting' },
    { q: 'Which spice is known as the most expensive in the world?', options: ['pepper', 'cinnamon', 'saffron', 'cardamom'], answer: 'saffron' },
    { q: 'What does "cuisine" mean?', options: ['a type of kitchen appliance', 'a style or method of cooking from a specific region', 'a cooking ingredient', 'a type of knife'], answer: 'a style or method of cooking from a specific region' },
    { q: 'What is the English word for a Vietnamese noodle soup?', options: ['ramen', 'udon', 'pho', 'laksa'], answer: 'pho' },
    { q: 'What does "garnish" mean in cooking?', options: ['to cook food thoroughly', 'to add a decorative item to a finished dish', 'to marinate food', 'to season with salt'], answer: 'to add a decorative item to a finished dish' },
    { q: 'Which of these is a fermented food?', options: ['fresh bread', 'raw carrot', 'yoghurt', 'boiled egg'], answer: 'yoghurt' },
    { q: 'What is the English word for thin strips of raw vegetables served as a starter?', options: ['coleslaw', 'crudités', 'tapas', 'antipasto'], answer: 'crudités' },
    { q: 'What does the term "braise" mean?', options: ['cook quickly at high heat', 'cook slowly in a covered pot with liquid', 'cook in steam', 'cook on an open flame'], answer: 'cook slowly in a covered pot with liquid' },
    { q: 'Which country is famous for "dim sum"?', options: ['Japan', 'Thailand', 'China', 'Vietnam'], answer: 'China' },
    { q: 'What is a "vinaigrette"?', options: ['a type of pasta', 'a French salad dressing made with oil and vinegar', 'a dessert', 'a cooking method'], answer: 'a French salad dressing made with oil and vinegar' },
    { q: 'What does "poach" mean in cooking?', options: ['cook in boiling water', 'cook gently in hot liquid below boiling point', 'cook in hot oil', 'cook in a microwave'], answer: 'cook gently in hot liquid below boiling point' },
    { q: 'Which of these describes food that is in season?', options: ['grown in a greenhouse all year', 'fresh and available naturally at a particular time of year', 'imported from another country', 'frozen for storage'], answer: 'fresh and available naturally at a particular time of year' },
    { q: 'What is the main ingredient in the Thai dish "Som Tam"?', options: ['rice', 'noodles', 'green papaya', 'tofu'], answer: 'green papaya' },
    { q: 'What does "savoury" mean?', options: ['sweet-tasting food', 'food that tastes of salt or spices, not sweet', 'food that is very spicy', 'food that is very healthy'], answer: 'food that tastes of salt or spices, not sweet' },
    { q: 'Which word describes cooking in the oven without any liquid or fat covering the food?', options: ['braising', 'steaming', 'dry roasting', 'poaching'], answer: 'dry roasting' },
    { q: 'What is a "sommelier"?', options: ['a head chef', 'a restaurant manager', 'a wine expert in a restaurant', 'a pastry chef'], answer: 'a wine expert in a restaurant' },
    { q: 'What does "umami" mean?', options: ['a sweet flavour', 'a sour flavour', 'a fifth basic taste described as savoury and rich', 'a bitter flavour'], answer: 'a fifth basic taste described as savoury and rich' },
    { q: 'Which of these is a leavening agent used in baking?', options: ['salt', 'vinegar', 'baking powder', 'butter'], answer: 'baking powder' },
    { q: 'What does "fusion cuisine" mean?', options: ['cooking only local ingredients', 'combining cooking styles from different cultures', 'cooking food very quickly', 'using only organic ingredients'], answer: 'combining cooking styles from different cultures' },
    { q: 'What is the English word for a thin pancake of French origin?', options: ['waffle', 'crepe', 'scone', 'muffin'], answer: 'crepe' },
    { q: 'Which of these describes the texture of well-cooked steak that is pink in the middle?', options: ['well done', 'raw', 'medium rare', 'overdone'], answer: 'medium rare' },
    { q: 'What does "infuse" mean in cooking?', options: ['mix two liquids together', 'let a flavour soak into a liquid by heating', 'add seasoning to food', 'cool food down quickly'], answer: 'let a flavour soak into a liquid by heating' },
    { q: 'What is a "broth"?', options: ['a thick stew', 'a thin flavoured liquid made by simmering meat or vegetables', 'a type of sauce', 'a type of bread'], answer: 'a thin flavoured liquid made by simmering meat or vegetables' },
    { q: 'Which term describes a dish that can be eaten by people with religious restrictions on pork?', options: ['organic', 'gluten-free', 'halal', 'vegan'], answer: 'halal' },
    { q: 'What does "reduce" mean in cooking?', options: ['use less salt', 'simmer a liquid until it thickens and becomes more flavourful', 'make a smaller portion', 'cool food down'], answer: 'simmer a liquid until it thickens and becomes more flavourful' },
    { q: 'Which of these is a type of bread from India?', options: ['focaccia', 'ciabatta', 'chapati', 'brioche'], answer: 'chapati' },
    { q: 'What does "gluten-free" mean?', options: ['food with no sugar', 'food containing no wheat protein', 'food with no salt', 'food that is not fried'], answer: 'food containing no wheat protein' },
    { q: 'What is the English word for the Korean barbecue dish of marinated grilled beef?', options: ['bibimbap', 'bulgogi', 'kimchi', 'japchae'], answer: 'bulgogi' },
    { q: 'What does "zest" mean in a recipe?', options: ['add extra sugar', 'the grated outer skin of a citrus fruit', 'the juice inside a fruit', 'the seed of a fruit'], answer: 'the grated outer skin of a citrus fruit' },
    { q: 'Which word describes a food that contains all the nutrients the body needs?', options: ['organic', 'nutritious', 'bland', 'processed'], answer: 'nutritious' },
    { q: 'What is the English term for Mexican food wrapped in a flour or corn tortilla?', options: ['burrito', 'dumpling', 'spring roll', 'samosa'], answer: 'burrito' },
    { q: 'What does "caramelise" mean in cooking?', options: ['add caramel to a dish', 'heat sugar until it turns brown and sweet', 'make food very spicy', 'cook food in cream'], answer: 'heat sugar until it turns brown and sweet' },
    { q: 'Which of these words means to cut food into thin, flat pieces?', options: ['mince', 'dice', 'slice', 'grate'], answer: 'slice' },
  ],
  'M1-M3': [
    { q: 'What does the culinary term "mise en place" mean?', options: ['a French dessert', 'everything in its place — having all ingredients prepared before cooking', 'a cooking technique from France', 'a type of presentation style'], answer: 'everything in its place — having all ingredients prepared before cooking' },
    { q: 'What is "molecular gastronomy"?', options: ['the study of nutrition', 'a cooking style using science and chemistry to create new textures and flavours', 'traditional French cuisine', 'the analysis of food ingredients'], answer: 'a cooking style using science and chemistry to create new textures and flavours' },
    { q: 'What does "sous vide" mean?', options: ['cooking under pressure', 'cooking in a vacuum-sealed bag in temperature-controlled water', 'cooking below freezing point', 'a French method of deep frying'], answer: 'cooking in a vacuum-sealed bag in temperature-controlled water' },
    { q: 'What is the English term for the process of removing bones from fish or meat?', options: ['trimming', 'marinating', 'deboning', 'rendering'], answer: 'deboning' },
    { q: 'What does "emulsify" mean in cooking?', options: ['add heat to a liquid', 'combine two liquids that do not normally mix such as oil and water', 'reduce a sauce', 'blend food into a paste'], answer: 'combine two liquids that do not normally mix such as oil and water' },
    { q: 'What is "food provenance"?', options: ['the nutritional content of food', 'the origin and history of where food comes from', 'the price of food in different countries', 'the process of packaging food'], answer: 'the origin and history of where food comes from' },
    { q: 'What does the term "farm to table" describe?', options: ['food that is frozen before delivery', 'food sourced directly from a farm to be served fresh in a restaurant', 'food grown using modern technology', 'imported food from overseas farms'], answer: 'food sourced directly from a farm to be served fresh in a restaurant' },
    { q: 'What is "food insecurity"?', options: ['not knowing how to cook', 'not having reliable access to enough affordable nutritious food', 'storing food incorrectly', 'uncertainty about food allergies'], answer: 'not having reliable access to enough affordable nutritious food' },
    { q: 'Which term describes the Maillard reaction in cooking?', options: ['food turning soft when boiled', 'the browning of food when exposed to high heat', 'food fermenting over time', 'oil separating from water'], answer: 'the browning of food when exposed to high heat' },
    { q: 'What is a "reduction" in culinary terms?', options: ['making a smaller portion of a dish', 'a sauce thickened and intensified by simmering', 'reducing the amount of salt in a recipe', 'a low-calorie version of a dish'], answer: 'a sauce thickened and intensified by simmering' },
    { q: 'What does "sustainable food" refer to?', options: ['food that lasts a long time in storage', 'food produced in ways that protect the environment and natural resources', 'food that is grown organically', 'food that is locally produced'], answer: 'food produced in ways that protect the environment and natural resources' },
    { q: 'What is "terroir" in the context of food and wine?', options: ['a French cooking technique', 'the environmental factors such as soil and climate that affect a crop\'s taste', 'the aging process of cheese', 'a type of vineyard layout'], answer: 'the environmental factors such as soil and climate that affect a crop\'s taste' },
    { q: 'What is a "deconstructed dish"?', options: ['food that has been blended into a liquid', 'a dish where the traditional components are presented separately in an artistic way', 'a dish that has been poorly made', 'a dish where the chef removed all fat'], answer: 'a dish where the traditional components are presented separately in an artistic way' },
    { q: 'What does "confit" mean?', options: ['a method of cooking and preserving food in its own fat at low temperature', 'a type of jam made from fruit', 'cooking food quickly at very high heat', 'a French word for fermentation'], answer: 'a method of cooking and preserving food in its own fat at low temperature' },
    { q: 'What is the English term for a detailed tasting menu in a fine dining restaurant?', options: ['buffet', 'à la carte', 'tasting menu', 'set menu'], answer: 'tasting menu' },
    { q: 'What does "à la carte" mean in a restaurant?', options: ['a fixed-price meal', 'ordering individual dishes separately from a menu', 'a style of French cooking', 'a table d\'hôte menu'], answer: 'ordering individual dishes separately from a menu' },
    { q: 'What is "food waste" as an environmental issue?', options: ['packaging that cannot be recycled', 'food that is produced but never eaten, wasting resources', 'water used in food production', 'energy used in cooking food'], answer: 'food that is produced but never eaten, wasting resources' },
    { q: 'What does "fermentation" do to food?', options: ['makes food freeze faster', 'breaks down sugars using microorganisms to preserve and flavour food', 'removes nutrients from food', 'makes food lose its colour'], answer: 'breaks down sugars using microorganisms to preserve and flavour food' },
    { q: 'What is a "food critic"?', options: ['a person who designs restaurant menus', 'a person who professionally reviews and evaluates food and restaurants', 'a person who teaches cooking techniques', 'a food scientist who analyses nutrition'], answer: 'a person who professionally reviews and evaluates food and restaurants' },
    { q: 'What does "artisan" mean when describing food?', options: ['food made in a large factory', 'food made in small batches using traditional skills by hand', 'food that is very expensive', 'food with no additives'], answer: 'food made in small batches using traditional skills by hand' },
    { q: 'What is "food traceability"?', options: ['tracking the nutritional value of food', 'the ability to track a food product through all stages of production and distribution', 'monitoring food quality in supermarkets', 'the study of food origins in history'], answer: 'the ability to track a food product through all stages of production and distribution' },
    { q: 'What does "fortified food" mean?', options: ['food that has been cooked for a long time', 'food with added nutrients not naturally present', 'food preserved using chemicals', 'food grown in controlled conditions'], answer: 'food with added nutrients not naturally present' },
    { q: 'What is "food sovereignty"?', options: ['a country\'s right to grow food for export', 'the right of people to define their own food systems and agricultural policies', 'the control of food prices by governments', 'the ability to import food freely'], answer: 'the right of people to define their own food systems and agricultural policies' },
    { q: 'What is a "bespoke menu"?', options: ['a standard restaurant menu', 'a menu specially created for a particular event or person', 'a menu focused on local ingredients', 'a fixed-price tasting menu'], answer: 'a menu specially created for a particular event or person' },
    { q: 'What does "canapé" refer to?', options: ['a type of soup', 'a small bite-sized appetiser served at social events', 'a French pastry', 'a method of presenting a main course'], answer: 'a small bite-sized appetiser served at social events' },
    { q: 'What is "food gentrification"?', options: ['using traditional recipes in modern restaurants', 'when cuisines from lower-income communities become fashionable and expensive', 'improving food safety standards in poor areas', 'teaching cooking to underprivileged communities'], answer: 'when cuisines from lower-income communities become fashionable and expensive' },
    { q: 'What does "palate" mean in the context of food?', options: ['a flat board used to present food', 'a person\'s ability to taste and appreciate different flavours', 'the roof of the mouth only', 'a method of food presentation'], answer: 'a person\'s ability to taste and appreciate different flavours' },
    { q: 'What is "food apartheid"?', options: ['segregation in restaurant seating', 'the unequal distribution of healthy food access in communities based on race or income', 'food labelling laws in certain countries', 'a historical method of food rationing'], answer: 'the unequal distribution of healthy food access in communities based on race or income' },
    { q: 'What does "macronutrient" refer to?', options: ['the vitamins in food', 'the main nutrients the body needs in large amounts: protein, carbohydrates and fat', 'the minerals found in food', 'the fibre content of food'], answer: 'the main nutrients the body needs in large amounts: protein, carbohydrates and fat' },
    { q: 'What is "vertical farming"?', options: ['growing crops on hillsides', 'growing crops in stacked layers indoors using artificial light', 'farming on tall structures outside', 'a method of rotating crops in fields'], answer: 'growing crops in stacked layers indoors using artificial light' },
    { q: 'What does "cross-contamination" mean in food safety?', options: ['mixing two cuisines together', 'the transfer of harmful bacteria from one food to another', 'cooking different foods in the same pan', 'using the same recipe for different dishes'], answer: 'the transfer of harmful bacteria from one food to another' },
    { q: 'What is "food diplomacy"?', options: ['using restaurants for political meetings', 'using food and culinary exchange to build relationships between countries', 'negotiating food import and export deals', 'distributing food aid to other nations'], answer: 'using food and culinary exchange to build relationships between countries' },
    { q: 'What does "blanching" do to vegetables before freezing?', options: ['removes all the colour', 'kills bacteria and preserves colour, texture and nutrients', 'removes the skin', 'makes them soft enough to eat immediately'], answer: 'kills bacteria and preserves colour, texture and nutrients' },
    { q: 'What is a "prix fixe" menu?', options: ['a menu where every dish is free', 'a fixed-price menu with a set number of courses', 'a menu that changes daily', 'a very expensive tasting menu'], answer: 'a fixed-price menu with a set number of courses' },
    { q: 'What does "food labelling" help consumers do?', options: ['find out where to buy food', 'understand the ingredients, nutrition and origin of a product', 'compare the prices of food', 'choose the best-looking food packaging'], answer: 'understand the ingredients, nutrition and origin of a product' },
    { q: 'What is a "Michelin star"?', options: ['an ingredient from a famous French company', 'a prestigious award given to outstanding restaurants by the Michelin Guide', 'a cooking technique developed in France', 'a type of oven used in professional kitchens'], answer: 'a prestigious award given to outstanding restaurants by the Michelin Guide' },
    { q: 'What does "batch cooking" mean?', options: ['cooking one dish several times', 'preparing large amounts of food at once to be stored and eaten later', 'cooking food in large commercial kitchens', 'following a recipe exactly'], answer: 'preparing large amounts of food at once to be stored and eaten later' },
    { q: 'What is "food miles"?', options: ['the distance a customer travels to buy food', 'the distance food travels from where it is produced to where it is consumed', 'the number of countries a food item is sold in', 'the carbon footprint of cooking food at home'], answer: 'the distance food travels from where it is produced to where it is consumed' },
    { q: 'What does "umami-rich" mean when describing a dish?', options: ['a dish that is very sweet', 'a dish with a deep, savoury and satisfying taste', 'a dish that is very spicy', 'a dish that is high in protein'], answer: 'a dish with a deep, savoury and satisfying taste' },
    { q: 'What is "food literacy"?', options: ['being able to read food labels', 'the knowledge and skills needed to make healthy, informed food choices', 'knowing the names of different cuisines', 'understanding agricultural practices'], answer: 'the knowledge and skills needed to make healthy, informed food choices' },
  ],
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}
