export const questionBank: Record<string, { q: string; options: string[]; answer: string }[]> = {
  'P1-P2': [
    { q: 'Which animal says "moo"?', options: ['sheep', 'pig', 'cow', 'horse'], answer: 'cow' },
    { q: 'What do we call a baby dog?', options: ['kitten', 'cub', 'puppy', 'foal'], answer: 'puppy' },
    { q: 'Which animal has a very long neck?', options: ['elephant', 'giraffe', 'zebra', 'lion'], answer: 'giraffe' },
    { q: 'What do we call an animal that only eats plants?', options: ['carnivore', 'omnivore', 'herbivore', 'predator'], answer: 'herbivore' },
    { q: 'Which of these animals can fly?', options: ['dog', 'cat', 'fish', 'bird'], answer: 'bird' },
    { q: 'What do we call a baby cat?', options: ['puppy', 'calf', 'kitten', 'chick'], answer: 'kitten' },
    { q: 'Which animal lives in water and has fins?', options: ['rabbit', 'fish', 'cat', 'horse'], answer: 'fish' },
    { q: 'What do we call the sound a dog makes?', options: ['meow', 'moo', 'bark', 'roar'], answer: 'bark' },
    { q: 'Which animal has black and white stripes?', options: ['lion', 'tiger', 'zebra', 'bear'], answer: 'zebra' },
    { q: 'What do we call a baby cow?', options: ['foal', 'calf', 'lamb', 'kitten'], answer: 'calf' },
    { q: 'Which animal is known as "man\'s best friend"?', options: ['cat', 'rabbit', 'dog', 'bird'], answer: 'dog' },
    { q: 'What do we call the place where farm animals live?', options: ['jungle', 'ocean', 'barn', 'desert'], answer: 'barn' },
    { q: 'Which animal hops and has long ears?', options: ['mouse', 'rabbit', 'frog', 'cat'], answer: 'rabbit' },
    { q: 'What do we call a baby sheep?', options: ['cub', 'kitten', 'lamb', 'foal'], answer: 'lamb' },
    { q: 'Which animal gives us milk?', options: ['dog', 'cat', 'cow', 'bird'], answer: 'cow' },
    { q: 'What do we call the sound a cat makes?', options: ['bark', 'moo', 'meow', 'oink'], answer: 'meow' },
    { q: 'Which animal has a shell on its back?', options: ['frog', 'turtle', 'rabbit', 'deer'], answer: 'turtle' },
    { q: 'What do we call a group of fish swimming together?', options: ['herd', 'flock', 'pack', 'school'], answer: 'school' },
    { q: 'Which animal is the biggest land animal?', options: ['giraffe', 'elephant', 'horse', 'bear'], answer: 'elephant' },
    { q: 'What do we call a baby horse?', options: ['calf', 'lamb', 'foal', 'cub'], answer: 'foal' },
    { q: 'Which of these animals lives in the sea?', options: ['lion', 'horse', 'dolphin', 'rabbit'], answer: 'dolphin' },
    { q: 'What do we call the sound a pig makes?', options: ['moo', 'oink', 'bark', 'roar'], answer: 'oink' },
    { q: 'Which animal sleeps hanging upside down?', options: ['eagle', 'monkey', 'bat', 'parrot'], answer: 'bat' },
    { q: 'What do we call a group of sheep?', options: ['pack', 'flock', 'herd', 'school'], answer: 'flock' },
    { q: 'Which animal has a very bushy tail and collects nuts?', options: ['mouse', 'rabbit', 'squirrel', 'hamster'], answer: 'squirrel' },
    { q: 'What do we call animals that are active at night?', options: ['diurnal', 'nocturnal', 'domestic', 'wild'], answer: 'nocturnal' },
    { q: 'Which animal is known for its beautiful colourful tail feathers?', options: ['crow', 'parrot', 'peacock', 'flamingo'], answer: 'peacock' },
    { q: 'What do we call a group of wolves?', options: ['herd', 'flock', 'pack', 'school'], answer: 'pack' },
    { q: 'Which animal makes silk?', options: ['bee', 'spider', 'butterfly', 'silkworm'], answer: 'silkworm' },
    { q: 'What do we call a baby bear?', options: ['cub', 'pup', 'calf', 'foal'], answer: 'cub' },
    { q: 'Which animal is famous for changing colour?', options: ['lizard', 'frog', 'chameleon', 'snake'], answer: 'chameleon' },
    { q: 'What do we call the home of a bird?', options: ['den', 'burrow', 'nest', 'stable'], answer: 'nest' },
    { q: 'Which of these is a reptile?', options: ['frog', 'whale', 'snake', 'eagle'], answer: 'snake' },
    { q: 'What do we call the sound a lion makes?', options: ['bark', 'moo', 'roar', 'hiss'], answer: 'roar' },
    { q: 'Which animal carries its baby in a pouch?', options: ['bear', 'kangaroo', 'elephant', 'tiger'], answer: 'kangaroo' },
    { q: 'What do we call a group of bees?', options: ['flock', 'pack', 'swarm', 'herd'], answer: 'swarm' },
    { q: 'Which animal is known for being very slow?', options: ['cheetah', 'rabbit', 'sloth', 'horse'], answer: 'sloth' },
    { q: 'What do we call animals that eat both plants and meat?', options: ['herbivore', 'carnivore', 'omnivore', 'predator'], answer: 'omnivore' },
    { q: 'Which animal has the longest tongue of all land animals?', options: ['elephant', 'giraffe', 'anteater', 'crocodile'], answer: 'anteater' },
    { q: 'What do we call the home of a rabbit?', options: ['den', 'burrow', 'nest', 'stable'], answer: 'burrow' },
  ],
  'P3-P4': [
    { q: 'What do we call an animal that only eats meat?', options: ['herbivore', 'omnivore', 'carnivore', 'scavenger'], answer: 'carnivore' },
    { q: 'Which word describes an animal that hunts other animals for food?', options: ['prey', 'predator', 'scavenger', 'herbivore'], answer: 'predator' },
    { q: 'What do we call an animal that is hunted by other animals?', options: ['predator', 'carnivore', 'prey', 'omnivore'], answer: 'prey' },
    { q: 'Which word describes animals that are active during the day?', options: ['nocturnal', 'domestic', 'diurnal', 'migratory'], answer: 'diurnal' },
    { q: 'What do we call the process when animals travel to warmer places in winter?', options: ['hibernation', 'migration', 'adaptation', 'evolution'], answer: 'migration' },
    { q: 'Which word describes animals that sleep through winter?', options: ['migrate', 'hibernate', 'camouflage', 'adapt'], answer: 'hibernate' },
    { q: 'What do we call animals that live in the wild, not with humans?', options: ['domestic', 'tame', 'wild', 'captive'], answer: 'wild' },
    { q: 'Which word describes an animal that can live both on land and in water?', options: ['reptile', 'mammal', 'amphibian', 'invertebrate'], answer: 'amphibian' },
    { q: 'What do we call a group of lions?', options: ['pack', 'pride', 'herd', 'flock'], answer: 'pride' },
    { q: 'Which word means an animal blends into its surroundings to hide?', options: ['migration', 'hibernation', 'camouflage', 'adaptation'], answer: 'camouflage' },
    { q: 'What do we call the home of a lion or fox?', options: ['burrow', 'nest', 'den', 'stable'], answer: 'den' },
    { q: 'Which of these animals is a mammal?', options: ['crocodile', 'shark', 'dolphin', 'frog'], answer: 'dolphin' },
    { q: 'What do we call a group of cows?', options: ['flock', 'pack', 'pride', 'herd'], answer: 'herd' },
    { q: 'Which word describes an animal that gives birth to live young?', options: ['oviparous', 'viviparous', 'amphibious', 'nocturnal'], answer: 'viviparous' },
    { q: 'What do we call the sharp claws of a bird of prey?', options: ['beak', 'talons', 'wings', 'feathers'], answer: 'talons' },
    { q: 'Which animal is the fastest land animal?', options: ['lion', 'horse', 'cheetah', 'leopard'], answer: 'cheetah' },
    { q: 'What do we call animals that are born from eggs?', options: ['viviparous', 'oviparous', 'nocturnal', 'diurnal'], answer: 'oviparous' },
    { q: 'Which word describes a young bird that has just hatched?', options: ['cub', 'foal', 'hatchling', 'fawn'], answer: 'hatchling' },
    { q: 'What do we call a group of elephants?', options: ['pride', 'pack', 'herd', 'colony'], answer: 'herd' },
    { q: 'Which word means an animal\'s natural home environment?', options: ['territory', 'habitat', 'burrow', 'range'], answer: 'habitat' },
    { q: 'What do we call the pattern or skin colour that helps an animal hide?', options: ['adaptation', 'migration', 'camouflage', 'evolution'], answer: 'camouflage' },
    { q: 'Which of these is an invertebrate (has no backbone)?', options: ['snake', 'frog', 'spider', 'bat'], answer: 'spider' },
    { q: 'What do we call the outer covering of a fish that helps it swim?', options: ['fur', 'scales', 'feathers', 'skin'], answer: 'scales' },
    { q: 'Which word describes an animal that feeds its young with milk?', options: ['reptile', 'amphibian', 'mammal', 'bird'], answer: 'mammal' },
    { q: 'What do we call a baby deer?', options: ['cub', 'fawn', 'foal', 'lamb'], answer: 'fawn' },
    { q: 'Which word describes the area an animal defends as its own?', options: ['habitat', 'burrow', 'territory', 'range'], answer: 'territory' },
    { q: 'What do we call an animal that eats dead animals left by others?', options: ['predator', 'prey', 'scavenger', 'herbivore'], answer: 'scavenger' },
    { q: 'Which of these is a cold-blooded animal?', options: ['dog', 'whale', 'lizard', 'rabbit'], answer: 'lizard' },
    { q: 'What do we call a group of ants?', options: ['flock', 'colony', 'pack', 'swarm'], answer: 'colony' },
    { q: 'Which word describes when an animal changes its body to survive in its environment?', options: ['migration', 'hibernation', 'adaptation', 'evolution'], answer: 'adaptation' },
    { q: 'What do we call the home of a horse?', options: ['den', 'burrow', 'stable', 'sty'], answer: 'stable' },
    { q: 'Which word describes an animal that is in danger of dying out completely?', options: ['wild', 'domestic', 'endangered', 'extinct'], answer: 'endangered' },
    { q: 'What do we call a group of dolphins?', options: ['school', 'pod', 'pack', 'herd'], answer: 'pod' },
    { q: 'Which word describes an animal species that no longer exists?', options: ['endangered', 'extinct', 'rare', 'wild'], answer: 'extinct' },
    { q: 'What do we call the hard outer covering of insects and crabs?', options: ['scales', 'shell', 'exoskeleton', 'fur'], answer: 'exoskeleton' },
    { q: 'Which animal is known for building dams in rivers?', options: ['otter', 'beaver', 'muskrat', 'platypus'], answer: 'beaver' },
    { q: 'What do we call a group of gorillas?', options: ['pride', 'troop', 'pack', 'colony'], answer: 'troop' },
    { q: 'Which word describes the way an animal moves to find food?', options: ['migrate', 'forage', 'hibernate', 'camouflage'], answer: 'forage' },
    { q: 'What do we call the home of a pig?', options: ['den', 'stable', 'sty', 'burrow'], answer: 'sty' },
    { q: 'Which of these animals uses echolocation to find its way in the dark?', options: ['eagle', 'owl', 'bat', 'parrot'], answer: 'bat' },
  ],
  'P5-P6': [
    { q: 'What is the scientific term for warm-blooded animals that nurse their young with milk?', options: ['reptiles', 'amphibians', 'mammals', 'arthropods'], answer: 'mammals' },
    { q: 'Which word describes the relationship where both animals benefit from living together?', options: ['parasitism', 'predation', 'mutualism', 'competition'], answer: 'mutualism' },
    { q: 'What do we call the process by which species gradually change over generations?', options: ['adaptation', 'migration', 'evolution', 'hibernation'], answer: 'evolution' },
    { q: 'Which term describes an animal that is active at twilight — dawn and dusk?', options: ['diurnal', 'nocturnal', 'crepuscular', 'hibernating'], answer: 'crepuscular' },
    { q: 'What do we call the relationship where one animal benefits and the other is harmed?', options: ['mutualism', 'parasitism', 'symbiosis', 'competition'], answer: 'parasitism' },
    { q: 'Which word describes the specific role an animal plays in its ecosystem?', options: ['habitat', 'territory', 'niche', 'range'], answer: 'niche' },
    { q: 'What do we call an animal introduced to a new area where it causes problems?', options: ['endangered species', 'invasive species', 'native species', 'migratory species'], answer: 'invasive species' },
    { q: 'Which term describes the chain of feeding relationships in an ecosystem?', options: ['food web', 'food chain', 'ecosystem', 'biome'], answer: 'food chain' },
    { q: 'What do we call animals with a backbone?', options: ['invertebrates', 'vertebrates', 'arthropods', 'molluscs'], answer: 'vertebrates' },
    { q: 'Which word describes the way animals communicate through chemicals?', options: ['echolocation', 'pheromones', 'bioluminescence', 'mimicry'], answer: 'pheromones' },
    { q: 'What do we call the type of relationship where one animal copies the appearance of another for protection?', options: ['camouflage', 'adaptation', 'mimicry', 'evolution'], answer: 'mimicry' },
    { q: 'Which term describes the variety of different species in an area?', options: ['ecology', 'biodiversity', 'habitat', 'taxonomy'], answer: 'biodiversity' },
    { q: 'What do we call the natural environment or community where organisms live together?', options: ['habitat', 'territory', 'ecosystem', 'biome'], answer: 'ecosystem' },
    { q: 'Which word describes animals without a backbone?', options: ['vertebrates', 'mammals', 'invertebrates', 'reptiles'], answer: 'invertebrates' },
    { q: 'What do we call the ability of some deep-sea creatures to produce their own light?', options: ['echolocation', 'pheromones', 'bioluminescence', 'camouflage'], answer: 'bioluminescence' },
    { q: 'Which term describes the top predator in a food chain with no natural enemies?', options: ['scavenger', 'apex predator', 'omnivore', 'keystone species'], answer: 'apex predator' },
    { q: 'What do we call the scientific study of animal behaviour?', options: ['zoology', 'ethology', 'ecology', 'taxonomy'], answer: 'ethology' },
    { q: 'Which word describes a species that has a large effect on its ecosystem out of proportion to its size?', options: ['apex predator', 'invasive species', 'keystone species', 'endemic species'], answer: 'keystone species' },
    { q: 'What do we call the moulting process where insects transform from larva to adult?', options: ['evolution', 'metamorphosis', 'adaptation', 'reproduction'], answer: 'metamorphosis' },
    { q: 'Which term describes species that are found only in one particular place on Earth?', options: ['invasive', 'migratory', 'endemic', 'nocturnal'], answer: 'endemic' },
    { q: 'What do we call the use of sound waves to navigate and locate objects — used by bats and dolphins?', options: ['pheromones', 'bioluminescence', 'echolocation', 'mimicry'], answer: 'echolocation' },
    { q: 'Which word describes when two different species live in close association?', options: ['predation', 'symbiosis', 'competition', 'evolution'], answer: 'symbiosis' },
    { q: 'What do we call the study of animals?', options: ['botany', 'geology', 'zoology', 'ecology'], answer: 'zoology' },
    { q: 'Which term describes an animal that feeds on both living prey and dead animals?', options: ['herbivore', 'carnivore', 'scavenger', 'omnivore'], answer: 'scavenger' },
    { q: 'What do we call the system of naming living things using two Latin words?', options: ['taxonomy', 'binomial nomenclature', 'classification', 'evolution'], answer: 'binomial nomenclature' },
    { q: 'Which word describes the gradual change in animal communities in an area over time?', options: ['evolution', 'migration', 'ecological succession', 'adaptation'], answer: 'ecological succession' },
    { q: 'What do we call the physical features of an animal that help it survive?', options: ['evolution', 'behaviour', 'structural adaptations', 'camouflage'], answer: 'structural adaptations' },
    { q: 'Which term describes animals that are raised by humans for food or work?', options: ['wild', 'feral', 'domestic', 'captive'], answer: 'domestic' },
    { q: 'What do we call the relationship where one animal benefits but the other is neither helped nor harmed?', options: ['mutualism', 'parasitism', 'commensalism', 'competition'], answer: 'commensalism' },
    { q: 'Which word describes the complete disappearance of a species from Earth?', options: ['endangered', 'threatened', 'extinct', 'vulnerable'], answer: 'extinct' },
    { q: 'What do we call the group of animals that includes crabs, insects and spiders?', options: ['molluscs', 'vertebrates', 'arthropods', 'echinoderms'], answer: 'arthropods' },
    { q: 'Which term describes seasonal colour or pattern changes in an animal\'s appearance?', options: ['camouflage', 'mimicry', 'moulting', 'adaptation'], answer: 'moulting' },
    { q: 'What do we call animals that decompose dead matter and return nutrients to the soil?', options: ['predators', 'scavengers', 'decomposers', 'producers'], answer: 'decomposers' },
    { q: 'Which word describes the hormone released by animals to attract a mate?', options: ['echolocation', 'pheromone', 'venom', 'enzyme'], answer: 'pheromone' },
    { q: 'What do we call a large geographic area with similar climate and animal communities?', options: ['habitat', 'ecosystem', 'territory', 'biome'], answer: 'biome' },
    { q: 'Which term describes the number of individuals of a species in a given area?', options: ['biodiversity', 'population', 'colony', 'habitat'], answer: 'population' },
    { q: 'What do we call the protective fluid some animals spit or inject to harm enemies?', options: ['pheromone', 'enzyme', 'venom', 'hormone'], answer: 'venom' },
    { q: 'Which word describes the movement of genes between populations of the same species?', options: ['evolution', 'adaptation', 'gene flow', 'natural selection'], answer: 'gene flow' },
    { q: 'What do we call the seasonal growth and shedding of an animal\'s outer covering?', options: ['migration', 'hibernation', 'moulting', 'metamorphosis'], answer: 'moulting' },
    { q: 'Which term describes how animals compete for the same limited resources in an area?', options: ['predation', 'mutualism', 'competition', 'symbiosis'], answer: 'competition' },
  ],
  'M1-M3': [
    { q: 'What is "natural selection" in the context of animal evolution?', options: ['animals choosing their habitat', 'the process where better-adapted animals survive and reproduce more', 'humans selecting animals for breeding', 'animals migrating to better environments'], answer: 'the process where better-adapted animals survive and reproduce more' },
    { q: 'Which term describes the complete set of genes in an organism?', options: ['chromosome', 'genome', 'DNA', 'protein'], answer: 'genome' },
    { q: 'What do we call the process by which new species form from existing ones over time?', options: ['adaptation', 'migration', 'speciation', 'mutation'], answer: 'speciation' },
    { q: 'Which word describes an organism\'s ability to regulate its internal body temperature?', options: ['homeostasis', 'thermoregulation', 'metabolism', 'osmosis'], answer: 'thermoregulation' },
    { q: 'What do we call the study of how animals interact with their environment?', options: ['zoology', 'ethology', 'ecology', 'taxonomy'], answer: 'ecology' },
    { q: 'Which term describes behaviour that is inherited rather than learned?', options: ['conditioned', 'acquired', 'instinctive', 'cognitive'], answer: 'instinctive' },
    { q: 'What do we call the gradual change in a community of organisms in an area over time?', options: ['evolution', 'adaptation', 'succession', 'migration'], answer: 'succession' },
    { q: 'Which word describes the total variety of life on Earth?', options: ['ecosystem', 'ecology', 'biodiversity', 'biosphere'], answer: 'biodiversity' },
    { q: 'What do we call the zone of the ocean below the reach of sunlight?', options: ['intertidal zone', 'pelagic zone', 'abyssal zone', 'littoral zone'], answer: 'abyssal zone' },
    { q: 'Which term describes an organism that produces its own food through photosynthesis?', options: ['consumer', 'decomposer', 'producer', 'scavenger'], answer: 'producer' },
    { q: 'What do we call the total mass of living organisms in a given area?', options: ['population', 'biodiversity', 'biomass', 'ecosystem'], answer: 'biomass' },
    { q: 'Which word describes the evolution of two species influencing each other over time?', options: ['natural selection', 'co-evolution', 'adaptation', 'speciation'], answer: 'co-evolution' },
    { q: 'What do we call the enzyme that breaks down hydrogen peroxide in animal cells?', options: ['lipase', 'amylase', 'catalase', 'protease'], answer: 'catalase' },
    { q: 'Which term describes a species that acts as an indicator of environmental health?', options: ['apex predator', 'keystone species', 'indicator species', 'endemic species'], answer: 'indicator species' },
    { q: 'What do we call the phenomenon where unrelated species evolve similar features independently?', options: ['co-evolution', 'parallel evolution', 'convergent evolution', 'natural selection'], answer: 'convergent evolution' },
    { q: 'Which word describes the chemical signals animals use to communicate within their species?', options: ['hormones', 'enzymes', 'pheromones', 'proteins'], answer: 'pheromones' },
    { q: 'What do we call the ability of an organism to maintain a stable internal environment?', options: ['metabolism', 'thermoregulation', 'homeostasis', 'adaptation'], answer: 'homeostasis' },
    { q: 'Which term describes the transfer of energy between organisms in an ecosystem expressed as a diagram?', options: ['food chain', 'energy pyramid', 'food web', 'carbon cycle'], answer: 'energy pyramid' },
    { q: 'What do we call the process where animals learn by watching others of their species?', options: ['instinct', 'conditioning', 'observational learning', 'imprinting'], answer: 'observational learning' },
    { q: 'Which word describes the early learning period where young animals form strong bonds with their caregivers?', options: ['conditioning', 'imprinting', 'socialisation', 'adaptation'], answer: 'imprinting' },
    { q: 'What do we call a random change in an organism\'s DNA that may be passed to offspring?', options: ['adaptation', 'evolution', 'mutation', 'selection'], answer: 'mutation' },
    { q: 'Which term describes the loss of a species from a particular region but not globally?', options: ['extinction', 'local extinction', 'endangered', 'vulnerable'], answer: 'local extinction' },
    { q: 'What do we call the scientific classification system with seven main levels?', options: ['binomial nomenclature', 'taxonomy', 'phylogeny', 'genetics'], answer: 'taxonomy' },
    { q: 'Which word describes organisms that recycle nutrients by breaking down dead organic matter?', options: ['producers', 'consumers', 'predators', 'decomposers'], answer: 'decomposers' },
    { q: 'What do we call the area of overlap between two different ecosystems?', options: ['biome', 'habitat', 'ecotone', 'niche'], answer: 'ecotone' },
    { q: 'Which term describes the maximum population size an environment can support?', options: ['population density', 'carrying capacity', 'biomass', 'biodiversity'], answer: 'carrying capacity' },
    { q: 'What do we call the relationship between a clownfish living safely among sea anemone tentacles?', options: ['parasitism', 'competition', 'mutualism', 'commensalism'], answer: 'mutualism' },
    { q: 'Which word describes the inherited traits that increase an organism\'s chance of survival?', options: ['evolution', 'mutations', 'adaptations', 'instincts'], answer: 'adaptations' },
    { q: 'What do we call the branch of biology dealing with the classification of organisms?', options: ['ecology', 'ethology', 'taxonomy', 'genetics'], answer: 'taxonomy' },
    { q: 'Which term describes the diversity of genes within a single species?', options: ['biodiversity', 'genetic diversity', 'species richness', 'ecosystem diversity'], answer: 'genetic diversity' },
    { q: 'What do we call the seasonal return of animals to their birthplace to breed?', options: ['migration', 'natal philopatry', 'hibernation', 'dispersal'], answer: 'natal philopatry' },
    { q: 'Which word describes an animal that uses tools to obtain food or solve problems?', options: ['instinctive', 'conditioned', 'cognitively advanced', 'imprinted'], answer: 'cognitively advanced' },
    { q: 'What do we call the scientific study of insect life?', options: ['zoology', 'herpetology', 'entomology', 'ornithology'], answer: 'entomology' },
    { q: 'Which term describes the scientific study of birds?', options: ['herpetology', 'ichthyology', 'ornithology', 'entomology'], answer: 'ornithology' },
    { q: 'What do we call the co-evolutionary arms race between predators and prey?', options: ['natural selection', 'competitive exclusion', 'evolutionary arms race', 'co-adaptation'], answer: 'evolutionary arms race' },
    { q: 'Which word describes species that occupy the same ecological niche and compete directly?', options: ['mutualistic', 'symbiotic', 'competing species', 'ecologically equivalent'], answer: 'ecologically equivalent' },
    { q: 'What do we call the scientific study of fish?', options: ['herpetology', 'ichthyology', 'ornithology', 'cetology'], answer: 'ichthyology' },
    { q: 'Which term describes the principle that two species competing for identical resources cannot coexist?', options: ['natural selection', 'competitive exclusion principle', 'niche differentiation', 'resource partitioning'], answer: 'competitive exclusion principle' },
    { q: 'What do we call the study of whales and dolphins?', options: ['ichthyology', 'ornithology', 'cetology', 'herpetology'], answer: 'cetology' },
    { q: 'Which word describes the scientific study of reptiles and amphibians?', options: ['ornithology', 'entomology', 'herpetology', 'cetology'], answer: 'herpetology' },
  ],
}

export function shuffle<T>(arr: T[]): T[] {
  return [...arr].sort(() => Math.random() - 0.5)
}
